// AUTO-GENERATED by CatalogIteratorMain - do not edit by hand.
package kranji.common.perclass.promoted.j.ing1;

import kranji.classification.EtymologicalCategory;
import kranji.component.basic.BasicComponents;
import kranji.component.basic.HeartFamily;
import kranji.pinyin.Body;
import kranji.pinyin.Final;
import kranji.pinyin.Head;
import kranji.pinyin.Initial;
import kranji.pinyin.PinyinSyllable;
import kranji.pinyin.Tail;
import kranji.pinyin.Tone;
import kranji.singular.structures.Structures;
import kranji.zi.ComposedZiT;
import kranji.zi.CompositionLayoutT;
import kranji.zi.LeftRightT;

public record JingStartle() implements ComposedZiT, LeftRightT<HeartFamily.ShuXinPang, Structures.Jing_Capital> {

    public static final JingStartle INSTANCE = new JingStartle();

    @Override public HeartFamily.ShuXinPang left() { return BasicComponents.SHU_XIN_PANG; }
    @Override public Structures.Jing_Capital right() { return Structures.JING_CAPITAL; }

    @Override public CompositionLayoutT layout() { return this; }

    @Override public String glyph() { return "\u60CA"; }

    @Override public PinyinSyllable pinyin() {
        return new PinyinSyllable(Initial.J, new Final(Head.OPEN, Body.I, Tail.NG), Tone.FIRST);
    }

    @Override public int strokes() { return 0; }
    @Override public int radicalNo() { return 0; }
    @Override public String meaning() { return ""; }

    @Override public EtymologicalCategory etymology() {
        return new EtymologicalCategory.PhonoSemantic(BasicComponents.SHU_XIN_PANG, Structures.JING_CAPITAL);
    }
}
