// AUTO-GENERATED by kranji-codegen. Do not edit by hand.
package kranji.singular.people.sh;

import kranji.library.BasicSet;
import kranji.library.LibraryMember;
import kranji.zi.SingularZi;

public record Shi_Clan() implements LibraryMember<BasicSet>, SingularZi {
    public static final Shi_Clan INSTANCE = new Shi_Clan();

    @Override public String glyph() { return "\u6C0F"; }
    @Override public String meaning() { return "clan"; }
    @Override public String pinyinText() { return "sh\u00EC"; }
    @Override public int strokes() { return 4; }
    @Override public BasicSet library() { return BasicSet.INSTANCE; }
}
