// AUTO-GENERATED by CatalogIteratorMain - do not edit by hand.
package kranji.common.perclass.promoted.j.i2;

import kranji.classification.EtymologicalCategory;
import kranji.component.basic.BasicComponents;
import kranji.component.basic.SilkFamily;
import kranji.pinyin.Body;
import kranji.pinyin.Final;
import kranji.pinyin.Head;
import kranji.pinyin.Initial;
import kranji.pinyin.PinyinSyllable;
import kranji.pinyin.Tail;
import kranji.pinyin.Tone;
import kranji.singular.actions.ActionsAndStates;
import kranji.zi.ComposedZiT;
import kranji.zi.CompositionLayoutT;
import kranji.zi.LeftRightT;

public record JiLevel() implements ComposedZiT, LeftRightT<SilkFamily.JiaoSiPang, ActionsAndStates.Ji_Reach> {

    public static final JiLevel INSTANCE = new JiLevel();

    @Override public SilkFamily.JiaoSiPang left() { return BasicComponents.JIAO_SI_PANG; }
    @Override public ActionsAndStates.Ji_Reach right() { return ActionsAndStates.JI_REACH; }

    @Override public CompositionLayoutT layout() { return this; }

    @Override public String glyph() { return "\u7EA7"; }

    @Override public PinyinSyllable pinyin() {
        return new PinyinSyllable(Initial.J, new Final(Head.OPEN, Body.I, Tail.NONE), Tone.SECOND);
    }

    @Override public int strokes() { return 0; }
    @Override public int radicalNo() { return 0; }
    @Override public String meaning() { return ""; }

    @Override public EtymologicalCategory etymology() {
        return new EtymologicalCategory.PhonoSemantic(BasicComponents.JIAO_SI_PANG, ActionsAndStates.JI_REACH);
    }
}
