// AUTO-GENERATED by CatalogIteratorMain - do not edit by hand.
package kranji.common.perclass.promoted.j.i2;

import kranji.classification.EtymologicalCategory;
import kranji.common.perclass.promoted.ch.u2.ChuFodder;
import kranji.pinyin.Body;
import kranji.pinyin.Final;
import kranji.pinyin.Head;
import kranji.pinyin.Initial;
import kranji.pinyin.PinyinSyllable;
import kranji.pinyin.Tail;
import kranji.pinyin.Tone;
import kranji.singular.body.BodyParts;
import kranji.zi.ComposedZiT;
import kranji.zi.CompositionLayoutT;
import kranji.zi.TopBottomT;

public record JiUrgent() implements ComposedZiT, TopBottomT<ChuFodder, BodyParts.Xin> {

    public static final JiUrgent INSTANCE = new JiUrgent();

    @Override public ChuFodder top() { return ChuFodder.INSTANCE; }
    @Override public BodyParts.Xin bottom() { return BodyParts.XIN; }

    @Override public CompositionLayoutT layout() { return this; }

    @Override public String glyph() { return "\u6025"; }

    @Override public PinyinSyllable pinyin() {
        return new PinyinSyllable(Initial.J, new Final(Head.OPEN, Body.I, Tail.NONE), Tone.SECOND);
    }

    @Override public int strokes() { return 0; }
    @Override public int radicalNo() { return 0; }
    @Override public String meaning() { return ""; }

    @Override public EtymologicalCategory etymology() {
        return new EtymologicalCategory.PhonoSemantic(BodyParts.XIN, ChuFodder.INSTANCE);
    }
}
