// AUTO-GENERATED by CatalogIteratorMain - do not edit by hand.
package kranji.common.perclass.promoted.l.ian2;

import kranji.classification.EtymologicalCategory;
import kranji.common.perclass.promoted.l.ian2.LianHonest;
import kranji.component.basic.BasicComponents;
import kranji.component.basic.MetalFamily;
import kranji.pinyin.Body;
import kranji.pinyin.Final;
import kranji.pinyin.Head;
import kranji.pinyin.Initial;
import kranji.pinyin.PinyinSyllable;
import kranji.pinyin.Tail;
import kranji.pinyin.Tone;
import kranji.zi.ComposedZiT;
import kranji.zi.CompositionLayoutT;
import kranji.zi.LeftRightT;

public record LianSickle() implements ComposedZiT, LeftRightT<MetalFamily.JinZiPang, LianHonest> {

    public static final LianSickle INSTANCE = new LianSickle();

    @Override public MetalFamily.JinZiPang left() { return BasicComponents.JIN_ZI_PANG; }
    @Override public LianHonest right() { return LianHonest.INSTANCE; }

    @Override public CompositionLayoutT layout() { return this; }

    @Override public String glyph() { return "\u9570"; }

    @Override public PinyinSyllable pinyin() {
        return new PinyinSyllable(Initial.L, new Final(Head.I, Body.A, Tail.N), Tone.SECOND);
    }

    @Override public int strokes() { return 0; }
    @Override public int radicalNo() { return 0; }
    @Override public String meaning() { return ""; }

    @Override public EtymologicalCategory etymology() {
        return new EtymologicalCategory.PhonoSemantic(BasicComponents.JIN_ZI_PANG, LianHonest.INSTANCE);
    }
}
