// AUTO-GENERATED by Depth2GenerateMain - do not edit by hand.
package kranji.common.depth2.zero;

import kranji.classification.EtymologicalCategory.*;
import kranji.component.basic.BasicComponents;
import kranji.pinyin.Body;
import kranji.pinyin.Final;
import kranji.pinyin.Head;
import kranji.pinyin.Initial;
import kranji.pinyin.PinyinSyllable;
import kranji.pinyin.Tail;
import kranji.pinyin.Tone;
import kranji.zi.ComposedPart;
import kranji.zi.ComposedZi;
import kranji.zi.CompositionLayout.*;
import kranji.zi.SingularPart;
import kranji.zi.ZiChar;
import java.util.List;

public final class Uan3 {

    private Uan3() {}

    public static final ComposedZi YUAN_FAR = new ComposedZi(
            new ZiChar.Unicode("\u8FDC"),
            new PinyinSyllable(Initial.ZERO, new Final(Head.U, Body.A, Tail.N), Tone.THIRD),
            7, 162, "",
            new SemiEnclosureBottomLeft(BasicComponents.ZOU_ZHI_DI, kranji.common.depth1.zero.Van2.YUAN.structure()),
            new PhonoSemantic(BasicComponents.ZOU_ZHI_DI, kranji.common.depth1.zero.Van2.YUAN.structure()));

    public static final List<ComposedZi> ALL = List.of(
            YUAN_FAR);
}
