// AUTO-GENERATED by CatalogIteratorMain - do not edit by hand.
package kranji.common.perclass.promoted.zh.e2;

import kranji.classification.EtymologicalCategory;
import kranji.common.perclass.zh.e2.ZheFold;
import kranji.pinyin.Body;
import kranji.pinyin.Final;
import kranji.pinyin.Head;
import kranji.pinyin.Initial;
import kranji.pinyin.PinyinSyllable;
import kranji.pinyin.Tail;
import kranji.pinyin.Tone;
import kranji.singular.body.BodyParts;
import kranji.zi.ComposedZiT;
import kranji.zi.CompositionLayoutT;
import kranji.zi.TopBottomT;

public record ZheWise() implements ComposedZiT, TopBottomT<ZheFold, BodyParts.Kou> {

    public static final ZheWise INSTANCE = new ZheWise();

    @Override public ZheFold top() { return ZheFold.INSTANCE; }
    @Override public BodyParts.Kou bottom() { return BodyParts.KOU; }

    @Override public CompositionLayoutT layout() { return this; }

    @Override public String glyph() { return "\u54F2"; }

    @Override public PinyinSyllable pinyin() {
        return new PinyinSyllable(Initial.ZH, new Final(Head.OPEN, Body.E, Tail.NONE), Tone.SECOND);
    }

    @Override public int strokes() { return 0; }
    @Override public int radicalNo() { return 0; }
    @Override public String meaning() { return ""; }

    @Override public EtymologicalCategory etymology() {
        return new EtymologicalCategory.PhonoSemantic(BodyParts.KOU, ZheFold.INSTANCE);
    }
}
