// AUTO-GENERATED by Depth1GenerateMain - do not edit by hand.
package kranji.common.depth1.j;

import kranji.classification.EtymologicalCategory.*;
import kranji.component.basic.BasicComponents;
import kranji.pinyin.Body;
import kranji.pinyin.Final;
import kranji.pinyin.Head;
import kranji.pinyin.Initial;
import kranji.pinyin.PinyinSyllable;
import kranji.pinyin.Tail;
import kranji.pinyin.Tone;
import kranji.singular.actions.ActionsAndStates;
import kranji.singular.body.BodyParts;
import kranji.singular.people.PeopleAndRoles;
import kranji.zi.ComposedPart;
import kranji.zi.ComposedZi;
import kranji.zi.CompositionLayout.*;
import kranji.zi.SingularPart;
import kranji.zi.ZiChar;
import java.util.List;

public final class I2 {

    private I2() {}

    public static final ComposedZi JI_EXTREME = new ComposedZi(
            new ZiChar.Unicode("\u6781"),
            new PinyinSyllable(Initial.J, new Final(Head.OPEN, Body.I, Tail.NONE), Tone.SECOND),
            7, 75, "",
            new LeftRight(BasicComponents.MU, ActionsAndStates.JI_REACH),
            new PhonoSemantic(BasicComponents.MU, ActionsAndStates.JI_REACH));

    public static final ComposedZi JI_LUCKY = new ComposedZi(
            new ZiChar.Unicode("\u5409"),
            new PinyinSyllable(Initial.J, new Final(Head.OPEN, Body.I, Tail.NONE), Tone.SECOND),
            6, 30, "",
            new TopBottom(PeopleAndRoles.SHI, BodyParts.KOU),
            new CompoundIndicative("士(scholar/jade tablet) + 口(mouth) → auspicious proclamation"));

    public static final List<ComposedZi> ALL = List.of(
            JI_EXTREME,
            JI_LUCKY);
}
