// AUTO-GENERATED by Depth1GenerateMain - do not edit by hand.
package kranji.common.depth1.j;

import kranji.classification.EtymologicalCategory.*;
import kranji.pinyin.Body;
import kranji.pinyin.Final;
import kranji.pinyin.Head;
import kranji.pinyin.Initial;
import kranji.pinyin.PinyinSyllable;
import kranji.pinyin.Tail;
import kranji.pinyin.Tone;
import kranji.singular.body.BodyParts;
import kranji.singular.tools.ToolsAndVessels;
import kranji.zi.ComposedPart;
import kranji.zi.ComposedZi;
import kranji.zi.CompositionLayout.*;
import kranji.zi.SingularPart;
import kranji.zi.ZiChar;
import java.util.List;

public final class Ia1 {

    private Ia1() {}

    public static final ComposedZi JIA_ADD = new ComposedZi(
            new ZiChar.Unicode("\u52A0"),
            new PinyinSyllable(Initial.J, new Final(Head.I, Body.A, Tail.NONE), Tone.FIRST),
            5, 19, "",
            new LeftRight(ToolsAndVessels.LI_PLOW, BodyParts.KOU),
            new CompoundIndicative("力(strength) + 口(mouth) → add, increase"));

    public static final List<ComposedZi> ALL = List.of(
            JIA_ADD);
}
