// AUTO-GENERATED by Depth1GenerateMain - do not edit by hand.
package kranji.common.depth1.j;

import kranji.classification.EtymologicalCategory.*;
import kranji.pinyin.Body;
import kranji.pinyin.Final;
import kranji.pinyin.Head;
import kranji.pinyin.Initial;
import kranji.pinyin.PinyinSyllable;
import kranji.pinyin.Tail;
import kranji.pinyin.Tone;
import kranji.singular.numbers.NumbersAndMeasure;
import kranji.singular.structures.Structures;
import kranji.zi.ComposedPart;
import kranji.zi.ComposedZi;
import kranji.zi.CompositionLayout.*;
import kranji.zi.SingularPart;
import kranji.zi.ZiChar;
import java.util.List;

public final class Iou1 {

    private Iou1() {}

    public static final ComposedZi JIU_INVESTIGATE = new ComposedZi(
            new ZiChar.Unicode("\u7A76"),
            new PinyinSyllable(Initial.J, new Final(Head.I, Body.O, Tail.VOWEL_U), Tone.FIRST),
            7, 116, "",
            new TopBottom(Structures.XUE, NumbersAndMeasure.JIU),
            new PhonoSemantic(Structures.XUE, NumbersAndMeasure.JIU));

    public static final List<ComposedZi> ALL = List.of(
            JIU_INVESTIGATE);
}
