// AUTO-GENERATED by CatalogIteratorMain - do not edit by hand.
package kranji.common.perclass.promoted.zero.v4;

import kranji.classification.EtymologicalCategory;
import kranji.pinyin.Body;
import kranji.pinyin.Final;
import kranji.pinyin.Head;
import kranji.pinyin.Initial;
import kranji.pinyin.PinyinSyllable;
import kranji.pinyin.Tail;
import kranji.pinyin.Tone;
import kranji.singular.nature.NatureElements;
import kranji.singular.radicals.RadicalComponents;
import kranji.zi.ComposedZiT;
import kranji.zi.CompositionLayoutT;
import kranji.zi.LeftRightT;

public record YuDesire() implements ComposedZiT, LeftRightT<NatureElements.Gu, RadicalComponents.Qian_Owe> {

    public static final YuDesire INSTANCE = new YuDesire();

    @Override public NatureElements.Gu left() { return NatureElements.GU; }
    @Override public RadicalComponents.Qian_Owe right() { return RadicalComponents.QIAN_OWE; }

    @Override public CompositionLayoutT layout() { return this; }

    @Override public String glyph() { return "\u6B32"; }

    @Override public PinyinSyllable pinyin() {
        return new PinyinSyllable(Initial.ZERO, new Final(Head.V, Body.U, Tail.NONE), Tone.FOURTH);
    }

    @Override public int strokes() { return 0; }
    @Override public int radicalNo() { return 0; }
    @Override public String meaning() { return ""; }

    @Override public EtymologicalCategory etymology() {
        return new EtymologicalCategory.PhonoSemantic(RadicalComponents.QIAN_OWE, NatureElements.GU);
    }
}
