// AUTO-GENERATED by CatalogIteratorMain - do not edit by hand.
package kranji.common.perclass.promoted.zero.v4;

import kranji.classification.EtymologicalCategory;
import kranji.component.basic.AnimalFamily;
import kranji.component.basic.BasicComponents;
import kranji.pinyin.Body;
import kranji.pinyin.Final;
import kranji.pinyin.Head;
import kranji.pinyin.Initial;
import kranji.pinyin.PinyinSyllable;
import kranji.pinyin.Tail;
import kranji.pinyin.Tone;
import kranji.singular.actions.ActionsAndStates;
import kranji.singular.animals.Animals;
import kranji.zi.ComposedZiT;
import kranji.zi.CompositionLayoutT;
import kranji.zi.LeftMiddleRightT;

public record YuPrison() implements ComposedZiT, LeftMiddleRightT<AnimalFamily.FanQuanPang, ActionsAndStates.Yan_Speech, Animals.Quan> {

    public static final YuPrison INSTANCE = new YuPrison();

    @Override public AnimalFamily.FanQuanPang left() { return BasicComponents.FAN_QUAN_PANG; }
    @Override public ActionsAndStates.Yan_Speech middle() { return ActionsAndStates.YAN_SPEECH; }
    @Override public Animals.Quan right() { return Animals.QUAN; }

    @Override public CompositionLayoutT layout() { return this; }

    @Override public String glyph() { return "\u72F1"; }

    @Override public PinyinSyllable pinyin() {
        return new PinyinSyllable(Initial.ZERO, new Final(Head.V, Body.U, Tail.NONE), Tone.FOURTH);
    }

    @Override public int strokes() { return 0; }
    @Override public int radicalNo() { return 0; }
    @Override public String meaning() { return ""; }

    @Override public EtymologicalCategory etymology() {
        return new EtymologicalCategory.CompoundIndicative("");
    }
}
