// AUTO-GENERATED by CatalogIteratorMain - do not edit by hand.
package kranji.common.perclass.promoted.zh.i2;

import kranji.classification.EtymologicalCategory;
import kranji.pinyin.Body;
import kranji.pinyin.Final;
import kranji.pinyin.Head;
import kranji.pinyin.Initial;
import kranji.pinyin.PinyinSyllable;
import kranji.pinyin.Tail;
import kranji.pinyin.Tone;
import kranji.singular.concepts.AbstractConcepts;
import kranji.singular.plants.PlantsAndAgriculture;
import kranji.zi.ComposedZiT;
import kranji.zi.CompositionLayoutT;
import kranji.zi.LeftRightT;

public record ZhiBreed() implements ComposedZiT, LeftRightT<PlantsAndAgriculture.Dai, AbstractConcepts.Zhi_Straight> {

    public static final ZhiBreed INSTANCE = new ZhiBreed();

    @Override public PlantsAndAgriculture.Dai left() { return PlantsAndAgriculture.DAI; }
    @Override public AbstractConcepts.Zhi_Straight right() { return AbstractConcepts.ZHI_STRAIGHT; }

    @Override public CompositionLayoutT layout() { return this; }

    @Override public String glyph() { return "\u6B96"; }

    @Override public PinyinSyllable pinyin() {
        return new PinyinSyllable(Initial.ZH, new Final(Head.OPEN, Body.I, Tail.NONE), Tone.SECOND);
    }

    @Override public int strokes() { return 0; }
    @Override public int radicalNo() { return 0; }
    @Override public String meaning() { return ""; }

    @Override public EtymologicalCategory etymology() {
        return new EtymologicalCategory.PhonoSemantic(PlantsAndAgriculture.DAI, AbstractConcepts.ZHI_STRAIGHT);
    }
}
