// AUTO-GENERATED by CatalogIteratorMain - do not edit by hand.
package kranji.common.perclass.promoted.s.u4;

import kranji.classification.EtymologicalCategory;
import kranji.common.perclass.promoted.sh.uo4.ShuoShuoAuto;
import kranji.pinyin.Body;
import kranji.pinyin.Final;
import kranji.pinyin.Head;
import kranji.pinyin.Initial;
import kranji.pinyin.PinyinSyllable;
import kranji.pinyin.Tail;
import kranji.pinyin.Tone;
import kranji.singular.nature.NatureElements;
import kranji.zi.ComposedZiT;
import kranji.zi.CompositionLayoutT;
import kranji.zi.TopBottomT;

public record SuMold() implements ComposedZiT, TopBottomT<ShuoShuoAuto, NatureElements.Tu> {

    public static final SuMold INSTANCE = new SuMold();

    @Override public ShuoShuoAuto top() { return ShuoShuoAuto.INSTANCE; }
    @Override public NatureElements.Tu bottom() { return NatureElements.TU; }

    @Override public CompositionLayoutT layout() { return this; }

    @Override public String glyph() { return "\u5851"; }

    @Override public PinyinSyllable pinyin() {
        return new PinyinSyllable(Initial.S, new Final(Head.U, Body.U, Tail.NONE), Tone.FOURTH);
    }

    @Override public int strokes() { return 0; }
    @Override public int radicalNo() { return 0; }
    @Override public String meaning() { return ""; }

    @Override public EtymologicalCategory etymology() {
        return new EtymologicalCategory.PhonoSemantic(NatureElements.TU, ShuoShuoAuto.INSTANCE);
    }
}
