// AUTO-GENERATED by Depth1GenerateMain - do not edit by hand.
package kranji.common.depth1.p;

import kranji.classification.EtymologicalCategory.*;
import kranji.component.basic.BasicComponents;
import kranji.pinyin.Body;
import kranji.pinyin.Final;
import kranji.pinyin.Head;
import kranji.pinyin.Initial;
import kranji.pinyin.PinyinSyllable;
import kranji.pinyin.Tail;
import kranji.pinyin.Tone;
import kranji.singular.actions.ActionsAndStates;
import kranji.singular.body.BodyParts;
import kranji.singular.nature.NatureElements;
import kranji.zi.ComposedPart;
import kranji.zi.ComposedZi;
import kranji.zi.CompositionLayout.*;
import kranji.zi.SingularPart;
import kranji.zi.ZiChar;
import java.util.List;

public final class O1 {

    private O1() {}

    public static final ComposedZi PO_SLOPE = new ComposedZi(
            new ZiChar.Unicode("\u5761"),
            new PinyinSyllable(Initial.P, new Final(Head.OPEN, Body.O, Tail.NONE), Tone.FIRST),
            8, 32, "",
            new LeftRight(NatureElements.TU, BodyParts.PI),
            new PhonoSemantic(NatureElements.TU, BodyParts.PI));

    public static final ComposedZi PO_SPLASH = new ComposedZi(
            new ZiChar.Unicode("\u6CFC"),
            new PinyinSyllable(Initial.P, new Final(Head.OPEN, Body.O, Tail.NONE), Tone.FIRST),
            8, 85, "",
            new LeftRight(BasicComponents.SAN_DIAN_SHUI, ActionsAndStates.FA_SEND),
            new PhonoSemantic(BasicComponents.SAN_DIAN_SHUI, ActionsAndStates.FA_SEND));

    public static final List<ComposedZi> ALL = List.of(
            PO_SLOPE,
            PO_SPLASH);
}
