// AUTO-GENERATED by Depth1GenerateMain - do not edit by hand.
package kranji.common.depth1.p;

import kranji.classification.EtymologicalCategory.*;
import kranji.component.basic.BasicComponents;
import kranji.pinyin.Body;
import kranji.pinyin.Final;
import kranji.pinyin.Head;
import kranji.pinyin.Initial;
import kranji.pinyin.PinyinSyllable;
import kranji.pinyin.Tail;
import kranji.pinyin.Tone;
import kranji.singular.tools.ToolsAndVessels;
import kranji.zi.ComposedPart;
import kranji.zi.ComposedZi;
import kranji.zi.CompositionLayout.*;
import kranji.zi.SingularPart;
import kranji.zi.ZiChar;
import java.util.List;

public final class U1 {

    private U1() {}

    public static final ComposedZi PU_POUNCE = new ComposedZi(
            new ZiChar.Unicode("\u6251"),
            new PinyinSyllable(Initial.P, new Final(Head.U, Body.U, Tail.NONE), Tone.FIRST),
            5, 64, "",
            new LeftRight(BasicComponents.TI_SHOU_PANG, ToolsAndVessels.BU_DIVINATION),
            new PhonoSemantic(BasicComponents.TI_SHOU_PANG, ToolsAndVessels.BU_DIVINATION));

    public static final List<ComposedZi> ALL = List.of(
            PU_POUNCE);
}
