// AUTO-GENERATED by CatalogIteratorMain - do not edit by hand.
package kranji.common.perclass.promoted.k.uang4;

import kranji.classification.EtymologicalCategory;
import kranji.common.perclass.promoted.k.uang1.KuangRectify;
import kranji.component.basic.BasicComponents;
import kranji.component.basic.WoodFamily;
import kranji.pinyin.Body;
import kranji.pinyin.Final;
import kranji.pinyin.Head;
import kranji.pinyin.Initial;
import kranji.pinyin.PinyinSyllable;
import kranji.pinyin.Tail;
import kranji.pinyin.Tone;
import kranji.zi.ComposedZiT;
import kranji.zi.CompositionLayoutT;
import kranji.zi.LeftRightT;

public record KuangFrame() implements ComposedZiT, LeftRightT<WoodFamily.Mu, KuangRectify> {

    public static final KuangFrame INSTANCE = new KuangFrame();

    @Override public WoodFamily.Mu left() { return BasicComponents.MU; }
    @Override public KuangRectify right() { return KuangRectify.INSTANCE; }

    @Override public CompositionLayoutT layout() { return this; }

    @Override public String glyph() { return "\u6846"; }

    @Override public PinyinSyllable pinyin() {
        return new PinyinSyllable(Initial.K, new Final(Head.U, Body.A, Tail.NG), Tone.FOURTH);
    }

    @Override public int strokes() { return 0; }
    @Override public int radicalNo() { return 0; }
    @Override public String meaning() { return ""; }

    @Override public EtymologicalCategory etymology() {
        return new EtymologicalCategory.PhonoSemantic(BasicComponents.MU, KuangRectify.INSTANCE);
    }
}
