// AUTO-GENERATED by kranji-codegen. Do not edit by hand.
package kranji.singular.actions.l;

import kranji.library.BasicSet;
import kranji.library.LibraryMember;
import kranji.zi.SingularZi;

public record Li_Stand() implements LibraryMember<BasicSet>, SingularZi {
    public static final Li_Stand INSTANCE = new Li_Stand();

    @Override public String glyph() { return "\u7ACB"; }
    @Override public String meaning() { return "stand"; }
    @Override public String pinyinText() { return "l\u00EC"; }
    @Override public int strokes() { return 5; }
    @Override public BasicSet library() { return BasicSet.INSTANCE; }
}
