// AUTO-GENERATED by Depth1GenerateMain - do not edit by hand.
package kranji.common.depth1.zh;

import kranji.classification.EtymologicalCategory.*;
import kranji.component.basic.BasicComponents;
import kranji.pinyin.Body;
import kranji.pinyin.Final;
import kranji.pinyin.Head;
import kranji.pinyin.Initial;
import kranji.pinyin.PinyinSyllable;
import kranji.pinyin.Tail;
import kranji.pinyin.Tone;
import kranji.singular.people.PeopleAndRoles;
import kranji.zi.ComposedPart;
import kranji.zi.ComposedZi;
import kranji.zi.CompositionLayout.*;
import kranji.zi.SingularPart;
import kranji.zi.ZiChar;
import java.util.List;

public final class E4 {

    private E4() {}

    public static final ComposedZi ZHE_THIS = new ComposedZi(
            new ZiChar.Unicode("\u8FD9"),
            new PinyinSyllable(Initial.ZH, new Final(Head.OPEN, Body.E, Tail.NONE), Tone.FOURTH),
            7, 162, "",
            new SemiEnclosureBottomLeft(BasicComponents.ZOU_ZHI_DI, PeopleAndRoles.WEN),
            new PhonoSemantic(BasicComponents.ZOU_ZHI_DI, PeopleAndRoles.WEN));

    public static final List<ComposedZi> ALL = List.of(
            ZHE_THIS);
}
