// AUTO-GENERATED by Depth1GenerateMain - do not edit by hand.
package kranji.common.depth1.zh;

import kranji.classification.EtymologicalCategory.*;
import kranji.component.basic.BasicComponents;
import kranji.pinyin.Body;
import kranji.pinyin.Final;
import kranji.pinyin.Head;
import kranji.pinyin.Initial;
import kranji.pinyin.PinyinSyllable;
import kranji.pinyin.Tail;
import kranji.pinyin.Tone;
import kranji.singular.body.BodyParts;
import kranji.zi.ComposedPart;
import kranji.zi.ComposedZi;
import kranji.zi.CompositionLayout.*;
import kranji.zi.SingularPart;
import kranji.zi.ZiChar;
import java.util.List;

public final class Ua1 {

    private Ua1() {}

    public static final ComposedZi ZHUA_GRAB = new ComposedZi(
            new ZiChar.Unicode("\u6293"),
            new PinyinSyllable(Initial.ZH, new Final(Head.U, Body.A, Tail.NONE), Tone.FIRST),
            7, 64, "",
            new LeftRight(BasicComponents.TI_SHOU_PANG, BodyParts.ZHUA),
            new PhonoSemantic(BasicComponents.TI_SHOU_PANG, BodyParts.ZHUA));

    public static final List<ComposedZi> ALL = List.of(
            ZHUA_GRAB);
}
