// AUTO-GENERATED by CatalogIteratorMain - do not edit by hand.
package kranji.common.perclass.promoted.q.i3;

import kranji.classification.EtymologicalCategory;
import kranji.pinyin.Body;
import kranji.pinyin.Final;
import kranji.pinyin.Head;
import kranji.pinyin.Initial;
import kranji.pinyin.PinyinSyllable;
import kranji.pinyin.Tail;
import kranji.pinyin.Tone;
import kranji.singular.concepts.AbstractConcepts;
import kranji.singular.nature.NatureElements;
import kranji.zi.ComposedZiT;
import kranji.zi.CompositionLayoutT;
import kranji.zi.TopBottomT;

public record QiHow() implements ComposedZiT, TopBottomT<NatureElements.Shan, AbstractConcepts.Ji_Self> {

    public static final QiHow INSTANCE = new QiHow();

    @Override public NatureElements.Shan top() { return NatureElements.SHAN; }
    @Override public AbstractConcepts.Ji_Self bottom() { return AbstractConcepts.JI_SELF; }

    @Override public CompositionLayoutT layout() { return this; }

    @Override public String glyph() { return "\u5C82"; }

    @Override public PinyinSyllable pinyin() {
        return new PinyinSyllable(Initial.Q, new Final(Head.OPEN, Body.I, Tail.NONE), Tone.THIRD);
    }

    @Override public int strokes() { return 0; }
    @Override public int radicalNo() { return 0; }
    @Override public String meaning() { return ""; }

    @Override public EtymologicalCategory etymology() {
        return new EtymologicalCategory.DerivativeCognate("");
    }
}
