// AUTO-GENERATED by CatalogIteratorMain - do not edit by hand.
package kranji.common.perclass.promoted.r.uen4;

import kranji.pinyin.Body;
import kranji.pinyin.Final;
import kranji.pinyin.Head;
import kranji.pinyin.Initial;
import kranji.pinyin.PinyinSyllable;
import kranji.pinyin.Tail;
import kranji.pinyin.Tone;
import kranji.zi.SingularZi;

public record RunRunAuto() implements SingularZi {

    public static final RunRunAuto INSTANCE = new RunRunAuto();

    @Override public String glyph() { return "\u95F0"; }

    @Override public PinyinSyllable pinyin() {
        return new PinyinSyllable(Initial.R, new Final(Head.U, Body.E, Tail.N), Tone.FOURTH);
    }

    @Override public boolean unsure() { return true; }
}
