// AUTO-GENERATED by PerclassGenerateMain - do not edit by hand.
package kranji.common.perclass.q.ian1;

import kranji.classification.EtymologicalCategory;
import kranji.component.basic.BasicComponents;
import kranji.component.basic.SpeechFamily.YanZiPang;
import kranji.pinyin.Body;
import kranji.pinyin.Final;
import kranji.pinyin.Head;
import kranji.pinyin.Initial;
import kranji.pinyin.PinyinSyllable;
import kranji.pinyin.Tail;
import kranji.pinyin.Tone;
import kranji.singular.actions.ActionsAndStates;
import kranji.singular.actions.ActionsAndStates.Jian_Combine;
import kranji.zi.ComposedZiT;
import kranji.zi.CompositionLayoutT;
import kranji.zi.LeftRightT;

public record QianModest() implements ComposedZiT, LeftRightT<YanZiPang, Jian_Combine> {

    public static final QianModest INSTANCE = new QianModest();

    @Override public YanZiPang left() { return BasicComponents.YAN_ZI_PANG; }
    @Override public Jian_Combine right() { return ActionsAndStates.JIAN_COMBINE; }

    @Override public CompositionLayoutT layout() { return this; }

    @Override public String glyph() { return "\u8C26"; }

    @Override public PinyinSyllable pinyin() {
        return new PinyinSyllable(Initial.Q, new Final(Head.I, Body.A, Tail.N), Tone.FIRST);
    }

    @Override public int strokes() { return 12; }
    @Override public int radicalNo() { return 149; }
    @Override public String meaning() { return ""; }

    @Override public EtymologicalCategory etymology() {
        return new EtymologicalCategory.PhonoSemantic(BasicComponents.YAN_ZI_PANG, ActionsAndStates.JIAN_COMBINE);
    }
}
