// AUTO-GENERATED by CatalogIteratorMain - do not edit by hand.
package kranji.common.perclass.promoted.x.ian1;

import kranji.classification.EtymologicalCategory;
import kranji.component.basic.BasicComponents;
import kranji.component.basic.SilkFamily;
import kranji.pinyin.Body;
import kranji.pinyin.Final;
import kranji.pinyin.Head;
import kranji.pinyin.Initial;
import kranji.pinyin.PinyinSyllable;
import kranji.pinyin.Tail;
import kranji.pinyin.Tone;
import kranji.singular.numbers.NumbersAndMeasure;
import kranji.zi.ComposedZiT;
import kranji.zi.CompositionLayoutT;
import kranji.zi.LeftRightT;

public record XianFine() implements ComposedZiT, LeftRightT<SilkFamily.JiaoSiPang, NumbersAndMeasure.Qian> {

    public static final XianFine INSTANCE = new XianFine();

    @Override public SilkFamily.JiaoSiPang left() { return BasicComponents.JIAO_SI_PANG; }
    @Override public NumbersAndMeasure.Qian right() { return NumbersAndMeasure.QIAN; }

    @Override public CompositionLayoutT layout() { return this; }

    @Override public String glyph() { return "\u7EA4"; }

    @Override public PinyinSyllable pinyin() {
        return new PinyinSyllable(Initial.X, new Final(Head.I, Body.A, Tail.N), Tone.FIRST);
    }

    @Override public int strokes() { return 0; }
    @Override public int radicalNo() { return 0; }
    @Override public String meaning() { return ""; }

    @Override public EtymologicalCategory etymology() {
        return new EtymologicalCategory.PhonoSemantic(BasicComponents.JIAO_SI_PANG, NumbersAndMeasure.QIAN);
    }
}
