// AUTO-GENERATED by kranji-codegen. Do not edit by hand.
package kranji.singular.actions.m;

import kranji.library.BasicSet;
import kranji.library.LibraryMember;
import kranji.zi.SingularZi;

public record Mian() implements LibraryMember<BasicSet>, SingularZi {
    public static final Mian INSTANCE = new Mian();

    @Override public String glyph() { return "\u514D"; }
    @Override public String meaning() { return "avoid, exempt"; }
    @Override public String pinyinText() { return "mi\u01CEn"; }
    @Override public int strokes() { return 7; }
    @Override public BasicSet library() { return BasicSet.INSTANCE; }
}
