// AUTO-GENERATED by PerclassGenerateMain - do not edit by hand.
package kranji.common.perclass.q.van2;

import kranji.classification.EtymologicalCategory;
import kranji.pinyin.Body;
import kranji.pinyin.Final;
import kranji.pinyin.Head;
import kranji.pinyin.Initial;
import kranji.pinyin.PinyinSyllable;
import kranji.pinyin.Tail;
import kranji.pinyin.Tone;
import kranji.singular.materials.Materials;
import kranji.singular.materials.Materials.Bai_White;
import kranji.singular.nature.NatureElements;
import kranji.singular.nature.NatureElements.Shui;
import kranji.zi.ComposedZiT;
import kranji.zi.CompositionLayoutT;
import kranji.zi.TopBottomT;

public record QuanSpring() implements ComposedZiT, TopBottomT<Bai_White, Shui> {

    public static final QuanSpring INSTANCE = new QuanSpring();

    @Override public Bai_White top() { return Materials.BAI_WHITE; }
    @Override public Shui bottom() { return NatureElements.SHUI; }

    @Override public CompositionLayoutT layout() { return this; }

    @Override public String glyph() { return "\u6CC9"; }

    @Override public PinyinSyllable pinyin() {
        return new PinyinSyllable(Initial.Q, new Final(Head.V, Body.A, Tail.N), Tone.SECOND);
    }

    @Override public int strokes() { return 9; }
    @Override public int radicalNo() { return 85; }
    @Override public String meaning() { return ""; }

    @Override public EtymologicalCategory etymology() {
        return new EtymologicalCategory.CompoundIndicative("白(clear) + 水(water) → spring water");
    }
}
