// AUTO-GENERATED by kranji-codegen. Do not edit by hand.
package kranji.singular.space.zero;

import kranji.library.BasicSet;
import kranji.library.LibraryMember;
import kranji.zi.SingularZi;

public record Ye_Page() implements LibraryMember<BasicSet>, SingularZi {
    public static final Ye_Page INSTANCE = new Ye_Page();

    @Override public String glyph() { return "\u9875"; }
    @Override public String meaning() { return "page/head"; }
    @Override public String pinyinText() { return "y\u00E8"; }
    @Override public int strokes() { return 6; }
    @Override public BasicSet library() { return BasicSet.INSTANCE; }
}
