// AUTO-GENERATED by PerclassGenerateMain - do not edit by hand.
package kranji.common.perclass.g.e1;

import kranji.classification.EtymologicalCategory;
import kranji.pinyin.Body;
import kranji.pinyin.Final;
import kranji.pinyin.Head;
import kranji.pinyin.Initial;
import kranji.pinyin.PinyinSyllable;
import kranji.pinyin.Tail;
import kranji.pinyin.Tone;
import kranji.singular.actions.ActionsAndStates;
import kranji.singular.actions.ActionsAndStates.Ke;
import kranji.zi.ComposedZiT;
import kranji.zi.CompositionLayoutT;
import kranji.zi.TopBottomT;

public record GeElder() implements ComposedZiT, TopBottomT<Ke, Ke> {

    public static final GeElder INSTANCE = new GeElder();

    @Override public Ke top() { return ActionsAndStates.KE; }
    @Override public Ke bottom() { return ActionsAndStates.KE; }

    @Override public CompositionLayoutT layout() { return this; }

    @Override public String glyph() { return "\u54E5"; }

    @Override public PinyinSyllable pinyin() {
        return new PinyinSyllable(Initial.G, new Final(Head.OPEN, Body.E, Tail.NONE), Tone.FIRST);
    }

    @Override public int strokes() { return 10; }
    @Override public int radicalNo() { return 30; }
    @Override public String meaning() { return ""; }

    @Override public EtymologicalCategory etymology() {
        return new EtymologicalCategory.CompoundIndicative("doubled 可 — elder brother");
    }
}
