// AUTO-GENERATED by PerclassGenerateMain - do not edit by hand.
package kranji.common.perclass.g.e1;

import kranji.classification.EtymologicalCategory;
import kranji.common.perclass.g.e1.GeElder;
import kranji.pinyin.Body;
import kranji.pinyin.Final;
import kranji.pinyin.Head;
import kranji.pinyin.Initial;
import kranji.pinyin.PinyinSyllable;
import kranji.pinyin.Tail;
import kranji.pinyin.Tone;
import kranji.singular.radicals.RadicalComponents;
import kranji.singular.radicals.RadicalComponents.Qian_Owe;
import kranji.zi.ComposedZiT;
import kranji.zi.CompositionLayoutT;
import kranji.zi.LeftRightT;

public record GeSing() implements ComposedZiT, LeftRightT<GeElder, Qian_Owe> {

    public static final GeSing INSTANCE = new GeSing();

    @Override public GeElder left() { return GeElder.INSTANCE; }
    @Override public Qian_Owe right() { return RadicalComponents.QIAN_OWE; }

    @Override public CompositionLayoutT layout() { return this; }

    @Override public String glyph() { return "\u6B4C"; }

    @Override public PinyinSyllable pinyin() {
        return new PinyinSyllable(Initial.G, new Final(Head.OPEN, Body.E, Tail.NONE), Tone.FIRST);
    }

    @Override public int strokes() { return 14; }
    @Override public int radicalNo() { return 76; }
    @Override public String meaning() { return ""; }

    @Override public EtymologicalCategory etymology() {
        return new EtymologicalCategory.PhonoSemantic(RadicalComponents.QIAN_OWE, GeElder.INSTANCE);
    }
}
