// AUTO-GENERATED by CatalogIteratorMain - do not edit by hand.
package kranji.common.perclass.promoted.r.e3;

import kranji.classification.EtymologicalCategory;
import kranji.common.perclass.r.uo4.Ruo;
import kranji.pinyin.Body;
import kranji.pinyin.Final;
import kranji.pinyin.Head;
import kranji.pinyin.Initial;
import kranji.pinyin.PinyinSyllable;
import kranji.pinyin.Tail;
import kranji.pinyin.Tone;
import kranji.singular.body.BodyParts;
import kranji.zi.ComposedZiT;
import kranji.zi.CompositionLayoutT;
import kranji.zi.TopBottomT;

public record ReProvoke() implements ComposedZiT, TopBottomT<Ruo, BodyParts.Xin> {

    public static final ReProvoke INSTANCE = new ReProvoke();

    @Override public Ruo top() { return Ruo.INSTANCE; }
    @Override public BodyParts.Xin bottom() { return BodyParts.XIN; }

    @Override public CompositionLayoutT layout() { return this; }

    @Override public String glyph() { return "\u60F9"; }

    @Override public PinyinSyllable pinyin() {
        return new PinyinSyllable(Initial.R, new Final(Head.OPEN, Body.E, Tail.NONE), Tone.THIRD);
    }

    @Override public int strokes() { return 0; }
    @Override public int radicalNo() { return 0; }
    @Override public String meaning() { return ""; }

    @Override public EtymologicalCategory etymology() {
        return new EtymologicalCategory.PhonoSemantic(BodyParts.XIN, Ruo.INSTANCE);
    }
}
