// AUTO-GENERATED by PerclassGenerateMain - do not edit by hand.
package kranji.common.perclass.zh.en3;

import kranji.classification.EtymologicalCategory;
import kranji.component.basic.BasicComponents;
import kranji.component.basic.SpeechFamily.YanZiPang;
import kranji.pinyin.Body;
import kranji.pinyin.Final;
import kranji.pinyin.Head;
import kranji.pinyin.Initial;
import kranji.pinyin.PinyinSyllable;
import kranji.pinyin.Tail;
import kranji.pinyin.Tone;
import kranji.singular.people.PeopleAndRoles;
import kranji.singular.people.PeopleAndRoles.Ren;
import kranji.singular.radicals.RadicalComponents;
import kranji.singular.radicals.RadicalComponents.Shan_Hair;
import kranji.zi.ComposedZiT;
import kranji.zi.CompositionLayoutT;
import kranji.zi.LeftRightT;
import kranji.zi.TopBottomPartT;

public record ZhenDiagnose() implements ComposedZiT, LeftRightT<YanZiPang, TopBottomPartT<Ren, Shan_Hair>> {

    public static final ZhenDiagnose INSTANCE = new ZhenDiagnose();

    @Override public YanZiPang left() { return BasicComponents.YAN_ZI_PANG; }
    @Override public TopBottomPartT<Ren, Shan_Hair> right() { return new TopBottomPartT<>(PeopleAndRoles.REN, RadicalComponents.SHAN_HAIR); }

    @Override public CompositionLayoutT layout() { return this; }

    @Override public String glyph() { return "\u8BCA"; }

    @Override public PinyinSyllable pinyin() {
        return new PinyinSyllable(Initial.ZH, new Final(Head.OPEN, Body.E, Tail.N), Tone.THIRD);
    }

    @Override public int strokes() { return 7; }
    @Override public int radicalNo() { return 149; }
    @Override public String meaning() { return ""; }

    @Override public EtymologicalCategory etymology() {
        return new EtymologicalCategory.PhonoSemantic(BasicComponents.YAN_ZI_PANG, new TopBottomPartT<>(PeopleAndRoles.REN, RadicalComponents.SHAN_HAIR));
    }
}
