// AUTO-GENERATED by PerclassGenerateMain - do not edit by hand.
package kranji.common.perclass.f.ang4;

import kranji.classification.EtymologicalCategory;
import kranji.component.basic.BasicComponents;
import kranji.component.basic.StrikeFamily.FanWenPang;
import kranji.pinyin.Body;
import kranji.pinyin.Final;
import kranji.pinyin.Head;
import kranji.pinyin.Initial;
import kranji.pinyin.PinyinSyllable;
import kranji.pinyin.Tail;
import kranji.pinyin.Tone;
import kranji.singular.space.SpaceAndDirection;
import kranji.singular.space.SpaceAndDirection.Fang;
import kranji.zi.ComposedZiT;
import kranji.zi.CompositionLayoutT;
import kranji.zi.LeftRightT;

public record FangRelease() implements ComposedZiT, LeftRightT<Fang, FanWenPang> {

    public static final FangRelease INSTANCE = new FangRelease();

    @Override public Fang left() { return SpaceAndDirection.FANG; }
    @Override public FanWenPang right() { return BasicComponents.FAN_WEN_PANG; }

    @Override public CompositionLayoutT layout() { return this; }

    @Override public String glyph() { return "\u653E"; }

    @Override public PinyinSyllable pinyin() {
        return new PinyinSyllable(Initial.F, new Final(Head.OPEN, Body.A, Tail.NG), Tone.FOURTH);
    }

    @Override public int strokes() { return 8; }
    @Override public int radicalNo() { return 66; }
    @Override public String meaning() { return ""; }

    @Override public EtymologicalCategory etymology() {
        return new EtymologicalCategory.CompoundIndicative("方(direction) + 攵(strike) → release");
    }
}
