// AUTO-GENERATED by PerclassGenerateMain - do not edit by hand.
package kranji.common.perclass.t.an4;

import kranji.classification.EtymologicalCategory;
import kranji.pinyin.Body;
import kranji.pinyin.Final;
import kranji.pinyin.Head;
import kranji.pinyin.Initial;
import kranji.pinyin.PinyinSyllable;
import kranji.pinyin.Tail;
import kranji.pinyin.Tone;
import kranji.singular.actions.ActionsAndStates;
import kranji.singular.actions.ActionsAndStates.You_Again;
import kranji.singular.body.BodyParts;
import kranji.singular.body.BodyParts.Kou;
import kranji.zi.ComposedZiT;
import kranji.zi.CompositionLayoutT;
import kranji.zi.LeftRightT;

public record TanSigh() implements ComposedZiT, LeftRightT<Kou, You_Again> {

    public static final TanSigh INSTANCE = new TanSigh();

    @Override public Kou left() { return BodyParts.KOU; }
    @Override public You_Again right() { return ActionsAndStates.YOU_AGAIN; }

    @Override public CompositionLayoutT layout() { return this; }

    @Override public String glyph() { return "\u53F9"; }

    @Override public PinyinSyllable pinyin() {
        return new PinyinSyllable(Initial.T, new Final(Head.OPEN, Body.A, Tail.N), Tone.FOURTH);
    }

    @Override public int strokes() { return 5; }
    @Override public int radicalNo() { return 30; }
    @Override public String meaning() { return ""; }

    @Override public EtymologicalCategory etymology() {
        return new EtymologicalCategory.PhonoSemantic(BodyParts.KOU, ActionsAndStates.YOU_AGAIN);
    }
}
