// AUTO-GENERATED by PerclassGenerateMain - do not edit by hand.
package kranji.common.perclass.l.u2;

import kranji.classification.EtymologicalCategory;
import kranji.component.basic.BasicComponents;
import kranji.component.basic.PlantFamily.CaoZiTou;
import kranji.pinyin.Body;
import kranji.pinyin.Final;
import kranji.pinyin.Head;
import kranji.pinyin.Initial;
import kranji.pinyin.PinyinSyllable;
import kranji.pinyin.Tail;
import kranji.pinyin.Tone;
import kranji.singular.structures.Structures;
import kranji.singular.structures.Structures.Hu;
import kranji.zi.ComposedZiT;
import kranji.zi.CompositionLayoutT;
import kranji.zi.TopBottomT;

public record LuReed() implements ComposedZiT, TopBottomT<CaoZiTou, Hu> {

    public static final LuReed INSTANCE = new LuReed();

    @Override public CaoZiTou top() { return BasicComponents.CAO_ZI_TOU; }
    @Override public Hu bottom() { return Structures.HU; }

    @Override public CompositionLayoutT layout() { return this; }

    @Override public String glyph() { return "\u82A6"; }

    @Override public PinyinSyllable pinyin() {
        return new PinyinSyllable(Initial.L, new Final(Head.U, Body.U, Tail.NONE), Tone.SECOND);
    }

    @Override public int strokes() { return 7; }
    @Override public int radicalNo() { return 140; }
    @Override public String meaning() { return ""; }

    @Override public EtymologicalCategory etymology() {
        return new EtymologicalCategory.PhonoSemantic(BasicComponents.CAO_ZI_TOU, Structures.HU);
    }
}
