// AUTO-GENERATED by PerclassGenerateMain - do not edit by hand.
package kranji.common.perclass.k.uen3;

import kranji.classification.EtymologicalCategory;
import kranji.common.perclass.k.uen4.Kun;
import kranji.component.basic.BasicComponents;
import kranji.component.basic.HandFamily.TiShouPang;
import kranji.pinyin.Body;
import kranji.pinyin.Final;
import kranji.pinyin.Head;
import kranji.pinyin.Initial;
import kranji.pinyin.PinyinSyllable;
import kranji.pinyin.Tail;
import kranji.pinyin.Tone;
import kranji.zi.ComposedZiT;
import kranji.zi.CompositionLayoutT;
import kranji.zi.LeftRightT;

public record KunBundle() implements ComposedZiT, LeftRightT<TiShouPang, Kun> {

    public static final KunBundle INSTANCE = new KunBundle();

    @Override public TiShouPang left() { return BasicComponents.TI_SHOU_PANG; }
    @Override public Kun right() { return Kun.INSTANCE; }

    @Override public CompositionLayoutT layout() { return this; }

    @Override public String glyph() { return "\u6346"; }

    @Override public PinyinSyllable pinyin() {
        return new PinyinSyllable(Initial.K, new Final(Head.U, Body.E, Tail.N), Tone.THIRD);
    }

    @Override public int strokes() { return 10; }
    @Override public int radicalNo() { return 64; }
    @Override public String meaning() { return ""; }

    @Override public EtymologicalCategory etymology() {
        return new EtymologicalCategory.PhonoSemantic(BasicComponents.TI_SHOU_PANG, Kun.INSTANCE);
    }
}
