// AUTO-GENERATED by CatalogIteratorMain - do not edit by hand.
package kranji.common.perclass.promoted.ch.a4;

import kranji.classification.EtymologicalCategory;
import kranji.common.perclass.promoted.zero.iang2.YangSheepVariantAtom;
import kranji.pinyin.Body;
import kranji.pinyin.Final;
import kranji.pinyin.Head;
import kranji.pinyin.Initial;
import kranji.pinyin.PinyinSyllable;
import kranji.pinyin.Tail;
import kranji.pinyin.Tone;
import kranji.singular.actions.ActionsAndStates;
import kranji.zi.ComposedZiT;
import kranji.zi.CompositionLayoutT;
import kranji.zi.SemiEnclosureUpperLeftT;

public record ChaDiffer() implements ComposedZiT, SemiEnclosureUpperLeftT<YangSheepVariantAtom, ActionsAndStates.Gong_Work> {

    public static final ChaDiffer INSTANCE = new ChaDiffer();

    @Override public YangSheepVariantAtom wrapper() { return YangSheepVariantAtom.INSTANCE; }
    @Override public ActionsAndStates.Gong_Work content() { return ActionsAndStates.GONG_WORK; }

    @Override public CompositionLayoutT layout() { return this; }

    @Override public String glyph() { return "\u5DEE"; }

    @Override public PinyinSyllable pinyin() {
        return new PinyinSyllable(Initial.CH, new Final(Head.OPEN, Body.A, Tail.NONE), Tone.FOURTH);
    }

    @Override public int strokes() { return 0; }
    @Override public int radicalNo() { return 0; }
    @Override public String meaning() { return ""; }

    @Override public EtymologicalCategory etymology() {
        return new EtymologicalCategory.CompoundIndicative("");
    }
}
