// AUTO-GENERATED by kranji-codegen. Do not edit by hand.
package kranji.singular.nature.q;

import kranji.library.BasicSet;
import kranji.library.LibraryMember;
import kranji.zi.SingularZi;

public record Qi() implements LibraryMember<BasicSet>, SingularZi {
    public static final Qi INSTANCE = new Qi();

    @Override public String glyph() { return "\u6C14"; }
    @Override public String meaning() { return "air, gas"; }
    @Override public String pinyinText() { return "q\u00EC"; }
    @Override public int strokes() { return 4; }
    @Override public BasicSet library() { return BasicSet.INSTANCE; }
}
