// AUTO-GENERATED by CatalogIteratorMain - do not edit by hand.
package kranji.common.perclass.promoted.zero.iao2;

import kranji.classification.EtymologicalCategory;
import kranji.pinyin.Body;
import kranji.pinyin.Final;
import kranji.pinyin.Head;
import kranji.pinyin.Initial;
import kranji.pinyin.PinyinSyllable;
import kranji.pinyin.Tail;
import kranji.pinyin.Tone;
import kranji.singular.structures.Structures;
import kranji.singular.tools.ToolsAndVessels;
import kranji.zi.ComposedZiT;
import kranji.zi.CompositionLayoutT;
import kranji.zi.SemiEnclosureUpperLeftT;

public record YaoKiln() implements ComposedZiT, SemiEnclosureUpperLeftT<Structures.Xue, ToolsAndVessels.Fou> {

    public static final YaoKiln INSTANCE = new YaoKiln();

    @Override public Structures.Xue wrapper() { return Structures.XUE; }
    @Override public ToolsAndVessels.Fou content() { return ToolsAndVessels.FOU; }

    @Override public CompositionLayoutT layout() { return this; }

    @Override public String glyph() { return "\u7A91"; }

    @Override public PinyinSyllable pinyin() {
        return new PinyinSyllable(Initial.ZERO, new Final(Head.I, Body.A, Tail.VOWEL_U), Tone.SECOND);
    }

    @Override public int strokes() { return 0; }
    @Override public int radicalNo() { return 0; }
    @Override public String meaning() { return ""; }

    @Override public EtymologicalCategory etymology() {
        return new EtymologicalCategory.DerivativeCognate("");
    }
}
