// AUTO-GENERATED by CatalogIteratorMain - do not edit by hand.
package kranji.common.perclass.promoted.zero.iao2;

import kranji.classification.EtymologicalCategory;
import kranji.common.perclass.promoted.zero.iao2.YaoYao;
import kranji.component.basic.BasicComponents;
import kranji.component.basic.HandFamily;
import kranji.pinyin.Body;
import kranji.pinyin.Final;
import kranji.pinyin.Head;
import kranji.pinyin.Initial;
import kranji.pinyin.PinyinSyllable;
import kranji.pinyin.Tail;
import kranji.pinyin.Tone;
import kranji.zi.ComposedZiT;
import kranji.zi.CompositionLayoutT;
import kranji.zi.LeftRightT;

public record YaoShake() implements ComposedZiT, LeftRightT<HandFamily.TiShouPang, YaoYao> {

    public static final YaoShake INSTANCE = new YaoShake();

    @Override public HandFamily.TiShouPang left() { return BasicComponents.TI_SHOU_PANG; }
    @Override public YaoYao right() { return YaoYao.INSTANCE; }

    @Override public CompositionLayoutT layout() { return this; }

    @Override public String glyph() { return "\u6447"; }

    @Override public PinyinSyllable pinyin() {
        return new PinyinSyllable(Initial.ZERO, new Final(Head.I, Body.A, Tail.VOWEL_U), Tone.SECOND);
    }

    @Override public int strokes() { return 0; }
    @Override public int radicalNo() { return 0; }
    @Override public String meaning() { return ""; }

    @Override public EtymologicalCategory etymology() {
        return new EtymologicalCategory.PhonoSemantic(BasicComponents.TI_SHOU_PANG, YaoYao.INSTANCE);
    }
}
