// AUTO-GENERATED by PerclassGenerateMain - do not edit by hand.
package kranji.common.perclass.zh.uang4;

import kranji.classification.EtymologicalCategory;
import kranji.pinyin.Body;
import kranji.pinyin.Final;
import kranji.pinyin.Head;
import kranji.pinyin.Initial;
import kranji.pinyin.PinyinSyllable;
import kranji.pinyin.Tail;
import kranji.pinyin.Tone;
import kranji.singular.animals.Animals;
import kranji.singular.animals.Animals.Quan;
import kranji.singular.space.SpaceAndDirection;
import kranji.singular.space.SpaceAndDirection.Pan;
import kranji.zi.ComposedZiT;
import kranji.zi.CompositionLayoutT;
import kranji.zi.LeftRightT;

public record ZhuangState() implements ComposedZiT, LeftRightT<Pan, Quan> {

    public static final ZhuangState INSTANCE = new ZhuangState();

    @Override public Pan left() { return SpaceAndDirection.PAN; }
    @Override public Quan right() { return Animals.QUAN; }

    @Override public CompositionLayoutT layout() { return this; }

    @Override public String glyph() { return "\u72B6"; }

    @Override public PinyinSyllable pinyin() {
        return new PinyinSyllable(Initial.ZH, new Final(Head.U, Body.A, Tail.NG), Tone.FOURTH);
    }

    @Override public int strokes() { return 7; }
    @Override public int radicalNo() { return 94; }
    @Override public String meaning() { return ""; }

    @Override public EtymologicalCategory etymology() {
        return new EtymologicalCategory.PhonoSemantic(SpaceAndDirection.PAN, Animals.QUAN);
    }
}
