// AUTO-GENERATED by CatalogIteratorMain - do not edit by hand.
package kranji.common.perclass.promoted.m.o2;

import kranji.classification.EtymologicalCategory;
import kranji.common.perclass.promoted.m.a2.MaHemp;
import kranji.pinyin.Body;
import kranji.pinyin.Final;
import kranji.pinyin.Head;
import kranji.pinyin.Initial;
import kranji.pinyin.PinyinSyllable;
import kranji.pinyin.Tail;
import kranji.pinyin.Tone;
import kranji.singular.nature.NatureElements;
import kranji.zi.ComposedZiT;
import kranji.zi.CompositionLayoutT;
import kranji.zi.TopBottomT;

public record MoGrind() implements ComposedZiT, TopBottomT<MaHemp, NatureElements.Shi> {

    public static final MoGrind INSTANCE = new MoGrind();

    @Override public MaHemp top() { return MaHemp.INSTANCE; }
    @Override public NatureElements.Shi bottom() { return NatureElements.SHI; }

    @Override public CompositionLayoutT layout() { return this; }

    @Override public String glyph() { return "\u78E8"; }

    @Override public PinyinSyllable pinyin() {
        return new PinyinSyllable(Initial.M, new Final(Head.OPEN, Body.O, Tail.NONE), Tone.SECOND);
    }

    @Override public int strokes() { return 0; }
    @Override public int radicalNo() { return 0; }
    @Override public String meaning() { return ""; }

    @Override public EtymologicalCategory etymology() {
        return new EtymologicalCategory.PhonoSemantic(NatureElements.SHI, MaHemp.INSTANCE);
    }
}
