// AUTO-GENERATED by CatalogIteratorMain - do not edit by hand.
package kranji.common.perclass.promoted.ch.u4;

import kranji.classification.EtymologicalCategory;
import kranji.pinyin.Body;
import kranji.pinyin.Final;
import kranji.pinyin.Head;
import kranji.pinyin.Initial;
import kranji.pinyin.PinyinSyllable;
import kranji.pinyin.Tail;
import kranji.pinyin.Tone;
import kranji.singular.nature.NatureElements;
import kranji.singular.radicals.RadicalComponents;
import kranji.zi.ComposedZiT;
import kranji.zi.CompositionLayoutT;
import kranji.zi.TopBottomT;

public record ChuLivestock() implements ComposedZiT, TopBottomT<RadicalComponents.Xuan_Dark, NatureElements.Tian> {

    public static final ChuLivestock INSTANCE = new ChuLivestock();

    @Override public RadicalComponents.Xuan_Dark top() { return RadicalComponents.XUAN_DARK; }
    @Override public NatureElements.Tian bottom() { return NatureElements.TIAN; }

    @Override public CompositionLayoutT layout() { return this; }

    @Override public String glyph() { return "\u755C"; }

    @Override public PinyinSyllable pinyin() {
        return new PinyinSyllable(Initial.CH, new Final(Head.U, Body.U, Tail.NONE), Tone.FOURTH);
    }

    @Override public int strokes() { return 0; }
    @Override public int radicalNo() { return 0; }
    @Override public String meaning() { return ""; }

    @Override public EtymologicalCategory etymology() {
        return new EtymologicalCategory.CompoundIndicative("");
    }
}
