// AUTO-GENERATED by kranji-codegen. Do not edit by hand.
package kranji.singular.actions.zero;

import kranji.library.BasicSet;
import kranji.library.LibraryMember;
import kranji.zi.SingularZi;

public record Wu_Affair() implements LibraryMember<BasicSet>, SingularZi {
    public static final Wu_Affair INSTANCE = new Wu_Affair();

    @Override public String glyph() { return "\u52A1"; }
    @Override public String meaning() { return "affair, business"; }
    @Override public String pinyinText() { return "w\u00F9"; }
    @Override public int strokes() { return 5; }
    @Override public BasicSet library() { return BasicSet.INSTANCE; }
}
