// AUTO-GENERATED by kranji-codegen. Do not edit by hand.
package kranji.singular.actions.zero;

import kranji.library.BasicSet;
import kranji.library.LibraryMember;
import kranji.zi.SingularZi;

public record Yi_Govern() implements LibraryMember<BasicSet>, SingularZi {
    public static final Yi_Govern INSTANCE = new Yi_Govern();

    @Override public String glyph() { return "\u4E42"; }
    @Override public String meaning() { return "govern, cut"; }
    @Override public String pinyinText() { return "y\u00EC"; }
    @Override public int strokes() { return 2; }
    @Override public BasicSet library() { return BasicSet.INSTANCE; }
}
