// AUTO-GENERATED by kranji-codegen. Do not edit by hand.
package kranji.singular.actions.zero;

import kranji.library.BasicSet;
import kranji.library.LibraryMember;
import kranji.zi.SingularZi;

public record Yu_Give() implements LibraryMember<BasicSet>, SingularZi {
    public static final Yu_Give INSTANCE = new Yu_Give();

    @Override public String glyph() { return "\u4E0E"; }
    @Override public String meaning() { return "give/participate"; }
    @Override public String pinyinText() { return "y\u01D4"; }
    @Override public int strokes() { return 3; }
    @Override public BasicSet library() { return BasicSet.INSTANCE; }
}
