// AUTO-GENERATED by CatalogIteratorMain - do not edit by hand.
package kranji.common.perclass.promoted.j.iao1;

import kranji.classification.EtymologicalCategory;
import kranji.component.basic.BasicComponents;
import kranji.component.basic.WoodFamily;
import kranji.pinyin.Body;
import kranji.pinyin.Final;
import kranji.pinyin.Head;
import kranji.pinyin.Initial;
import kranji.pinyin.PinyinSyllable;
import kranji.pinyin.Tail;
import kranji.pinyin.Tone;
import kranji.singular.people.PeopleAndRoles;
import kranji.zi.ComposedZiT;
import kranji.zi.CompositionLayoutT;
import kranji.zi.LeftRightT;

public record JiaoPepper() implements ComposedZiT, LeftRightT<WoodFamily.Mu, PeopleAndRoles.Shu_Uncle> {

    public static final JiaoPepper INSTANCE = new JiaoPepper();

    @Override public WoodFamily.Mu left() { return BasicComponents.MU; }
    @Override public PeopleAndRoles.Shu_Uncle right() { return PeopleAndRoles.SHU_UNCLE; }

    @Override public CompositionLayoutT layout() { return this; }

    @Override public String glyph() { return "\u6912"; }

    @Override public PinyinSyllable pinyin() {
        return new PinyinSyllable(Initial.J, new Final(Head.I, Body.A, Tail.VOWEL_U), Tone.FIRST);
    }

    @Override public int strokes() { return 0; }
    @Override public int radicalNo() { return 0; }
    @Override public String meaning() { return ""; }

    @Override public EtymologicalCategory etymology() {
        return new EtymologicalCategory.PhonoSemantic(BasicComponents.MU, PeopleAndRoles.SHU_UNCLE);
    }
}
