// AUTO-GENERATED by CatalogIteratorMain - do not edit by hand.
package kranji.common.perclass.promoted.j.iao1;

import kranji.classification.EtymologicalCategory;
import kranji.pinyin.Body;
import kranji.pinyin.Final;
import kranji.pinyin.Head;
import kranji.pinyin.Initial;
import kranji.pinyin.PinyinSyllable;
import kranji.pinyin.Tail;
import kranji.pinyin.Tone;
import kranji.singular.people.PeopleAndRoles;
import kranji.singular.unsure.UnsureSingulars;
import kranji.zi.ComposedZiT;
import kranji.zi.CompositionLayoutT;
import kranji.zi.LeftRightT;

public record JiaoTender() implements ComposedZiT, LeftRightT<PeopleAndRoles.Nv, UnsureSingulars.Qiao_Tall> {

    public static final JiaoTender INSTANCE = new JiaoTender();

    @Override public PeopleAndRoles.Nv left() { return PeopleAndRoles.NV; }
    @Override public UnsureSingulars.Qiao_Tall right() { return UnsureSingulars.QIAO_TALL; }

    @Override public CompositionLayoutT layout() { return this; }

    @Override public String glyph() { return "\u5A07"; }

    @Override public PinyinSyllable pinyin() {
        return new PinyinSyllable(Initial.J, new Final(Head.I, Body.A, Tail.VOWEL_U), Tone.FIRST);
    }

    @Override public int strokes() { return 0; }
    @Override public int radicalNo() { return 0; }
    @Override public String meaning() { return ""; }

    @Override public EtymologicalCategory etymology() {
        return new EtymologicalCategory.PhonoSemantic(PeopleAndRoles.NV, UnsureSingulars.QIAO_TALL);
    }
}
