// AUTO-GENERATED by PerclassGenerateMain - do not edit by hand.
package kranji.common.perclass.d.ian4;

import kranji.classification.EtymologicalCategory;
import kranji.common.perclass.zh.an4.ZhanOccupy;
import kranji.pinyin.Body;
import kranji.pinyin.Final;
import kranji.pinyin.Head;
import kranji.pinyin.Initial;
import kranji.pinyin.PinyinSyllable;
import kranji.pinyin.Tail;
import kranji.pinyin.Tone;
import kranji.singular.structures.Structures;
import kranji.singular.structures.Structures.Guang;
import kranji.zi.ComposedZiT;
import kranji.zi.CompositionLayoutT;
import kranji.zi.SemiEnclosureUpperLeftT;

public record DianShop() implements ComposedZiT, SemiEnclosureUpperLeftT<Guang, ZhanOccupy> {

    public static final DianShop INSTANCE = new DianShop();

    @Override public Guang wrapper() { return Structures.GUANG; }
    @Override public ZhanOccupy content() { return ZhanOccupy.INSTANCE; }

    @Override public CompositionLayoutT layout() { return this; }

    @Override public String glyph() { return "\u5E97"; }

    @Override public PinyinSyllable pinyin() {
        return new PinyinSyllable(Initial.D, new Final(Head.I, Body.A, Tail.N), Tone.FOURTH);
    }

    @Override public int strokes() { return 8; }
    @Override public int radicalNo() { return 53; }
    @Override public String meaning() { return ""; }

    @Override public EtymologicalCategory etymology() {
        return new EtymologicalCategory.PhonoSemantic(Structures.GUANG, ZhanOccupy.INSTANCE);
    }
}
