// AUTO-GENERATED by CatalogIteratorMain - do not edit by hand.
package kranji.common.perclass.promoted.zh.ai4;

import kranji.classification.EtymologicalCategory;
import kranji.component.basic.BasicComponents;
import kranji.component.basic.PersonFamily;
import kranji.pinyin.Body;
import kranji.pinyin.Final;
import kranji.pinyin.Head;
import kranji.pinyin.Initial;
import kranji.pinyin.PinyinSyllable;
import kranji.pinyin.Tail;
import kranji.pinyin.Tone;
import kranji.singular.concepts.AbstractConcepts;
import kranji.zi.ComposedZiT;
import kranji.zi.CompositionLayoutT;
import kranji.zi.LeftRightT;

public record ZhaiDebt() implements ComposedZiT, LeftRightT<PersonFamily.DanRenPang, AbstractConcepts.Ze_Duty> {

    public static final ZhaiDebt INSTANCE = new ZhaiDebt();

    @Override public PersonFamily.DanRenPang left() { return BasicComponents.DAN_REN_PANG; }
    @Override public AbstractConcepts.Ze_Duty right() { return AbstractConcepts.ZE_DUTY; }

    @Override public CompositionLayoutT layout() { return this; }

    @Override public String glyph() { return "\u503A"; }

    @Override public PinyinSyllable pinyin() {
        return new PinyinSyllable(Initial.ZH, new Final(Head.OPEN, Body.A, Tail.VOWEL_I), Tone.FOURTH);
    }

    @Override public int strokes() { return 0; }
    @Override public int radicalNo() { return 0; }
    @Override public String meaning() { return ""; }

    @Override public EtymologicalCategory etymology() {
        return new EtymologicalCategory.PhonoSemantic(BasicComponents.DAN_REN_PANG, AbstractConcepts.ZE_DUTY);
    }
}
