// AUTO-GENERATED by PerclassGenerateMain - do not edit by hand.
package kranji.common.perclass.g.ong3;

import kranji.classification.EtymologicalCategory;
import kranji.pinyin.Body;
import kranji.pinyin.Final;
import kranji.pinyin.Head;
import kranji.pinyin.Initial;
import kranji.pinyin.PinyinSyllable;
import kranji.pinyin.Tail;
import kranji.pinyin.Tone;
import kranji.singular.actions.ActionsAndStates;
import kranji.singular.actions.ActionsAndStates.Gong_Work;
import kranji.singular.tools.ToolsAndVessels;
import kranji.singular.tools.ToolsAndVessels.Fan;
import kranji.zi.ComposedZiT;
import kranji.zi.CompositionLayoutT;
import kranji.zi.LeftRightT;

public record GongSolid() implements ComposedZiT, LeftRightT<Gong_Work, Fan> {

    public static final GongSolid INSTANCE = new GongSolid();

    @Override public Gong_Work left() { return ActionsAndStates.GONG_WORK; }
    @Override public Fan right() { return ToolsAndVessels.FAN; }

    @Override public CompositionLayoutT layout() { return this; }

    @Override public String glyph() { return "\u5DE9"; }

    @Override public PinyinSyllable pinyin() {
        return new PinyinSyllable(Initial.G, new Final(Head.OPEN, Body.O, Tail.NG), Tone.THIRD);
    }

    @Override public int strokes() { return 6; }
    @Override public int radicalNo() { return 48; }
    @Override public String meaning() { return ""; }

    @Override public EtymologicalCategory etymology() {
        return new EtymologicalCategory.PhonoSemantic(ActionsAndStates.GONG_WORK, ToolsAndVessels.FAN);
    }
}
