// AUTO-GENERATED by PerclassGenerateMain - do not edit by hand.
package kranji.common.perclass.zh.ong1;

import kranji.classification.EtymologicalCategory;
import kranji.component.basic.BasicComponents;
import kranji.component.basic.SilkFamily.JiaoSiPang;
import kranji.pinyin.Body;
import kranji.pinyin.Final;
import kranji.pinyin.Head;
import kranji.pinyin.Initial;
import kranji.pinyin.PinyinSyllable;
import kranji.pinyin.Tail;
import kranji.pinyin.Tone;
import kranji.singular.nature.NatureElements;
import kranji.singular.nature.NatureElements.Dong_Winter;
import kranji.zi.ComposedZiT;
import kranji.zi.CompositionLayoutT;
import kranji.zi.LeftRightT;

public record ZhongEnd() implements ComposedZiT, LeftRightT<JiaoSiPang, Dong_Winter> {

    public static final ZhongEnd INSTANCE = new ZhongEnd();

    @Override public JiaoSiPang left() { return BasicComponents.JIAO_SI_PANG; }
    @Override public Dong_Winter right() { return NatureElements.DONG_WINTER; }

    @Override public CompositionLayoutT layout() { return this; }

    @Override public String glyph() { return "\u7EC8"; }

    @Override public PinyinSyllable pinyin() {
        return new PinyinSyllable(Initial.ZH, new Final(Head.OPEN, Body.O, Tail.NG), Tone.FIRST);
    }

    @Override public int strokes() { return 8; }
    @Override public int radicalNo() { return 120; }
    @Override public String meaning() { return ""; }

    @Override public EtymologicalCategory etymology() {
        return new EtymologicalCategory.PhonoSemantic(BasicComponents.JIAO_SI_PANG, NatureElements.DONG_WINTER);
    }
}
