// AUTO-GENERATED by kranji-codegen. Do not edit by hand.
package kranji.singular.concepts.sh;

import kranji.library.BasicSet;
import kranji.library.LibraryMember;
import kranji.zi.SingularZi;

public record Shi_Thing() implements LibraryMember<BasicSet>, SingularZi {
    public static final Shi_Thing INSTANCE = new Shi_Thing();

    @Override public String glyph() { return "\u4E8B"; }
    @Override public String meaning() { return "matter, affair"; }
    @Override public String pinyinText() { return "sh\u00EC"; }
    @Override public int strokes() { return 8; }
    @Override public BasicSet library() { return BasicSet.INSTANCE; }
}
