// AUTO-GENERATED by kranji-codegen. Do not edit by hand.
package kranji.singular.concepts.sh;

import kranji.library.BasicSet;
import kranji.library.LibraryMember;
import kranji.zi.SingularZi;

public record Shou_Long() implements LibraryMember<BasicSet>, SingularZi {
    public static final Shou_Long INSTANCE = new Shou_Long();

    @Override public String glyph() { return "\u5BFF"; }
    @Override public String meaning() { return "longevity"; }
    @Override public String pinyinText() { return "sh\u00F2u"; }
    @Override public int strokes() { return 7; }
    @Override public BasicSet library() { return BasicSet.INSTANCE; }
}
