// AUTO-GENERATED by CatalogIteratorMain - do not edit by hand.
package kranji.common.perclass.promoted.zero.iou3;

import kranji.classification.EtymologicalCategory;
import kranji.pinyin.Body;
import kranji.pinyin.Final;
import kranji.pinyin.Head;
import kranji.pinyin.Initial;
import kranji.pinyin.PinyinSyllable;
import kranji.pinyin.Tail;
import kranji.pinyin.Tone;
import kranji.singular.nature.NatureElements;
import kranji.singular.radicals.RadicalComponents;
import kranji.zi.ComposedZiT;
import kranji.zi.CompositionLayoutT;
import kranji.zi.TopBottomT;

public record YouHave() implements ComposedZiT, TopBottomT<RadicalComponents.Zuo_Hand, NatureElements.Yue> {

    public static final YouHave INSTANCE = new YouHave();

    @Override public RadicalComponents.Zuo_Hand top() { return RadicalComponents.ZUO_HAND; }
    @Override public NatureElements.Yue bottom() { return NatureElements.YUE; }

    @Override public CompositionLayoutT layout() { return this; }

    @Override public String glyph() { return "\u6709"; }

    @Override public PinyinSyllable pinyin() {
        return new PinyinSyllable(Initial.ZERO, new Final(Head.I, Body.O, Tail.VOWEL_U), Tone.THIRD);
    }

    @Override public int strokes() { return 0; }
    @Override public int radicalNo() { return 0; }
    @Override public String meaning() { return ""; }

    @Override public EtymologicalCategory etymology() {
        return new EtymologicalCategory.DerivativeCognate("");
    }
}
