// AUTO-GENERATED by PerclassGenerateMain - do not edit by hand.
package kranji.common.perclass.s.u4;

import kranji.classification.EtymologicalCategory;
import kranji.component.basic.BasicComponents;
import kranji.component.basic.MovementFamily.ZouZhiDi;
import kranji.pinyin.Body;
import kranji.pinyin.Final;
import kranji.pinyin.Head;
import kranji.pinyin.Initial;
import kranji.pinyin.PinyinSyllable;
import kranji.pinyin.Tail;
import kranji.pinyin.Tone;
import kranji.singular.plants.PlantsAndAgriculture;
import kranji.singular.plants.PlantsAndAgriculture.Shu;
import kranji.zi.ComposedZiT;
import kranji.zi.CompositionLayoutT;
import kranji.zi.SemiEnclosureBottomLeftT;

public record SuFast() implements ComposedZiT, SemiEnclosureBottomLeftT<ZouZhiDi, Shu> {

    public static final SuFast INSTANCE = new SuFast();

    @Override public ZouZhiDi wrapper() { return BasicComponents.ZOU_ZHI_DI; }
    @Override public Shu content() { return PlantsAndAgriculture.SHU; }

    @Override public CompositionLayoutT layout() { return this; }

    @Override public String glyph() { return "\u901F"; }

    @Override public PinyinSyllable pinyin() {
        return new PinyinSyllable(Initial.S, new Final(Head.U, Body.U, Tail.NONE), Tone.FOURTH);
    }

    @Override public int strokes() { return 10; }
    @Override public int radicalNo() { return 162; }
    @Override public String meaning() { return ""; }

    @Override public EtymologicalCategory etymology() {
        return new EtymologicalCategory.PhonoSemantic(BasicComponents.ZOU_ZHI_DI, PlantsAndAgriculture.SHU);
    }
}
