// AUTO-GENERATED by PerclassGenerateMain - do not edit by hand.
package kranji.common.perclass.s.u4;

import kranji.classification.EtymologicalCategory;
import kranji.component.basic.BasicComponents;
import kranji.component.basic.PersonFamily.DanRenPang;
import kranji.component.basic.ShelterFamily.BaoGaiTou;
import kranji.pinyin.Body;
import kranji.pinyin.Final;
import kranji.pinyin.Head;
import kranji.pinyin.Initial;
import kranji.pinyin.PinyinSyllable;
import kranji.pinyin.Tail;
import kranji.pinyin.Tone;
import kranji.singular.numbers.NumbersAndMeasure;
import kranji.singular.numbers.NumbersAndMeasure.Bai;
import kranji.zi.ComposedZiT;
import kranji.zi.CompositionLayoutT;
import kranji.zi.LeftRightPartT;
import kranji.zi.TopBottomT;

public record SuLodge() implements ComposedZiT, TopBottomT<BaoGaiTou, LeftRightPartT<DanRenPang, Bai>> {

    public static final SuLodge INSTANCE = new SuLodge();

    @Override public BaoGaiTou top() { return BasicComponents.BAO_GAI_TOU; }
    @Override public LeftRightPartT<DanRenPang, Bai> bottom() { return new LeftRightPartT<>(BasicComponents.DAN_REN_PANG, NumbersAndMeasure.BAI); }

    @Override public CompositionLayoutT layout() { return this; }

    @Override public String glyph() { return "\u5BBF"; }

    @Override public PinyinSyllable pinyin() {
        return new PinyinSyllable(Initial.S, new Final(Head.U, Body.U, Tail.NONE), Tone.FOURTH);
    }

    @Override public int strokes() { return 11; }
    @Override public int radicalNo() { return 40; }
    @Override public String meaning() { return ""; }

    @Override public EtymologicalCategory etymology() {
        return new EtymologicalCategory.CompoundIndicative("宀(roof) + 亻(person) + 百(hundred/many) → a place where people lodge");
    }
}
