// AUTO-GENERATED by CatalogIteratorMain - do not edit by hand.
package kranji.common.perclass.promoted.t.ong4;

import kranji.classification.EtymologicalCategory;
import kranji.common.perclass.promoted.zero.iong3.YongPath;
import kranji.component.basic.BasicComponents;
import kranji.component.basic.EnclosureFamily;
import kranji.pinyin.Body;
import kranji.pinyin.Final;
import kranji.pinyin.Head;
import kranji.pinyin.Initial;
import kranji.pinyin.PinyinSyllable;
import kranji.pinyin.Tail;
import kranji.pinyin.Tone;
import kranji.zi.ComposedZiT;
import kranji.zi.CompositionLayoutT;
import kranji.zi.SemiEnclosureUpperLeftT;

public record TongPain() implements ComposedZiT, SemiEnclosureUpperLeftT<EnclosureFamily.BingZiPang, YongPath> {

    public static final TongPain INSTANCE = new TongPain();

    @Override public EnclosureFamily.BingZiPang wrapper() { return BasicComponents.BING_ZI_PANG; }
    @Override public YongPath content() { return YongPath.INSTANCE; }

    @Override public CompositionLayoutT layout() { return this; }

    @Override public String glyph() { return "\u75DB"; }

    @Override public PinyinSyllable pinyin() {
        return new PinyinSyllable(Initial.T, new Final(Head.OPEN, Body.O, Tail.NG), Tone.FOURTH);
    }

    @Override public int strokes() { return 0; }
    @Override public int radicalNo() { return 0; }
    @Override public String meaning() { return ""; }

    @Override public EtymologicalCategory etymology() {
        return new EtymologicalCategory.PhonoSemantic(BasicComponents.BING_ZI_PANG, YongPath.INSTANCE);
    }
}
