// AUTO-GENERATED by CatalogIteratorMain - do not edit by hand.
package kranji.common.perclass.promoted.zero.uei4;

import kranji.classification.EtymologicalCategory;
import kranji.common.perclass.promoted.zero.uei4.WeiWeiAuto;
import kranji.pinyin.Body;
import kranji.pinyin.Final;
import kranji.pinyin.Head;
import kranji.pinyin.Initial;
import kranji.pinyin.PinyinSyllable;
import kranji.pinyin.Tail;
import kranji.pinyin.Tone;
import kranji.singular.body.BodyParts;
import kranji.zi.ComposedZiT;
import kranji.zi.CompositionLayoutT;
import kranji.zi.TopBottomT;

public record WeiComfort() implements ComposedZiT, TopBottomT<WeiWeiAuto, BodyParts.Xin> {

    public static final WeiComfort INSTANCE = new WeiComfort();

    @Override public WeiWeiAuto top() { return WeiWeiAuto.INSTANCE; }
    @Override public BodyParts.Xin bottom() { return BodyParts.XIN; }

    @Override public CompositionLayoutT layout() { return this; }

    @Override public String glyph() { return "\u6170"; }

    @Override public PinyinSyllable pinyin() {
        return new PinyinSyllable(Initial.ZERO, new Final(Head.U, Body.E, Tail.VOWEL_I), Tone.FOURTH);
    }

    @Override public int strokes() { return 0; }
    @Override public int radicalNo() { return 0; }
    @Override public String meaning() { return ""; }

    @Override public EtymologicalCategory etymology() {
        return new EtymologicalCategory.PhonoSemantic(BodyParts.XIN, WeiWeiAuto.INSTANCE);
    }
}
