// AUTO-GENERATED by Depth2GenerateMain - do not edit by hand.
package kranji.common.depth2;

import kranji.zi.ComposedZi;

import kranji.common.depth2.t.An3;
import kranji.common.depth2.t.Ie1;
import kranji.common.depth2.t.Uo2;

import java.util.ArrayList;
import java.util.Collections;
import java.util.List;

public final class Depth2T {

    private Depth2T() {}

    public static final List<ComposedZi> ALL;
    static {
        var list = new ArrayList<ComposedZi>();
        list.addAll(An3.ALL);
        list.addAll(Ie1.ALL);
        list.addAll(Uo2.ALL);
        ALL = Collections.unmodifiableList(list);
    }
}
