// AUTO-GENERATED by Depth2GenerateMain - do not edit by hand.
package kranji.common.depth2;

import kranji.zi.ComposedZi;

import kranji.common.depth2.ch.A4;
import kranji.common.depth2.ch.E4;
import kranji.common.depth2.ch.Uen3;

import java.util.ArrayList;
import java.util.Collections;
import java.util.List;

public final class Depth2Ch {

    private Depth2Ch() {}

    public static final List<ComposedZi> ALL;
    static {
        var list = new ArrayList<ComposedZi>();
        list.addAll(A4.ALL);
        list.addAll(E4.ALL);
        list.addAll(Uen3.ALL);
        ALL = Collections.unmodifiableList(list);
    }
}
