// AUTO-GENERATED by PerclassGenerateMain - do not edit by hand.
package kranji.common.perclass.t.u1;

import kranji.classification.EtymologicalCategory;
import kranji.pinyin.Body;
import kranji.pinyin.Final;
import kranji.pinyin.Head;
import kranji.pinyin.Initial;
import kranji.pinyin.PinyinSyllable;
import kranji.pinyin.Tail;
import kranji.pinyin.Tone;
import kranji.singular.people.PeopleAndRoles;
import kranji.singular.people.PeopleAndRoles.Er_Child;
import kranji.singular.plants.PlantsAndAgriculture;
import kranji.singular.plants.PlantsAndAgriculture.He;
import kranji.zi.ComposedZiT;
import kranji.zi.CompositionLayoutT;
import kranji.zi.TopBottomT;

public record TuBald() implements ComposedZiT, TopBottomT<He, Er_Child> {

    public static final TuBald INSTANCE = new TuBald();

    @Override public He top() { return PlantsAndAgriculture.HE; }
    @Override public Er_Child bottom() { return PeopleAndRoles.ER_CHILD; }

    @Override public CompositionLayoutT layout() { return this; }

    @Override public String glyph() { return "\u79C3"; }

    @Override public PinyinSyllable pinyin() {
        return new PinyinSyllable(Initial.T, new Final(Head.U, Body.U, Tail.NONE), Tone.FIRST);
    }

    @Override public int strokes() { return 7; }
    @Override public int radicalNo() { return 115; }
    @Override public String meaning() { return ""; }

    @Override public EtymologicalCategory etymology() {
        return new EtymologicalCategory.PhonoSemantic(PlantsAndAgriculture.HE, PeopleAndRoles.ER_CHILD);
    }
}
