// AUTO-GENERATED by kranji-codegen. Do not edit by hand.
package kranji.singular.space;

import kranji.library.BasicSet;
import kranji.library.LibraryMember;

import kranji.singular.space.b.Bei_North;
import kranji.singular.space.ch.Chang;
import kranji.singular.space.ch.Chen;
import kranji.singular.space.d.Dong;
import kranji.singular.space.f.Fang;
import kranji.singular.space.f.Fu_Begin;
import kranji.singular.space.g.Gan_Dry;
import kranji.singular.space.j.Jia_First;
import kranji.singular.space.j.Jiu_Long;
import kranji.singular.space.l.Li_Inside;
import kranji.singular.space.n.Nan;
import kranji.singular.space.n.Nei;
import kranji.singular.space.n.Nian_Year;
import kranji.singular.space.p.Pan;
import kranji.singular.space.q.Qian_Front;
import kranji.singular.space.q.Qu_Area;
import kranji.singular.space.sh.Shang;
import kranji.singular.space.sh.Shen_Extend;
import kranji.singular.space.x.Xi;
import kranji.singular.space.x.Xia;
import kranji.singular.space.x.Xiang_Village;
import kranji.singular.space.z.Zuo_Left;
import kranji.singular.space.zero.Wu_Noon;
import kranji.singular.space.zero.Yang_Center;
import kranji.singular.space.zero.Ye_Page;
import kranji.singular.space.zero.You_From;
import kranji.singular.space.zero.You_Right;
import kranji.singular.space.zero.Yu_At;
import kranji.singular.space.zh.Zhong;

import java.util.List;

public final class SpaceSingulars {
    private SpaceSingulars() {}

    public static final List<LibraryMember<BasicSet>> ALL = List.of(
            Bei_North.INSTANCE,
            Chang.INSTANCE,
            Chen.INSTANCE,
            Dong.INSTANCE,
            Fang.INSTANCE,
            Fu_Begin.INSTANCE,
            Gan_Dry.INSTANCE,
            Jia_First.INSTANCE,
            Jiu_Long.INSTANCE,
            Li_Inside.INSTANCE,
            Nan.INSTANCE,
            Nei.INSTANCE,
            Nian_Year.INSTANCE,
            Pan.INSTANCE,
            Qian_Front.INSTANCE,
            Qu_Area.INSTANCE,
            Shang.INSTANCE,
            Shen_Extend.INSTANCE,
            Wu_Noon.INSTANCE,
            Xi.INSTANCE,
            Xia.INSTANCE,
            Xiang_Village.INSTANCE,
            Yang_Center.INSTANCE,
            Ye_Page.INSTANCE,
            You_From.INSTANCE,
            You_Right.INSTANCE,
            Yu_At.INSTANCE,
            Zhong.INSTANCE,
            Zuo_Left.INSTANCE);
}
