// AUTO-GENERATED by CatalogIteratorMain - do not edit by hand.
package kranji.common.perclass.promoted.j.in3;

import kranji.classification.EtymologicalCategory;
import kranji.common.perclass.promoted.b.o2.BoSilk;
import kranji.component.basic.BasicComponents;
import kranji.component.basic.MetalFamily;
import kranji.pinyin.Body;
import kranji.pinyin.Final;
import kranji.pinyin.Head;
import kranji.pinyin.Initial;
import kranji.pinyin.PinyinSyllable;
import kranji.pinyin.Tail;
import kranji.pinyin.Tone;
import kranji.zi.ComposedZiT;
import kranji.zi.CompositionLayoutT;
import kranji.zi.LeftRightT;

public record JinBrocade() implements ComposedZiT, LeftRightT<MetalFamily.JinZiPang, BoSilk> {

    public static final JinBrocade INSTANCE = new JinBrocade();

    @Override public MetalFamily.JinZiPang left() { return BasicComponents.JIN_ZI_PANG; }
    @Override public BoSilk right() { return BoSilk.INSTANCE; }

    @Override public CompositionLayoutT layout() { return this; }

    @Override public String glyph() { return "\u9526"; }

    @Override public PinyinSyllable pinyin() {
        return new PinyinSyllable(Initial.J, new Final(Head.OPEN, Body.I, Tail.N), Tone.THIRD);
    }

    @Override public int strokes() { return 0; }
    @Override public int radicalNo() { return 0; }
    @Override public String meaning() { return ""; }

    @Override public EtymologicalCategory etymology() {
        return new EtymologicalCategory.PhonoSemantic(BasicComponents.JIN_ZI_PANG, BoSilk.INSTANCE);
    }
}
