// AUTO-GENERATED by CatalogIteratorMain - do not edit by hand.
package kranji.common.perclass.promoted.j.in3;

import kranji.pinyin.Body;
import kranji.pinyin.Final;
import kranji.pinyin.Head;
import kranji.pinyin.Initial;
import kranji.pinyin.PinyinSyllable;
import kranji.pinyin.Tail;
import kranji.pinyin.Tone;
import kranji.zi.SingularZi;

public record JinClay() implements SingularZi {

    public static final JinClay INSTANCE = new JinClay();

    @Override public String glyph() { return "\u5807"; }

    @Override public PinyinSyllable pinyin() {
        return new PinyinSyllable(Initial.J, new Final(Head.OPEN, Body.I, Tail.N), Tone.THIRD);
    }

    @Override public boolean unsure() { return true; }
}
