// AUTO-GENERATED by CatalogIteratorMain - do not edit by hand.
package kranji.common.perclass.promoted.j.in3;

import kranji.classification.EtymologicalCategory;
import kranji.pinyin.Body;
import kranji.pinyin.Final;
import kranji.pinyin.Head;
import kranji.pinyin.Initial;
import kranji.pinyin.PinyinSyllable;
import kranji.pinyin.Tail;
import kranji.pinyin.Tone;
import kranji.singular.radicals.RadicalComponents;
import kranji.singular.structures.Structures;
import kranji.zi.ComposedZiT;
import kranji.zi.CompositionLayoutT;
import kranji.zi.TopBottomT;

public record JinExhaust() implements ComposedZiT, TopBottomT<Structures.Chi_Ruler, RadicalComponents.Dian> {

    public static final JinExhaust INSTANCE = new JinExhaust();

    @Override public Structures.Chi_Ruler top() { return Structures.CHI_RULER; }
    @Override public RadicalComponents.Dian bottom() { return RadicalComponents.DIAN; }

    @Override public CompositionLayoutT layout() { return this; }

    @Override public String glyph() { return "\u5C3D"; }

    @Override public PinyinSyllable pinyin() {
        return new PinyinSyllable(Initial.J, new Final(Head.OPEN, Body.I, Tail.N), Tone.THIRD);
    }

    @Override public int strokes() { return 0; }
    @Override public int radicalNo() { return 0; }
    @Override public String meaning() { return ""; }

    @Override public EtymologicalCategory etymology() {
        return new EtymologicalCategory.DerivativeCognate("");
    }
}
