// AUTO-GENERATED by CatalogIteratorMain - do not edit by hand.
package kranji.common.perclass.promoted.b.ei4;

import kranji.classification.EtymologicalCategory;
import kranji.pinyin.Body;
import kranji.pinyin.Final;
import kranji.pinyin.Head;
import kranji.pinyin.Initial;
import kranji.pinyin.PinyinSyllable;
import kranji.pinyin.Tail;
import kranji.pinyin.Tone;
import kranji.singular.radicals.RadicalComponents;
import kranji.singular.radicals.RadicalComponents.Fei_Wrong;
import kranji.singular.tools.ToolsAndVessels;
import kranji.singular.tools.ToolsAndVessels.Che;
import kranji.zi.ComposedZiT;
import kranji.zi.CompositionLayoutT;
import kranji.zi.TopBottomT;

public record BeiGeneration() implements ComposedZiT, TopBottomT<Fei_Wrong, Che> {

    public static final BeiGeneration INSTANCE = new BeiGeneration();

    @Override public Fei_Wrong top() { return RadicalComponents.FEI_WRONG; }
    @Override public Che bottom() { return ToolsAndVessels.CHE; }

    @Override public CompositionLayoutT layout() { return this; }

    @Override public String glyph() { return "\u8F88"; }

    @Override public PinyinSyllable pinyin() {
        return new PinyinSyllable(Initial.B, new Final(Head.OPEN, Body.E, Tail.VOWEL_I), Tone.FOURTH);
    }

    @Override public int strokes() { return 0; }
    @Override public int radicalNo() { return 0; }
    @Override public String meaning() { return ""; }

    @Override public EtymologicalCategory etymology() {
        return new EtymologicalCategory.PhonoSemantic(ToolsAndVessels.CHE, RadicalComponents.FEI_WRONG);
    }
}
