// AUTO-GENERATED by PerclassGenerateMain - do not edit by hand.
package kranji.common.perclass.f.a2;

import kranji.classification.EtymologicalCategory;
import kranji.common.perclass.f.a2.FaStrike;
import kranji.pinyin.Body;
import kranji.pinyin.Final;
import kranji.pinyin.Head;
import kranji.pinyin.Initial;
import kranji.pinyin.PinyinSyllable;
import kranji.pinyin.Tail;
import kranji.pinyin.Tone;
import kranji.singular.tools.ToolsAndVessels;
import kranji.singular.tools.ToolsAndVessels.Men;
import kranji.zi.ComposedZiT;
import kranji.zi.CompositionLayoutT;
import kranji.zi.SemiEnclosureUpperLeftT;

public record FaValve() implements ComposedZiT, SemiEnclosureUpperLeftT<Men, FaStrike> {

    public static final FaValve INSTANCE = new FaValve();

    @Override public Men wrapper() { return ToolsAndVessels.MEN; }
    @Override public FaStrike content() { return FaStrike.INSTANCE; }

    @Override public CompositionLayoutT layout() { return this; }

    @Override public String glyph() { return "\u9600"; }

    @Override public PinyinSyllable pinyin() {
        return new PinyinSyllable(Initial.F, new Final(Head.OPEN, Body.A, Tail.NONE), Tone.SECOND);
    }

    @Override public int strokes() { return 9; }
    @Override public int radicalNo() { return 169; }
    @Override public String meaning() { return ""; }

    @Override public EtymologicalCategory etymology() {
        return new EtymologicalCategory.PhonoSemantic(ToolsAndVessels.MEN, FaStrike.INSTANCE);
    }
}
