// AUTO-GENERATED by kranji-codegen. Do not edit by hand.
package kranji.singular.plants.r;

import kranji.library.BasicSet;
import kranji.library.LibraryMember;
import kranji.zi.SingularZi;

public record Ran() implements LibraryMember<BasicSet>, SingularZi {
    public static final Ran INSTANCE = new Ran();

    @Override public String glyph() { return "\u5189"; }
    @Override public String meaning() { return "slowly, gradually"; }
    @Override public String pinyinText() { return "r\u01CEn"; }
    @Override public int strokes() { return 5; }
    @Override public BasicSet library() { return BasicSet.INSTANCE; }
}
