// AUTO-GENERATED by CatalogIteratorMain - do not edit by hand.
package kranji.common.perclass.promoted.zero.an4;

import kranji.classification.EtymologicalCategory;
import kranji.common.perclass.promoted.zero.an1.AnPeace;
import kranji.component.basic.BasicComponents;
import kranji.component.basic.WoodFamily;
import kranji.pinyin.Body;
import kranji.pinyin.Final;
import kranji.pinyin.Head;
import kranji.pinyin.Initial;
import kranji.pinyin.PinyinSyllable;
import kranji.pinyin.Tail;
import kranji.pinyin.Tone;
import kranji.zi.ComposedZiT;
import kranji.zi.CompositionLayoutT;
import kranji.zi.TopBottomT;

public record AnCase() implements ComposedZiT, TopBottomT<AnPeace, WoodFamily.Mu> {

    public static final AnCase INSTANCE = new AnCase();

    @Override public AnPeace top() { return AnPeace.INSTANCE; }
    @Override public WoodFamily.Mu bottom() { return BasicComponents.MU; }

    @Override public CompositionLayoutT layout() { return this; }

    @Override public String glyph() { return "\u6848"; }

    @Override public PinyinSyllable pinyin() {
        return new PinyinSyllable(Initial.ZERO, new Final(Head.OPEN, Body.A, Tail.N), Tone.FOURTH);
    }

    @Override public int strokes() { return 0; }
    @Override public int radicalNo() { return 0; }
    @Override public String meaning() { return ""; }

    @Override public EtymologicalCategory etymology() {
        return new EtymologicalCategory.PhonoSemantic(BasicComponents.MU, AnPeace.INSTANCE);
    }
}
