// AUTO-GENERATED by PerclassGenerateMain - do not edit by hand.
package kranji.common.perclass.g.eng1;

import kranji.classification.EtymologicalCategory;
import kranji.pinyin.Body;
import kranji.pinyin.Final;
import kranji.pinyin.Head;
import kranji.pinyin.Initial;
import kranji.pinyin.PinyinSyllable;
import kranji.pinyin.Tail;
import kranji.pinyin.Tone;
import kranji.singular.nature.NatureElements;
import kranji.singular.nature.NatureElements.Jing;
import kranji.singular.plants.PlantsAndAgriculture;
import kranji.singular.plants.PlantsAndAgriculture.Lei_Plow;
import kranji.zi.ComposedZiT;
import kranji.zi.CompositionLayoutT;
import kranji.zi.LeftRightT;

public record GengPlow() implements ComposedZiT, LeftRightT<Lei_Plow, Jing> {

    public static final GengPlow INSTANCE = new GengPlow();

    @Override public Lei_Plow left() { return PlantsAndAgriculture.LEI_PLOW; }
    @Override public Jing right() { return NatureElements.JING; }

    @Override public CompositionLayoutT layout() { return this; }

    @Override public String glyph() { return "\u8015"; }

    @Override public PinyinSyllable pinyin() {
        return new PinyinSyllable(Initial.G, new Final(Head.OPEN, Body.E, Tail.NG), Tone.FIRST);
    }

    @Override public int strokes() { return 10; }
    @Override public int radicalNo() { return 127; }
    @Override public String meaning() { return ""; }

    @Override public EtymologicalCategory etymology() {
        return new EtymologicalCategory.CompoundIndicative("plow (耒) and well-field (井) — to till, plow");
    }
}
