// AUTO-GENERATED by CatalogIteratorMain - do not edit by hand.
package kranji.common.perclass.promoted.sh.a4;

import kranji.classification.EtymologicalCategory;
import kranji.common.perclass.promoted.x.ia4.XiaXiaAuto;
import kranji.pinyin.Body;
import kranji.pinyin.Final;
import kranji.pinyin.Head;
import kranji.pinyin.Initial;
import kranji.pinyin.PinyinSyllable;
import kranji.pinyin.Tail;
import kranji.pinyin.Tone;
import kranji.singular.structures.Structures;
import kranji.zi.ComposedZiT;
import kranji.zi.CompositionLayoutT;
import kranji.zi.SemiEnclosureUpperLeftT;

public record ShaMansion() implements ComposedZiT, SemiEnclosureUpperLeftT<Structures.Chang_Factory, XiaXiaAuto> {

    public static final ShaMansion INSTANCE = new ShaMansion();

    @Override public Structures.Chang_Factory wrapper() { return Structures.CHANG_FACTORY; }
    @Override public XiaXiaAuto content() { return XiaXiaAuto.INSTANCE; }

    @Override public CompositionLayoutT layout() { return this; }

    @Override public String glyph() { return "\u53A6"; }

    @Override public PinyinSyllable pinyin() {
        return new PinyinSyllable(Initial.SH, new Final(Head.OPEN, Body.A, Tail.NONE), Tone.FOURTH);
    }

    @Override public int strokes() { return 0; }
    @Override public int radicalNo() { return 0; }
    @Override public String meaning() { return ""; }

    @Override public EtymologicalCategory etymology() {
        return new EtymologicalCategory.PhonoSemantic(Structures.CHANG_FACTORY, XiaXiaAuto.INSTANCE);
    }
}
