// AUTO-GENERATED by Depth1GenerateMain - do not edit by hand.
package kranji.common.depth1.h;

import kranji.classification.EtymologicalCategory.*;
import kranji.component.basic.BasicComponents;
import kranji.pinyin.Body;
import kranji.pinyin.Final;
import kranji.pinyin.Head;
import kranji.pinyin.Initial;
import kranji.pinyin.PinyinSyllable;
import kranji.pinyin.Tail;
import kranji.pinyin.Tone;
import kranji.singular.actions.ActionsAndStates;
import kranji.singular.nature.NatureElements;
import kranji.singular.space.SpaceAndDirection;
import kranji.zi.ComposedPart;
import kranji.zi.ComposedZi;
import kranji.zi.CompositionLayout.*;
import kranji.zi.SingularPart;
import kranji.zi.ZiChar;
import java.util.List;

public final class An4 {

    private An4() {}

    public static final ComposedZi HAN = new ComposedZi(
            new ZiChar.Unicode("\u6C49"),
            new PinyinSyllable(Initial.H, new Final(Head.OPEN, Body.A, Tail.N), Tone.FOURTH),
            5, 85, "",
            new LeftRight(BasicComponents.SAN_DIAN_SHUI, ActionsAndStates.YOU_AGAIN),
            new PhonoSemantic(BasicComponents.SAN_DIAN_SHUI, ActionsAndStates.YOU_AGAIN));

    public static final ComposedZi HAN_DROUGHT = new ComposedZi(
            new ZiChar.Unicode("\u65F1"),
            new PinyinSyllable(Initial.H, new Final(Head.OPEN, Body.A, Tail.N), Tone.FOURTH),
            7, 72, "",
            new TopBottom(NatureElements.RI, SpaceAndDirection.GAN_DRY),
            new PhonoSemantic(NatureElements.RI, SpaceAndDirection.GAN_DRY));

    public static final List<ComposedZi> ALL = List.of(
            HAN,
            HAN_DROUGHT);
}
