// AUTO-GENERATED by Depth1GenerateMain - do not edit by hand.
package kranji.common.depth1.h;

import kranji.classification.EtymologicalCategory.*;
import kranji.component.basic.BasicComponents;
import kranji.pinyin.Body;
import kranji.pinyin.Final;
import kranji.pinyin.Head;
import kranji.pinyin.Initial;
import kranji.pinyin.PinyinSyllable;
import kranji.pinyin.Tail;
import kranji.pinyin.Tone;
import kranji.singular.body.BodyParts;
import kranji.zi.ComposedPart;
import kranji.zi.ComposedZi;
import kranji.zi.CompositionLayout.*;
import kranji.zi.SingularPart;
import kranji.zi.ZiChar;
import java.util.List;

public final class Ua4 {

    private Ua4() {}

    public static final ComposedZi HUA_SPEECH = new ComposedZi(
            new ZiChar.Unicode("\u8BDD"),
            new PinyinSyllable(Initial.H, new Final(Head.U, Body.A, Tail.NONE), Tone.FOURTH),
            8, 149, "",
            new LeftRight(BasicComponents.YAN_ZI_PANG, BodyParts.SHE),
            new PhonoSemantic(BasicComponents.YAN_ZI_PANG, BodyParts.SHE));

    public static final List<ComposedZi> ALL = List.of(
            HUA_SPEECH);
}
