// AUTO-GENERATED by CatalogIteratorMain - do not edit by hand.
package kranji.common.perclass.promoted.g.uan4;

import kranji.pinyin.Body;
import kranji.pinyin.Final;
import kranji.pinyin.Head;
import kranji.pinyin.Initial;
import kranji.pinyin.PinyinSyllable;
import kranji.pinyin.Tail;
import kranji.pinyin.Tone;
import kranji.zi.SingularZi;

public record GuanGuan() implements SingularZi {

    public static final GuanGuan INSTANCE = new GuanGuan();

    @Override public String glyph() { return "\u96DA"; }

    @Override public PinyinSyllable pinyin() {
        return new PinyinSyllable(Initial.G, new Final(Head.U, Body.A, Tail.N), Tone.FOURTH);
    }

    @Override public boolean unsure() { return true; }
}
