// AUTO-GENERATED by Depth1GenerateMain - do not edit by hand.
package kranji.common.depth1.c;

import kranji.classification.EtymologicalCategory.*;
import kranji.component.basic.BasicComponents;
import kranji.pinyin.Body;
import kranji.pinyin.Final;
import kranji.pinyin.Head;
import kranji.pinyin.Initial;
import kranji.pinyin.PinyinSyllable;
import kranji.pinyin.Tail;
import kranji.pinyin.Tone;
import kranji.singular.structures.Structures;
import kranji.zi.ComposedPart;
import kranji.zi.ComposedZi;
import kranji.zi.CompositionLayout.*;
import kranji.zi.SingularPart;
import kranji.zi.ZiChar;
import java.util.List;

public final class Ang1 {

    private Ang1() {}

    public static final ComposedZi CANG_PALE = new ComposedZi(
            new ZiChar.Unicode("\u82CD"),
            new PinyinSyllable(Initial.C, new Final(Head.OPEN, Body.A, Tail.NG), Tone.FIRST),
            7, 140, "",
            new TopBottom(BasicComponents.CAO_ZI_TOU, Structures.CANG),
            new PhonoSemantic(BasicComponents.CAO_ZI_TOU, Structures.CANG));

    public static final List<ComposedZi> ALL = List.of(
            CANG_PALE);
}
