// AUTO-GENERATED by CatalogIteratorMain - do not edit by hand.
package kranji.common.perclass.promoted.h.uang2;

import kranji.classification.EtymologicalCategory;
import kranji.pinyin.Body;
import kranji.pinyin.Final;
import kranji.pinyin.Head;
import kranji.pinyin.Initial;
import kranji.pinyin.PinyinSyllable;
import kranji.pinyin.Tail;
import kranji.pinyin.Tone;
import kranji.singular.nature.NatureElements;
import kranji.singular.unsure.UnsureSingulars;
import kranji.zi.ComposedZiT;
import kranji.zi.CompositionLayoutT;
import kranji.zi.LeftRightT;

public record HuangBright() implements ComposedZiT, LeftRightT<NatureElements.Huo, UnsureSingulars.Huang_Sovereign> {

    public static final HuangBright INSTANCE = new HuangBright();

    @Override public NatureElements.Huo left() { return NatureElements.HUO; }
    @Override public UnsureSingulars.Huang_Sovereign right() { return UnsureSingulars.HUANG_SOVEREIGN; }

    @Override public CompositionLayoutT layout() { return this; }

    @Override public String glyph() { return "\u714C"; }

    @Override public PinyinSyllable pinyin() {
        return new PinyinSyllable(Initial.H, new Final(Head.U, Body.A, Tail.NG), Tone.SECOND);
    }

    @Override public int strokes() { return 0; }
    @Override public int radicalNo() { return 0; }
    @Override public String meaning() { return ""; }

    @Override public EtymologicalCategory etymology() {
        return new EtymologicalCategory.PhonoSemantic(NatureElements.HUO, UnsureSingulars.HUANG_SOVEREIGN);
    }
}
