// AUTO-GENERATED by CatalogIteratorMain - do not edit by hand.
package kranji.common.perclass.promoted.b.ian1;

import kranji.classification.EtymologicalCategory;
import kranji.common.perclass.promoted.b.ian4.BianConvenient;
import kranji.pinyin.Body;
import kranji.pinyin.Final;
import kranji.pinyin.Head;
import kranji.pinyin.Initial;
import kranji.pinyin.PinyinSyllable;
import kranji.pinyin.Tail;
import kranji.pinyin.Tone;
import kranji.singular.materials.Materials;
import kranji.singular.materials.Materials.Ge;
import kranji.zi.ComposedZiT;
import kranji.zi.CompositionLayoutT;
import kranji.zi.LeftRightT;

public record BianWhip() implements ComposedZiT, LeftRightT<Ge, BianConvenient> {

    public static final BianWhip INSTANCE = new BianWhip();

    @Override public Ge left() { return Materials.GE; }
    @Override public BianConvenient right() { return BianConvenient.INSTANCE; }

    @Override public CompositionLayoutT layout() { return this; }

    @Override public String glyph() { return "\u97AD"; }

    @Override public PinyinSyllable pinyin() {
        return new PinyinSyllable(Initial.B, new Final(Head.I, Body.A, Tail.N), Tone.FIRST);
    }

    @Override public int strokes() { return 0; }
    @Override public int radicalNo() { return 0; }
    @Override public String meaning() { return ""; }

    @Override public EtymologicalCategory etymology() {
        return new EtymologicalCategory.PhonoSemantic(Materials.GE, BianConvenient.INSTANCE);
    }
}
