// AUTO-GENERATED by PerclassGenerateMain - do not edit by hand.
package kranji.common.perclass.h.u4;

import kranji.classification.EtymologicalCategory;
import kranji.component.basic.BasicComponents;
import kranji.component.basic.HandFamily.TiShouPang;
import kranji.pinyin.Body;
import kranji.pinyin.Final;
import kranji.pinyin.Head;
import kranji.pinyin.Initial;
import kranji.pinyin.PinyinSyllable;
import kranji.pinyin.Tail;
import kranji.pinyin.Tone;
import kranji.singular.structures.Structures;
import kranji.singular.structures.Structures.Hu;
import kranji.zi.ComposedZiT;
import kranji.zi.CompositionLayoutT;
import kranji.zi.LeftRightT;

public record HuProtect() implements ComposedZiT, LeftRightT<TiShouPang, Hu> {

    public static final HuProtect INSTANCE = new HuProtect();

    @Override public TiShouPang left() { return BasicComponents.TI_SHOU_PANG; }
    @Override public Hu right() { return Structures.HU; }

    @Override public CompositionLayoutT layout() { return this; }

    @Override public String glyph() { return "\u62A4"; }

    @Override public PinyinSyllable pinyin() {
        return new PinyinSyllable(Initial.H, new Final(Head.U, Body.U, Tail.NONE), Tone.FOURTH);
    }

    @Override public int strokes() { return 7; }
    @Override public int radicalNo() { return 64; }
    @Override public String meaning() { return ""; }

    @Override public EtymologicalCategory etymology() {
        return new EtymologicalCategory.PhonoSemantic(BasicComponents.TI_SHOU_PANG, Structures.HU);
    }
}
