package kranji.studio.gloss;

import hue.captains.singapura.js.homing.core.Importable;
import hue.captains.singapura.js.homing.core.ModuleImports;
import hue.captains.singapura.js.homing.grid.RelationGridModule;
import hue.captains.singapura.js.homing.grid.StockCellsModule;
import hue.captains.singapura.js.homing.workspace.LifecycleHint;
import hue.captains.singapura.js.homing.workspace.WorkspaceWidget;
import kranji.reading.workbench.relation.RelationCss;

import java.util.List;

/**
 * The readings, filtered by initial and final, picked several at a time.
 *
 * <h2>Why this is not a {@link GlossEntityWidget}</h2>
 *
 * <p>Every other grid in the workbench is one link of a chain: it takes the
 * keys from above, shows what hangs off them, takes the first row and passes
 * that down. This one sits at the top and does the opposite of most of that —
 * it is scoped by nothing, it takes <b>no</b> row automatically, and it hands
 * down a set rather than a key. Sharing a base class with the cascade would
 * mean overriding the two methods that carry all the behaviour, which is
 * inheritance in name only.</p>
 *
 * <h2>Nothing picked is not nothing selected</h2>
 *
 * <p>A cascade link with an empty selection shows nothing downstream, and that
 * is right: no sound selected means no senses to show. A <i>filter</i> with
 * nothing ticked means the opposite — do not filter — so this announces
 * {@code SelectionCleared} rather than an empty {@code PksSelected}, and the
 * bus drops the entry so demand goes back to whole.</p>
 *
 * <p>It follows that the grid's own habit of putting the cursor on the first
 * row must not count as a pick. The cursor is ignored until a person touches
 * the grid, and ignored again while a redraw is rebuilding it — otherwise
 * changing the initial filter would silently collapse a set someone had just
 * finished assembling.</p>
 *
 * <h2>Picking</h2>
 *
 * <p>The grid already knows how: plain click sets one, ctrl-click adds,
 * shift-click extends, and {@code onSelectionChanged} reports the ranges in
 * identity space. Two buttons cover what clicking is bad at — take everything
 * the filters left, or drop the lot.</p>
 */
public final class SoundEntityWidget extends WorkspaceWidget<WorkspaceWidget._None, SoundEntityWidget> {

    public static final SoundEntityWidget INSTANCE = new SoundEntityWidget();

    private SoundEntityWidget() {}

    private record construct() implements _Construct<_None, SoundEntityWidget> {}

    @Override protected _Construct<_None, SoundEntityWidget> construct() { return new construct(); }

    @Override public Class<_None> paramsType() { return _None.class; }

    @Override public String title() { return "Sound"; }

    /** MULTI, like the rest: two pickers scoped differently is a real use. */
    @Override public LifecycleHint lifecycleHint() { return LifecycleHint.MULTI; }

    @Override
    protected List<ModuleImports<? extends Importable>> bodyImports() {
        return List.of(
                new ModuleImports<>(
                        List.of(new RelationGridModule.RelationGrid()),
                        RelationGridModule.INSTANCE),
                new ModuleImports<>(
                        List.of(new StockCellsModule.TextCell()),
                        StockCellsModule.INSTANCE),
                // The frame is the shared relation CSS; only the picker's own
                // controls - the dropdowns, the two buttons, the picked line -
                // are the gloss workbench's to style.
                new ModuleImports<>(List.of(
                        new RelationCss.rel_root(),
                        new RelationCss.rel_bar(),
                        new RelationCss.rel_status(),
                        new RelationCss.rel_find(),
                        new RelationCss.rel_grid_host()),
                        RelationCss.INSTANCE),
                new ModuleImports<>(List.of(
                        new GlossCss.gl_select(),
                        new GlossCss.gl_button(),
                        new GlossCss.gl_picked()),
                        GlossCss.INSTANCE));
    }

    @Override
    protected List<String> constructBodyJs() {
        return List.of(
                "    var ENTITY = 'sound';",
                "",
                "    var root = branch.createElement('root', 'div');",
                "    css.setClass(root, rel_root);",
                "",
                "    var bar = branch.createElement('bar', 'div');",
                "    css.setClass(bar, rel_bar);",
                "    root.appendChild(bar);",
                "",
                "    // The two filters the sound system actually has. They narrow",
                "    // what is shown; they do not pick anything.",
                "    var initialSel = branch.createElement('initial', 'select');",
                "    css.setClass(initialSel, gl_select);",
                "    initialSel.title = 'initial (\\u58F0\\u6BCD)';",
                "    bar.appendChild(initialSel);",
                "",
                "    var rhymeSel = branch.createElement('rhyme', 'select');",
                "    css.setClass(rhymeSel, gl_select);",
                "    rhymeSel.title = 'final (\\u97F5\\u6BCD)';",
                "    bar.appendChild(rhymeSel);",
                "",
                "    var find = branch.createElement('find', 'input');",
                "    css.setClass(find, rel_find);",
                "    find.type = 'search';",
                "    find.placeholder = 'filter sounds';",
                "    bar.appendChild(find);",
                "",
                "    var allBtn = branch.createElement('all', 'button');",
                "    css.setClass(allBtn, gl_button);",
                "    allBtn.type = 'button';",
                "    allBtn.textContent = 'All shown';",
                "    bar.appendChild(allBtn);",
                "",
                "    var noneBtn = branch.createElement('none', 'button');",
                "    css.setClass(noneBtn, gl_button);",
                "    noneBtn.type = 'button';",
                "    noneBtn.textContent = 'None';",
                "    bar.appendChild(noneBtn);",
                "",
                "    var picked = branch.createElement('picked', 'div');",
                "    css.setClass(picked, gl_picked);",
                "    bar.appendChild(picked);",
                "",
                "    var status = branch.createElement('status', 'div');",
                "    css.setClass(status, rel_status);",
                "    bar.appendChild(status);",
                "",
                "    var host = branch.createElement('host', 'div');",
                "    css.setClass(host, rel_grid_host);",
                "    root.appendChild(host);",
                "",
                "    var owner = Object.freeze({ toString: function () { return 'gloss/' + ENTITY; } });",
                "    var grid = null;",
                "    var seq = 0;",
                "    var __focusWhenReady = false;",
                "    var __rows = [];",
                "    var __columns = [];",
                "    var __find = '';",
                "    var __picked = [];",
                "    var __ranges = [];",
                "    var __cursorPk = null;",
                "    // The grid puts a cursor on row 0 the moment it has rows, and it",
                "    // does so again after every rebuild. Neither is a person picking a",
                "    // sound, so neither may count as one.",
                "    var __touched = false;",
                "    var __redrawing = false;",
                "    var __filtersBuilt = false;",
                "",
                "    var __party = (workspaceCtx && workspaceCtx.glossParty)",
                "                ? workspaceCtx.glossParty : null;",
                "    var __actorId = null;",
                "",
                "    // ── The bus ───────────────────────────────",
                "",
                "    function announce() {",
                "        if (!__party || !__actorId) return;",
                "        if (__picked.length === 0) {",
                "            // Not an empty selection - no selection. The entry is dropped",
                "            // and demand goes back to showing every pair.",
                "            __party.tellFrom(__actorId, { kind: 'SelectionCleared', entity: ENTITY });",
                "        } else {",
                "            __party.tellFrom(__actorId,",
                "                    { kind: 'PksSelected', entity: ENTITY, pks: __picked.slice() });",
                "        }",
                "    }",
                "",
                "    // One ctrl-click moves the cursor AND changes the ranges, and the",
                "    // grid reports those as two callbacks in the same turn. Announcing",
                "    // from each would send the intermediate set downstream, so the two",
                "    // are collapsed into the one announcement the gesture deserves.",
                "    var __pending = false;",
                "    function schedule() {",
                "        if (__pending) return;",
                "        __pending = true;",
                "        Promise.resolve().then(function () { __pending = false; announce(); });",
                "    }",
                "",
                "    function setPicked(pks) {",
                "        var next = pks.slice();",
                "        if (next.join('\\u0000') === __picked.join('\\u0000')) return;",
                "        __picked = next;",
                "        paintPicked();",
                "        schedule();",
                "    }",
                "",
                "    function paintPicked() {",
                "        picked.textContent = __picked.length === 0",
                "                ? 'all sounds'",
                "                : (__picked.length <= 4",
                "                        ? __picked.join(' ')",
                "                        : __picked.slice(0, 4).join(' ')",
                "                          + ' +' + (__picked.length - 4));",
                "    }",
                "",
                "    // ── Rows ─────────────────────────────────",
                "",
                "    function countText(shown, total) {",
                "        var noun = total === 1 ? ' row' : ' rows';",
                "        return shown === total ? total + noun",
                "                               : shown + ' of ' + total + noun;",
                "    }",
                "",
                "    function matching() {",
                "        var wantInitial = initialSel.value;",
                "        var wantRhyme = rhymeSel.value;",
                "        var out = [];",
                "        for (var i = 0; i < __rows.length; i++) {",
                "            var row = __rows[i];",
                "            if (wantInitial && String(row['initial']) !== wantInitial) continue;",
                "            if (wantRhyme && String(row['final']) !== wantRhyme) continue;",
                "            if (__find) {",
                "                var hit = false;",
                "                for (var c = 0; c < __columns.length; c++) {",
                "                    var v = row[__columns[c]];",
                "                    if (v !== undefined && v !== null",
                "                            && String(v).indexOf(__find) >= 0) { hit = true; break; }",
                "                }",
                "                if (!hit) continue;",
                "            }",
                "            out.push(row);",
                "        }",
                "        return out;",
                "    }",
                "",
                "    // The vocabulary is whatever the relation holds, built once: the",
                "    // sound relation is a root and never reloads, and rebuilding option",
                "    // elements on every keystroke would churn branch names for nothing.",
                "    function buildFilters() {",
                "        if (__filtersBuilt) return;",
                "        __filtersBuilt = true;",
                "        fill(initialSel, 'initial', 'any initial');",
                "        fill(rhymeSel, 'final', 'any final');",
                "    }",
                "",
                "    function fill(sel, column, anyLabel) {",
                "        var seen = {}, values = [];",
                "        for (var i = 0; i < __rows.length; i++) {",
                "            var v = __rows[i][column];",
                "            if (v === undefined || v === null) continue;",
                "            v = String(v);",
                "            if (!seen[v]) { seen[v] = true; values.push(v); }",
                "        }",
                "        values.sort();",
                "        var any = branch.createElement(column + '-any', 'option');",
                "        any.value = '';",
                "        any.textContent = anyLabel;",
                "        sel.appendChild(any);",
                "        for (var k = 0; k < values.length; k++) {",
                "            var opt = branch.createElement(column + '-' + k, 'option');",
                "            opt.value = values[k];",
                "            opt.textContent = values[k];",
                "            sel.appendChild(opt);",
                "        }",
                "    }",
                "",
                "    function freshCellsBranch() {",
                "        if (branch.getBranch('cells')) branch.dissolveBranch('cells');",
                "        var b = branch.createBranch('cells');",
                "        b.activate(owner);",
                "        return b;",
                "    }",
                "",
                "    function relationOver(rows, columns) {",
                "        var byPk = {};",
                "        var order = [];",
                "        rows.forEach(function (r) { byPk[r.pk] = r; order.push(r.pk); });",
                "        var subs = [];",
                "        return {",
                "            pks:     function () { return order.slice(); },",
                "            columns: function () { return columns.slice(); },",
                "            get:     function (pk, col) {",
                "                         return byPk[pk] ? byPk[pk][col] : undefined; },",
                "            subscribe:   function (fn) { subs.push(fn); },",
                "            unsubscribe: function (fn) {",
                "                         var i = subs.indexOf(fn);",
                "                         if (i >= 0) subs.splice(i, 1); },",
                "            update:     function () {},",
                "            deleteRows: function () {}",
                "        };",
                "    }",
                "",
                "    // A range is an anchor and a focus in IDENTITY space, so turning one",
                "    // into rows means walking the view between them. A corner that has",
                "    // been filtered away is skipped rather than guessed at.",
                "    function pksOfRanges(ranges) {",
                "        var rows = matching();",
                "        var at = {};",
                "        for (var i = 0; i < rows.length; i++) at[rows[i].pk] = i;",
                "        var out = [], seen = {};",
                "        for (var r = 0; r < ranges.length; r++) {",
                "            var a = at[ranges[r].anchor.pk], f = at[ranges[r].focus.pk];",
                "            if (a === undefined || f === undefined) continue;",
                "            var lo = Math.min(a, f), hi = Math.max(a, f);",
                "            for (var k = lo; k <= hi; k++) {",
                "                var pk = rows[k].pk;",
                "                if (!seen[pk]) { seen[pk] = true; out.push(pk); }",
                "            }",
                "        }",
                "        return out;",
                "    }",
                "",
                "    // Both grid callbacks land here, so the cursor and the ranges cannot",
                "    // disagree about what is picked. A collapsed range list is not an",
                "    // empty pick - it is a plain click, and the cursor is the pick.",
                "    function sync() {",
                "        if (__redrawing || !__touched) return;",
                "        setPicked(__ranges.length ? pksOfRanges(__ranges)",
                "                                  : (__cursorPk ? [__cursorPk] : []));",
                "    }",
                "",
                "    function draw() {",
                "        var rows = matching();",
                "        if (grid) { grid.destroy(); grid = null; }",
                "        // A remap resets the grid's ranges and re-seats its cursor. Both",
                "        // arrive as callbacks, and neither is a person choosing, so the",
                "        // picked set is held still across the rebuild.",
                "        __redrawing = true;",
                "        __ranges = [];",
                "        grid = new RelationGrid({",
                "            container: host,",
                "            branch:    freshCellsBranch(),",
                "            adapter:   relationOver(rows, __columns),",
                "            label:     'Gloss ' + ENTITY,",
                "            cellFactory: function () { return new TextCell(); },",
                "            onCursorMoved: function (pk) { __cursorPk = pk; sync(); },",
                "            onSelectionChanged: function (ranges) {",
                "                __ranges = ranges || []; sync(); }",
                "        });",
                "        __redrawing = false;",
                "        status.textContent = countText(rows.length, __rows.length);",
                "        if (__focusWhenReady) { __focusWhenReady = false; grid.focus(); }",
                "    }",
                "",
                "    function load() {",
                "        var mine = ++seq;",
                "        status.textContent = 'Loading...';",
                "        import('/gloss-relation?name=' + encodeURIComponent(ENTITY))",
                "            .then(function (mod) {",
                "                if (mine !== seq) return;",
                "                if (mod.problem) {",
                "                    __rows = []; __columns = [];",
                "                    status.textContent = mod.problem;",
                "                    return;",
                "                }",
                "                __rows = mod.rows || [];",
                "                __columns = mod.columns || [];",
                "                buildFilters();",
                "                draw();",
                "                paintPicked();",
                "            })",
                "            .catch(function (e) {",
                "                if (mine !== seq) return;",
                "                status.textContent = 'Could not load ' + ENTITY + ': ' + e;",
                "            });",
                "    }",
                "",
                "    // ── Gestures ─────────────────────────────",
                "",
                "    // Only a person touching the grid turns the cursor into a pick. The",
                "    // listeners are on the host and fire before the grid handles the",
                "    // event, so the very first click counts.",
                "    host.addEventListener('mousedown', function () { __touched = true; });",
                "    host.addEventListener('keydown', function () { __touched = true; });",
                "",
                "    initialSel.addEventListener('change', function () {",
                "        if (__columns.length) draw();",
                "    });",
                "    rhymeSel.addEventListener('change', function () {",
                "        if (__columns.length) draw();",
                "    });",
                "    find.addEventListener('input', function () {",
                "        __find = find.value;",
                "        if (__columns.length) draw();",
                "    });",
                "",
                "    allBtn.addEventListener('click', function () {",
                "        __touched = true;",
                "        var rows = matching(), pks = [];",
                "        for (var i = 0; i < rows.length; i++) pks.push(rows[i].pk);",
                "        setPicked(pks);",
                "    });",
                "",
                "    noneBtn.addEventListener('click', function () {",
                "        // Back to untouched, not to an empty pick: the next rebuild must",
                "        // not read the cursor as a choice either.",
                "        __touched = false;",
                "        __ranges = [];",
                "        setPicked([]);",
                "    });",
                "",
                "    // ── Joining ──────────────────────────────",
                "",
                "    // No reactors: a root is scoped by nothing, so there is no message",
                "    // this widget could act on. It joins to be able to speak.",
                "    if (__party) {",
                "        __actorId = 'gloss-' + ENTITY + '-'",
                "                  + Math.random().toString(36).slice(2, 8);",
                "        __party.joinActor({",
                "            id: __actorId,",
                "            parentSecretary: 'glossSelection',",
                "            reactors: {}",
                "        });",
                "    }",
                "",
                "    paintPicked();",
                "    load();",
                "",
                "    return {",
                "        root: root,",
                "        setActive: function (active) {",
                "            if (!active) return;",
                "            if (grid) grid.focus(); else __focusWhenReady = true;",
                "        },",
                "        partyDeregister: function () {",
                "            if (__party && __actorId) __party.leaveActor(__actorId);",
                "        },",
                "        dispose: function () {",
                "            seq++;",
                "            if (grid) { grid.destroy(); grid = null; }",
                "        }",
                "    };");
    }
}
