// AUTO-GENERATED by CatalogIteratorMain - do not edit by hand.
package kranji.common.perclass.promoted.h.eng2;

import kranji.classification.EtymologicalCategory;
import kranji.common.perclass.promoted.g.en4.GenExtend;
import kranji.component.basic.BasicComponents;
import kranji.component.basic.HeartFamily;
import kranji.pinyin.Body;
import kranji.pinyin.Final;
import kranji.pinyin.Head;
import kranji.pinyin.Initial;
import kranji.pinyin.PinyinSyllable;
import kranji.pinyin.Tail;
import kranji.pinyin.Tone;
import kranji.zi.ComposedZiT;
import kranji.zi.CompositionLayoutT;
import kranji.zi.LeftRightT;

public record HengEternal() implements ComposedZiT, LeftRightT<HeartFamily.ShuXinPang, GenExtend> {

    public static final HengEternal INSTANCE = new HengEternal();

    @Override public HeartFamily.ShuXinPang left() { return BasicComponents.SHU_XIN_PANG; }
    @Override public GenExtend right() { return GenExtend.INSTANCE; }

    @Override public CompositionLayoutT layout() { return this; }

    @Override public String glyph() { return "\u6052"; }

    @Override public PinyinSyllable pinyin() {
        return new PinyinSyllable(Initial.H, new Final(Head.OPEN, Body.E, Tail.NG), Tone.SECOND);
    }

    @Override public int strokes() { return 0; }
    @Override public int radicalNo() { return 0; }
    @Override public String meaning() { return ""; }

    @Override public EtymologicalCategory etymology() {
        return new EtymologicalCategory.PhonoSemantic(BasicComponents.SHU_XIN_PANG, GenExtend.INSTANCE);
    }
}
