// AUTO-GENERATED by kranji-codegen. Do not edit by hand.
package kranji.singular.materials.zero;

import kranji.library.BasicSet;
import kranji.library.LibraryMember;
import kranji.zi.SingularZi;

public record Wei_Leather() implements LibraryMember<BasicSet>, SingularZi {
    public static final Wei_Leather INSTANCE = new Wei_Leather();

    @Override public String glyph() { return "\u97E6"; }
    @Override public String meaning() { return "leather/tanned hide"; }
    @Override public String pinyinText() { return "w\u00E9i"; }
    @Override public int strokes() { return 4; }
    @Override public BasicSet library() { return BasicSet.INSTANCE; }
}
