// AUTO-GENERATED by PerclassGenerateMain - do not edit by hand.
package kranji.common.perclass.r.eng2;

import kranji.classification.EtymologicalCategory;
import kranji.component.basic.BasicComponents;
import kranji.component.basic.PersonFamily.DanRenPang;
import kranji.pinyin.Body;
import kranji.pinyin.Final;
import kranji.pinyin.Head;
import kranji.pinyin.Initial;
import kranji.pinyin.PinyinSyllable;
import kranji.pinyin.Tail;
import kranji.pinyin.Tone;
import kranji.singular.concepts.AbstractConcepts;
import kranji.singular.concepts.AbstractConcepts.Nai;
import kranji.zi.ComposedZiT;
import kranji.zi.CompositionLayoutT;
import kranji.zi.LeftRightT;

public record Reng() implements ComposedZiT, LeftRightT<DanRenPang, Nai> {

    public static final Reng INSTANCE = new Reng();

    @Override public DanRenPang left() { return BasicComponents.DAN_REN_PANG; }
    @Override public Nai right() { return AbstractConcepts.NAI; }

    @Override public CompositionLayoutT layout() { return this; }

    @Override public String glyph() { return "\u4ECD"; }

    @Override public PinyinSyllable pinyin() {
        return new PinyinSyllable(Initial.R, new Final(Head.OPEN, Body.E, Tail.NG), Tone.SECOND);
    }

    @Override public int strokes() { return 4; }
    @Override public int radicalNo() { return 9; }
    @Override public String meaning() { return ""; }

    @Override public EtymologicalCategory etymology() {
        return new EtymologicalCategory.PhonoSemantic(BasicComponents.DAN_REN_PANG, AbstractConcepts.NAI);
    }
}
