// AUTO-GENERATED by CatalogIteratorMain - do not edit by hand.
package kranji.common.perclass.promoted.zero.uen2;

import kranji.classification.EtymologicalCategory;
import kranji.pinyin.Body;
import kranji.pinyin.Final;
import kranji.pinyin.Head;
import kranji.pinyin.Initial;
import kranji.pinyin.PinyinSyllable;
import kranji.pinyin.Tail;
import kranji.pinyin.Tone;
import kranji.singular.animals.Animals;
import kranji.singular.people.PeopleAndRoles;
import kranji.zi.ComposedZiT;
import kranji.zi.CompositionLayoutT;
import kranji.zi.LeftRightT;

public record WenMosquito() implements ComposedZiT, LeftRightT<Animals.Chong, PeopleAndRoles.Wen> {

    public static final WenMosquito INSTANCE = new WenMosquito();

    @Override public Animals.Chong left() { return Animals.CHONG; }
    @Override public PeopleAndRoles.Wen right() { return PeopleAndRoles.WEN; }

    @Override public CompositionLayoutT layout() { return this; }

    @Override public String glyph() { return "\u868A"; }

    @Override public PinyinSyllable pinyin() {
        return new PinyinSyllable(Initial.ZERO, new Final(Head.U, Body.E, Tail.N), Tone.SECOND);
    }

    @Override public int strokes() { return 0; }
    @Override public int radicalNo() { return 0; }
    @Override public String meaning() { return ""; }

    @Override public EtymologicalCategory etymology() {
        return new EtymologicalCategory.PhonoSemantic(Animals.CHONG, PeopleAndRoles.WEN);
    }
}
