// AUTO-GENERATED by CatalogIteratorMain - do not edit by hand.
package kranji.common.perclass.promoted.zero.a5;

import kranji.classification.EtymologicalCategory;
import kranji.common.perclass.zero.a1.APrefix;
import kranji.pinyin.Body;
import kranji.pinyin.Final;
import kranji.pinyin.Head;
import kranji.pinyin.Initial;
import kranji.pinyin.PinyinSyllable;
import kranji.pinyin.Tail;
import kranji.pinyin.Tone;
import kranji.singular.body.BodyParts;
import kranji.zi.ComposedZiT;
import kranji.zi.CompositionLayoutT;
import kranji.zi.LeftRightT;

public record AParticle() implements ComposedZiT, LeftRightT<BodyParts.Kou, APrefix> {

    public static final AParticle INSTANCE = new AParticle();

    @Override public BodyParts.Kou left() { return BodyParts.KOU; }
    @Override public APrefix right() { return APrefix.INSTANCE; }

    @Override public CompositionLayoutT layout() { return this; }

    @Override public String glyph() { return "\u554A"; }

    @Override public PinyinSyllable pinyin() {
        return new PinyinSyllable(Initial.ZERO, new Final(Head.OPEN, Body.A, Tail.NONE), Tone.NEUTRAL);
    }

    @Override public int strokes() { return 0; }
    @Override public int radicalNo() { return 0; }
    @Override public String meaning() { return ""; }

    @Override public EtymologicalCategory etymology() {
        return new EtymologicalCategory.PhonoSemantic(BodyParts.KOU, APrefix.INSTANCE);
    }
}
