// AUTO-GENERATED by CatalogIteratorMain - do not edit by hand.
package kranji.common.perclass.promoted.zero.van1;

import kranji.classification.EtymologicalCategory;
import kranji.component.basic.BasicComponents;
import kranji.component.basic.ShelterFamily;
import kranji.pinyin.Body;
import kranji.pinyin.Final;
import kranji.pinyin.Head;
import kranji.pinyin.Initial;
import kranji.pinyin.PinyinSyllable;
import kranji.pinyin.Tail;
import kranji.pinyin.Tone;
import kranji.singular.animals.Animals;
import kranji.zi.ComposedZiT;
import kranji.zi.CompositionLayoutT;
import kranji.zi.TopBottomT;

public record YuanWrong() implements ComposedZiT, TopBottomT<ShelterFamily.TuBaoGai, Animals.Tu_Rabbit> {

    public static final YuanWrong INSTANCE = new YuanWrong();

    @Override public ShelterFamily.TuBaoGai top() { return BasicComponents.TU_BAO_GAI; }
    @Override public Animals.Tu_Rabbit bottom() { return Animals.TU_RABBIT; }

    @Override public CompositionLayoutT layout() { return this; }

    @Override public String glyph() { return "\u51A4"; }

    @Override public PinyinSyllable pinyin() {
        return new PinyinSyllable(Initial.ZERO, new Final(Head.V, Body.A, Tail.N), Tone.FIRST);
    }

    @Override public int strokes() { return 0; }
    @Override public int radicalNo() { return 0; }
    @Override public String meaning() { return ""; }

    @Override public EtymologicalCategory etymology() {
        return new EtymologicalCategory.DerivativeCognate("");
    }
}
