// AUTO-GENERATED by PerclassGenerateMain - do not edit by hand.
package kranji.common.perclass.r.eng1;

import kranji.classification.EtymologicalCategory;
import kranji.component.basic.BasicComponents;
import kranji.component.basic.HandFamily.TiShouPang;
import kranji.pinyin.Body;
import kranji.pinyin.Final;
import kranji.pinyin.Head;
import kranji.pinyin.Initial;
import kranji.pinyin.PinyinSyllable;
import kranji.pinyin.Tail;
import kranji.pinyin.Tone;
import kranji.singular.concepts.AbstractConcepts;
import kranji.singular.concepts.AbstractConcepts.Nai;
import kranji.zi.ComposedZiT;
import kranji.zi.CompositionLayoutT;
import kranji.zi.LeftRightT;

public record RengThrow() implements ComposedZiT, LeftRightT<TiShouPang, Nai> {

    public static final RengThrow INSTANCE = new RengThrow();

    @Override public TiShouPang left() { return BasicComponents.TI_SHOU_PANG; }
    @Override public Nai right() { return AbstractConcepts.NAI; }

    @Override public CompositionLayoutT layout() { return this; }

    @Override public String glyph() { return "\u6254"; }

    @Override public PinyinSyllable pinyin() {
        return new PinyinSyllable(Initial.R, new Final(Head.OPEN, Body.E, Tail.NG), Tone.FIRST);
    }

    @Override public int strokes() { return 5; }
    @Override public int radicalNo() { return 64; }
    @Override public String meaning() { return ""; }

    @Override public EtymologicalCategory etymology() {
        return new EtymologicalCategory.PhonoSemantic(BasicComponents.TI_SHOU_PANG, AbstractConcepts.NAI);
    }
}
