// AUTO-GENERATED by PerclassGenerateMain - do not edit by hand.
package kranji.common.perclass.f.u2;

import kranji.classification.EtymologicalCategory;
import kranji.component.basic.BasicComponents;
import kranji.component.basic.PersonFamily.DanRenPang;
import kranji.pinyin.Body;
import kranji.pinyin.Final;
import kranji.pinyin.Head;
import kranji.pinyin.Initial;
import kranji.pinyin.PinyinSyllable;
import kranji.pinyin.Tail;
import kranji.pinyin.Tone;
import kranji.singular.people.PeopleAndRoles;
import kranji.singular.people.PeopleAndRoles.Zi;
import kranji.singular.radicals.RadicalComponents;
import kranji.singular.radicals.RadicalComponents.Zhao_Claw;
import kranji.zi.ComposedZiT;
import kranji.zi.CompositionLayoutT;
import kranji.zi.LeftRightT;
import kranji.zi.TopBottomPartT;

public record FuCaptive() implements ComposedZiT, LeftRightT<DanRenPang, TopBottomPartT<Zhao_Claw, Zi>> {

    public static final FuCaptive INSTANCE = new FuCaptive();

    @Override public DanRenPang left() { return BasicComponents.DAN_REN_PANG; }
    @Override public TopBottomPartT<Zhao_Claw, Zi> right() { return new TopBottomPartT<>(RadicalComponents.ZHAO_CLAW, PeopleAndRoles.ZI); }

    @Override public CompositionLayoutT layout() { return this; }

    @Override public String glyph() { return "\u4FD8"; }

    @Override public PinyinSyllable pinyin() {
        return new PinyinSyllable(Initial.F, new Final(Head.U, Body.U, Tail.NONE), Tone.SECOND);
    }

    @Override public int strokes() { return 9; }
    @Override public int radicalNo() { return 9; }
    @Override public String meaning() { return ""; }

    @Override public EtymologicalCategory etymology() {
        return new EtymologicalCategory.PhonoSemantic(BasicComponents.DAN_REN_PANG, new TopBottomPartT<>(RadicalComponents.ZHAO_CLAW, PeopleAndRoles.ZI));
    }
}
