// AUTO-GENERATED by PerclassGenerateMain - do not edit by hand.
package kranji.common.perclass.m.eng2;

import kranji.classification.EtymologicalCategory;
import kranji.common.perclass.m.ing2.Ming;
import kranji.component.basic.BasicComponents;
import kranji.component.basic.PlantFamily.CaoZiTou;
import kranji.pinyin.Body;
import kranji.pinyin.Final;
import kranji.pinyin.Head;
import kranji.pinyin.Initial;
import kranji.pinyin.PinyinSyllable;
import kranji.pinyin.Tail;
import kranji.pinyin.Tone;
import kranji.zi.ComposedZiT;
import kranji.zi.CompositionLayoutT;
import kranji.zi.TopBottomT;

public record Meng() implements ComposedZiT, TopBottomT<CaoZiTou, Ming> {

    public static final Meng INSTANCE = new Meng();

    @Override public CaoZiTou top() { return BasicComponents.CAO_ZI_TOU; }
    @Override public Ming bottom() { return Ming.INSTANCE; }

    @Override public CompositionLayoutT layout() { return this; }

    @Override public String glyph() { return "\u840C"; }

    @Override public PinyinSyllable pinyin() {
        return new PinyinSyllable(Initial.M, new Final(Head.OPEN, Body.E, Tail.NG), Tone.SECOND);
    }

    @Override public int strokes() { return 11; }
    @Override public int radicalNo() { return 140; }
    @Override public String meaning() { return ""; }

    @Override public EtymologicalCategory etymology() {
        return new EtymologicalCategory.PhonoSemantic(BasicComponents.CAO_ZI_TOU, Ming.INSTANCE);
    }
}
