// AUTO-GENERATED by Depth1GenerateMain - do not edit by hand.
package kranji.common.depth1.t;

import kranji.classification.EtymologicalCategory.*;
import kranji.component.basic.BasicComponents;
import kranji.pinyin.Body;
import kranji.pinyin.Final;
import kranji.pinyin.Head;
import kranji.pinyin.Initial;
import kranji.pinyin.PinyinSyllable;
import kranji.pinyin.Tail;
import kranji.pinyin.Tone;
import kranji.singular.nature.NatureElements;
import kranji.zi.ComposedPart;
import kranji.zi.ComposedZi;
import kranji.zi.CompositionLayout.*;
import kranji.zi.SingularPart;
import kranji.zi.ZiChar;
import java.util.List;

public final class U2 {

    private U2() {}

    public static final ComposedZi TU_MAP = new ComposedZi(
            new ZiChar.Unicode("\u56FE"),
            new PinyinSyllable(Initial.T, new Final(Head.U, Body.U, Tail.NONE), Tone.SECOND),
            8, 31, "",
            new FullEnclosure(BasicComponents.GUO_ZI_KUANG, NatureElements.DONG_WINTER),
            new PhonoSemantic(BasicComponents.GUO_ZI_KUANG, NatureElements.DONG_WINTER));

    public static final List<ComposedZi> ALL = List.of(
            TU_MAP);
}
