// AUTO-GENERATED by PerclassGenerateMain - do not edit by hand.
package kranji.common.perclass.l.in2;

import kranji.classification.EtymologicalCategory;
import kranji.component.basic.BasicComponents;
import kranji.component.basic.EarFamily.ErPang;
import kranji.pinyin.Body;
import kranji.pinyin.Final;
import kranji.pinyin.Head;
import kranji.pinyin.Initial;
import kranji.pinyin.PinyinSyllable;
import kranji.pinyin.Tail;
import kranji.pinyin.Tone;
import kranji.singular.actions.ActionsAndStates;
import kranji.singular.actions.ActionsAndStates.Ling;
import kranji.zi.ComposedZiT;
import kranji.zi.CompositionLayoutT;
import kranji.zi.LeftRightT;

public record LinNeighbor() implements ComposedZiT, LeftRightT<Ling, ErPang> {

    public static final LinNeighbor INSTANCE = new LinNeighbor();

    @Override public Ling left() { return ActionsAndStates.LING; }
    @Override public ErPang right() { return BasicComponents.ER_PANG; }

    @Override public CompositionLayoutT layout() { return this; }

    @Override public String glyph() { return "\u90BB"; }

    @Override public PinyinSyllable pinyin() {
        return new PinyinSyllable(Initial.L, new Final(Head.OPEN, Body.I, Tail.N), Tone.SECOND);
    }

    @Override public int strokes() { return 7; }
    @Override public int radicalNo() { return 163; }
    @Override public String meaning() { return ""; }

    @Override public EtymologicalCategory etymology() {
        return new EtymologicalCategory.PhonoSemantic(BasicComponents.ER_PANG, ActionsAndStates.LING);
    }
}
