// AUTO-GENERATED by PerclassGenerateMain - do not edit by hand.
package kranji.common.perclass.r.en3;

import kranji.classification.EtymologicalCategory;
import kranji.pinyin.Body;
import kranji.pinyin.Final;
import kranji.pinyin.Head;
import kranji.pinyin.Initial;
import kranji.pinyin.PinyinSyllable;
import kranji.pinyin.Tail;
import kranji.pinyin.Tone;
import kranji.singular.body.BodyParts;
import kranji.singular.body.BodyParts.Xin;
import kranji.singular.tools.ToolsAndVessels;
import kranji.singular.tools.ToolsAndVessels.Ren_Blade;
import kranji.zi.ComposedZiT;
import kranji.zi.CompositionLayoutT;
import kranji.zi.TopBottomT;

public record RenEndure() implements ComposedZiT, TopBottomT<Ren_Blade, Xin> {

    public static final RenEndure INSTANCE = new RenEndure();

    @Override public Ren_Blade top() { return ToolsAndVessels.REN_BLADE; }
    @Override public Xin bottom() { return BodyParts.XIN; }

    @Override public CompositionLayoutT layout() { return this; }

    @Override public String glyph() { return "\u5FCD"; }

    @Override public PinyinSyllable pinyin() {
        return new PinyinSyllable(Initial.R, new Final(Head.OPEN, Body.E, Tail.N), Tone.THIRD);
    }

    @Override public int strokes() { return 7; }
    @Override public int radicalNo() { return 61; }
    @Override public String meaning() { return ""; }

    @Override public EtymologicalCategory etymology() {
        return new EtymologicalCategory.PhonoSemantic(BodyParts.XIN, ToolsAndVessels.REN_BLADE);
    }
}
