// AUTO-GENERATED by kranji-codegen. Do not edit by hand.
package kranji.singular.numbers.l;

import kranji.library.BasicSet;
import kranji.library.LibraryMember;
import kranji.zi.SingularZi;

public record Liu() implements LibraryMember<BasicSet>, SingularZi {
    public static final Liu INSTANCE = new Liu();

    @Override public String glyph() { return "\u516D"; }
    @Override public String meaning() { return "six"; }
    @Override public String pinyinText() { return "li\u00F9"; }
    @Override public int strokes() { return 4; }
    @Override public BasicSet library() { return BasicSet.INSTANCE; }
}
