// AUTO-GENERATED by kranji-codegen. Do not edit by hand.
package kranji.singular.tools.d;

import kranji.library.BasicSet;
import kranji.library.LibraryMember;
import kranji.zi.SingularZi;

public record Dao() implements LibraryMember<BasicSet>, SingularZi {
    public static final Dao INSTANCE = new Dao();

    @Override public String glyph() { return "\u5200"; }
    @Override public String meaning() { return "knife"; }
    @Override public String pinyinText() { return "d\u0101o"; }
    @Override public int strokes() { return 2; }
    @Override public BasicSet library() { return BasicSet.INSTANCE; }
}
