// AUTO-GENERATED by kranji-codegen. Do not edit by hand.
package kranji.singular.tools.d;

import kranji.library.BasicSet;
import kranji.library.LibraryMember;
import kranji.zi.SingularZi;

public record Ding_Nail() implements LibraryMember<BasicSet>, SingularZi {
    public static final Ding_Nail INSTANCE = new Ding_Nail();

    @Override public String glyph() { return "\u4E01"; }
    @Override public String meaning() { return "nail/4th Heavenly Stem"; }
    @Override public String pinyinText() { return "d\u012Bng"; }
    @Override public int strokes() { return 2; }
    @Override public BasicSet library() { return BasicSet.INSTANCE; }
}
