// AUTO-GENERATED by kranji-codegen. Do not edit by hand.
package kranji.singular.animals.n;

import kranji.library.BasicSet;
import kranji.library.LibraryMember;
import kranji.zi.SingularZi;

public record Niao() implements LibraryMember<BasicSet>, SingularZi {
    public static final Niao INSTANCE = new Niao();

    @Override public String glyph() { return "\u9E1F"; }
    @Override public String meaning() { return "bird"; }
    @Override public String pinyinText() { return "ni\u01CEo"; }
    @Override public int strokes() { return 5; }
    @Override public BasicSet library() { return BasicSet.INSTANCE; }
}
