// AUTO-GENERATED by kranji-codegen. Do not edit by hand.
package kranji.singular.plants.l;

import kranji.library.BasicSet;
import kranji.library.LibraryMember;
import kranji.zi.SingularZi;

public record Lei_Plow() implements LibraryMember<BasicSet>, SingularZi {
    public static final Lei_Plow INSTANCE = new Lei_Plow();

    @Override public String glyph() { return "\u8012"; }
    @Override public String meaning() { return "plow handle"; }
    @Override public String pinyinText() { return "l\u011Bi"; }
    @Override public int strokes() { return 6; }
    @Override public BasicSet library() { return BasicSet.INSTANCE; }
}
