// AUTO-GENERATED by CatalogIteratorMain - do not edit by hand.
package kranji.common.perclass.promoted.zh.ou1;

import kranji.classification.EtymologicalCategory;
import kranji.pinyin.Body;
import kranji.pinyin.Final;
import kranji.pinyin.Head;
import kranji.pinyin.Initial;
import kranji.pinyin.PinyinSyllable;
import kranji.pinyin.Tail;
import kranji.pinyin.Tone;
import kranji.singular.plants.PlantsAndAgriculture;
import kranji.singular.tools.ToolsAndVessels;
import kranji.zi.ComposedZiT;
import kranji.zi.CompositionLayoutT;
import kranji.zi.LeftMiddleRightT;

public record ZhouPorridge() implements ComposedZiT, LeftMiddleRightT<ToolsAndVessels.Gong, PlantsAndAgriculture.Mi, ToolsAndVessels.Gong> {

    public static final ZhouPorridge INSTANCE = new ZhouPorridge();

    @Override public ToolsAndVessels.Gong left() { return ToolsAndVessels.GONG; }
    @Override public PlantsAndAgriculture.Mi middle() { return PlantsAndAgriculture.MI; }
    @Override public ToolsAndVessels.Gong right() { return ToolsAndVessels.GONG; }

    @Override public CompositionLayoutT layout() { return this; }

    @Override public String glyph() { return "\u7CA5"; }

    @Override public PinyinSyllable pinyin() {
        return new PinyinSyllable(Initial.ZH, new Final(Head.OPEN, Body.O, Tail.VOWEL_U), Tone.FIRST);
    }

    @Override public int strokes() { return 0; }
    @Override public int radicalNo() { return 0; }
    @Override public String meaning() { return ""; }

    @Override public EtymologicalCategory etymology() {
        return new EtymologicalCategory.DerivativeCognate("");
    }
}
