// AUTO-GENERATED by PerclassGenerateMain - do not edit by hand.
package kranji.common.perclass.b.an4;

import kranji.classification.EtymologicalCategory;
import kranji.common.perclass.f.en1.Fen;
import kranji.component.basic.BasicComponents;
import kranji.component.basic.HandFamily.TiShouPang;
import kranji.pinyin.Body;
import kranji.pinyin.Final;
import kranji.pinyin.Head;
import kranji.pinyin.Initial;
import kranji.pinyin.PinyinSyllable;
import kranji.pinyin.Tail;
import kranji.pinyin.Tone;
import kranji.zi.ComposedZiT;
import kranji.zi.CompositionLayoutT;
import kranji.zi.LeftRightT;

public record BanDress() implements ComposedZiT, LeftRightT<TiShouPang, Fen> {

    public static final BanDress INSTANCE = new BanDress();

    @Override public TiShouPang left() { return BasicComponents.TI_SHOU_PANG; }
    @Override public Fen right() { return Fen.INSTANCE; }

    @Override public CompositionLayoutT layout() { return this; }

    @Override public String glyph() { return "\u626E"; }

    @Override public PinyinSyllable pinyin() {
        return new PinyinSyllable(Initial.B, new Final(Head.OPEN, Body.A, Tail.N), Tone.FOURTH);
    }

    @Override public int strokes() { return 7; }
    @Override public int radicalNo() { return 64; }
    @Override public String meaning() { return ""; }

    @Override public EtymologicalCategory etymology() {
        return new EtymologicalCategory.PhonoSemantic(BasicComponents.TI_SHOU_PANG, Fen.INSTANCE);
    }
}
