// AUTO-GENERATED by kranji-codegen. Do not edit by hand.
package kranji.singular.radicals;

import kranji.library.BasicSet;
import kranji.library.LibraryMember;

import kranji.singular.radicals.b.Ba_Top;
import kranji.singular.radicals.b.Bian_Pick;
import kranji.singular.radicals.c.Ci_Thorn;
import kranji.singular.radicals.ch.Cha_Spade;
import kranji.singular.radicals.ch.Che_Sprout;
import kranji.singular.radicals.ch.Chu_Step;
import kranji.singular.radicals.d.Dao_Top;
import kranji.singular.radicals.d.Duan_Upright;
import kranji.singular.radicals.d.Dui_Mound;
import kranji.singular.radicals.f.Fei_Wrong;
import kranji.singular.radicals.f.Fu_Full;
import kranji.singular.radicals.g.Gan_Shield;
import kranji.singular.radicals.g.Gan_Upper;
import kranji.singular.radicals.g.Gong_Clasp;
import kranji.singular.radicals.g.Gun;
import kranji.singular.radicals.h.Hu_Tiger;
import kranji.singular.radicals.h.Hua_Stroke;
import kranji.singular.radicals.j.Ji_Not;
import kranji.singular.radicals.j.Ji_Person;
import kranji.singular.radicals.j.Ji_Snout;
import kranji.singular.radicals.j.Jian_Firm;
import kranji.singular.radicals.j.Jie_Seal;
import kranji.singular.radicals.j.Jing_Stream;
import kranji.singular.radicals.j.Jiu_Twist;
import kranji.singular.radicals.j.Jun_Talent;
import kranji.singular.radicals.k.Kang;
import kranji.singular.radicals.k.Kao;
import kranji.singular.radicals.l.Lao_Top;
import kranji.singular.radicals.l.Liang_Good;
import kranji.singular.radicals.l.Liu_Flow;
import kranji.singular.radicals.m.Mao_Cap;
import kranji.singular.radicals.m.Mei_Each;
import kranji.singular.radicals.m.Mi_Silk;
import kranji.singular.radicals.m.Mu_Variant;
import kranji.singular.radicals.n.Niu_Left;
import kranji.singular.radicals.n.Niu_Top;
import kranji.singular.radicals.p.Pai_Spread;
import kranji.singular.radicals.p.Pie;
import kranji.singular.radicals.q.Qi_Lacquer;
import kranji.singular.radicals.q.Qian_Owe;
import kranji.singular.radicals.q.Qiang_Left;
import kranji.singular.radicals.q.Qing_Chime;
import kranji.singular.radicals.q.Quan_Upper;
import kranji.singular.radicals.r.Ran_Flesh;
import kranji.singular.radicals.r.Ran_Whiskers;
import kranji.singular.radicals.s.Si_Private;
import kranji.singular.radicals.sh.Shan_Hair;
import kranji.singular.radicals.sh.Shen_Deep;
import kranji.singular.radicals.sh.Shi_Show;
import kranji.singular.radicals.sh.Shu_Erect;
import kranji.singular.radicals.sh.Shu_Lance;
import kranji.singular.radicals.sh.Shui_Variant;
import kranji.singular.radicals.t.Tu_Old;
import kranji.singular.radicals.x.Shang_Dot;
import kranji.singular.radicals.x.Xi_Cover;
import kranji.singular.radicals.x.Xia_Hook;
import kranji.singular.radicals.x.Xian_Pit;
import kranji.singular.radicals.x.Xiang_Descend;
import kranji.singular.radicals.x.Xiao_Top;
import kranji.singular.radicals.x.Xuan_Dark;
import kranji.singular.radicals.z.Zuo_Hand;
import kranji.singular.radicals.zero.Ang;
import kranji.singular.radicals.zero.Wang_Net;
import kranji.singular.radicals.zero.Wu_Cross;
import kranji.singular.radicals.zero.Yan_Flag;
import kranji.singular.radicals.zero.Yan_Marsh;
import kranji.singular.radicals.zero.Yang_Bright;
import kranji.singular.radicals.zero.Yao_Lines;
import kranji.singular.radicals.zero.Ye_Leaf;
import kranji.singular.radicals.zero.Yi_Hook;
import kranji.singular.radicals.zero.Yi_Turn;
import kranji.singular.radicals.zero.Yin_Hook;
import kranji.singular.radicals.zero.Yin_Sound;
import kranji.singular.radicals.zero.Yin_Waver;
import kranji.singular.radicals.zero.Yu_Feather;
import kranji.singular.radicals.zh.Dian;
import kranji.singular.radicals.zh.Zhao_Claw;
import kranji.singular.radicals.zh.Zhi_Arrive;
import kranji.singular.radicals.zh.Zhi_Slow;
import kranji.singular.radicals.zh.Zhu_Drum;
import kranji.singular.radicals.zh.Zhu_Top;

import java.util.List;

public final class RadicalsSingulars {
    private RadicalsSingulars() {}

    public static final List<LibraryMember<BasicSet>> ALL = List.of(
            Ang.INSTANCE,
            Ba_Top.INSTANCE,
            Bian_Pick.INSTANCE,
            Cha_Spade.INSTANCE,
            Che_Sprout.INSTANCE,
            Chu_Step.INSTANCE,
            Ci_Thorn.INSTANCE,
            Dao_Top.INSTANCE,
            Dian.INSTANCE,
            Duan_Upright.INSTANCE,
            Dui_Mound.INSTANCE,
            Fei_Wrong.INSTANCE,
            Fu_Full.INSTANCE,
            Gan_Shield.INSTANCE,
            Gan_Upper.INSTANCE,
            Gong_Clasp.INSTANCE,
            Gun.INSTANCE,
            Hu_Tiger.INSTANCE,
            Hua_Stroke.INSTANCE,
            Ji_Not.INSTANCE,
            Ji_Person.INSTANCE,
            Ji_Snout.INSTANCE,
            Jian_Firm.INSTANCE,
            Jie_Seal.INSTANCE,
            Jing_Stream.INSTANCE,
            Jiu_Twist.INSTANCE,
            Jun_Talent.INSTANCE,
            Kang.INSTANCE,
            Kao.INSTANCE,
            Lao_Top.INSTANCE,
            Liang_Good.INSTANCE,
            Liu_Flow.INSTANCE,
            Mao_Cap.INSTANCE,
            Mei_Each.INSTANCE,
            Mi_Silk.INSTANCE,
            Mu_Variant.INSTANCE,
            Niu_Left.INSTANCE,
            Niu_Top.INSTANCE,
            Pai_Spread.INSTANCE,
            Pie.INSTANCE,
            Qi_Lacquer.INSTANCE,
            Qian_Owe.INSTANCE,
            Qiang_Left.INSTANCE,
            Qing_Chime.INSTANCE,
            Quan_Upper.INSTANCE,
            Ran_Flesh.INSTANCE,
            Ran_Whiskers.INSTANCE,
            Shan_Hair.INSTANCE,
            Shang_Dot.INSTANCE,
            Shen_Deep.INSTANCE,
            Shi_Show.INSTANCE,
            Shu_Erect.INSTANCE,
            Shu_Lance.INSTANCE,
            Shui_Variant.INSTANCE,
            Si_Private.INSTANCE,
            Tu_Old.INSTANCE,
            Wang_Net.INSTANCE,
            Wu_Cross.INSTANCE,
            Xi_Cover.INSTANCE,
            Xia_Hook.INSTANCE,
            Xian_Pit.INSTANCE,
            Xiang_Descend.INSTANCE,
            Xiao_Top.INSTANCE,
            Xuan_Dark.INSTANCE,
            Yan_Flag.INSTANCE,
            Yan_Marsh.INSTANCE,
            Yang_Bright.INSTANCE,
            Yao_Lines.INSTANCE,
            Ye_Leaf.INSTANCE,
            Yi_Hook.INSTANCE,
            Yi_Turn.INSTANCE,
            Yin_Hook.INSTANCE,
            Yin_Sound.INSTANCE,
            Yin_Waver.INSTANCE,
            Yu_Feather.INSTANCE,
            Zhao_Claw.INSTANCE,
            Zhi_Arrive.INSTANCE,
            Zhi_Slow.INSTANCE,
            Zhu_Drum.INSTANCE,
            Zhu_Top.INSTANCE,
            Zuo_Hand.INSTANCE);
}
