// AUTO-GENERATED by kranji-codegen. Do not edit by hand.
package kranji.singular.body.p;

import kranji.library.BasicSet;
import kranji.library.LibraryMember;
import kranji.zi.SingularZi;

public record Pi() implements LibraryMember<BasicSet>, SingularZi {
    public static final Pi INSTANCE = new Pi();

    @Override public String glyph() { return "\u76AE"; }
    @Override public String meaning() { return "skin"; }
    @Override public String pinyinText() { return "p\u00ED"; }
    @Override public int strokes() { return 5; }
    @Override public BasicSet library() { return BasicSet.INSTANCE; }
}
