// AUTO-GENERATED by kranji-codegen. Do not edit by hand.
package kranji.singular.space.sh;

import kranji.library.BasicSet;
import kranji.library.LibraryMember;
import kranji.zi.SingularZi;

public record Shang() implements LibraryMember<BasicSet>, SingularZi {
    public static final Shang INSTANCE = new Shang();

    @Override public String glyph() { return "\u4E0A"; }
    @Override public String meaning() { return "above, up"; }
    @Override public String pinyinText() { return "sh\u00E0ng"; }
    @Override public int strokes() { return 3; }
    @Override public BasicSet library() { return BasicSet.INSTANCE; }
}
