// AUTO-GENERATED by CatalogIteratorMain - do not edit by hand.
package kranji.common.perclass.promoted.sh.u2;

import kranji.pinyin.Body;
import kranji.pinyin.Final;
import kranji.pinyin.Head;
import kranji.pinyin.Initial;
import kranji.pinyin.PinyinSyllable;
import kranji.pinyin.Tail;
import kranji.pinyin.Tone;
import kranji.zi.SingularZi;

public record ShuShuAuto() implements SingularZi {

    public static final ShuShuAuto INSTANCE = new ShuShuAuto();

    @Override public String glyph() { return "\u5B70"; }

    @Override public PinyinSyllable pinyin() {
        return new PinyinSyllable(Initial.SH, new Final(Head.U, Body.U, Tail.NONE), Tone.SECOND);
    }

    @Override public boolean unsure() { return true; }
}
