// AUTO-GENERATED by Depth1GenerateMain - do not edit by hand.
package kranji.common.depth1.x;

import kranji.classification.EtymologicalCategory.*;
import kranji.component.basic.BasicComponents;
import kranji.pinyin.Body;
import kranji.pinyin.Final;
import kranji.pinyin.Head;
import kranji.pinyin.Initial;
import kranji.pinyin.PinyinSyllable;
import kranji.pinyin.Tail;
import kranji.pinyin.Tone;
import kranji.singular.tools.ToolsAndVessels;
import kranji.zi.ComposedPart;
import kranji.zi.ComposedZi;
import kranji.zi.CompositionLayout.*;
import kranji.zi.SingularPart;
import kranji.zi.ZiChar;
import java.util.List;

public final class Ian2 {

    private Ian2() {}

    public static final ComposedZi XIAN_IDLE = new ComposedZi(
            new ZiChar.Unicode("\u95F2"),
            new PinyinSyllable(Initial.X, new Final(Head.I, Body.A, Tail.N), Tone.SECOND),
            7, 169, "",
            new SemiEnclosureTopThree(ToolsAndVessels.MEN, BasicComponents.MU),
            new PhonoSemantic(ToolsAndVessels.MEN, BasicComponents.MU));

    public static final List<ComposedZi> ALL = List.of(
            XIAN_IDLE);
}
