// AUTO-GENERATED by Depth1GenerateMain - do not edit by hand.
package kranji.common.depth1.x;

import kranji.classification.EtymologicalCategory.*;
import kranji.component.basic.BasicComponents;
import kranji.pinyin.Body;
import kranji.pinyin.Final;
import kranji.pinyin.Head;
import kranji.pinyin.Initial;
import kranji.pinyin.PinyinSyllable;
import kranji.pinyin.Tail;
import kranji.pinyin.Tone;
import kranji.singular.actions.ActionsAndStates;
import kranji.singular.radicals.RadicalComponents;
import kranji.zi.ComposedPart;
import kranji.zi.ComposedZi;
import kranji.zi.CompositionLayout.*;
import kranji.zi.SingularPart;
import kranji.zi.ZiChar;
import java.util.List;

public final class Ing2 {

    private Ing2() {}

    public static final ComposedZi XING_PUNISH = new ComposedZi(
            new ZiChar.Unicode("\u5211"),
            new PinyinSyllable(Initial.X, new Final(Head.OPEN, Body.I, Tail.NG), Tone.SECOND),
            6, 18, "",
            new LeftRight(ActionsAndStates.KAI, BasicComponents.LI_DAO_PANG),
            new PhonoSemantic(BasicComponents.LI_DAO_PANG, ActionsAndStates.KAI));

    public static final ComposedZi XING_SHAPE = new ComposedZi(
            new ZiChar.Unicode("\u5F62"),
            new PinyinSyllable(Initial.X, new Final(Head.OPEN, Body.I, Tail.NG), Tone.SECOND),
            7, 59, "",
            new LeftRight(ActionsAndStates.KAI, RadicalComponents.SHAN_HAIR),
            new PhonoSemantic(ActionsAndStates.KAI, RadicalComponents.SHAN_HAIR));

    public static final List<ComposedZi> ALL = List.of(
            XING_PUNISH,
            XING_SHAPE);
}
