// AUTO-GENERATED by CatalogIteratorMain - do not edit by hand.
package kranji.common.perclass.promoted.c.e4;

import kranji.classification.EtymologicalCategory;
import kranji.pinyin.Body;
import kranji.pinyin.Final;
import kranji.pinyin.Head;
import kranji.pinyin.Initial;
import kranji.pinyin.PinyinSyllable;
import kranji.pinyin.Tail;
import kranji.pinyin.Tone;
import kranji.singular.radicals.RadicalComponents;
import kranji.zi.ComposedZiT;
import kranji.zi.CompositionLayoutT;
import kranji.zi.TopBottomT;

public record CePlan() implements ComposedZiT, TopBottomT<RadicalComponents.Zhu_Bamboo, RadicalComponents.Ci_Thorn> {

    public static final CePlan INSTANCE = new CePlan();

    @Override public RadicalComponents.Zhu_Bamboo top() { return RadicalComponents.ZHU_BAMBOO; }
    @Override public RadicalComponents.Ci_Thorn bottom() { return RadicalComponents.CI_THORN; }

    @Override public CompositionLayoutT layout() { return this; }

    @Override public String glyph() { return "\u7B56"; }

    @Override public PinyinSyllable pinyin() {
        return new PinyinSyllable(Initial.C, new Final(Head.OPEN, Body.E, Tail.NONE), Tone.FOURTH);
    }

    @Override public int strokes() { return 0; }
    @Override public int radicalNo() { return 0; }
    @Override public String meaning() { return ""; }

    @Override public EtymologicalCategory etymology() {
        return new EtymologicalCategory.PhonoSemantic(RadicalComponents.ZHU_BAMBOO, RadicalComponents.CI_THORN);
    }
}
