// AUTO-GENERATED by kranji-codegen. Do not edit by hand.
package kranji.singular.radicals.r;

import kranji.library.BasicSet;
import kranji.library.LibraryMember;
import kranji.zi.SingularPart;

public record Ran_Whiskers() implements LibraryMember<BasicSet>, SingularPart {
    public static final Ran_Whiskers INSTANCE = new Ran_Whiskers();

    @Override public String glyph() { return "\u5184"; }
    @Override public String meaning() { return "whiskers, tender"; }
    @Override public String pinyinText() { return "r\u01CEn"; }
    @Override public int strokes() { return 4; }
    @Override public BasicSet library() { return BasicSet.INSTANCE; }
}
