// AUTO-GENERATED by PerclassGenerateMain - do not edit by hand.
package kranji.common.perclass.d.ao4;

import kranji.classification.EtymologicalCategory;
import kranji.component.basic.BasicComponents;
import kranji.component.basic.KnifeFamily.LiDaoPang;
import kranji.pinyin.Body;
import kranji.pinyin.Final;
import kranji.pinyin.Head;
import kranji.pinyin.Initial;
import kranji.pinyin.PinyinSyllable;
import kranji.pinyin.Tail;
import kranji.pinyin.Tone;
import kranji.singular.radicals.RadicalComponents;
import kranji.singular.radicals.RadicalComponents.Zhi_Arrive;
import kranji.zi.ComposedZiT;
import kranji.zi.CompositionLayoutT;
import kranji.zi.LeftRightT;

public record DaoArrive() implements ComposedZiT, LeftRightT<Zhi_Arrive, LiDaoPang> {

    public static final DaoArrive INSTANCE = new DaoArrive();

    @Override public Zhi_Arrive left() { return RadicalComponents.ZHI_ARRIVE; }
    @Override public LiDaoPang right() { return BasicComponents.LI_DAO_PANG; }

    @Override public CompositionLayoutT layout() { return this; }

    @Override public String glyph() { return "\u5230"; }

    @Override public PinyinSyllable pinyin() {
        return new PinyinSyllable(Initial.D, new Final(Head.OPEN, Body.A, Tail.VOWEL_U), Tone.FOURTH);
    }

    @Override public int strokes() { return 8; }
    @Override public int radicalNo() { return 18; }
    @Override public String meaning() { return ""; }

    @Override public EtymologicalCategory etymology() {
        return new EtymologicalCategory.PhonoSemantic(RadicalComponents.ZHI_ARRIVE, BasicComponents.LI_DAO_PANG);
    }
}
