// AUTO-GENERATED by PerclassGenerateMain - do not edit by hand.
package kranji.common.perclass.l.i4;

import kranji.classification.EtymologicalCategory;
import kranji.pinyin.Body;
import kranji.pinyin.Final;
import kranji.pinyin.Head;
import kranji.pinyin.Initial;
import kranji.pinyin.PinyinSyllable;
import kranji.pinyin.Tail;
import kranji.pinyin.Tone;
import kranji.singular.structures.Structures;
import kranji.singular.structures.Structures.Chang_Factory;
import kranji.singular.tools.ToolsAndVessels;
import kranji.singular.tools.ToolsAndVessels.Li_Plow;
import kranji.zi.ComposedZiT;
import kranji.zi.CompositionLayoutT;
import kranji.zi.SemiEnclosureUpperLeftT;

public record LiHistory() implements ComposedZiT, SemiEnclosureUpperLeftT<Chang_Factory, Li_Plow> {

    public static final LiHistory INSTANCE = new LiHistory();

    @Override public Chang_Factory wrapper() { return Structures.CHANG_FACTORY; }
    @Override public Li_Plow content() { return ToolsAndVessels.LI_PLOW; }

    @Override public CompositionLayoutT layout() { return this; }

    @Override public String glyph() { return "\u5386"; }

    @Override public PinyinSyllable pinyin() {
        return new PinyinSyllable(Initial.L, new Final(Head.OPEN, Body.I, Tail.NONE), Tone.FOURTH);
    }

    @Override public int strokes() { return 4; }
    @Override public int radicalNo() { return 27; }
    @Override public String meaning() { return ""; }

    @Override public EtymologicalCategory etymology() {
        return new EtymologicalCategory.PhonoSemantic(Structures.CHANG_FACTORY, ToolsAndVessels.LI_PLOW);
    }
}
