// AUTO-GENERATED by Depth1GenerateMain - do not edit by hand.
package kranji.common.depth1.d;

import kranji.classification.EtymologicalCategory.*;
import kranji.pinyin.Body;
import kranji.pinyin.Final;
import kranji.pinyin.Head;
import kranji.pinyin.Initial;
import kranji.pinyin.PinyinSyllable;
import kranji.pinyin.Tail;
import kranji.pinyin.Tone;
import kranji.singular.materials.Materials;
import kranji.singular.tools.ToolsAndVessels;
import kranji.zi.ComposedPart;
import kranji.zi.ComposedZi;
import kranji.zi.CompositionLayout.*;
import kranji.zi.SingularPart;
import kranji.zi.ZiChar;
import java.util.List;

public final class I4 {

    private I4() {}

    public static final ComposedZi DI_TARGET = new ComposedZi(
            new ZiChar.Unicode("\u7684"),
            new PinyinSyllable(Initial.D, new Final(Head.OPEN, Body.I, Tail.NONE), Tone.FOURTH),
            8, 106, "",
            new LeftRight(Materials.BAI_WHITE, ToolsAndVessels.SHAO),
            new PhonoSemantic(Materials.BAI_WHITE, ToolsAndVessels.SHAO));

    public static final List<ComposedZi> ALL = List.of(
            DI_TARGET);
}
