// AUTO-GENERATED by Depth1GenerateMain - do not edit by hand.
package kranji.common.depth1.d;

import kranji.classification.EtymologicalCategory.*;
import kranji.pinyin.Body;
import kranji.pinyin.Final;
import kranji.pinyin.Head;
import kranji.pinyin.Initial;
import kranji.pinyin.PinyinSyllable;
import kranji.pinyin.Tail;
import kranji.pinyin.Tone;
import kranji.singular.body.BodyParts;
import kranji.singular.tools.ToolsAndVessels;
import kranji.zi.ComposedPart;
import kranji.zi.ComposedZi;
import kranji.zi.CompositionLayout.*;
import kranji.zi.SingularPart;
import kranji.zi.ZiChar;
import java.util.List;

public final class Iao1 {

    private Iao1() {}

    public static final ComposedZi DIAO_HOLD = new ComposedZi(
            new ZiChar.Unicode("\u53FC"),
            new PinyinSyllable(Initial.D, new Final(Head.I, Body.A, Tail.VOWEL_U), Tone.FIRST),
            5, 30, "",
            new LeftRight(BodyParts.KOU, ToolsAndVessels.DIAO),
            new PhonoSemantic(BodyParts.KOU, ToolsAndVessels.DIAO));

    public static final List<ComposedZi> ALL = List.of(
            DIAO_HOLD);
}
