// AUTO-GENERATED by Depth1GenerateMain - do not edit by hand.
package kranji.common.depth1.d;

import kranji.classification.EtymologicalCategory.*;
import kranji.component.basic.BasicComponents;
import kranji.pinyin.Body;
import kranji.pinyin.Final;
import kranji.pinyin.Head;
import kranji.pinyin.Initial;
import kranji.pinyin.PinyinSyllable;
import kranji.pinyin.Tail;
import kranji.pinyin.Tone;
import kranji.singular.tools.ToolsAndVessels;
import kranji.zi.ComposedPart;
import kranji.zi.ComposedZi;
import kranji.zi.CompositionLayout.*;
import kranji.zi.SingularPart;
import kranji.zi.ZiChar;
import java.util.List;

public final class Ing4 {

    private Ing4() {}

    public static final ComposedZi DING_SUBSCRIBE = new ComposedZi(
            new ZiChar.Unicode("\u8BA2"),
            new PinyinSyllable(Initial.D, new Final(Head.OPEN, Body.I, Tail.NG), Tone.FOURTH),
            4, 149, "",
            new LeftRight(BasicComponents.YAN_ZI_PANG, ToolsAndVessels.DING_NAIL),
            new PhonoSemantic(BasicComponents.YAN_ZI_PANG, ToolsAndVessels.DING_NAIL));

    public static final List<ComposedZi> ALL = List.of(
            DING_SUBSCRIBE);
}
