// AUTO-GENERATED by Depth1GenerateMain - do not edit by hand.
package kranji.common.depth1.d;

import kranji.classification.EtymologicalCategory.*;
import kranji.component.basic.BasicComponents;
import kranji.pinyin.Body;
import kranji.pinyin.Final;
import kranji.pinyin.Head;
import kranji.pinyin.Initial;
import kranji.pinyin.PinyinSyllable;
import kranji.pinyin.Tail;
import kranji.pinyin.Tone;
import kranji.singular.actions.ActionsAndStates;
import kranji.singular.people.PeopleAndRoles;
import kranji.singular.structures.Structures;
import kranji.zi.ComposedPart;
import kranji.zi.ComposedZi;
import kranji.zi.CompositionLayout.*;
import kranji.zi.SingularPart;
import kranji.zi.ZiChar;
import java.util.List;

public final class Uei4 {

    private Uei4() {}

    public static final ComposedZi DUI_CORRECT = new ComposedZi(
            new ZiChar.Unicode("\u5BF9"),
            new PinyinSyllable(Initial.D, new Final(Head.U, Body.E, Tail.VOWEL_I), Tone.FOURTH),
            5, 41, "",
            new LeftRight(ActionsAndStates.YOU_AGAIN, Structures.CUN_INCH),
            new CompoundIndicative("又(hand) + 寸(inch/measure) → correct, pair"));

    public static final ComposedZi DUI_TEAM = new ComposedZi(
            new ZiChar.Unicode("\u961F"),
            new PinyinSyllable(Initial.D, new Final(Head.U, Body.E, Tail.VOWEL_I), Tone.FOURTH),
            4, 170, "",
            new LeftRight(BasicComponents.ER_PANG, PeopleAndRoles.REN),
            new PhonoSemantic(BasicComponents.ER_PANG, PeopleAndRoles.REN));

    public static final List<ComposedZi> ALL = List.of(
            DUI_CORRECT,
            DUI_TEAM);
}
