// AUTO-GENERATED by Depth2GenerateMain - do not edit by hand.
package kranji.common.depth2.b;

import kranji.classification.EtymologicalCategory.*;
import kranji.component.basic.BasicComponents;
import kranji.pinyin.Body;
import kranji.pinyin.Final;
import kranji.pinyin.Head;
import kranji.pinyin.Initial;
import kranji.pinyin.PinyinSyllable;
import kranji.pinyin.Tail;
import kranji.pinyin.Tone;
import kranji.zi.ComposedPart;
import kranji.zi.ComposedZi;
import kranji.zi.CompositionLayout.*;
import kranji.zi.SingularPart;
import kranji.zi.ZiChar;
import java.util.List;

public final class Ao3 {

    private Ao3() {}

    public static final ComposedZi BAO_FULL = new ComposedZi(
            new ZiChar.Unicode("\u9971"),
            new PinyinSyllable(Initial.B, new Final(Head.OPEN, Body.A, Tail.VOWEL_U), Tone.THIRD),
            8, 184, "",
            new LeftRight(BasicComponents.SHI_ZI_PANG, kranji.common.depth1.b.Ao1.BAO_WRAP.structure()),
            new PhonoSemantic(BasicComponents.SHI_ZI_PANG, kranji.common.depth1.b.Ao1.BAO_WRAP.structure()));

    public static final List<ComposedZi> ALL = List.of(
            BAO_FULL);
}
