// AUTO-GENERATED by Depth1GenerateMain - do not edit by hand.
package kranji.common.depth1.f;

import kranji.classification.EtymologicalCategory.*;
import kranji.pinyin.Body;
import kranji.pinyin.Final;
import kranji.pinyin.Head;
import kranji.pinyin.Initial;
import kranji.pinyin.PinyinSyllable;
import kranji.pinyin.Tail;
import kranji.pinyin.Tone;
import kranji.singular.people.PeopleAndRoles;
import kranji.singular.space.SpaceAndDirection;
import kranji.singular.structures.Structures;
import kranji.zi.ComposedPart;
import kranji.zi.ComposedZi;
import kranji.zi.CompositionLayout.*;
import kranji.zi.SingularPart;
import kranji.zi.ZiChar;
import java.util.List;

public final class Ang2 {

    private Ang2() {}

    public static final ComposedZi FANG_HINDER = new ComposedZi(
            new ZiChar.Unicode("\u59A8"),
            new PinyinSyllable(Initial.F, new Final(Head.OPEN, Body.A, Tail.NG), Tone.SECOND),
            7, 38, "",
            new LeftRight(PeopleAndRoles.NV, SpaceAndDirection.FANG),
            new PhonoSemantic(PeopleAndRoles.NV, SpaceAndDirection.FANG));

    public static final ComposedZi FANG_ROOM = new ComposedZi(
            new ZiChar.Unicode("\u623F"),
            new PinyinSyllable(Initial.F, new Final(Head.OPEN, Body.A, Tail.NG), Tone.SECOND),
            8, 63, "",
            new SemiEnclosureUpperLeft(Structures.HU, SpaceAndDirection.FANG),
            new PhonoSemantic(Structures.HU, SpaceAndDirection.FANG));

    public static final List<ComposedZi> ALL = List.of(
            FANG_HINDER,
            FANG_ROOM);
}
