// AUTO-GENERATED by Depth1GenerateMain - do not edit by hand.
package kranji.common.depth1.f;

import kranji.classification.EtymologicalCategory.*;
import kranji.component.basic.BasicComponents;
import kranji.pinyin.Body;
import kranji.pinyin.Final;
import kranji.pinyin.Head;
import kranji.pinyin.Initial;
import kranji.pinyin.PinyinSyllable;
import kranji.pinyin.Tail;
import kranji.pinyin.Tone;
import kranji.singular.tools.ToolsAndVessels;
import kranji.zi.ComposedPart;
import kranji.zi.ComposedZi;
import kranji.zi.CompositionLayout.*;
import kranji.zi.SingularPart;
import kranji.zi.ZiChar;
import java.util.List;

public final class O2 {

    private O2() {}

    public static final ComposedZi FO_BUDDHA = new ComposedZi(
            new ZiChar.Unicode("\u4F5B"),
            new PinyinSyllable(Initial.F, new Final(Head.OPEN, Body.O, Tail.NONE), Tone.SECOND),
            7, 9, "",
            new LeftRight(BasicComponents.DAN_REN_PANG, ToolsAndVessels.FU_NOT),
            new PhonoSemantic(BasicComponents.DAN_REN_PANG, ToolsAndVessels.FU_NOT));

    public static final List<ComposedZi> ALL = List.of(
            FO_BUDDHA);
}
