// AUTO-GENERATED by CatalogIteratorMain - do not edit by hand.
package kranji.common.perclass.promoted.x.v4;

import kranji.classification.EtymologicalCategory;
import kranji.pinyin.Body;
import kranji.pinyin.Final;
import kranji.pinyin.Head;
import kranji.pinyin.Initial;
import kranji.pinyin.PinyinSyllable;
import kranji.pinyin.Tail;
import kranji.pinyin.Tone;
import kranji.singular.actions.ActionsAndStates;
import kranji.singular.concepts.AbstractConcepts;
import kranji.zi.ComposedZiT;
import kranji.zi.CompositionLayoutT;
import kranji.zi.LeftRightT;

public record XuNarrate() implements ComposedZiT, LeftRightT<AbstractConcepts.Yu_Surplus, ActionsAndStates.You_Again> {

    public static final XuNarrate INSTANCE = new XuNarrate();

    @Override public AbstractConcepts.Yu_Surplus left() { return AbstractConcepts.YU_SURPLUS; }
    @Override public ActionsAndStates.You_Again right() { return ActionsAndStates.YOU_AGAIN; }

    @Override public CompositionLayoutT layout() { return this; }

    @Override public String glyph() { return "\u53D9"; }

    @Override public PinyinSyllable pinyin() {
        return new PinyinSyllable(Initial.X, new Final(Head.V, Body.U, Tail.NONE), Tone.FOURTH);
    }

    @Override public int strokes() { return 0; }
    @Override public int radicalNo() { return 0; }
    @Override public String meaning() { return ""; }

    @Override public EtymologicalCategory etymology() {
        return new EtymologicalCategory.PhonoSemantic(ActionsAndStates.YOU_AGAIN, AbstractConcepts.YU_SURPLUS);
    }
}
