// AUTO-GENERATED by CatalogIteratorMain - do not edit by hand.
package kranji.common.perclass.promoted.sh.u1;

import kranji.pinyin.Body;
import kranji.pinyin.Final;
import kranji.pinyin.Head;
import kranji.pinyin.Initial;
import kranji.pinyin.PinyinSyllable;
import kranji.pinyin.Tail;
import kranji.pinyin.Tone;
import kranji.zi.SingularZi;

public record ShuPiAtom() implements SingularZi {

    public static final ShuPiAtom INSTANCE = new ShuPiAtom();

    @Override public String glyph() { return "\u758B"; }

    @Override public PinyinSyllable pinyin() {
        return new PinyinSyllable(Initial.SH, new Final(Head.U, Body.U, Tail.NONE), Tone.FIRST);
    }

    @Override public boolean unsure() { return true; }
}
