// AUTO-GENERATED by PerclassGenerateMain - do not edit by hand.
package kranji.common.perclass.zh.i1;

import kranji.classification.EtymologicalCategory;
import kranji.common.perclass.zh.i3.ZhiOnly;
import kranji.component.basic.BasicComponents;
import kranji.component.basic.SilkFamily.JiaoSiPang;
import kranji.pinyin.Body;
import kranji.pinyin.Final;
import kranji.pinyin.Head;
import kranji.pinyin.Initial;
import kranji.pinyin.PinyinSyllable;
import kranji.pinyin.Tail;
import kranji.pinyin.Tone;
import kranji.zi.ComposedZiT;
import kranji.zi.CompositionLayoutT;
import kranji.zi.LeftRightT;

public record ZhiWeave() implements ComposedZiT, LeftRightT<JiaoSiPang, ZhiOnly> {

    public static final ZhiWeave INSTANCE = new ZhiWeave();

    @Override public JiaoSiPang left() { return BasicComponents.JIAO_SI_PANG; }
    @Override public ZhiOnly right() { return ZhiOnly.INSTANCE; }

    @Override public CompositionLayoutT layout() { return this; }

    @Override public String glyph() { return "\u7EC7"; }

    @Override public PinyinSyllable pinyin() {
        return new PinyinSyllable(Initial.ZH, new Final(Head.OPEN, Body.NULL, Tail.NONE), Tone.FIRST);
    }

    @Override public int strokes() { return 8; }
    @Override public int radicalNo() { return 120; }
    @Override public String meaning() { return ""; }

    @Override public EtymologicalCategory etymology() {
        return new EtymologicalCategory.PhonoSemantic(BasicComponents.JIAO_SI_PANG, ZhiOnly.INSTANCE);
    }
}
