// AUTO-GENERATED by Depth1GenerateMain - do not edit by hand.
package kranji.common.depth1.q;

import kranji.classification.EtymologicalCategory.*;
import kranji.pinyin.Body;
import kranji.pinyin.Final;
import kranji.pinyin.Head;
import kranji.pinyin.Initial;
import kranji.pinyin.PinyinSyllable;
import kranji.pinyin.Tail;
import kranji.pinyin.Tone;
import kranji.singular.actions.ActionsAndStates;
import kranji.singular.people.PeopleAndRoles;
import kranji.zi.ComposedPart;
import kranji.zi.ComposedZi;
import kranji.zi.CompositionLayout.*;
import kranji.zi.SingularPart;
import kranji.zi.ZiChar;
import java.util.List;

public final class I2 {

    private I2() {}

    public static final ComposedZi QI_STRANGE = new ComposedZi(
            new ZiChar.Unicode("\u5947"),
            new PinyinSyllable(Initial.Q, new Final(Head.OPEN, Body.I, Tail.NONE), Tone.SECOND),
            8, 37, "",
            new TopBottom(PeopleAndRoles.DA, ActionsAndStates.KE),
            new PhonoSemantic(PeopleAndRoles.DA, ActionsAndStates.KE));

    public static final List<ComposedZi> ALL = List.of(
            QI_STRANGE);
}
