// AUTO-GENERATED by Depth1GenerateMain - do not edit by hand.
package kranji.common.depth1.q;

import kranji.classification.EtymologicalCategory.*;
import kranji.component.basic.BasicComponents;
import kranji.pinyin.Body;
import kranji.pinyin.Final;
import kranji.pinyin.Head;
import kranji.pinyin.Initial;
import kranji.pinyin.PinyinSyllable;
import kranji.pinyin.Tail;
import kranji.pinyin.Tone;
import kranji.singular.materials.Materials;
import kranji.zi.ComposedPart;
import kranji.zi.ComposedZi;
import kranji.zi.CompositionLayout.*;
import kranji.zi.SingularPart;
import kranji.zi.ZiChar;
import java.util.List;

public final class Ing1 {

    private Ing1() {}

    public static final ComposedZi QING_CLEAR = new ComposedZi(
            new ZiChar.Unicode("\u6E05"),
            new PinyinSyllable(Initial.Q, new Final(Head.OPEN, Body.I, Tail.NG), Tone.FIRST),
            11, 85, "",
            new LeftRight(BasicComponents.SAN_DIAN_SHUI, Materials.QING),
            new PhonoSemantic(BasicComponents.SAN_DIAN_SHUI, Materials.QING));

    public static final List<ComposedZi> ALL = List.of(
            QING_CLEAR);
}
