// AUTO-GENERATED by Depth1GenerateMain - do not edit by hand.
package kranji.common.depth1.q;

import kranji.classification.EtymologicalCategory.*;
import kranji.pinyin.Body;
import kranji.pinyin.Final;
import kranji.pinyin.Head;
import kranji.pinyin.Initial;
import kranji.pinyin.PinyinSyllable;
import kranji.pinyin.Tail;
import kranji.pinyin.Tone;
import kranji.singular.actions.ActionsAndStates;
import kranji.singular.radicals.RadicalComponents;
import kranji.zi.ComposedPart;
import kranji.zi.ComposedZi;
import kranji.zi.CompositionLayout.*;
import kranji.zi.SingularPart;
import kranji.zi.ZiChar;
import java.util.List;

public final class Ve4 {

    private Ve4() {}

    public static final ComposedZi QUE = new ComposedZi(
            new ZiChar.Unicode("\u5374"),
            new PinyinSyllable(Initial.Q, new Final(Head.V, Body.E_CARON, Tail.NONE), Tone.FOURTH),
            7, 26, "",
            new LeftRight(ActionsAndStates.QU, RadicalComponents.JIE_SEAL),
            new PhonoSemantic(RadicalComponents.JIE_SEAL, ActionsAndStates.QU));

    public static final List<ComposedZi> ALL = List.of(
            QUE);
}
