// AUTO-GENERATED by PerclassGenerateMain - do not edit by hand.
package kranji.common.perclass.f.u4;

import kranji.classification.EtymologicalCategory;
import kranji.common.perclass.f.u4.FuPay;
import kranji.component.basic.BasicComponents;
import kranji.component.basic.EarFamily.ErPang;
import kranji.pinyin.Body;
import kranji.pinyin.Final;
import kranji.pinyin.Head;
import kranji.pinyin.Initial;
import kranji.pinyin.PinyinSyllable;
import kranji.pinyin.Tail;
import kranji.pinyin.Tone;
import kranji.zi.ComposedZiT;
import kranji.zi.CompositionLayoutT;
import kranji.zi.LeftRightT;

public record FuAttach() implements ComposedZiT, LeftRightT<ErPang, FuPay> {

    public static final FuAttach INSTANCE = new FuAttach();

    @Override public ErPang left() { return BasicComponents.ER_PANG; }
    @Override public FuPay right() { return FuPay.INSTANCE; }

    @Override public CompositionLayoutT layout() { return this; }

    @Override public String glyph() { return "\u9644"; }

    @Override public PinyinSyllable pinyin() {
        return new PinyinSyllable(Initial.F, new Final(Head.U, Body.U, Tail.NONE), Tone.FOURTH);
    }

    @Override public int strokes() { return 7; }
    @Override public int radicalNo() { return 170; }
    @Override public String meaning() { return ""; }

    @Override public EtymologicalCategory etymology() {
        return new EtymologicalCategory.PhonoSemantic(BasicComponents.ER_PANG, FuPay.INSTANCE);
    }
}
