// AUTO-GENERATED by PerclassGenerateMain - do not edit by hand.
package kranji.common.perclass.f.u4;

import kranji.classification.EtymologicalCategory;
import kranji.component.basic.BasicComponents;
import kranji.component.basic.PersonFamily.DanRenPang;
import kranji.pinyin.Body;
import kranji.pinyin.Final;
import kranji.pinyin.Head;
import kranji.pinyin.Initial;
import kranji.pinyin.PinyinSyllable;
import kranji.pinyin.Tail;
import kranji.pinyin.Tone;
import kranji.singular.space.SpaceAndDirection;
import kranji.singular.space.SpaceAndDirection.Fu_Begin;
import kranji.singular.structures.Structures;
import kranji.singular.structures.Structures.Cun_Inch;
import kranji.zi.ComposedZiT;
import kranji.zi.CompositionLayoutT;
import kranji.zi.LeftRightPartT;
import kranji.zi.LeftRightT;

public record FuTeacher() implements ComposedZiT, LeftRightT<DanRenPang, LeftRightPartT<Fu_Begin, Cun_Inch>> {

    public static final FuTeacher INSTANCE = new FuTeacher();

    @Override public DanRenPang left() { return BasicComponents.DAN_REN_PANG; }
    @Override public LeftRightPartT<Fu_Begin, Cun_Inch> right() { return new LeftRightPartT<>(SpaceAndDirection.FU_BEGIN, Structures.CUN_INCH); }

    @Override public CompositionLayoutT layout() { return this; }

    @Override public String glyph() { return "\u5085"; }

    @Override public PinyinSyllable pinyin() {
        return new PinyinSyllable(Initial.F, new Final(Head.U, Body.U, Tail.NONE), Tone.FOURTH);
    }

    @Override public int strokes() { return 12; }
    @Override public int radicalNo() { return 9; }
    @Override public String meaning() { return ""; }

    @Override public EtymologicalCategory etymology() {
        return new EtymologicalCategory.PhonoSemantic(BasicComponents.DAN_REN_PANG, new LeftRightPartT<>(SpaceAndDirection.FU_BEGIN, Structures.CUN_INCH));
    }
}
