// AUTO-GENERATED by CatalogIteratorMain - do not edit by hand.
package kranji.common.perclass.promoted.g.an3;

import kranji.classification.EtymologicalCategory;
import kranji.common.perclass.promoted.x.ian2.XianSalty;
import kranji.pinyin.Body;
import kranji.pinyin.Final;
import kranji.pinyin.Head;
import kranji.pinyin.Initial;
import kranji.pinyin.PinyinSyllable;
import kranji.pinyin.Tail;
import kranji.pinyin.Tone;
import kranji.singular.body.BodyParts;
import kranji.zi.ComposedZiT;
import kranji.zi.CompositionLayoutT;
import kranji.zi.TopBottomT;

public record GanFeel() implements ComposedZiT, TopBottomT<XianSalty, BodyParts.Xin> {

    public static final GanFeel INSTANCE = new GanFeel();

    @Override public XianSalty top() { return XianSalty.INSTANCE; }
    @Override public BodyParts.Xin bottom() { return BodyParts.XIN; }

    @Override public CompositionLayoutT layout() { return this; }

    @Override public String glyph() { return "\u611F"; }

    @Override public PinyinSyllable pinyin() {
        return new PinyinSyllable(Initial.G, new Final(Head.OPEN, Body.A, Tail.N), Tone.THIRD);
    }

    @Override public int strokes() { return 0; }
    @Override public int radicalNo() { return 0; }
    @Override public String meaning() { return ""; }

    @Override public EtymologicalCategory etymology() {
        return new EtymologicalCategory.PhonoSemantic(BodyParts.XIN, XianSalty.INSTANCE);
    }
}
