// AUTO-GENERATED by kranji-codegen. Do not edit by hand.
package kranji.singular.concepts.zero;

import kranji.library.BasicSet;
import kranji.library.LibraryMember;
import kranji.zi.SingularZi;

public record Ye_Also() implements LibraryMember<BasicSet>, SingularZi {
    public static final Ye_Also INSTANCE = new Ye_Also();

    @Override public String glyph() { return "\u4E5F"; }
    @Override public String meaning() { return "also"; }
    @Override public String pinyinText() { return "y\u011B"; }
    @Override public int strokes() { return 3; }
    @Override public BasicSet library() { return BasicSet.INSTANCE; }
}
