// AUTO-GENERATED by kranji-codegen. Do not edit by hand.
package kranji.singular.concepts.zero;

import kranji.library.BasicSet;
import kranji.library.LibraryMember;
import kranji.zi.SingularZi;

public record Yue_Say() implements LibraryMember<BasicSet>, SingularZi {
    public static final Yue_Say INSTANCE = new Yue_Say();

    @Override public String glyph() { return "\u66F0"; }
    @Override public String meaning() { return "say, speak"; }
    @Override public String pinyinText() { return "yu\u0113"; }
    @Override public int strokes() { return 4; }
    @Override public BasicSet library() { return BasicSet.INSTANCE; }
}
