// AUTO-GENERATED by kranji-codegen. Do not edit by hand.
package kranji.singular.radicals.zero;

import kranji.library.BasicSet;
import kranji.library.LibraryMember;
import kranji.zi.SingularPart;

public record Wang_Net() implements LibraryMember<BasicSet>, SingularPart {
    public static final Wang_Net INSTANCE = new Wang_Net();

    @Override public String glyph() { return "\u7F52"; }
    @Override public String meaning() { return "net radical top"; }
    @Override public String pinyinText() { return "w\u01CEng"; }
    @Override public int strokes() { return 5; }
    @Override public BasicSet library() { return BasicSet.INSTANCE; }
}
