// AUTO-GENERATED by kranji-codegen. Do not edit by hand.
package kranji.singular.radicals.zero;

import kranji.library.BasicSet;
import kranji.library.LibraryMember;
import kranji.zi.SingularPart;

public record Yan_Marsh() implements LibraryMember<BasicSet>, SingularPart {
    public static final Yan_Marsh INSTANCE = new Yan_Marsh();

    @Override public String glyph() { return "\u3563"; }
    @Override public String meaning() { return "marsh, swamp"; }
    @Override public String pinyinText() { return "y\u01CEn"; }
    @Override public int strokes() { return 5; }
    @Override public BasicSet library() { return BasicSet.INSTANCE; }
}
