// AUTO-GENERATED by CatalogIteratorMain - do not edit by hand.
package kranji.common.perclass.promoted.h.uei1;

import kranji.classification.EtymologicalCategory;
import kranji.common.perclass.promoted.g.uang1.GuangLight;
import kranji.common.perclass.promoted.j.ven1.JunArmy;
import kranji.pinyin.Body;
import kranji.pinyin.Final;
import kranji.pinyin.Head;
import kranji.pinyin.Initial;
import kranji.pinyin.PinyinSyllable;
import kranji.pinyin.Tail;
import kranji.pinyin.Tone;
import kranji.zi.ComposedZiT;
import kranji.zi.CompositionLayoutT;
import kranji.zi.LeftRightT;

public record HuiRadiance() implements ComposedZiT, LeftRightT<GuangLight, JunArmy> {

    public static final HuiRadiance INSTANCE = new HuiRadiance();

    @Override public GuangLight left() { return GuangLight.INSTANCE; }
    @Override public JunArmy right() { return JunArmy.INSTANCE; }

    @Override public CompositionLayoutT layout() { return this; }

    @Override public String glyph() { return "\u8F89"; }

    @Override public PinyinSyllable pinyin() {
        return new PinyinSyllable(Initial.H, new Final(Head.U, Body.E, Tail.VOWEL_I), Tone.FIRST);
    }

    @Override public int strokes() { return 0; }
    @Override public int radicalNo() { return 0; }
    @Override public String meaning() { return ""; }

    @Override public EtymologicalCategory etymology() {
        return new EtymologicalCategory.PhonoSemantic(GuangLight.INSTANCE, JunArmy.INSTANCE);
    }
}
