// AUTO-GENERATED by CatalogIteratorMain - do not edit by hand.
package kranji.common.perclass.promoted.x.ie1;

import kranji.classification.EtymologicalCategory;
import kranji.common.perclass.promoted.h.e2.HeHe;
import kranji.pinyin.Body;
import kranji.pinyin.Final;
import kranji.pinyin.Head;
import kranji.pinyin.Initial;
import kranji.pinyin.PinyinSyllable;
import kranji.pinyin.Tail;
import kranji.pinyin.Tone;
import kranji.singular.radicals.RadicalComponents;
import kranji.zi.ComposedZiT;
import kranji.zi.CompositionLayoutT;
import kranji.zi.LeftRightT;

public record XieRest() implements ComposedZiT, LeftRightT<HeHe, RadicalComponents.Qian_Owe> {

    public static final XieRest INSTANCE = new XieRest();

    @Override public HeHe left() { return HeHe.INSTANCE; }
    @Override public RadicalComponents.Qian_Owe right() { return RadicalComponents.QIAN_OWE; }

    @Override public CompositionLayoutT layout() { return this; }

    @Override public String glyph() { return "\u6B47"; }

    @Override public PinyinSyllable pinyin() {
        return new PinyinSyllable(Initial.X, new Final(Head.I, Body.E_CARON, Tail.NONE), Tone.FIRST);
    }

    @Override public int strokes() { return 0; }
    @Override public int radicalNo() { return 0; }
    @Override public String meaning() { return ""; }

    @Override public EtymologicalCategory etymology() {
        return new EtymologicalCategory.PhonoSemantic(RadicalComponents.QIAN_OWE, HeHe.INSTANCE);
    }
}
