// AUTO-GENERATED by PerclassGenerateMain - do not edit by hand.
package kranji.common.perclass.zero.uo4;

import kranji.classification.EtymologicalCategory;
import kranji.component.basic.BasicComponents;
import kranji.component.basic.WaterFamily.SanDianShui;
import kranji.pinyin.Body;
import kranji.pinyin.Final;
import kranji.pinyin.Head;
import kranji.pinyin.Initial;
import kranji.pinyin.PinyinSyllable;
import kranji.pinyin.Tail;
import kranji.pinyin.Tone;
import kranji.singular.people.PeopleAndRoles;
import kranji.singular.people.PeopleAndRoles.Yao;
import kranji.zi.ComposedZiT;
import kranji.zi.CompositionLayoutT;
import kranji.zi.LeftRightT;

public record WoFertile() implements ComposedZiT, LeftRightT<SanDianShui, Yao> {

    public static final WoFertile INSTANCE = new WoFertile();

    @Override public SanDianShui left() { return BasicComponents.SAN_DIAN_SHUI; }
    @Override public Yao right() { return PeopleAndRoles.YAO; }

    @Override public CompositionLayoutT layout() { return this; }

    @Override public String glyph() { return "\u6C83"; }

    @Override public PinyinSyllable pinyin() {
        return new PinyinSyllable(Initial.ZERO, new Final(Head.U, Body.O, Tail.NONE), Tone.FOURTH);
    }

    @Override public int strokes() { return 7; }
    @Override public int radicalNo() { return 85; }
    @Override public String meaning() { return ""; }

    @Override public EtymologicalCategory etymology() {
        return new EtymologicalCategory.PhonoSemantic(BasicComponents.SAN_DIAN_SHUI, PeopleAndRoles.YAO);
    }
}
