// AUTO-GENERATED by PerclassGenerateMain - do not edit by hand.
package kranji.common.perclass.z.ai1;

import kranji.classification.EtymologicalCategory;
import kranji.component.basic.BasicComponents;
import kranji.component.basic.ShelterFamily.BaoGaiTou;
import kranji.pinyin.Body;
import kranji.pinyin.Final;
import kranji.pinyin.Head;
import kranji.pinyin.Initial;
import kranji.pinyin.PinyinSyllable;
import kranji.pinyin.Tail;
import kranji.pinyin.Tone;
import kranji.singular.nature.NatureElements;
import kranji.singular.nature.NatureElements.Huo;
import kranji.zi.ComposedZiT;
import kranji.zi.CompositionLayoutT;
import kranji.zi.TopBottomT;

public record ZaiDisaster() implements ComposedZiT, TopBottomT<BaoGaiTou, Huo> {

    public static final ZaiDisaster INSTANCE = new ZaiDisaster();

    @Override public BaoGaiTou top() { return BasicComponents.BAO_GAI_TOU; }
    @Override public Huo bottom() { return NatureElements.HUO; }

    @Override public CompositionLayoutT layout() { return this; }

    @Override public String glyph() { return "\u707E"; }

    @Override public PinyinSyllable pinyin() {
        return new PinyinSyllable(Initial.Z, new Final(Head.OPEN, Body.A, Tail.VOWEL_I), Tone.FIRST);
    }

    @Override public int strokes() { return 7; }
    @Override public int radicalNo() { return 86; }
    @Override public String meaning() { return ""; }

    @Override public EtymologicalCategory etymology() {
        return new EtymologicalCategory.CompoundIndicative("宀(roof) + 火(fire) → disaster");
    }
}
