// AUTO-GENERATED by PerclassGenerateMain - do not edit by hand.
package kranji.common.perclass.x.iou4;

import kranji.classification.EtymologicalCategory;
import kranji.pinyin.Body;
import kranji.pinyin.Final;
import kranji.pinyin.Head;
import kranji.pinyin.Initial;
import kranji.pinyin.PinyinSyllable;
import kranji.pinyin.Tail;
import kranji.pinyin.Tone;
import kranji.singular.concepts.AbstractConcepts;
import kranji.singular.concepts.AbstractConcepts.Nai;
import kranji.singular.plants.PlantsAndAgriculture;
import kranji.singular.plants.PlantsAndAgriculture.He;
import kranji.zi.ComposedZiT;
import kranji.zi.CompositionLayoutT;
import kranji.zi.TopBottomT;

public record XiuElegant() implements ComposedZiT, TopBottomT<He, Nai> {

    public static final XiuElegant INSTANCE = new XiuElegant();

    @Override public He top() { return PlantsAndAgriculture.HE; }
    @Override public Nai bottom() { return AbstractConcepts.NAI; }

    @Override public CompositionLayoutT layout() { return this; }

    @Override public String glyph() { return "\u79C0"; }

    @Override public PinyinSyllable pinyin() {
        return new PinyinSyllable(Initial.X, new Final(Head.I, Body.O, Tail.VOWEL_U), Tone.FOURTH);
    }

    @Override public int strokes() { return 7; }
    @Override public int radicalNo() { return 115; }
    @Override public String meaning() { return ""; }

    @Override public EtymologicalCategory etymology() {
        return new EtymologicalCategory.PhonoSemantic(PlantsAndAgriculture.HE, AbstractConcepts.NAI);
    }
}
