// AUTO-GENERATED by kranji-codegen. Do not edit by hand.
package kranji.singular.space.q;

import kranji.library.BasicSet;
import kranji.library.LibraryMember;
import kranji.zi.SingularZi;

public record Qu_Area() implements LibraryMember<BasicSet>, SingularZi {
    public static final Qu_Area INSTANCE = new Qu_Area();

    @Override public String glyph() { return "\u533A"; }
    @Override public String meaning() { return "area, district"; }
    @Override public String pinyinText() { return "q\u016B"; }
    @Override public int strokes() { return 4; }
    @Override public BasicSet library() { return BasicSet.INSTANCE; }
}
