// AUTO-GENERATED by CatalogIteratorMain - do not edit by hand.
package kranji.common.perclass.promoted.m.eng3;

import kranji.classification.EtymologicalCategory;
import kranji.component.basic.AnimalFamily;
import kranji.component.basic.BasicComponents;
import kranji.pinyin.Body;
import kranji.pinyin.Final;
import kranji.pinyin.Head;
import kranji.pinyin.Initial;
import kranji.pinyin.PinyinSyllable;
import kranji.pinyin.Tail;
import kranji.pinyin.Tone;
import kranji.singular.people.PeopleAndRoles;
import kranji.zi.ComposedZiT;
import kranji.zi.CompositionLayoutT;
import kranji.zi.LeftRightT;

public record MengFierce() implements ComposedZiT, LeftRightT<AnimalFamily.FanQuanPang, PeopleAndRoles.Meng> {

    public static final MengFierce INSTANCE = new MengFierce();

    @Override public AnimalFamily.FanQuanPang left() { return BasicComponents.FAN_QUAN_PANG; }
    @Override public PeopleAndRoles.Meng right() { return PeopleAndRoles.MENG; }

    @Override public CompositionLayoutT layout() { return this; }

    @Override public String glyph() { return "\u731B"; }

    @Override public PinyinSyllable pinyin() {
        return new PinyinSyllable(Initial.M, new Final(Head.OPEN, Body.E, Tail.NG), Tone.THIRD);
    }

    @Override public int strokes() { return 0; }
    @Override public int radicalNo() { return 0; }
    @Override public String meaning() { return ""; }

    @Override public EtymologicalCategory etymology() {
        return new EtymologicalCategory.PhonoSemantic(BasicComponents.FAN_QUAN_PANG, PeopleAndRoles.MENG);
    }
}
