// AUTO-GENERATED by PerclassGenerateMain - do not edit by hand.
package kranji.common.perclass.h.e2;

import kranji.classification.EtymologicalCategory;
import kranji.pinyin.Body;
import kranji.pinyin.Final;
import kranji.pinyin.Head;
import kranji.pinyin.Initial;
import kranji.pinyin.PinyinSyllable;
import kranji.pinyin.Tail;
import kranji.pinyin.Tone;
import kranji.singular.concepts.AbstractConcepts;
import kranji.singular.concepts.AbstractConcepts.He_Unite;
import kranji.singular.tools.ToolsAndVessels;
import kranji.singular.tools.ToolsAndVessels.Min;
import kranji.zi.ComposedZiT;
import kranji.zi.CompositionLayoutT;
import kranji.zi.TopBottomT;

public record HeBox() implements ComposedZiT, TopBottomT<He_Unite, Min> {

    public static final HeBox INSTANCE = new HeBox();

    @Override public He_Unite top() { return AbstractConcepts.HE_UNITE; }
    @Override public Min bottom() { return ToolsAndVessels.MIN; }

    @Override public CompositionLayoutT layout() { return this; }

    @Override public String glyph() { return "\u76D2"; }

    @Override public PinyinSyllable pinyin() {
        return new PinyinSyllable(Initial.H, new Final(Head.OPEN, Body.E, Tail.NONE), Tone.SECOND);
    }

    @Override public int strokes() { return 11; }
    @Override public int radicalNo() { return 108; }
    @Override public String meaning() { return ""; }

    @Override public EtymologicalCategory etymology() {
        return new EtymologicalCategory.PhonoSemantic(ToolsAndVessels.MIN, AbstractConcepts.HE_UNITE);
    }
}
