// AUTO-GENERATED by CatalogIteratorMain - do not edit by hand.
package kranji.common.perclass.promoted.l.i2;

import kranji.classification.EtymologicalCategory;
import kranji.common.perclass.promoted.sh.u3.ShuMillet;
import kranji.common.perclass.promoted.l.i2.LiMultitude_Inner1;
import kranji.pinyin.Body;
import kranji.pinyin.Final;
import kranji.pinyin.Head;
import kranji.pinyin.Initial;
import kranji.pinyin.PinyinSyllable;
import kranji.pinyin.Tail;
import kranji.pinyin.Tone;
import kranji.zi.ComposedZiT;
import kranji.zi.CompositionLayoutT;
import kranji.zi.TopBottomT;

public record LiMultitude() implements ComposedZiT, TopBottomT<ShuMillet, LiMultitude_Inner1> {

    public static final LiMultitude INSTANCE = new LiMultitude();

    @Override public ShuMillet top() { return ShuMillet.INSTANCE; }
    @Override public LiMultitude_Inner1 bottom() { return LiMultitude_Inner1.INSTANCE; }

    @Override public CompositionLayoutT layout() { return this; }

    @Override public String glyph() { return "\u9ECE"; }

    @Override public PinyinSyllable pinyin() {
        return new PinyinSyllable(Initial.L, new Final(Head.OPEN, Body.I, Tail.NONE), Tone.SECOND);
    }

    @Override public int strokes() { return 0; }
    @Override public int radicalNo() { return 0; }
    @Override public String meaning() { return ""; }

    @Override public EtymologicalCategory etymology() {
        return new EtymologicalCategory.CompoundIndicative("");
    }
}
