// AUTO-GENERATED by CatalogIteratorMain - do not edit by hand.
package kranji.common.perclass.promoted.l.i2;

import kranji.classification.EtymologicalCategory;
import kranji.common.perclass.l.i4.LiProfit;
import kranji.pinyin.Body;
import kranji.pinyin.Final;
import kranji.pinyin.Head;
import kranji.pinyin.Initial;
import kranji.pinyin.PinyinSyllable;
import kranji.pinyin.Tail;
import kranji.pinyin.Tone;
import kranji.singular.animals.Animals;
import kranji.zi.ComposedZiT;
import kranji.zi.CompositionLayoutT;
import kranji.zi.TopBottomT;

public record LiPlow() implements ComposedZiT, TopBottomT<LiProfit, Animals.Niu> {

    public static final LiPlow INSTANCE = new LiPlow();

    @Override public LiProfit top() { return LiProfit.INSTANCE; }
    @Override public Animals.Niu bottom() { return Animals.NIU; }

    @Override public CompositionLayoutT layout() { return this; }

    @Override public String glyph() { return "\u7281"; }

    @Override public PinyinSyllable pinyin() {
        return new PinyinSyllable(Initial.L, new Final(Head.OPEN, Body.I, Tail.NONE), Tone.SECOND);
    }

    @Override public int strokes() { return 0; }
    @Override public int radicalNo() { return 0; }
    @Override public String meaning() { return ""; }

    @Override public EtymologicalCategory etymology() {
        return new EtymologicalCategory.PhonoSemantic(Animals.NIU, LiProfit.INSTANCE);
    }
}
