// AUTO-GENERATED by CatalogIteratorMain - do not edit by hand.
package kranji.common.perclass.promoted.t.uo1;

import kranji.pinyin.Body;
import kranji.pinyin.Final;
import kranji.pinyin.Head;
import kranji.pinyin.Initial;
import kranji.pinyin.PinyinSyllable;
import kranji.pinyin.Tail;
import kranji.pinyin.Tone;
import kranji.zi.SingularZi;

public record TuoTuo() implements SingularZi {

    public static final TuoTuo INSTANCE = new TuoTuo();

    @Override public String glyph() { return "\u4E47"; }

    @Override public PinyinSyllable pinyin() {
        return new PinyinSyllable(Initial.T, new Final(Head.U, Body.O, Tail.NONE), Tone.FIRST);
    }

    @Override public boolean unsure() { return true; }
}
