// AUTO-GENERATED by kranji-codegen. Do not edit by hand.
package kranji.singular.concepts.ch;

import kranji.library.BasicSet;
import kranji.library.LibraryMember;
import kranji.zi.SingularZi;

public record Chou() implements LibraryMember<BasicSet>, SingularZi {
    public static final Chou INSTANCE = new Chou();

    @Override public String glyph() { return "\u4E11"; }
    @Override public String meaning() { return "ugly, clown"; }
    @Override public String pinyinText() { return "ch\u01D2u"; }
    @Override public int strokes() { return 4; }
    @Override public BasicSet library() { return BasicSet.INSTANCE; }
}
