// AUTO-GENERATED by CatalogIteratorMain - do not edit by hand.
package kranji.common.perclass.promoted.zero.uen1;

import kranji.classification.EtymologicalCategory;
import kranji.common.perclass.promoted.zero.uen1.WenWenAuto;
import kranji.component.basic.BasicComponents;
import kranji.component.basic.WaterFamily;
import kranji.pinyin.Body;
import kranji.pinyin.Final;
import kranji.pinyin.Head;
import kranji.pinyin.Initial;
import kranji.pinyin.PinyinSyllable;
import kranji.pinyin.Tail;
import kranji.pinyin.Tone;
import kranji.zi.ComposedZiT;
import kranji.zi.CompositionLayoutT;
import kranji.zi.LeftRightT;

public record WenWarm() implements ComposedZiT, LeftRightT<WaterFamily.SanDianShui, WenWenAuto> {

    public static final WenWarm INSTANCE = new WenWarm();

    @Override public WaterFamily.SanDianShui left() { return BasicComponents.SAN_DIAN_SHUI; }
    @Override public WenWenAuto right() { return WenWenAuto.INSTANCE; }

    @Override public CompositionLayoutT layout() { return this; }

    @Override public String glyph() { return "\u6E29"; }

    @Override public PinyinSyllable pinyin() {
        return new PinyinSyllable(Initial.ZERO, new Final(Head.U, Body.E, Tail.N), Tone.FIRST);
    }

    @Override public int strokes() { return 0; }
    @Override public int radicalNo() { return 0; }
    @Override public String meaning() { return ""; }

    @Override public EtymologicalCategory etymology() {
        return new EtymologicalCategory.PhonoSemantic(BasicComponents.SAN_DIAN_SHUI, WenWenAuto.INSTANCE);
    }
}
