// AUTO-GENERATED by CatalogIteratorMain - do not edit by hand.
package kranji.common.perclass.promoted.z.ong1;

import kranji.classification.EtymologicalCategory;
import kranji.common.perclass.z.ong1.ZongClan;
import kranji.component.basic.BasicComponents;
import kranji.component.basic.WoodFamily;
import kranji.pinyin.Body;
import kranji.pinyin.Final;
import kranji.pinyin.Head;
import kranji.pinyin.Initial;
import kranji.pinyin.PinyinSyllable;
import kranji.pinyin.Tail;
import kranji.pinyin.Tone;
import kranji.zi.ComposedZiT;
import kranji.zi.CompositionLayoutT;
import kranji.zi.LeftRightT;

public record ZongPalm() implements ComposedZiT, LeftRightT<WoodFamily.Mu, ZongClan> {

    public static final ZongPalm INSTANCE = new ZongPalm();

    @Override public WoodFamily.Mu left() { return BasicComponents.MU; }
    @Override public ZongClan right() { return ZongClan.INSTANCE; }

    @Override public CompositionLayoutT layout() { return this; }

    @Override public String glyph() { return "\u68D5"; }

    @Override public PinyinSyllable pinyin() {
        return new PinyinSyllable(Initial.Z, new Final(Head.OPEN, Body.O, Tail.NG), Tone.FIRST);
    }

    @Override public int strokes() { return 0; }
    @Override public int radicalNo() { return 0; }
    @Override public String meaning() { return ""; }

    @Override public EtymologicalCategory etymology() {
        return new EtymologicalCategory.PhonoSemantic(BasicComponents.MU, ZongClan.INSTANCE);
    }
}
