// AUTO-GENERATED by PerclassGenerateMain - do not edit by hand.
package kranji.common.perclass.m.iao4;

import kranji.classification.EtymologicalCategory;
import kranji.pinyin.Body;
import kranji.pinyin.Final;
import kranji.pinyin.Head;
import kranji.pinyin.Initial;
import kranji.pinyin.PinyinSyllable;
import kranji.pinyin.Tail;
import kranji.pinyin.Tone;
import kranji.singular.people.PeopleAndRoles;
import kranji.singular.people.PeopleAndRoles.Nv;
import kranji.singular.people.PeopleAndRoles.Shao;
import kranji.zi.ComposedZiT;
import kranji.zi.CompositionLayoutT;
import kranji.zi.LeftRightT;

public record Miao() implements ComposedZiT, LeftRightT<Nv, Shao> {

    public static final Miao INSTANCE = new Miao();

    @Override public Nv left() { return PeopleAndRoles.NV; }
    @Override public Shao right() { return PeopleAndRoles.SHAO; }

    @Override public CompositionLayoutT layout() { return this; }

    @Override public String glyph() { return "\u5999"; }

    @Override public PinyinSyllable pinyin() {
        return new PinyinSyllable(Initial.M, new Final(Head.I, Body.A, Tail.VOWEL_U), Tone.FOURTH);
    }

    @Override public int strokes() { return 7; }
    @Override public int radicalNo() { return 38; }
    @Override public String meaning() { return ""; }

    @Override public EtymologicalCategory etymology() {
        return new EtymologicalCategory.PhonoSemantic(PeopleAndRoles.NV, PeopleAndRoles.SHAO);
    }
}
