// AUTO-GENERATED by kranji-codegen. Do not edit by hand.
package kranji.singular.radicals.x;

import kranji.library.BasicSet;
import kranji.library.LibraryMember;
import kranji.zi.SingularPart;

public record Xiao_Top() implements LibraryMember<BasicSet>, SingularPart {
    public static final Xiao_Top INSTANCE = new Xiao_Top();

    @Override public String glyph() { return "\u2E8C"; }
    @Override public String meaning() { return "small radical top"; }
    @Override public String pinyinText() { return "xi\u01CEo"; }
    @Override public int strokes() { return 3; }
    @Override public BasicSet library() { return BasicSet.INSTANCE; }
}
