// AUTO-GENERATED by CatalogIteratorMain - do not edit by hand.
package kranji.common.perclass.promoted.zh.e4;

import kranji.classification.EtymologicalCategory;
import kranji.common.perclass.zh.e2.ZheFold;
import kranji.component.basic.BasicComponents;
import kranji.component.basic.WaterFamily;
import kranji.pinyin.Body;
import kranji.pinyin.Final;
import kranji.pinyin.Head;
import kranji.pinyin.Initial;
import kranji.pinyin.PinyinSyllable;
import kranji.pinyin.Tail;
import kranji.pinyin.Tone;
import kranji.zi.ComposedZiT;
import kranji.zi.CompositionLayoutT;
import kranji.zi.LeftRightT;

public record ZheZhejiang() implements ComposedZiT, LeftRightT<WaterFamily.SanDianShui, ZheFold> {

    public static final ZheZhejiang INSTANCE = new ZheZhejiang();

    @Override public WaterFamily.SanDianShui left() { return BasicComponents.SAN_DIAN_SHUI; }
    @Override public ZheFold right() { return ZheFold.INSTANCE; }

    @Override public CompositionLayoutT layout() { return this; }

    @Override public String glyph() { return "\u6D59"; }

    @Override public PinyinSyllable pinyin() {
        return new PinyinSyllable(Initial.ZH, new Final(Head.OPEN, Body.E, Tail.NONE), Tone.FOURTH);
    }

    @Override public int strokes() { return 0; }
    @Override public int radicalNo() { return 0; }
    @Override public String meaning() { return ""; }

    @Override public EtymologicalCategory etymology() {
        return new EtymologicalCategory.PhonoSemantic(BasicComponents.SAN_DIAN_SHUI, ZheFold.INSTANCE);
    }
}
