// AUTO-GENERATED by kranji-codegen. Do not edit by hand.
package kranji.singular.actions.k;

import kranji.library.BasicSet;
import kranji.library.LibraryMember;
import kranji.zi.SingularZi;

public record Ken() implements LibraryMember<BasicSet>, SingularZi {
    public static final Ken INSTANCE = new Ken();

    @Override public String glyph() { return "\u80AF"; }
    @Override public String meaning() { return "willing, agree"; }
    @Override public String pinyinText() { return "k\u011Bn"; }
    @Override public int strokes() { return 8; }
    @Override public BasicSet library() { return BasicSet.INSTANCE; }
}
