// AUTO-GENERATED by CatalogIteratorMain - do not edit by hand.
package kranji.common.perclass.promoted.k.ua3;

import kranji.classification.EtymologicalCategory;
import kranji.pinyin.Body;
import kranji.pinyin.Final;
import kranji.pinyin.Head;
import kranji.pinyin.Initial;
import kranji.pinyin.PinyinSyllable;
import kranji.pinyin.Tail;
import kranji.pinyin.Tone;
import kranji.singular.nature.NatureElements;
import kranji.singular.unsure.UnsureSingulars;
import kranji.zi.ComposedZiT;
import kranji.zi.CompositionLayoutT;
import kranji.zi.LeftRightT;

public record KuaCollapse() implements ComposedZiT, LeftRightT<NatureElements.Tu, UnsureSingulars.Kua_Boast> {

    public static final KuaCollapse INSTANCE = new KuaCollapse();

    @Override public NatureElements.Tu left() { return NatureElements.TU; }
    @Override public UnsureSingulars.Kua_Boast right() { return UnsureSingulars.KUA_BOAST; }

    @Override public CompositionLayoutT layout() { return this; }

    @Override public String glyph() { return "\u57AE"; }

    @Override public PinyinSyllable pinyin() {
        return new PinyinSyllable(Initial.K, new Final(Head.U, Body.A, Tail.NONE), Tone.THIRD);
    }

    @Override public int strokes() { return 0; }
    @Override public int radicalNo() { return 0; }
    @Override public String meaning() { return ""; }

    @Override public EtymologicalCategory etymology() {
        return new EtymologicalCategory.PhonoSemantic(NatureElements.TU, UnsureSingulars.KUA_BOAST);
    }
}
