// AUTO-GENERATED by kranji-codegen. Do not edit by hand.
package kranji.singular.people.s;

import kranji.library.BasicSet;
import kranji.library.LibraryMember;
import kranji.zi.SingularZi;

public record Su() implements LibraryMember<BasicSet>, SingularZi {
    public static final Su INSTANCE = new Su();

    @Override public String glyph() { return "\u8083"; }
    @Override public String meaning() { return "solemn/respectful"; }
    @Override public String pinyinText() { return "s\u00F9"; }
    @Override public int strokes() { return 8; }
    @Override public BasicSet library() { return BasicSet.INSTANCE; }
}
