// AUTO-GENERATED by CatalogIteratorMain - do not edit by hand.
package kranji.common.perclass.promoted.m.ao1;

import kranji.classification.EtymologicalCategory;
import kranji.common.perclass.m.iao2.MiaoSeedling;
import kranji.component.basic.AnimalFamily;
import kranji.component.basic.BasicComponents;
import kranji.pinyin.Body;
import kranji.pinyin.Final;
import kranji.pinyin.Head;
import kranji.pinyin.Initial;
import kranji.pinyin.PinyinSyllable;
import kranji.pinyin.Tail;
import kranji.pinyin.Tone;
import kranji.zi.ComposedZiT;
import kranji.zi.CompositionLayoutT;
import kranji.zi.LeftRightT;

public record MaoCat() implements ComposedZiT, LeftRightT<AnimalFamily.FanQuanPang, MiaoSeedling> {

    public static final MaoCat INSTANCE = new MaoCat();

    @Override public AnimalFamily.FanQuanPang left() { return BasicComponents.FAN_QUAN_PANG; }
    @Override public MiaoSeedling right() { return MiaoSeedling.INSTANCE; }

    @Override public CompositionLayoutT layout() { return this; }

    @Override public String glyph() { return "\u732B"; }

    @Override public PinyinSyllable pinyin() {
        return new PinyinSyllable(Initial.M, new Final(Head.OPEN, Body.A, Tail.VOWEL_U), Tone.FIRST);
    }

    @Override public int strokes() { return 0; }
    @Override public int radicalNo() { return 0; }
    @Override public String meaning() { return ""; }

    @Override public EtymologicalCategory etymology() {
        return new EtymologicalCategory.PhonoSemantic(BasicComponents.FAN_QUAN_PANG, MiaoSeedling.INSTANCE);
    }
}
