// AUTO-GENERATED by CatalogIteratorMain - do not edit by hand.
package kranji.common.perclass.promoted.ch.i4;

import kranji.classification.EtymologicalCategory;
import kranji.pinyin.Body;
import kranji.pinyin.Final;
import kranji.pinyin.Head;
import kranji.pinyin.Initial;
import kranji.pinyin.PinyinSyllable;
import kranji.pinyin.Tail;
import kranji.pinyin.Tone;
import kranji.singular.actions.ActionsAndStates;
import kranji.singular.radicals.RadicalComponents;
import kranji.zi.ComposedZiT;
import kranji.zi.CompositionLayoutT;
import kranji.zi.LeftRightT;

public record ChiWing() implements ComposedZiT, LeftRightT<ActionsAndStates.Zhi_Branch, RadicalComponents.Yu_Feather> {

    public static final ChiWing INSTANCE = new ChiWing();

    @Override public ActionsAndStates.Zhi_Branch left() { return ActionsAndStates.ZHI_BRANCH; }
    @Override public RadicalComponents.Yu_Feather right() { return RadicalComponents.YU_FEATHER; }

    @Override public CompositionLayoutT layout() { return this; }

    @Override public String glyph() { return "\u7FC5"; }

    @Override public PinyinSyllable pinyin() {
        return new PinyinSyllable(Initial.CH, new Final(Head.OPEN, Body.I, Tail.NONE), Tone.FOURTH);
    }

    @Override public int strokes() { return 0; }
    @Override public int radicalNo() { return 0; }
    @Override public String meaning() { return ""; }

    @Override public EtymologicalCategory etymology() {
        return new EtymologicalCategory.PhonoSemantic(RadicalComponents.YU_FEATHER, ActionsAndStates.ZHI_BRANCH);
    }
}
