// AUTO-GENERATED by CatalogIteratorMain - do not edit by hand.
package kranji.common.perclass.promoted.t.a1;

import kranji.classification.EtymologicalCategory;
import kranji.pinyin.Body;
import kranji.pinyin.Final;
import kranji.pinyin.Head;
import kranji.pinyin.Initial;
import kranji.pinyin.PinyinSyllable;
import kranji.pinyin.Tail;
import kranji.pinyin.Tone;
import kranji.singular.concepts.AbstractConcepts;
import kranji.singular.people.PeopleAndRoles;
import kranji.zi.ComposedZiT;
import kranji.zi.CompositionLayoutT;
import kranji.zi.LeftRightT;

public record TaShe() implements ComposedZiT, LeftRightT<PeopleAndRoles.Nv, AbstractConcepts.Ye_Also> {

    public static final TaShe INSTANCE = new TaShe();

    @Override public PeopleAndRoles.Nv left() { return PeopleAndRoles.NV; }
    @Override public AbstractConcepts.Ye_Also right() { return AbstractConcepts.YE_ALSO; }

    @Override public CompositionLayoutT layout() { return this; }

    @Override public String glyph() { return "\u5979"; }

    @Override public PinyinSyllable pinyin() {
        return new PinyinSyllable(Initial.T, new Final(Head.OPEN, Body.A, Tail.NONE), Tone.FIRST);
    }

    @Override public int strokes() { return 0; }
    @Override public int radicalNo() { return 0; }
    @Override public String meaning() { return ""; }

    @Override public EtymologicalCategory etymology() {
        return new EtymologicalCategory.PhonoSemantic(PeopleAndRoles.NV, AbstractConcepts.YE_ALSO);
    }
}
