// AUTO-GENERATED by CatalogIteratorMain - do not edit by hand.
package kranji.common.perclass.promoted.m.iao3;

import kranji.classification.EtymologicalCategory;
import kranji.pinyin.Body;
import kranji.pinyin.Final;
import kranji.pinyin.Head;
import kranji.pinyin.Initial;
import kranji.pinyin.PinyinSyllable;
import kranji.pinyin.Tail;
import kranji.pinyin.Tone;
import kranji.singular.people.PeopleAndRoles;
import kranji.singular.plants.PlantsAndAgriculture;
import kranji.zi.ComposedZiT;
import kranji.zi.CompositionLayoutT;
import kranji.zi.LeftRightT;

public record MiaoSecond() implements ComposedZiT, LeftRightT<PlantsAndAgriculture.He, PeopleAndRoles.Shao> {

    public static final MiaoSecond INSTANCE = new MiaoSecond();

    @Override public PlantsAndAgriculture.He left() { return PlantsAndAgriculture.HE; }
    @Override public PeopleAndRoles.Shao right() { return PeopleAndRoles.SHAO; }

    @Override public CompositionLayoutT layout() { return this; }

    @Override public String glyph() { return "\u79D2"; }

    @Override public PinyinSyllable pinyin() {
        return new PinyinSyllable(Initial.M, new Final(Head.I, Body.A, Tail.VOWEL_U), Tone.THIRD);
    }

    @Override public int strokes() { return 0; }
    @Override public int radicalNo() { return 0; }
    @Override public String meaning() { return ""; }

    @Override public EtymologicalCategory etymology() {
        return new EtymologicalCategory.PhonoSemantic(PlantsAndAgriculture.HE, PeopleAndRoles.SHAO);
    }
}
