// AUTO-GENERATED by CatalogIteratorMain - do not edit by hand.
package kranji.common.perclass.promoted.l.an2;

import kranji.classification.EtymologicalCategory;
import kranji.common.perclass.promoted.j.ian1.JianInspect;
import kranji.component.basic.BasicComponents;
import kranji.component.basic.PlantFamily;
import kranji.pinyin.Body;
import kranji.pinyin.Final;
import kranji.pinyin.Head;
import kranji.pinyin.Initial;
import kranji.pinyin.PinyinSyllable;
import kranji.pinyin.Tail;
import kranji.pinyin.Tone;
import kranji.zi.ComposedZiT;
import kranji.zi.CompositionLayoutT;
import kranji.zi.TopBottomT;

public record LanBlue() implements ComposedZiT, TopBottomT<PlantFamily.CaoZiTou, JianInspect> {

    public static final LanBlue INSTANCE = new LanBlue();

    @Override public PlantFamily.CaoZiTou top() { return BasicComponents.CAO_ZI_TOU; }
    @Override public JianInspect bottom() { return JianInspect.INSTANCE; }

    @Override public CompositionLayoutT layout() { return this; }

    @Override public String glyph() { return "\u84DD"; }

    @Override public PinyinSyllable pinyin() {
        return new PinyinSyllable(Initial.L, new Final(Head.OPEN, Body.A, Tail.N), Tone.SECOND);
    }

    @Override public int strokes() { return 0; }
    @Override public int radicalNo() { return 0; }
    @Override public String meaning() { return ""; }

    @Override public EtymologicalCategory etymology() {
        return new EtymologicalCategory.PhonoSemantic(BasicComponents.CAO_ZI_TOU, JianInspect.INSTANCE);
    }
}
