// AUTO-GENERATED by CatalogIteratorMain - do not edit by hand.
package kranji.common.perclass.promoted.zero.iao3;

import kranji.pinyin.Body;
import kranji.pinyin.Final;
import kranji.pinyin.Head;
import kranji.pinyin.Initial;
import kranji.pinyin.PinyinSyllable;
import kranji.pinyin.Tail;
import kranji.pinyin.Tone;
import kranji.zi.SingularZi;

public record YaoScoop() implements SingularZi {

    public static final YaoScoop INSTANCE = new YaoScoop();

    @Override public String glyph() { return "\u8200"; }

    @Override public PinyinSyllable pinyin() {
        return new PinyinSyllable(Initial.ZERO, new Final(Head.I, Body.A, Tail.VOWEL_U), Tone.THIRD);
    }

    @Override public boolean unsure() { return true; }
}
