// AUTO-GENERATED by PerclassGenerateMain - do not edit by hand.
package kranji.common.perclass.c.uo4;

import kranji.classification.EtymologicalCategory;
import kranji.component.basic.BasicComponents;
import kranji.component.basic.MetalFamily.JinZiPang;
import kranji.pinyin.Body;
import kranji.pinyin.Final;
import kranji.pinyin.Head;
import kranji.pinyin.Initial;
import kranji.pinyin.PinyinSyllable;
import kranji.pinyin.Tail;
import kranji.pinyin.Tone;
import kranji.singular.unsure.UnsureSingulars;
import kranji.singular.unsure.UnsureSingulars.Xi_Former;
import kranji.zi.ComposedZiT;
import kranji.zi.CompositionLayoutT;
import kranji.zi.LeftRightT;

public record CuoWrong() implements ComposedZiT, LeftRightT<JinZiPang, Xi_Former> {

    public static final CuoWrong INSTANCE = new CuoWrong();

    @Override public JinZiPang left() { return BasicComponents.JIN_ZI_PANG; }
    @Override public Xi_Former right() { return UnsureSingulars.XI_FORMER; }

    @Override public CompositionLayoutT layout() { return this; }

    @Override public String glyph() { return "\u9519"; }

    @Override public PinyinSyllable pinyin() {
        return new PinyinSyllable(Initial.C, new Final(Head.U, Body.O, Tail.NONE), Tone.FOURTH);
    }

    @Override public int strokes() { return 13; }
    @Override public int radicalNo() { return 167; }
    @Override public String meaning() { return ""; }

    @Override public EtymologicalCategory etymology() {
        return new EtymologicalCategory.PhonoSemantic(BasicComponents.JIN_ZI_PANG, UnsureSingulars.XI_FORMER);
    }
}
