// AUTO-GENERATED by kranji-codegen. Do not edit by hand.
package kranji.singular.actions.ch;

import kranji.library.BasicSet;
import kranji.library.LibraryMember;
import kranji.zi.SingularZi;

public record Chang_Smooth() implements LibraryMember<BasicSet>, SingularZi {
    public static final Chang_Smooth INSTANCE = new Chang_Smooth();

    @Override public String glyph() { return "\u7545"; }
    @Override public String meaning() { return "smooth, fluent"; }
    @Override public String pinyinText() { return "ch\u00E0ng"; }
    @Override public int strokes() { return 8; }
    @Override public BasicSet library() { return BasicSet.INSTANCE; }
}
