// AUTO-GENERATED by kranji-codegen. Do not edit by hand.
package kranji.singular.actions.ch;

import kranji.library.BasicSet;
import kranji.library.LibraryMember;
import kranji.zi.SingularZi;

public record Chan() implements LibraryMember<BasicSet>, SingularZi {
    public static final Chan INSTANCE = new Chan();

    @Override public String glyph() { return "\u4EA7"; }
    @Override public String meaning() { return "produce/give birth"; }
    @Override public String pinyinText() { return "ch\u01CEn"; }
    @Override public int strokes() { return 6; }
    @Override public BasicSet library() { return BasicSet.INSTANCE; }
}
