// AUTO-GENERATED by kranji-codegen. Do not edit by hand.
package kranji.singular.people.j;

import kranji.library.BasicSet;
import kranji.library.LibraryMember;
import kranji.zi.SingularZi;

public record Jie_Alone() implements LibraryMember<BasicSet>, SingularZi {
    public static final Jie_Alone INSTANCE = new Jie_Alone();

    @Override public String glyph() { return "\u5B51"; }
    @Override public String meaning() { return "alone/solitary"; }
    @Override public String pinyinText() { return "ji\u00E9"; }
    @Override public int strokes() { return 3; }
    @Override public BasicSet library() { return BasicSet.INSTANCE; }
}
