// AUTO-GENERATED by kranji-codegen. Do not edit by hand.
package kranji.singular.people.j;

import kranji.library.BasicSet;
import kranji.library.LibraryMember;
import kranji.zi.SingularZi;

public record Jun() implements LibraryMember<BasicSet>, SingularZi {
    public static final Jun INSTANCE = new Jun();

    @Override public String glyph() { return "\u541B"; }
    @Override public String meaning() { return "lord"; }
    @Override public String pinyinText() { return "j\u016Bn"; }
    @Override public int strokes() { return 7; }
    @Override public BasicSet library() { return BasicSet.INSTANCE; }
}
