// AUTO-GENERATED by CatalogIteratorMain - do not edit by hand.
package kranji.common.perclass.promoted.s.ang1;

import kranji.pinyin.Body;
import kranji.pinyin.Final;
import kranji.pinyin.Head;
import kranji.pinyin.Initial;
import kranji.pinyin.PinyinSyllable;
import kranji.pinyin.Tail;
import kranji.pinyin.Tone;
import kranji.zi.SingularZi;

public record SangSangAuto() implements SingularZi {

    public static final SangSangAuto INSTANCE = new SangSangAuto();

    @Override public String glyph() { return "\u6851"; }

    @Override public PinyinSyllable pinyin() {
        return new PinyinSyllable(Initial.S, new Final(Head.OPEN, Body.A, Tail.NG), Tone.FIRST);
    }

    @Override public boolean unsure() { return true; }
}
