// AUTO-GENERATED by PerclassGenerateMain - do not edit by hand.
package kranji.common.perclass.h.ong2;

import kranji.classification.EtymologicalCategory;
import kranji.component.basic.BasicComponents;
import kranji.component.basic.ShelterFamily.BaoGaiTou;
import kranji.pinyin.Body;
import kranji.pinyin.Final;
import kranji.pinyin.Head;
import kranji.pinyin.Initial;
import kranji.pinyin.PinyinSyllable;
import kranji.pinyin.Tail;
import kranji.pinyin.Tone;
import kranji.singular.unsure.UnsureSingulars;
import kranji.singular.unsure.UnsureSingulars.Gong_Forearm;
import kranji.zi.ComposedZiT;
import kranji.zi.CompositionLayoutT;
import kranji.zi.TopBottomT;

public record HongGrand() implements ComposedZiT, TopBottomT<BaoGaiTou, Gong_Forearm> {

    public static final HongGrand INSTANCE = new HongGrand();

    @Override public BaoGaiTou top() { return BasicComponents.BAO_GAI_TOU; }
    @Override public Gong_Forearm bottom() { return UnsureSingulars.GONG_FOREARM; }

    @Override public CompositionLayoutT layout() { return this; }

    @Override public String glyph() { return "\u5B8F"; }

    @Override public PinyinSyllable pinyin() {
        return new PinyinSyllable(Initial.H, new Final(Head.OPEN, Body.O, Tail.NG), Tone.SECOND);
    }

    @Override public int strokes() { return 7; }
    @Override public int radicalNo() { return 40; }
    @Override public String meaning() { return ""; }

    @Override public EtymologicalCategory etymology() {
        return new EtymologicalCategory.PhonoSemantic(BasicComponents.BAO_GAI_TOU, UnsureSingulars.GONG_FOREARM);
    }
}
