// AUTO-GENERATED by kranji-codegen. Do not edit by hand.
package kranji.singular.people.g;

import kranji.library.BasicSet;
import kranji.library.LibraryMember;
import kranji.zi.SingularZi;

public record Gai() implements LibraryMember<BasicSet>, SingularZi {
    public static final Gai INSTANCE = new Gai();

    @Override public String glyph() { return "\u4E10"; }
    @Override public String meaning() { return "beggar"; }
    @Override public String pinyinText() { return "g\u00E0i"; }
    @Override public int strokes() { return 4; }
    @Override public BasicSet library() { return BasicSet.INSTANCE; }
}
