// AUTO-GENERATED by PerclassGenerateMain - do not edit by hand.
package kranji.common.perclass.m.o3;

import kranji.classification.EtymologicalCategory;
import kranji.component.basic.BasicComponents;
import kranji.component.basic.HandFamily.TiShouPang;
import kranji.pinyin.Body;
import kranji.pinyin.Final;
import kranji.pinyin.Head;
import kranji.pinyin.Initial;
import kranji.pinyin.PinyinSyllable;
import kranji.pinyin.Tail;
import kranji.pinyin.Tone;
import kranji.singular.plants.PlantsAndAgriculture;
import kranji.singular.plants.PlantsAndAgriculture.Mo;
import kranji.zi.ComposedZiT;
import kranji.zi.CompositionLayoutT;
import kranji.zi.LeftRightT;

public record MoWipe() implements ComposedZiT, LeftRightT<TiShouPang, Mo> {

    public static final MoWipe INSTANCE = new MoWipe();

    @Override public TiShouPang left() { return BasicComponents.TI_SHOU_PANG; }
    @Override public Mo right() { return PlantsAndAgriculture.MO; }

    @Override public CompositionLayoutT layout() { return this; }

    @Override public String glyph() { return "\u62B9"; }

    @Override public PinyinSyllable pinyin() {
        return new PinyinSyllable(Initial.M, new Final(Head.OPEN, Body.O, Tail.NONE), Tone.THIRD);
    }

    @Override public int strokes() { return 8; }
    @Override public int radicalNo() { return 64; }
    @Override public String meaning() { return ""; }

    @Override public EtymologicalCategory etymology() {
        return new EtymologicalCategory.PhonoSemantic(BasicComponents.TI_SHOU_PANG, PlantsAndAgriculture.MO);
    }
}
