// AUTO-GENERATED by kranji-codegen. Do not edit by hand.
package kranji.singular.actions.j;

import kranji.library.BasicSet;
import kranji.library.LibraryMember;
import kranji.zi.SingularZi;

public record Ji_Reach() implements LibraryMember<BasicSet>, SingularZi {
    public static final Ji_Reach INSTANCE = new Ji_Reach();

    @Override public String glyph() { return "\u53CA"; }
    @Override public String meaning() { return "reach/and"; }
    @Override public String pinyinText() { return "j\u00ED"; }
    @Override public int strokes() { return 3; }
    @Override public BasicSet library() { return BasicSet.INSTANCE; }
}
