// AUTO-GENERATED by kranji-codegen. Do not edit by hand.
package kranji.singular.actions.j;

import kranji.library.BasicSet;
import kranji.library.LibraryMember;
import kranji.zi.SingularZi;

public record Jian_Combine() implements LibraryMember<BasicSet>, SingularZi {
    public static final Jian_Combine INSTANCE = new Jian_Combine();

    @Override public String glyph() { return "\u517C"; }
    @Override public String meaning() { return "combine/simultaneously"; }
    @Override public String pinyinText() { return "ji\u0101n"; }
    @Override public int strokes() { return 10; }
    @Override public BasicSet library() { return BasicSet.INSTANCE; }
}
