// AUTO-GENERATED by CatalogIteratorMain - do not edit by hand.
package kranji.common.perclass.promoted.x.ie2;

import kranji.classification.EtymologicalCategory;
import kranji.pinyin.Body;
import kranji.pinyin.Final;
import kranji.pinyin.Head;
import kranji.pinyin.Initial;
import kranji.pinyin.PinyinSyllable;
import kranji.pinyin.Tail;
import kranji.pinyin.Tone;
import kranji.singular.materials.Materials;
import kranji.zi.ComposedZiT;
import kranji.zi.CompositionLayoutT;
import kranji.zi.LeftRightT;

public record XieShoe() implements ComposedZiT, LeftRightT<Materials.Ge, Materials.Gui_Tablet> {

    public static final XieShoe INSTANCE = new XieShoe();

    @Override public Materials.Ge left() { return Materials.GE; }
    @Override public Materials.Gui_Tablet right() { return Materials.GUI_TABLET; }

    @Override public CompositionLayoutT layout() { return this; }

    @Override public String glyph() { return "\u978B"; }

    @Override public PinyinSyllable pinyin() {
        return new PinyinSyllable(Initial.X, new Final(Head.I, Body.E_CARON, Tail.NONE), Tone.SECOND);
    }

    @Override public int strokes() { return 0; }
    @Override public int radicalNo() { return 0; }
    @Override public String meaning() { return ""; }

    @Override public EtymologicalCategory etymology() {
        return new EtymologicalCategory.PhonoSemantic(Materials.GE, Materials.GUI_TABLET);
    }
}
