// AUTO-GENERATED by CatalogIteratorMain - do not edit by hand.
package kranji.common.perclass.promoted.r.ang3;

import kranji.classification.EtymologicalCategory;
import kranji.common.perclass.promoted.x.iang1.XiangXiangAuto;
import kranji.pinyin.Body;
import kranji.pinyin.Final;
import kranji.pinyin.Head;
import kranji.pinyin.Initial;
import kranji.pinyin.PinyinSyllable;
import kranji.pinyin.Tail;
import kranji.pinyin.Tone;
import kranji.singular.body.BodyParts;
import kranji.zi.ComposedZiT;
import kranji.zi.CompositionLayoutT;
import kranji.zi.LeftRightT;

public record RangYell() implements ComposedZiT, LeftRightT<BodyParts.Kou, XiangXiangAuto> {

    public static final RangYell INSTANCE = new RangYell();

    @Override public BodyParts.Kou left() { return BodyParts.KOU; }
    @Override public XiangXiangAuto right() { return XiangXiangAuto.INSTANCE; }

    @Override public CompositionLayoutT layout() { return this; }

    @Override public String glyph() { return "\u56B7"; }

    @Override public PinyinSyllable pinyin() {
        return new PinyinSyllable(Initial.R, new Final(Head.OPEN, Body.A, Tail.NG), Tone.THIRD);
    }

    @Override public int strokes() { return 0; }
    @Override public int radicalNo() { return 0; }
    @Override public String meaning() { return ""; }

    @Override public EtymologicalCategory etymology() {
        return new EtymologicalCategory.PhonoSemantic(BodyParts.KOU, XiangXiangAuto.INSTANCE);
    }
}
