// AUTO-GENERATED by kranji-codegen. Do not edit by hand.
package kranji.singular.tools.m;

import kranji.library.BasicSet;
import kranji.library.LibraryMember;
import kranji.zi.SingularZi;

public record Mao() implements LibraryMember<BasicSet>, SingularZi {
    public static final Mao INSTANCE = new Mao();

    @Override public String glyph() { return "\u77DB"; }
    @Override public String meaning() { return "spear"; }
    @Override public String pinyinText() { return "m\u00E1o"; }
    @Override public int strokes() { return 5; }
    @Override public BasicSet library() { return BasicSet.INSTANCE; }
}
