// AUTO-GENERATED by kranji-codegen. Do not edit by hand.
package kranji.singular.radicals.z;

import kranji.library.BasicSet;
import kranji.library.LibraryMember;
import kranji.zi.SingularPart;

public record Zuo_Hand() implements LibraryMember<BasicSet>, SingularPart {
    public static final Zuo_Hand INSTANCE = new Zuo_Hand();

    @Override public String glyph() { return "\uD840\uDC87"; }
    @Override public String meaning() { return "left hand"; }
    @Override public String pinyinText() { return "zu\u01D2"; }
    @Override public int strokes() { return 2; }
    @Override public BasicSet library() { return BasicSet.INSTANCE; }
}
