// AUTO-GENERATED by kranji-codegen. Do not edit by hand.
package kranji.singular.concepts.j;

import kranji.library.BasicSet;
import kranji.library.LibraryMember;
import kranji.zi.SingularZi;

public record Ji_Self() implements LibraryMember<BasicSet>, SingularZi {
    public static final Ji_Self INSTANCE = new Ji_Self();

    @Override public String glyph() { return "\u5DF1"; }
    @Override public String meaning() { return "self, oneself"; }
    @Override public String pinyinText() { return "j\u01D0"; }
    @Override public int strokes() { return 3; }
    @Override public BasicSet library() { return BasicSet.INSTANCE; }
}
