// AUTO-GENERATED by kranji-codegen. Do not edit by hand.
package kranji.singular.concepts.j;

import kranji.library.BasicSet;
import kranji.library.LibraryMember;
import kranji.zi.SingularZi;

public record Jin() implements LibraryMember<BasicSet>, SingularZi {
    public static final Jin INSTANCE = new Jin();

    @Override public String glyph() { return "\u4ECA"; }
    @Override public String meaning() { return "today, now"; }
    @Override public String pinyinText() { return "j\u012Bn"; }
    @Override public int strokes() { return 4; }
    @Override public BasicSet library() { return BasicSet.INSTANCE; }
}
