// AUTO-GENERATED by CatalogIteratorMain - do not edit by hand.
package kranji.common.perclass.promoted.zero.i4;

import kranji.classification.EtymologicalCategory;
import kranji.pinyin.Body;
import kranji.pinyin.Final;
import kranji.pinyin.Head;
import kranji.pinyin.Initial;
import kranji.pinyin.PinyinSyllable;
import kranji.pinyin.Tail;
import kranji.pinyin.Tone;
import kranji.singular.actions.ActionsAndStates;
import kranji.singular.animals.Animals;
import kranji.zi.ComposedZiT;
import kranji.zi.CompositionLayoutT;
import kranji.zi.LeftRightT;

public record YiResolute_Inner1() implements ComposedZiT, LeftRightT<ActionsAndStates.Li_Stand, Animals.Shi_Pig> {

    public static final YiResolute_Inner1 INSTANCE = new YiResolute_Inner1();

    @Override public ActionsAndStates.Li_Stand left() { return ActionsAndStates.LI_STAND; }
    @Override public Animals.Shi_Pig right() { return Animals.SHI_PIG; }

    @Override public CompositionLayoutT layout() { return this; }

    @Override public String glyph() { return ""; }

    @Override public PinyinSyllable pinyin() {
        return new PinyinSyllable(Initial.ZERO, new Final(Head.OPEN, Body.I, Tail.NONE), Tone.FOURTH);
    }

    @Override public int strokes() { return 0; }
    @Override public int radicalNo() { return 0; }
    @Override public String meaning() { return ""; }

    @Override public EtymologicalCategory etymology() {
        return new EtymologicalCategory.CompoundIndicative("");
    }
}
