// AUTO-GENERATED by CatalogIteratorMain - do not edit by hand.
package kranji.common.perclass.promoted.zero.iang2;

import kranji.pinyin.Body;
import kranji.pinyin.Final;
import kranji.pinyin.Head;
import kranji.pinyin.Initial;
import kranji.pinyin.PinyinSyllable;
import kranji.pinyin.Tail;
import kranji.pinyin.Tone;
import kranji.zi.SingularZi;

public record YangSheepVariantAtom() implements SingularZi {

    public static final YangSheepVariantAtom INSTANCE = new YangSheepVariantAtom();

    @Override public String glyph() { return "\uD858\uDF4C"; }

    @Override public PinyinSyllable pinyin() {
        return new PinyinSyllable(Initial.ZERO, new Final(Head.I, Body.A, Tail.NG), Tone.SECOND);
    }

    @Override public boolean unsure() { return true; }
}
