// AUTO-GENERATED by Depth1GenerateMain - do not edit by hand.
package kranji.common.depth1.z;

import kranji.classification.EtymologicalCategory.*;
import kranji.component.basic.BasicComponents;
import kranji.pinyin.Body;
import kranji.pinyin.Final;
import kranji.pinyin.Head;
import kranji.pinyin.Initial;
import kranji.pinyin.PinyinSyllable;
import kranji.pinyin.Tail;
import kranji.pinyin.Tone;
import kranji.singular.concepts.AbstractConcepts;
import kranji.zi.ComposedPart;
import kranji.zi.ComposedZi;
import kranji.zi.CompositionLayout.*;
import kranji.zi.SingularPart;
import kranji.zi.ZiChar;
import java.util.List;

public final class U3 {

    private U3() {}

    public static final ComposedZi ZU_BLOCK = new ComposedZi(
            new ZiChar.Unicode("\u963B"),
            new PinyinSyllable(Initial.Z, new Final(Head.U, Body.U, Tail.NONE), Tone.THIRD),
            7, 170, "",
            new LeftRight(BasicComponents.ER_PANG, AbstractConcepts.QIE),
            new PhonoSemantic(BasicComponents.ER_PANG, AbstractConcepts.QIE));

    public static final ComposedZi ZU_GROUP = new ComposedZi(
            new ZiChar.Unicode("\u7EC4"),
            new PinyinSyllable(Initial.Z, new Final(Head.U, Body.U, Tail.NONE), Tone.THIRD),
            8, 120, "",
            new LeftRight(BasicComponents.JIAO_SI_PANG, AbstractConcepts.QIE),
            new PhonoSemantic(BasicComponents.JIAO_SI_PANG, AbstractConcepts.QIE));

    public static final List<ComposedZi> ALL = List.of(
            ZU_BLOCK,
            ZU_GROUP);
}
