// AUTO-GENERATED by PerclassGenerateMain - do not edit by hand.
package kranji.common.perclass.g.ao1;

import kranji.classification.EtymologicalCategory;
import kranji.component.basic.BasicComponents;
import kranji.component.basic.FireFamily.SiDianDi;
import kranji.pinyin.Body;
import kranji.pinyin.Final;
import kranji.pinyin.Head;
import kranji.pinyin.Initial;
import kranji.pinyin.PinyinSyllable;
import kranji.pinyin.Tail;
import kranji.pinyin.Tone;
import kranji.singular.animals.Animals;
import kranji.singular.animals.Animals.Yang;
import kranji.singular.plants.PlantsAndAgriculture;
import kranji.singular.plants.PlantsAndAgriculture.Mi;
import kranji.zi.ComposedZiT;
import kranji.zi.CompositionLayoutT;
import kranji.zi.LeftRightT;
import kranji.zi.TopBottomPartT;

public record GaoCake() implements ComposedZiT, LeftRightT<Mi, TopBottomPartT<Yang, SiDianDi>> {

    public static final GaoCake INSTANCE = new GaoCake();

    @Override public Mi left() { return PlantsAndAgriculture.MI; }
    @Override public TopBottomPartT<Yang, SiDianDi> right() { return new TopBottomPartT<>(Animals.YANG, BasicComponents.SI_DIAN_DI); }

    @Override public CompositionLayoutT layout() { return this; }

    @Override public String glyph() { return "\u7CD5"; }

    @Override public PinyinSyllable pinyin() {
        return new PinyinSyllable(Initial.G, new Final(Head.OPEN, Body.A, Tail.VOWEL_U), Tone.FIRST);
    }

    @Override public int strokes() { return 16; }
    @Override public int radicalNo() { return 119; }
    @Override public String meaning() { return ""; }

    @Override public EtymologicalCategory etymology() {
        return new EtymologicalCategory.PhonoSemantic(PlantsAndAgriculture.MI, new TopBottomPartT<>(Animals.YANG, BasicComponents.SI_DIAN_DI));
    }
}
