// AUTO-GENERATED by kranji-codegen. Do not edit by hand.
package kranji.singular.space.x;

import kranji.library.BasicSet;
import kranji.library.LibraryMember;
import kranji.zi.SingularZi;

public record Xi() implements LibraryMember<BasicSet>, SingularZi {
    public static final Xi INSTANCE = new Xi();

    @Override public String glyph() { return "\u897F"; }
    @Override public String meaning() { return "west"; }
    @Override public String pinyinText() { return "x\u012B"; }
    @Override public int strokes() { return 6; }
    @Override public BasicSet library() { return BasicSet.INSTANCE; }
}
