// AUTO-GENERATED by kranji-codegen. Do not edit by hand.
package kranji.singular.concepts.h;

import kranji.library.BasicSet;
import kranji.library.LibraryMember;
import kranji.zi.SingularZi;

public record Hao() implements LibraryMember<BasicSet>, SingularZi {
    public static final Hao INSTANCE = new Hao();

    @Override public String glyph() { return "\u53F7"; }
    @Override public String meaning() { return "number, sign"; }
    @Override public String pinyinText() { return "h\u00E0o"; }
    @Override public int strokes() { return 5; }
    @Override public BasicSet library() { return BasicSet.INSTANCE; }
}
