// AUTO-GENERATED by kranji-codegen. Do not edit by hand.
package kranji.singular.tools.zh;

import kranji.library.BasicSet;
import kranji.library.LibraryMember;
import kranji.zi.SingularZi;

public record Zhou() implements LibraryMember<BasicSet>, SingularZi {
    public static final Zhou INSTANCE = new Zhou();

    @Override public String glyph() { return "\u821F"; }
    @Override public String meaning() { return "boat"; }
    @Override public String pinyinText() { return "zh\u014Du"; }
    @Override public int strokes() { return 6; }
    @Override public BasicSet library() { return BasicSet.INSTANCE; }
}
