// AUTO-GENERATED by Depth5GenerateMain - do not edit by hand.
package kranji.common.depth5.b;

import kranji.classification.EtymologicalCategory.*;
import kranji.component.basic.BasicComponents;
import kranji.pinyin.Body;
import kranji.pinyin.Final;
import kranji.pinyin.Head;
import kranji.pinyin.Initial;
import kranji.pinyin.PinyinSyllable;
import kranji.pinyin.Tail;
import kranji.pinyin.Tone;
import kranji.singular.actions.ActionsAndStates;
import kranji.singular.animals.Animals;
import kranji.singular.body.BodyParts;
import kranji.singular.nature.NatureElements;
import kranji.singular.numbers.NumbersAndMeasure;
import kranji.singular.space.SpaceAndDirection;
import kranji.singular.structures.Structures;
import kranji.zi.ComposedPart;
import kranji.zi.ComposedZi;
import kranji.zi.CompositionLayout.*;
import kranji.zi.SingularPart;
import kranji.zi.ZiChar;
import java.util.List;

public final class Iang2 {

    private Iang2() {}

    public static final ComposedZi BIANG = new ComposedZi(
            new ZiChar.Unicode("\uD883\uDEDD"),
            new PinyinSyllable(Initial.B, new Final(Head.I, Body.A, Tail.NG), Tone.SECOND),
            58, 162, "",
            new SemiEnclosureBottomLeft(BasicComponents.ZOU_ZHI_DI, new ComposedPart(new TopMiddleBottom(Structures.XUE, new ComposedPart(new LeftMiddleRight(NatureElements.YUE, new ComposedPart(new TopBottom(new ComposedPart(new LeftMiddleRight(NumbersAndMeasure.YAO_TINY, ActionsAndStates.YAN_SPEECH, NumbersAndMeasure.YAO_TINY)), new ComposedPart(new LeftMiddleRight(SpaceAndDirection.CHANG, Animals.MA, SpaceAndDirection.CHANG)))), BasicComponents.LI_DAO_PANG)), BodyParts.XIN))),
            new CompoundIndicative("folk-coined character for the sound biáng — the slapping noise of noodle dough pulled and struck against a board"));

    public static final List<ComposedZi> ALL = List.of(
            BIANG);
}
