// AUTO-GENERATED by PerclassGenerateMain - do not edit by hand.
package kranji.common.perclass.p.o1;

import kranji.classification.EtymologicalCategory;
import kranji.component.basic.BasicComponents;
import kranji.component.basic.WaterFamily.SanDianShui;
import kranji.pinyin.Body;
import kranji.pinyin.Final;
import kranji.pinyin.Head;
import kranji.pinyin.Initial;
import kranji.pinyin.PinyinSyllable;
import kranji.pinyin.Tail;
import kranji.pinyin.Tone;
import kranji.singular.actions.ActionsAndStates;
import kranji.singular.actions.ActionsAndStates.Fa_Send;
import kranji.zi.ComposedZiT;
import kranji.zi.CompositionLayoutT;
import kranji.zi.LeftRightT;

public record PoSplash() implements ComposedZiT, LeftRightT<SanDianShui, Fa_Send> {

    public static final PoSplash INSTANCE = new PoSplash();

    @Override public SanDianShui left() { return BasicComponents.SAN_DIAN_SHUI; }
    @Override public Fa_Send right() { return ActionsAndStates.FA_SEND; }

    @Override public CompositionLayoutT layout() { return this; }

    @Override public String glyph() { return "\u6CFC"; }

    @Override public PinyinSyllable pinyin() {
        return new PinyinSyllable(Initial.P, new Final(Head.OPEN, Body.O, Tail.NONE), Tone.FIRST);
    }

    @Override public int strokes() { return 8; }
    @Override public int radicalNo() { return 85; }
    @Override public String meaning() { return ""; }

    @Override public EtymologicalCategory etymology() {
        return new EtymologicalCategory.PhonoSemantic(BasicComponents.SAN_DIAN_SHUI, ActionsAndStates.FA_SEND);
    }
}
