// AUTO-GENERATED by kranji-codegen. Do not edit by hand.
package kranji.singular.body.r;

import kranji.library.BasicSet;
import kranji.library.LibraryMember;
import kranji.zi.SingularZi;

public record Ru_Milk() implements LibraryMember<BasicSet>, SingularZi {
    public static final Ru_Milk INSTANCE = new Ru_Milk();

    @Override public String glyph() { return "\u4E73"; }
    @Override public String meaning() { return "breast, milk"; }
    @Override public String pinyinText() { return "r\u01D4"; }
    @Override public int strokes() { return 8; }
    @Override public BasicSet library() { return BasicSet.INSTANCE; }
}
