// AUTO-GENERATED by kranji-codegen. Do not edit by hand.
package kranji.singular.actions.f;

import kranji.library.BasicSet;
import kranji.library.LibraryMember;
import kranji.zi.SingularZi;

public record Feng_Offer() implements LibraryMember<BasicSet>, SingularZi {
    public static final Feng_Offer INSTANCE = new Feng_Offer();

    @Override public String glyph() { return "\u5949"; }
    @Override public String meaning() { return "offer, serve"; }
    @Override public String pinyinText() { return "f\u00E8ng"; }
    @Override public int strokes() { return 8; }
    @Override public BasicSet library() { return BasicSet.INSTANCE; }
}
