// AUTO-GENERATED by kranji-codegen. Do not edit by hand.
package kranji.singular.people.ch;

import kranji.library.BasicSet;
import kranji.library.LibraryMember;
import kranji.zi.SingularZi;

public record Chen() implements LibraryMember<BasicSet>, SingularZi {
    public static final Chen INSTANCE = new Chen();

    @Override public String glyph() { return "\u81E3"; }
    @Override public String meaning() { return "minister"; }
    @Override public String pinyinText() { return "ch\u00E9n"; }
    @Override public int strokes() { return 6; }
    @Override public BasicSet library() { return BasicSet.INSTANCE; }
}
