// AUTO-GENERATED by PerclassGenerateMain - do not edit by hand.
package kranji.common.perclass.g.e4;

import kranji.classification.EtymologicalCategory;
import kranji.pinyin.Body;
import kranji.pinyin.Final;
import kranji.pinyin.Head;
import kranji.pinyin.Initial;
import kranji.pinyin.PinyinSyllable;
import kranji.pinyin.Tail;
import kranji.pinyin.Tone;
import kranji.singular.body.BodyParts;
import kranji.singular.body.BodyParts.Kou;
import kranji.singular.radicals.RadicalComponents;
import kranji.singular.radicals.RadicalComponents.Zhi_Slow;
import kranji.zi.ComposedZiT;
import kranji.zi.CompositionLayoutT;
import kranji.zi.TopBottomT;

public record GeEach() implements ComposedZiT, TopBottomT<Zhi_Slow, Kou> {

    public static final GeEach INSTANCE = new GeEach();

    @Override public Zhi_Slow top() { return RadicalComponents.ZHI_SLOW; }
    @Override public Kou bottom() { return BodyParts.KOU; }

    @Override public CompositionLayoutT layout() { return this; }

    @Override public String glyph() { return "\u5404"; }

    @Override public PinyinSyllable pinyin() {
        return new PinyinSyllable(Initial.G, new Final(Head.OPEN, Body.E, Tail.NONE), Tone.FOURTH);
    }

    @Override public int strokes() { return 6; }
    @Override public int radicalNo() { return 30; }
    @Override public String meaning() { return ""; }

    @Override public EtymologicalCategory etymology() {
        return new EtymologicalCategory.CompoundIndicative("foot (夂) arriving at mouth of cave (口) — each, every");
    }
}
