package kranji.codegen.singulars;

import kranji.json.dto.SingularZiJson;

import java.util.Objects;

/**
 * Stateless builder for the Java source text of a per-class singular Zi
 * record.
 *
 * <p>Given a {@link SingularZiJson} plus the target package and class name,
 * produces a complete {@code .java} file body whose shape matches the
 * existing in-file records in {@code kranji-singulars} — the only
 * difference is one record per file plus a singleton {@code INSTANCE}
 * field.</p>
 *
 * <p>The emitter emits overrides for every field that is present and
 * non-default in the JSON. {@code radicalNo} is emitted only when
 * non-null. {@code name} is emitted only when different from {@code glyph}
 * (the {@link kranji.zi.SingularBlock#name()} default). Structured pinyin
 * and etymology are intentionally not emitted here — most records inherit
 * the defaults; records with non-default values are hand-ported after
 * codegen per the plan.</p>
 *
 * <p>The banner on the first line is significant: {@link #AUTO_BANNER}
 * marks a file that can be freely regenerated, while
 * {@link #PARTIAL_BANNER} (applied by hand) tells {@code GenerateMain} to
 * skip regeneration so hand-ported overrides survive.</p>
 */
public final class JavaEmitter {

    private JavaEmitter() {}

    public static final String AUTO_BANNER =
            "// AUTO-GENERATED by kranji-codegen. Do not edit by hand.";
    public static final String PARTIAL_BANNER =
            "// PARTIALLY GENERATED \u2014 see overrides.";

    /**
     * Emit a complete Java source file body for one {@link SingularZiJson}.
     *
     * @param packageName  target package, e.g. {@code "kranji.singular.people.w"}
     * @param className    target record class name, e.g. {@code "Wang_King"}
     * @param data         the JSON payload
     * @return the generated source (newline-terminated)
     */
    public static String emitSingularZi(String packageName,
                                        String className,
                                        SingularZiJson data) {
        Objects.requireNonNull(packageName, "packageName");
        Objects.requireNonNull(className, "className");
        Objects.requireNonNull(data, "data");
        if (data.glyph() == null || data.glyph().isEmpty()) {
            throw new IllegalArgumentException("glyph is required");
        }

        StringBuilder sb = new StringBuilder();
        sb.append(AUTO_BANNER).append('\n');
        sb.append("package ").append(packageName).append(";\n\n");
        sb.append("import kranji.library.BasicSet;\n");
        sb.append("import kranji.library.LibraryMember;\n");
        sb.append("import kranji.zi.SingularZi;\n\n");
        sb.append("public record ").append(className)
                .append("() implements LibraryMember<BasicSet>, SingularZi {\n");
        sb.append("    public static final ").append(className)
                .append(" INSTANCE = new ").append(className).append("();\n\n");

        // glyph is required; always emit as a Unicode escape so the
        // generated file stays pure ASCII and round-trips cleanly across
        // encodings.
        sb.append(override("String",   "glyph",      quoteUnicode(data.glyph())));
        if (data.name() != null && !data.name().equals(data.glyph())) {
            sb.append(override("String", "name",     quoteUnicode(data.name())));
        }
        if (data.meaning() != null && !data.meaning().isEmpty()) {
            sb.append(override("String", "meaning",  quoteJava(data.meaning())));
        }
        if (data.pinyinText() != null && !data.pinyinText().isEmpty()) {
            sb.append(override("String", "pinyinText", quoteUnicode(data.pinyinText())));
        }
        if (data.strokes() != null && data.strokes() != 0) {
            sb.append(override("int",    "strokes",  String.valueOf(data.strokes())));
        }
        if (data.radicalNo() != null && data.radicalNo() != 0) {
            sb.append(override("int",    "radicalNo", String.valueOf(data.radicalNo())));
        }
        sb.append(override("BasicSet", "library",   "BasicSet.INSTANCE"));

        sb.append("}\n");
        return sb.toString();
    }

    /** Render an override line: {@code @Override public <type> <name>() { return <expr>; }}. */
    private static String override(String returnType, String methodName, String expr) {
        return "    @Override public " + returnType + " " + methodName
                + "() { return " + expr + "; }\n";
    }

    /**
     * Quote a string literal, escaping all non-ASCII code points as
     * {@code \\uXXXX} / surrogate pairs. Keeps generated sources pure
     * ASCII — the same style as the existing in-place records (see
     * {@code Materials.java}).
     */
    static String quoteUnicode(String s) {
        StringBuilder b = new StringBuilder("\"");
        for (int i = 0; i < s.length(); i++) {
            char c = s.charAt(i);
            if (c == '"')       b.append("\\\"");
            else if (c == '\\') b.append("\\\\");
            else if (c == '\n') b.append("\\n");
            else if (c == '\r') b.append("\\r");
            else if (c == '\t') b.append("\\t");
            else if (c >= 0x20 && c < 0x7F) b.append(c);
            else b.append(String.format("\\u%04X", (int) c));
        }
        b.append('"');
        return b.toString();
    }

    /** Quote a string literal keeping non-ASCII chars verbatim (for meanings). */
    static String quoteJava(String s) {
        StringBuilder b = new StringBuilder("\"");
        for (int i = 0; i < s.length(); i++) {
            char c = s.charAt(i);
            if (c == '"')       b.append("\\\"");
            else if (c == '\\') b.append("\\\\");
            else if (c == '\n') b.append("\\n");
            else if (c == '\r') b.append("\\r");
            else if (c == '\t') b.append("\\t");
            else                b.append(c);
        }
        b.append('"');
        return b.toString();
    }
}
