// AUTO-GENERATED by CatalogIteratorMain - do not edit by hand.
package kranji.common.perclass.promoted.zero.iong1;

import kranji.classification.EtymologicalCategory;
import kranji.common.perclass.promoted.zero.iong1.YongMediocre_Inner1;
import kranji.pinyin.Body;
import kranji.pinyin.Final;
import kranji.pinyin.Head;
import kranji.pinyin.Initial;
import kranji.pinyin.PinyinSyllable;
import kranji.pinyin.Tail;
import kranji.pinyin.Tone;
import kranji.singular.structures.Structures;
import kranji.zi.ComposedZiT;
import kranji.zi.CompositionLayoutT;
import kranji.zi.SemiEnclosureUpperLeftT;

public record YongMediocre() implements ComposedZiT, SemiEnclosureUpperLeftT<Structures.Guang, YongMediocre_Inner1> {

    public static final YongMediocre INSTANCE = new YongMediocre();

    @Override public Structures.Guang wrapper() { return Structures.GUANG; }
    @Override public YongMediocre_Inner1 content() { return YongMediocre_Inner1.INSTANCE; }

    @Override public CompositionLayoutT layout() { return this; }

    @Override public String glyph() { return "\u5EB8"; }

    @Override public PinyinSyllable pinyin() {
        return new PinyinSyllable(Initial.ZERO, new Final(Head.I, Body.O, Tail.NG), Tone.FIRST);
    }

    @Override public int strokes() { return 0; }
    @Override public int radicalNo() { return 0; }
    @Override public String meaning() { return ""; }

    @Override public EtymologicalCategory etymology() {
        return new EtymologicalCategory.DerivativeCognate("");
    }
}
