// AUTO-GENERATED by CatalogIteratorMain - do not edit by hand.
package kranji.common.perclass.promoted.r.uei4;

import kranji.classification.EtymologicalCategory;
import kranji.pinyin.Body;
import kranji.pinyin.Final;
import kranji.pinyin.Head;
import kranji.pinyin.Initial;
import kranji.pinyin.PinyinSyllable;
import kranji.pinyin.Tail;
import kranji.pinyin.Tone;
import kranji.singular.people.PeopleAndRoles;
import kranji.singular.radicals.RadicalComponents;
import kranji.zi.ComposedZiT;
import kranji.zi.CompositionLayoutT;
import kranji.zi.LeftRightT;

public record RuiAuspicious() implements ComposedZiT, LeftRightT<PeopleAndRoles.Wang, RadicalComponents.Duan_Upright> {

    public static final RuiAuspicious INSTANCE = new RuiAuspicious();

    @Override public PeopleAndRoles.Wang left() { return PeopleAndRoles.WANG; }
    @Override public RadicalComponents.Duan_Upright right() { return RadicalComponents.DUAN_UPRIGHT; }

    @Override public CompositionLayoutT layout() { return this; }

    @Override public String glyph() { return "\u745E"; }

    @Override public PinyinSyllable pinyin() {
        return new PinyinSyllable(Initial.R, new Final(Head.U, Body.E, Tail.VOWEL_I), Tone.FOURTH);
    }

    @Override public int strokes() { return 0; }
    @Override public int radicalNo() { return 0; }
    @Override public String meaning() { return ""; }

    @Override public EtymologicalCategory etymology() {
        return new EtymologicalCategory.PhonoSemantic(PeopleAndRoles.WANG, RadicalComponents.DUAN_UPRIGHT);
    }
}
