// AUTO-GENERATED by CatalogIteratorMain - do not edit by hand.
package kranji.common.perclass.promoted.r.uei4;

import kranji.classification.EtymologicalCategory;
import kranji.common.perclass.promoted.d.uei4.DuiExchange;
import kranji.component.basic.BasicComponents;
import kranji.component.basic.MetalFamily;
import kranji.pinyin.Body;
import kranji.pinyin.Final;
import kranji.pinyin.Head;
import kranji.pinyin.Initial;
import kranji.pinyin.PinyinSyllable;
import kranji.pinyin.Tail;
import kranji.pinyin.Tone;
import kranji.zi.ComposedZiT;
import kranji.zi.CompositionLayoutT;
import kranji.zi.LeftRightT;

public record RuiSharp() implements ComposedZiT, LeftRightT<MetalFamily.JinZiPang, DuiExchange> {

    public static final RuiSharp INSTANCE = new RuiSharp();

    @Override public MetalFamily.JinZiPang left() { return BasicComponents.JIN_ZI_PANG; }
    @Override public DuiExchange right() { return DuiExchange.INSTANCE; }

    @Override public CompositionLayoutT layout() { return this; }

    @Override public String glyph() { return "\u9510"; }

    @Override public PinyinSyllable pinyin() {
        return new PinyinSyllable(Initial.R, new Final(Head.U, Body.E, Tail.VOWEL_I), Tone.FOURTH);
    }

    @Override public int strokes() { return 0; }
    @Override public int radicalNo() { return 0; }
    @Override public String meaning() { return ""; }

    @Override public EtymologicalCategory etymology() {
        return new EtymologicalCategory.PhonoSemantic(BasicComponents.JIN_ZI_PANG, DuiExchange.INSTANCE);
    }
}
