// AUTO-GENERATED by Depth1GenerateMain - do not edit by hand.
package kranji.common.depth1.b;

import kranji.classification.EtymologicalCategory.*;
import kranji.component.basic.BasicComponents;
import kranji.pinyin.Body;
import kranji.pinyin.Final;
import kranji.pinyin.Head;
import kranji.pinyin.Initial;
import kranji.pinyin.PinyinSyllable;
import kranji.pinyin.Tail;
import kranji.pinyin.Tone;
import kranji.singular.numbers.NumbersAndMeasure;
import kranji.zi.ComposedPart;
import kranji.zi.ComposedZi;
import kranji.zi.CompositionLayout.*;
import kranji.zi.SingularPart;
import kranji.zi.ZiChar;
import java.util.List;

public final class A1 {

    private A1() {}

    public static final ComposedZi BA_RAKE = new ComposedZi(
            new ZiChar.Unicode("\u6252"),
            new PinyinSyllable(Initial.B, new Final(Head.OPEN, Body.A, Tail.NONE), Tone.FIRST),
            5, 64, "",
            new LeftRight(BasicComponents.TI_SHOU_PANG, NumbersAndMeasure.BA),
            new PhonoSemantic(BasicComponents.TI_SHOU_PANG, NumbersAndMeasure.BA));

    public static final List<ComposedZi> ALL = List.of(
            BA_RAKE);
}
