// AUTO-GENERATED by CatalogIteratorMain - do not edit by hand.
package kranji.common.perclass.promoted.b.en4;

import kranji.classification.EtymologicalCategory;
import kranji.pinyin.Body;
import kranji.pinyin.Final;
import kranji.pinyin.Head;
import kranji.pinyin.Initial;
import kranji.pinyin.PinyinSyllable;
import kranji.pinyin.Tail;
import kranji.pinyin.Tone;
import kranji.singular.plants.PlantsAndAgriculture;
import kranji.singular.plants.PlantsAndAgriculture.Ben;
import kranji.singular.radicals.RadicalComponents;
import kranji.singular.radicals.RadicalComponents.Zhu_Bamboo;
import kranji.zi.ComposedZiT;
import kranji.zi.CompositionLayoutT;
import kranji.zi.TopBottomT;

public record BenStupid() implements ComposedZiT, TopBottomT<Zhu_Bamboo, Ben> {

    public static final BenStupid INSTANCE = new BenStupid();

    @Override public Zhu_Bamboo top() { return RadicalComponents.ZHU_BAMBOO; }
    @Override public Ben bottom() { return PlantsAndAgriculture.BEN; }

    @Override public CompositionLayoutT layout() { return this; }

    @Override public String glyph() { return "\u7B28"; }

    @Override public PinyinSyllable pinyin() {
        return new PinyinSyllable(Initial.B, new Final(Head.OPEN, Body.E, Tail.N), Tone.FOURTH);
    }

    @Override public int strokes() { return 0; }
    @Override public int radicalNo() { return 0; }
    @Override public String meaning() { return ""; }

    @Override public EtymologicalCategory etymology() {
        return new EtymologicalCategory.PhonoSemantic(RadicalComponents.ZHU_BAMBOO, PlantsAndAgriculture.BEN);
    }
}
