// AUTO-GENERATED by kranji-codegen. Do not edit by hand.
package kranji.singular.space.l;

import kranji.library.BasicSet;
import kranji.library.LibraryMember;
import kranji.zi.SingularZi;

public record Li_Inside() implements LibraryMember<BasicSet>, SingularZi {
    public static final Li_Inside INSTANCE = new Li_Inside();

    @Override public String glyph() { return "\u91CC"; }
    @Override public String meaning() { return "inside, mile"; }
    @Override public String pinyinText() { return "l\u01D0"; }
    @Override public int strokes() { return 7; }
    @Override public BasicSet library() { return BasicSet.INSTANCE; }
}
