// AUTO-GENERATED by Depth1GenerateMain - do not edit by hand.
package kranji.common.depth1;

import kranji.zi.ComposedZi;

import kranji.common.depth1.f.A3;
import kranji.common.depth1.f.An3;
import kranji.common.depth1.f.An4;
import kranji.common.depth1.f.Ang1;
import kranji.common.depth1.f.Ang2;
import kranji.common.depth1.f.Ang3;
import kranji.common.depth1.f.Ang4;
import kranji.common.depth1.f.Ei2;
import kranji.common.depth1.f.Ei4;
import kranji.common.depth1.f.En1;
import kranji.common.depth1.f.En2;
import kranji.common.depth1.f.En4;
import kranji.common.depth1.f.O2;
import kranji.common.depth1.f.Ou3;
import kranji.common.depth1.f.U1;
import kranji.common.depth1.f.U2;
import kranji.common.depth1.f.U3;
import kranji.common.depth1.f.U4;

import java.util.ArrayList;
import java.util.Collections;
import java.util.List;

public final class Depth1F {

    private Depth1F() {}

    public static final List<ComposedZi> ALL;
    static {
        var list = new ArrayList<ComposedZi>();
        list.addAll(A3.ALL);
        list.addAll(An3.ALL);
        list.addAll(An4.ALL);
        list.addAll(Ang1.ALL);
        list.addAll(Ang2.ALL);
        list.addAll(Ang3.ALL);
        list.addAll(Ang4.ALL);
        list.addAll(Ei2.ALL);
        list.addAll(Ei4.ALL);
        list.addAll(En1.ALL);
        list.addAll(En2.ALL);
        list.addAll(En4.ALL);
        list.addAll(O2.ALL);
        list.addAll(Ou3.ALL);
        list.addAll(U1.ALL);
        list.addAll(U2.ALL);
        list.addAll(U3.ALL);
        list.addAll(U4.ALL);
        ALL = Collections.unmodifiableList(list);
    }
}
