// AUTO-GENERATED by Depth1GenerateMain - do not edit by hand.
package kranji.common.depth1;

import kranji.zi.ComposedZi;

import kranji.common.depth1.q.I2;
import kranji.common.depth1.q.I3;
import kranji.common.depth1.q.I4;
import kranji.common.depth1.q.Iang1;
import kranji.common.depth1.q.Iang3;
import kranji.common.depth1.q.Ie1;
import kranji.common.depth1.q.In2;
import kranji.common.depth1.q.Ing1;
import kranji.common.depth1.q.Ing2;
import kranji.common.depth1.q.Ing3;
import kranji.common.depth1.q.Iong2;
import kranji.common.depth1.q.V1;
import kranji.common.depth1.q.V3;
import kranji.common.depth1.q.Van4;
import kranji.common.depth1.q.Ve4;

import java.util.ArrayList;
import java.util.Collections;
import java.util.List;

public final class Depth1Q {

    private Depth1Q() {}

    public static final List<ComposedZi> ALL;
    static {
        var list = new ArrayList<ComposedZi>();
        list.addAll(I2.ALL);
        list.addAll(I3.ALL);
        list.addAll(I4.ALL);
        list.addAll(Iang1.ALL);
        list.addAll(Iang3.ALL);
        list.addAll(Ie1.ALL);
        list.addAll(In2.ALL);
        list.addAll(Ing1.ALL);
        list.addAll(Ing2.ALL);
        list.addAll(Ing3.ALL);
        list.addAll(Iong2.ALL);
        list.addAll(V1.ALL);
        list.addAll(V3.ALL);
        list.addAll(Van4.ALL);
        list.addAll(Ve4.ALL);
        ALL = Collections.unmodifiableList(list);
    }
}
