// AUTO-GENERATED by Depth1GenerateMain - do not edit by hand.
package kranji.common.depth1;

import kranji.zi.ComposedZi;

import kranji.common.depth1.g.Ai1;
import kranji.common.depth1.g.Ai3;
import kranji.common.depth1.g.An1;
import kranji.common.depth1.g.An3;
import kranji.common.depth1.g.Ang1;
import kranji.common.depth1.g.Ang4;
import kranji.common.depth1.g.Ao4;
import kranji.common.depth1.g.Ong1;
import kranji.common.depth1.g.Ong4;
import kranji.common.depth1.g.Ou1;
import kranji.common.depth1.g.U1;
import kranji.common.depth1.g.U4;
import kranji.common.depth1.g.Ua1;
import kranji.common.depth1.g.Uei1;
import kranji.common.depth1.g.Uei4;
import kranji.common.depth1.g.Uo2;

import java.util.ArrayList;
import java.util.Collections;
import java.util.List;

public final class Depth1G {

    private Depth1G() {}

    public static final List<ComposedZi> ALL;
    static {
        var list = new ArrayList<ComposedZi>();
        list.addAll(Ai1.ALL);
        list.addAll(Ai3.ALL);
        list.addAll(An1.ALL);
        list.addAll(An3.ALL);
        list.addAll(Ang1.ALL);
        list.addAll(Ang4.ALL);
        list.addAll(Ao4.ALL);
        list.addAll(Ong1.ALL);
        list.addAll(Ong4.ALL);
        list.addAll(Ou1.ALL);
        list.addAll(U1.ALL);
        list.addAll(U4.ALL);
        list.addAll(Ua1.ALL);
        list.addAll(Uei1.ALL);
        list.addAll(Uei4.ALL);
        list.addAll(Uo2.ALL);
        ALL = Collections.unmodifiableList(list);
    }
}
