// AUTO-GENERATED by CatalogIteratorMain - do not edit by hand.
package kranji.common.perclass.promoted.b.o1;

import kranji.classification.EtymologicalCategory;
import kranji.component.basic.BasicComponents;
import kranji.component.basic.KnifeFamily;
import kranji.pinyin.Body;
import kranji.pinyin.Final;
import kranji.pinyin.Head;
import kranji.pinyin.Initial;
import kranji.pinyin.PinyinSyllable;
import kranji.pinyin.Tail;
import kranji.pinyin.Tone;
import kranji.singular.actions.ActionsAndStates;
import kranji.zi.ComposedZiT;
import kranji.zi.CompositionLayoutT;
import kranji.zi.LeftRightT;

public record BoPeel() implements ComposedZiT, LeftRightT<ActionsAndStates.Lu_Record, KnifeFamily.LiDaoPang> {

    public static final BoPeel INSTANCE = new BoPeel();

    @Override public ActionsAndStates.Lu_Record left() { return ActionsAndStates.LU_RECORD; }
    @Override public KnifeFamily.LiDaoPang right() { return BasicComponents.LI_DAO_PANG; }

    @Override public CompositionLayoutT layout() { return this; }

    @Override public String glyph() { return "\u5265"; }

    @Override public PinyinSyllable pinyin() {
        return new PinyinSyllable(Initial.B, new Final(Head.OPEN, Body.O, Tail.NONE), Tone.FIRST);
    }

    @Override public int strokes() { return 0; }
    @Override public int radicalNo() { return 0; }
    @Override public String meaning() { return ""; }

    @Override public EtymologicalCategory etymology() {
        return new EtymologicalCategory.PhonoSemantic(BasicComponents.LI_DAO_PANG, ActionsAndStates.LU_RECORD);
    }
}
