// AUTO-GENERATED by CatalogIteratorMain - do not edit by hand.
package kranji.common.perclass.promoted.b.o1;

import kranji.classification.EtymologicalCategory;
import kranji.common.perclass.b.o1.BoWave;
import kranji.component.basic.BasicComponents;
import kranji.component.basic.PlantFamily;
import kranji.pinyin.Body;
import kranji.pinyin.Final;
import kranji.pinyin.Head;
import kranji.pinyin.Initial;
import kranji.pinyin.PinyinSyllable;
import kranji.pinyin.Tail;
import kranji.pinyin.Tone;
import kranji.zi.ComposedZiT;
import kranji.zi.CompositionLayoutT;
import kranji.zi.TopBottomT;

public record BoSpinach() implements ComposedZiT, TopBottomT<PlantFamily.CaoZiTou, BoWave> {

    public static final BoSpinach INSTANCE = new BoSpinach();

    @Override public PlantFamily.CaoZiTou top() { return BasicComponents.CAO_ZI_TOU; }
    @Override public BoWave bottom() { return BoWave.INSTANCE; }

    @Override public CompositionLayoutT layout() { return this; }

    @Override public String glyph() { return "\u83E0"; }

    @Override public PinyinSyllable pinyin() {
        return new PinyinSyllable(Initial.B, new Final(Head.OPEN, Body.O, Tail.NONE), Tone.FIRST);
    }

    @Override public int strokes() { return 0; }
    @Override public int radicalNo() { return 0; }
    @Override public String meaning() { return ""; }

    @Override public EtymologicalCategory etymology() {
        return new EtymologicalCategory.PhonoSemantic(BasicComponents.CAO_ZI_TOU, BoWave.INSTANCE);
    }
}
