// AUTO-GENERATED by kranji-codegen. Do not edit by hand.
package kranji.singular.actions.c;

import kranji.library.BasicSet;
import kranji.library.LibraryMember;
import kranji.zi.SingularZi;

public record Cai() implements LibraryMember<BasicSet>, SingularZi {
    public static final Cai INSTANCE = new Cai();

    @Override public String glyph() { return "\u91C7"; }
    @Override public String meaning() { return "gather, pick"; }
    @Override public String pinyinText() { return "c\u01CEi"; }
    @Override public int strokes() { return 8; }
    @Override public BasicSet library() { return BasicSet.INSTANCE; }
}
