// AUTO-GENERATED by CatalogIteratorMain - do not edit by hand.
package kranji.common.perclass.promoted.p.ing2;

import kranji.classification.EtymologicalCategory;
import kranji.common.perclass.r.en4.RenDuty;
import kranji.pinyin.Body;
import kranji.pinyin.Final;
import kranji.pinyin.Head;
import kranji.pinyin.Initial;
import kranji.pinyin.PinyinSyllable;
import kranji.pinyin.Tail;
import kranji.pinyin.Tone;
import kranji.singular.tools.ToolsAndVessels;
import kranji.zi.ComposedZiT;
import kranji.zi.CompositionLayoutT;
import kranji.zi.TopBottomT;

public record PingLeanOn() implements ComposedZiT, TopBottomT<RenDuty, ToolsAndVessels.Ji_Table> {

    public static final PingLeanOn INSTANCE = new PingLeanOn();

    @Override public RenDuty top() { return RenDuty.INSTANCE; }
    @Override public ToolsAndVessels.Ji_Table bottom() { return ToolsAndVessels.JI_TABLE; }

    @Override public CompositionLayoutT layout() { return this; }

    @Override public String glyph() { return "\u51ED"; }

    @Override public PinyinSyllable pinyin() {
        return new PinyinSyllable(Initial.P, new Final(Head.OPEN, Body.I, Tail.NG), Tone.SECOND);
    }

    @Override public int strokes() { return 0; }
    @Override public int radicalNo() { return 0; }
    @Override public String meaning() { return ""; }

    @Override public EtymologicalCategory etymology() {
        return new EtymologicalCategory.PhonoSemantic(ToolsAndVessels.JI_TABLE, RenDuty.INSTANCE);
    }
}
