// AUTO-GENERATED by CatalogIteratorMain - do not edit by hand.
package kranji.common.perclass.promoted.p.i2;

import kranji.classification.EtymologicalCategory;
import kranji.common.perclass.promoted.b.ei1.BeiHumble;
import kranji.pinyin.Body;
import kranji.pinyin.Final;
import kranji.pinyin.Head;
import kranji.pinyin.Initial;
import kranji.pinyin.PinyinSyllable;
import kranji.pinyin.Tail;
import kranji.pinyin.Tone;
import kranji.singular.nature.NatureElements;
import kranji.zi.ComposedZiT;
import kranji.zi.CompositionLayoutT;
import kranji.zi.LeftRightT;

public record PiSpleen() implements ComposedZiT, LeftRightT<NatureElements.Yue, BeiHumble> {

    public static final PiSpleen INSTANCE = new PiSpleen();

    @Override public NatureElements.Yue left() { return NatureElements.YUE; }
    @Override public BeiHumble right() { return BeiHumble.INSTANCE; }

    @Override public CompositionLayoutT layout() { return this; }

    @Override public String glyph() { return "\u813E"; }

    @Override public PinyinSyllable pinyin() {
        return new PinyinSyllable(Initial.P, new Final(Head.OPEN, Body.I, Tail.NONE), Tone.SECOND);
    }

    @Override public int strokes() { return 0; }
    @Override public int radicalNo() { return 0; }
    @Override public String meaning() { return ""; }

    @Override public EtymologicalCategory etymology() {
        return new EtymologicalCategory.PhonoSemantic(NatureElements.YUE, BeiHumble.INSTANCE);
    }
}
