// AUTO-GENERATED by PerclassGenerateMain - do not edit by hand.
package kranji.common.perclass.t.an3;

import kranji.classification.EtymologicalCategory;
import kranji.common.perclass.d.an4.DanDawn;
import kranji.pinyin.Body;
import kranji.pinyin.Final;
import kranji.pinyin.Head;
import kranji.pinyin.Initial;
import kranji.pinyin.PinyinSyllable;
import kranji.pinyin.Tail;
import kranji.pinyin.Tone;
import kranji.singular.nature.NatureElements;
import kranji.singular.nature.NatureElements.Tu;
import kranji.zi.ComposedZiT;
import kranji.zi.CompositionLayoutT;
import kranji.zi.LeftRightT;

public record TanFlat() implements ComposedZiT, LeftRightT<Tu, DanDawn> {

    public static final TanFlat INSTANCE = new TanFlat();

    @Override public Tu left() { return NatureElements.TU; }
    @Override public DanDawn right() { return DanDawn.INSTANCE; }

    @Override public CompositionLayoutT layout() { return this; }

    @Override public String glyph() { return "\u5766"; }

    @Override public PinyinSyllable pinyin() {
        return new PinyinSyllable(Initial.T, new Final(Head.OPEN, Body.A, Tail.N), Tone.THIRD);
    }

    @Override public int strokes() { return 8; }
    @Override public int radicalNo() { return 32; }
    @Override public String meaning() { return ""; }

    @Override public EtymologicalCategory etymology() {
        return new EtymologicalCategory.PhonoSemantic(NatureElements.TU, DanDawn.INSTANCE);
    }
}
