// AUTO-GENERATED by kranji-codegen. Do not edit by hand.
package kranji.singular.structures;

import kranji.library.BasicSet;
import kranji.library.LibraryMember;

import kranji.singular.structures.b.Ba_Cling;
import kranji.singular.structures.c.Cang;
import kranji.singular.structures.c.Cong_Chimney;
import kranji.singular.structures.c.Cun_Inch;
import kranji.singular.structures.ch.Chang_Factory;
import kranji.singular.structures.ch.Chi_Ruler;
import kranji.singular.structures.g.Guang;
import kranji.singular.structures.h.Hu;
import kranji.singular.structures.j.Jing_Capital;
import kranji.singular.structures.j.Ju;
import kranji.singular.structures.sh.Shi_Corpse;
import kranji.singular.structures.sh.Shi_Market;
import kranji.singular.structures.t.Tai;
import kranji.singular.structures.t.Ting;
import kranji.singular.structures.t.Tun;
import kranji.singular.structures.x.Xue;

import java.util.List;

public final class Structures {
    private Structures() {}

    public static final List<LibraryMember<BasicSet>> ALL = List.of(
            Ba_Cling.INSTANCE,
            Cang.INSTANCE,
            Chang_Factory.INSTANCE,
            Chi_Ruler.INSTANCE,
            Cong_Chimney.INSTANCE,
            Cun_Inch.INSTANCE,
            Guang.INSTANCE,
            Hu.INSTANCE,
            Jing_Capital.INSTANCE,
            Ju.INSTANCE,
            Shi_Corpse.INSTANCE,
            Shi_Market.INSTANCE,
            Tai.INSTANCE,
            Ting.INSTANCE,
            Tun.INSTANCE,
            Xue.INSTANCE);
}
