// AUTO-GENERATED by kranji-codegen. Do not edit by hand.
package kranji.singular.plants.h;

import kranji.library.BasicSet;
import kranji.library.LibraryMember;
import kranji.zi.SingularZi;

public record He() implements LibraryMember<BasicSet>, SingularZi {
    public static final He INSTANCE = new He();

    @Override public String glyph() { return "\u79BE"; }
    @Override public String meaning() { return "grain, cereal"; }
    @Override public String pinyinText() { return "h\u00E9"; }
    @Override public int strokes() { return 5; }
    @Override public BasicSet library() { return BasicSet.INSTANCE; }
}
