// AUTO-GENERATED by CatalogIteratorMain - do not edit by hand.
package kranji.common.perclass.promoted.d.uen4;

import kranji.pinyin.Body;
import kranji.pinyin.Final;
import kranji.pinyin.Head;
import kranji.pinyin.Initial;
import kranji.pinyin.PinyinSyllable;
import kranji.pinyin.Tail;
import kranji.pinyin.Tone;
import kranji.zi.SingularZi;

public record DunDunAuto() implements SingularZi {

    public static final DunDunAuto INSTANCE = new DunDunAuto();

    @Override public String glyph() { return "\u76FE"; }

    @Override public PinyinSyllable pinyin() {
        return new PinyinSyllable(Initial.D, new Final(Head.U, Body.E, Tail.N), Tone.FOURTH);
    }

    @Override public boolean unsure() { return true; }
}
