// AUTO-GENERATED by CatalogIteratorMain - do not edit by hand.
package kranji.common.perclass.promoted.d.uen4;

import kranji.classification.EtymologicalCategory;
import kranji.pinyin.Body;
import kranji.pinyin.Final;
import kranji.pinyin.Head;
import kranji.pinyin.Initial;
import kranji.pinyin.PinyinSyllable;
import kranji.pinyin.Tail;
import kranji.pinyin.Tone;
import kranji.singular.space.SpaceAndDirection;
import kranji.singular.structures.Structures;
import kranji.zi.ComposedZiT;
import kranji.zi.CompositionLayoutT;
import kranji.zi.LeftRightT;

public record DunPause() implements ComposedZiT, LeftRightT<Structures.Tun, SpaceAndDirection.Ye_Page> {

    public static final DunPause INSTANCE = new DunPause();

    @Override public Structures.Tun left() { return Structures.TUN; }
    @Override public SpaceAndDirection.Ye_Page right() { return SpaceAndDirection.YE_PAGE; }

    @Override public CompositionLayoutT layout() { return this; }

    @Override public String glyph() { return "\u987F"; }

    @Override public PinyinSyllable pinyin() {
        return new PinyinSyllable(Initial.D, new Final(Head.U, Body.E, Tail.N), Tone.FOURTH);
    }

    @Override public int strokes() { return 0; }
    @Override public int radicalNo() { return 0; }
    @Override public String meaning() { return ""; }

    @Override public EtymologicalCategory etymology() {
        return new EtymologicalCategory.PhonoSemantic(SpaceAndDirection.YE_PAGE, Structures.TUN);
    }
}
