// AUTO-GENERATED by CatalogIteratorMain - do not edit by hand.
package kranji.common.perclass.promoted.j.ing4;

import kranji.pinyin.Body;
import kranji.pinyin.Final;
import kranji.pinyin.Head;
import kranji.pinyin.Initial;
import kranji.pinyin.PinyinSyllable;
import kranji.pinyin.Tail;
import kranji.pinyin.Tone;
import kranji.zi.SingularZi;

public record JingJingAuto() implements SingularZi {

    public static final JingJingAuto INSTANCE = new JingJingAuto();

    @Override public String glyph() { return "\u656C"; }

    @Override public PinyinSyllable pinyin() {
        return new PinyinSyllable(Initial.J, new Final(Head.OPEN, Body.I, Tail.NG), Tone.FOURTH);
    }

    @Override public boolean unsure() { return true; }
}
