// AUTO-GENERATED by kranji-codegen. Do not edit by hand.
package kranji.singular.actions.sh;

import kranji.library.BasicSet;
import kranji.library.LibraryMember;
import kranji.zi.SingularZi;

public record Shi_Yes() implements LibraryMember<BasicSet>, SingularZi {
    public static final Shi_Yes INSTANCE = new Shi_Yes();

    @Override public String glyph() { return "\u662F"; }
    @Override public String meaning() { return "is, yes"; }
    @Override public String pinyinText() { return "sh\u00EC"; }
    @Override public int strokes() { return 9; }
    @Override public BasicSet library() { return BasicSet.INSTANCE; }
}
