// AUTO-GENERATED by kranji-codegen. Do not edit by hand.
package kranji.singular.actions.sh;

import kranji.library.BasicSet;
import kranji.library.LibraryMember;
import kranji.zi.SingularZi;

public record Shi_Lose() implements LibraryMember<BasicSet>, SingularZi {
    public static final Shi_Lose INSTANCE = new Shi_Lose();

    @Override public String glyph() { return "\u5931"; }
    @Override public String meaning() { return "lose"; }
    @Override public String pinyinText() { return "sh\u012B"; }
    @Override public int strokes() { return 5; }
    @Override public BasicSet library() { return BasicSet.INSTANCE; }
}
