// AUTO-GENERATED by CatalogIteratorMain - do not edit by hand.
package kranji.common.perclass.promoted.d.uei1;

import kranji.classification.EtymologicalCategory;
import kranji.pinyin.Body;
import kranji.pinyin.Final;
import kranji.pinyin.Head;
import kranji.pinyin.Initial;
import kranji.pinyin.PinyinSyllable;
import kranji.pinyin.Tail;
import kranji.pinyin.Tone;
import kranji.singular.animals.Animals;
import kranji.singular.nature.NatureElements;
import kranji.zi.ComposedZiT;
import kranji.zi.CompositionLayoutT;
import kranji.zi.LeftRightT;

public record DuiPile() implements ComposedZiT, LeftRightT<NatureElements.Tu, Animals.Zhui> {

    public static final DuiPile INSTANCE = new DuiPile();

    @Override public NatureElements.Tu left() { return NatureElements.TU; }
    @Override public Animals.Zhui right() { return Animals.ZHUI; }

    @Override public CompositionLayoutT layout() { return this; }

    @Override public String glyph() { return "\u5806"; }

    @Override public PinyinSyllable pinyin() {
        return new PinyinSyllable(Initial.D, new Final(Head.U, Body.E, Tail.VOWEL_I), Tone.FIRST);
    }

    @Override public int strokes() { return 0; }
    @Override public int radicalNo() { return 0; }
    @Override public String meaning() { return ""; }

    @Override public EtymologicalCategory etymology() {
        return new EtymologicalCategory.PhonoSemantic(NatureElements.TU, Animals.ZHUI);
    }
}
