// AUTO-GENERATED by CatalogIteratorMain - do not edit by hand.
package kranji.common.perclass.promoted.d.ou3;

import kranji.classification.EtymologicalCategory;
import kranji.component.basic.BasicComponents;
import kranji.component.basic.EarFamily;
import kranji.pinyin.Body;
import kranji.pinyin.Final;
import kranji.pinyin.Head;
import kranji.pinyin.Initial;
import kranji.pinyin.PinyinSyllable;
import kranji.pinyin.Tail;
import kranji.pinyin.Tone;
import kranji.singular.actions.ActionsAndStates;
import kranji.zi.ComposedZiT;
import kranji.zi.CompositionLayoutT;
import kranji.zi.LeftRightT;

public record DouSteep() implements ComposedZiT, LeftRightT<EarFamily.ErPang, ActionsAndStates.Zou> {

    public static final DouSteep INSTANCE = new DouSteep();

    @Override public EarFamily.ErPang left() { return BasicComponents.ER_PANG; }
    @Override public ActionsAndStates.Zou right() { return ActionsAndStates.ZOU; }

    @Override public CompositionLayoutT layout() { return this; }

    @Override public String glyph() { return "\u9661"; }

    @Override public PinyinSyllable pinyin() {
        return new PinyinSyllable(Initial.D, new Final(Head.OPEN, Body.O, Tail.VOWEL_U), Tone.THIRD);
    }

    @Override public int strokes() { return 0; }
    @Override public int radicalNo() { return 0; }
    @Override public String meaning() { return ""; }

    @Override public EtymologicalCategory etymology() {
        return new EtymologicalCategory.PhonoSemantic(BasicComponents.ER_PANG, ActionsAndStates.ZOU);
    }
}
