// AUTO-GENERATED by CatalogIteratorMain - do not edit by hand.
package kranji.common.perclass.promoted.z.ao3;

import kranji.classification.EtymologicalCategory;
import kranji.common.perclass.promoted.z.ao4.ZaoZaoAuto;
import kranji.component.basic.BasicComponents;
import kranji.component.basic.WaterFamily;
import kranji.pinyin.Body;
import kranji.pinyin.Final;
import kranji.pinyin.Head;
import kranji.pinyin.Initial;
import kranji.pinyin.PinyinSyllable;
import kranji.pinyin.Tail;
import kranji.pinyin.Tone;
import kranji.zi.ComposedZiT;
import kranji.zi.CompositionLayoutT;
import kranji.zi.LeftRightT;

public record ZaoBathe() implements ComposedZiT, LeftRightT<WaterFamily.SanDianShui, ZaoZaoAuto> {

    public static final ZaoBathe INSTANCE = new ZaoBathe();

    @Override public WaterFamily.SanDianShui left() { return BasicComponents.SAN_DIAN_SHUI; }
    @Override public ZaoZaoAuto right() { return ZaoZaoAuto.INSTANCE; }

    @Override public CompositionLayoutT layout() { return this; }

    @Override public String glyph() { return "\u6FA1"; }

    @Override public PinyinSyllable pinyin() {
        return new PinyinSyllable(Initial.Z, new Final(Head.OPEN, Body.A, Tail.VOWEL_U), Tone.THIRD);
    }

    @Override public int strokes() { return 0; }
    @Override public int radicalNo() { return 0; }
    @Override public String meaning() { return ""; }

    @Override public EtymologicalCategory etymology() {
        return new EtymologicalCategory.PhonoSemantic(BasicComponents.SAN_DIAN_SHUI, ZaoZaoAuto.INSTANCE);
    }
}
