// AUTO-GENERATED by CatalogIteratorMain - do not edit by hand.
package kranji.common.perclass.promoted.b.o2;

import kranji.pinyin.Body;
import kranji.pinyin.Final;
import kranji.pinyin.Head;
import kranji.pinyin.Initial;
import kranji.pinyin.PinyinSyllable;
import kranji.pinyin.Tail;
import kranji.pinyin.Tone;
import kranji.zi.SingularZi;

public record BoSilk() implements SingularZi {

    public static final BoSilk INSTANCE = new BoSilk();

    @Override public String glyph() { return "\u5E1B"; }

    @Override public PinyinSyllable pinyin() {
        return new PinyinSyllable(Initial.B, new Final(Head.OPEN, Body.O, Tail.NONE), Tone.SECOND);
    }

    @Override public boolean unsure() { return true; }
}
