// AUTO-GENERATED by CatalogIteratorMain - do not edit by hand.
package kranji.common.perclass.promoted.b.o2;

import kranji.classification.EtymologicalCategory;
import kranji.common.perclass.promoted.f.u1.FuSpread;
import kranji.pinyin.Body;
import kranji.pinyin.Final;
import kranji.pinyin.Head;
import kranji.pinyin.Initial;
import kranji.pinyin.PinyinSyllable;
import kranji.pinyin.Tail;
import kranji.pinyin.Tone;
import kranji.singular.numbers.NumbersAndMeasure;
import kranji.zi.ComposedZiT;
import kranji.zi.CompositionLayoutT;
import kranji.zi.LeftRightT;

public record BoWide() implements ComposedZiT, LeftRightT<NumbersAndMeasure.Shi, FuSpread> {

    public static final BoWide INSTANCE = new BoWide();

    @Override public NumbersAndMeasure.Shi left() { return NumbersAndMeasure.SHI; }
    @Override public FuSpread right() { return FuSpread.INSTANCE; }

    @Override public CompositionLayoutT layout() { return this; }

    @Override public String glyph() { return "\u535A"; }

    @Override public PinyinSyllable pinyin() {
        return new PinyinSyllable(Initial.B, new Final(Head.OPEN, Body.O, Tail.NONE), Tone.SECOND);
    }

    @Override public int strokes() { return 0; }
    @Override public int radicalNo() { return 0; }
    @Override public String meaning() { return ""; }

    @Override public EtymologicalCategory etymology() {
        return new EtymologicalCategory.PhonoSemantic(NumbersAndMeasure.SHI, FuSpread.INSTANCE);
    }
}
