// AUTO-GENERATED by CatalogIteratorMain - do not edit by hand.
package kranji.common.perclass.promoted.l.iang2;

import kranji.classification.EtymologicalCategory;
import kranji.component.basic.BasicComponents;
import kranji.component.basic.WaterFamily;
import kranji.pinyin.Body;
import kranji.pinyin.Final;
import kranji.pinyin.Head;
import kranji.pinyin.Initial;
import kranji.pinyin.PinyinSyllable;
import kranji.pinyin.Tail;
import kranji.pinyin.Tone;
import kranji.singular.tools.ToolsAndVessels;
import kranji.zi.ComposedZiT;
import kranji.zi.CompositionLayoutT;
import kranji.zi.LeftRightT;

public record LiangBeam_Inner1() implements ComposedZiT, LeftRightT<WaterFamily.SanDianShui, ToolsAndVessels.Dao> {

    public static final LiangBeam_Inner1 INSTANCE = new LiangBeam_Inner1();

    @Override public WaterFamily.SanDianShui left() { return BasicComponents.SAN_DIAN_SHUI; }
    @Override public ToolsAndVessels.Dao right() { return ToolsAndVessels.DAO; }

    @Override public CompositionLayoutT layout() { return this; }

    @Override public String glyph() { return ""; }

    @Override public PinyinSyllable pinyin() {
        return new PinyinSyllable(Initial.L, new Final(Head.I, Body.A, Tail.NG), Tone.SECOND);
    }

    @Override public int strokes() { return 0; }
    @Override public int radicalNo() { return 0; }
    @Override public String meaning() { return ""; }

    @Override public EtymologicalCategory etymology() {
        return new EtymologicalCategory.CompoundIndicative("");
    }
}
