// AUTO-GENERATED by CatalogIteratorMain - do not edit by hand.
package kranji.common.perclass.promoted.b.i3;

import kranji.classification.EtymologicalCategory;
import kranji.common.perclass.promoted.b.i3.BiBiAuto;
import kranji.component.basic.BasicComponents;
import kranji.component.basic.EarFamily;
import kranji.pinyin.Body;
import kranji.pinyin.Final;
import kranji.pinyin.Head;
import kranji.pinyin.Initial;
import kranji.pinyin.PinyinSyllable;
import kranji.pinyin.Tail;
import kranji.pinyin.Tone;
import kranji.zi.ComposedZiT;
import kranji.zi.CompositionLayoutT;
import kranji.zi.LeftRightT;

public record BiDespise() implements ComposedZiT, LeftRightT<BiBiAuto, EarFamily.ErPang> {

    public static final BiDespise INSTANCE = new BiDespise();

    @Override public BiBiAuto left() { return BiBiAuto.INSTANCE; }
    @Override public EarFamily.ErPang right() { return BasicComponents.ER_PANG; }

    @Override public CompositionLayoutT layout() { return this; }

    @Override public String glyph() { return "\u9119"; }

    @Override public PinyinSyllable pinyin() {
        return new PinyinSyllable(Initial.B, new Final(Head.OPEN, Body.I, Tail.NONE), Tone.THIRD);
    }

    @Override public int strokes() { return 0; }
    @Override public int radicalNo() { return 0; }
    @Override public String meaning() { return ""; }

    @Override public EtymologicalCategory etymology() {
        return new EtymologicalCategory.PhonoSemantic(BasicComponents.ER_PANG, BiBiAuto.INSTANCE);
    }
}
