// AUTO-GENERATED by CatalogIteratorMain - do not edit by hand.
package kranji.common.perclass.promoted.zh.e1;

import kranji.classification.EtymologicalCategory;
import kranji.common.perclass.promoted.sh.u4.ShuShuAuto;
import kranji.component.basic.BasicComponents;
import kranji.component.basic.MovementFamily;
import kranji.pinyin.Body;
import kranji.pinyin.Final;
import kranji.pinyin.Head;
import kranji.pinyin.Initial;
import kranji.pinyin.PinyinSyllable;
import kranji.pinyin.Tail;
import kranji.pinyin.Tone;
import kranji.zi.ComposedZiT;
import kranji.zi.CompositionLayoutT;
import kranji.zi.SemiEnclosureBottomLeftT;

public record ZheCover() implements ComposedZiT, SemiEnclosureBottomLeftT<MovementFamily.ZouZhiDi, ShuShuAuto> {

    public static final ZheCover INSTANCE = new ZheCover();

    @Override public MovementFamily.ZouZhiDi wrapper() { return BasicComponents.ZOU_ZHI_DI; }
    @Override public ShuShuAuto content() { return ShuShuAuto.INSTANCE; }

    @Override public CompositionLayoutT layout() { return this; }

    @Override public String glyph() { return "\u906E"; }

    @Override public PinyinSyllable pinyin() {
        return new PinyinSyllable(Initial.ZH, new Final(Head.OPEN, Body.E, Tail.NONE), Tone.FIRST);
    }

    @Override public int strokes() { return 0; }
    @Override public int radicalNo() { return 0; }
    @Override public String meaning() { return ""; }

    @Override public EtymologicalCategory etymology() {
        return new EtymologicalCategory.PhonoSemantic(BasicComponents.ZOU_ZHI_DI, ShuShuAuto.INSTANCE);
    }
}
