// AUTO-GENERATED by PerclassGenerateMain - do not edit by hand.
package kranji.common.perclass.h.an2;

import kranji.classification.EtymologicalCategory;
import kranji.pinyin.Body;
import kranji.pinyin.Final;
import kranji.pinyin.Head;
import kranji.pinyin.Initial;
import kranji.pinyin.PinyinSyllable;
import kranji.pinyin.Tail;
import kranji.pinyin.Tone;
import kranji.singular.body.BodyParts;
import kranji.singular.body.BodyParts.Kou;
import kranji.singular.concepts.AbstractConcepts;
import kranji.singular.concepts.AbstractConcepts.Jin;
import kranji.zi.ComposedZiT;
import kranji.zi.CompositionLayoutT;
import kranji.zi.TopBottomT;

public record HanContain() implements ComposedZiT, TopBottomT<Jin, Kou> {

    public static final HanContain INSTANCE = new HanContain();

    @Override public Jin top() { return AbstractConcepts.JIN; }
    @Override public Kou bottom() { return BodyParts.KOU; }

    @Override public CompositionLayoutT layout() { return this; }

    @Override public String glyph() { return "\u542B"; }

    @Override public PinyinSyllable pinyin() {
        return new PinyinSyllable(Initial.H, new Final(Head.OPEN, Body.A, Tail.N), Tone.SECOND);
    }

    @Override public int strokes() { return 7; }
    @Override public int radicalNo() { return 30; }
    @Override public String meaning() { return ""; }

    @Override public EtymologicalCategory etymology() {
        return new EtymologicalCategory.PhonoSemantic(BodyParts.KOU, AbstractConcepts.JIN);
    }
}
