// AUTO-GENERATED by CatalogIteratorMain - do not edit by hand.
package kranji.common.perclass.promoted.x.iang4;

import kranji.classification.EtymologicalCategory;
import kranji.component.basic.BasicComponents;
import kranji.component.basic.PersonFamily;
import kranji.pinyin.Body;
import kranji.pinyin.Final;
import kranji.pinyin.Head;
import kranji.pinyin.Initial;
import kranji.pinyin.PinyinSyllable;
import kranji.pinyin.Tail;
import kranji.pinyin.Tone;
import kranji.singular.animals.Animals;
import kranji.zi.ComposedZiT;
import kranji.zi.CompositionLayoutT;
import kranji.zi.LeftRightT;

public record XiangImage() implements ComposedZiT, LeftRightT<PersonFamily.DanRenPang, Animals.Xiang> {

    public static final XiangImage INSTANCE = new XiangImage();

    @Override public PersonFamily.DanRenPang left() { return BasicComponents.DAN_REN_PANG; }
    @Override public Animals.Xiang right() { return Animals.XIANG; }

    @Override public CompositionLayoutT layout() { return this; }

    @Override public String glyph() { return "\u50CF"; }

    @Override public PinyinSyllable pinyin() {
        return new PinyinSyllable(Initial.X, new Final(Head.I, Body.A, Tail.NG), Tone.FOURTH);
    }

    @Override public int strokes() { return 0; }
    @Override public int radicalNo() { return 0; }
    @Override public String meaning() { return ""; }

    @Override public EtymologicalCategory etymology() {
        return new EtymologicalCategory.PhonoSemantic(BasicComponents.DAN_REN_PANG, Animals.XIANG);
    }
}
