// AUTO-GENERATED by CatalogIteratorMain - do not edit by hand.
package kranji.common.perclass.promoted.m.u4;

import kranji.classification.EtymologicalCategory;
import kranji.common.perclass.promoted.m.o4.MoNotMo;
import kranji.common.perclass.promoted.x.in1.XinHeartVariant;
import kranji.pinyin.Body;
import kranji.pinyin.Final;
import kranji.pinyin.Head;
import kranji.pinyin.Initial;
import kranji.pinyin.PinyinSyllable;
import kranji.pinyin.Tail;
import kranji.pinyin.Tone;
import kranji.zi.ComposedZiT;
import kranji.zi.CompositionLayoutT;
import kranji.zi.TopBottomT;

public record MuAdmire() implements ComposedZiT, TopBottomT<MoNotMo, XinHeartVariant> {

    public static final MuAdmire INSTANCE = new MuAdmire();

    @Override public MoNotMo top() { return MoNotMo.INSTANCE; }
    @Override public XinHeartVariant bottom() { return XinHeartVariant.INSTANCE; }

    @Override public CompositionLayoutT layout() { return this; }

    @Override public String glyph() { return "\u6155"; }

    @Override public PinyinSyllable pinyin() {
        return new PinyinSyllable(Initial.M, new Final(Head.U, Body.U, Tail.NONE), Tone.FOURTH);
    }

    @Override public int strokes() { return 0; }
    @Override public int radicalNo() { return 0; }
    @Override public String meaning() { return ""; }

    @Override public EtymologicalCategory etymology() {
        return new EtymologicalCategory.PhonoSemantic(XinHeartVariant.INSTANCE, MoNotMo.INSTANCE);
    }
}
