// AUTO-GENERATED by CatalogIteratorMain - do not edit by hand.
package kranji.common.perclass.promoted.m.u4;

import kranji.classification.EtymologicalCategory;
import kranji.common.perclass.promoted.m.o4.MoNotMo;
import kranji.pinyin.Body;
import kranji.pinyin.Final;
import kranji.pinyin.Head;
import kranji.pinyin.Initial;
import kranji.pinyin.PinyinSyllable;
import kranji.pinyin.Tail;
import kranji.pinyin.Tone;
import kranji.singular.nature.NatureElements;
import kranji.zi.ComposedZiT;
import kranji.zi.CompositionLayoutT;
import kranji.zi.TopBottomT;

public record MuDusk() implements ComposedZiT, TopBottomT<MoNotMo, NatureElements.Ri> {

    public static final MuDusk INSTANCE = new MuDusk();

    @Override public MoNotMo top() { return MoNotMo.INSTANCE; }
    @Override public NatureElements.Ri bottom() { return NatureElements.RI; }

    @Override public CompositionLayoutT layout() { return this; }

    @Override public String glyph() { return "\u66AE"; }

    @Override public PinyinSyllable pinyin() {
        return new PinyinSyllable(Initial.M, new Final(Head.U, Body.U, Tail.NONE), Tone.FOURTH);
    }

    @Override public int strokes() { return 0; }
    @Override public int radicalNo() { return 0; }
    @Override public String meaning() { return ""; }

    @Override public EtymologicalCategory etymology() {
        return new EtymologicalCategory.PhonoSemantic(NatureElements.RI, MoNotMo.INSTANCE);
    }
}
