// AUTO-GENERATED by PerclassGenerateMain - do not edit by hand.
package kranji.common.perclass.ch.ai1;

import kranji.classification.EtymologicalCategory;
import kranji.component.basic.BasicComponents;
import kranji.component.basic.HandFamily.TiShouPang;
import kranji.pinyin.Body;
import kranji.pinyin.Final;
import kranji.pinyin.Head;
import kranji.pinyin.Initial;
import kranji.pinyin.PinyinSyllable;
import kranji.pinyin.Tail;
import kranji.pinyin.Tone;
import kranji.singular.actions.ActionsAndStates;
import kranji.singular.actions.ActionsAndStates.Chi_Repel;
import kranji.zi.ComposedZiT;
import kranji.zi.CompositionLayoutT;
import kranji.zi.LeftRightT;

public record Chai() implements ComposedZiT, LeftRightT<TiShouPang, Chi_Repel> {

    public static final Chai INSTANCE = new Chai();

    @Override public TiShouPang left() { return BasicComponents.TI_SHOU_PANG; }
    @Override public Chi_Repel right() { return ActionsAndStates.CHI_REPEL; }

    @Override public CompositionLayoutT layout() { return this; }

    @Override public String glyph() { return "\u62C6"; }

    @Override public PinyinSyllable pinyin() {
        return new PinyinSyllable(Initial.CH, new Final(Head.OPEN, Body.A, Tail.VOWEL_I), Tone.FIRST);
    }

    @Override public int strokes() { return 8; }
    @Override public int radicalNo() { return 64; }
    @Override public String meaning() { return ""; }

    @Override public EtymologicalCategory etymology() {
        return new EtymologicalCategory.PhonoSemantic(BasicComponents.TI_SHOU_PANG, ActionsAndStates.CHI_REPEL);
    }
}
