// AUTO-GENERATED by PerclassGenerateMain - do not edit by hand.
package kranji.common.perclass.j.ie4;

import kranji.classification.EtymologicalCategory;
import kranji.pinyin.Body;
import kranji.pinyin.Final;
import kranji.pinyin.Head;
import kranji.pinyin.Initial;
import kranji.pinyin.PinyinSyllable;
import kranji.pinyin.Tail;
import kranji.pinyin.Tone;
import kranji.singular.radicals.RadicalComponents;
import kranji.singular.radicals.RadicalComponents.Gong_Clasp;
import kranji.singular.tools.ToolsAndVessels;
import kranji.singular.tools.ToolsAndVessels.Ge;
import kranji.zi.ComposedZiT;
import kranji.zi.CompositionLayoutT;
import kranji.zi.TopBottomT;

public record JieWarn() implements ComposedZiT, TopBottomT<Ge, Gong_Clasp> {

    public static final JieWarn INSTANCE = new JieWarn();

    @Override public Ge top() { return ToolsAndVessels.GE; }
    @Override public Gong_Clasp bottom() { return RadicalComponents.GONG_CLASP; }

    @Override public CompositionLayoutT layout() { return this; }

    @Override public String glyph() { return "\u6212"; }

    @Override public PinyinSyllable pinyin() {
        return new PinyinSyllable(Initial.J, new Final(Head.I, Body.E_CARON, Tail.NONE), Tone.FOURTH);
    }

    @Override public int strokes() { return 7; }
    @Override public int radicalNo() { return 62; }
    @Override public String meaning() { return ""; }

    @Override public EtymologicalCategory etymology() {
        return new EtymologicalCategory.CompoundIndicative("戈(weapon) + 廾(two hands) → guard/warn");
    }
}
