// AUTO-GENERATED by CatalogIteratorMain - do not edit by hand.
package kranji.common.perclass.promoted.zero.iang3;

import kranji.classification.EtymologicalCategory;
import kranji.common.perclass.promoted.j.iou3.JiuJiuAuto;
import kranji.common.perclass.promoted.zero.iang2.YangSheepVariantAtom;
import kranji.pinyin.Body;
import kranji.pinyin.Final;
import kranji.pinyin.Head;
import kranji.pinyin.Initial;
import kranji.pinyin.PinyinSyllable;
import kranji.pinyin.Tail;
import kranji.pinyin.Tone;
import kranji.zi.ComposedZiT;
import kranji.zi.CompositionLayoutT;
import kranji.zi.TopBottomT;

public record YangRaise() implements ComposedZiT, TopBottomT<YangSheepVariantAtom, JiuJiuAuto> {

    public static final YangRaise INSTANCE = new YangRaise();

    @Override public YangSheepVariantAtom top() { return YangSheepVariantAtom.INSTANCE; }
    @Override public JiuJiuAuto bottom() { return JiuJiuAuto.INSTANCE; }

    @Override public CompositionLayoutT layout() { return this; }

    @Override public String glyph() { return "\u517B"; }

    @Override public PinyinSyllable pinyin() {
        return new PinyinSyllable(Initial.ZERO, new Final(Head.I, Body.A, Tail.NG), Tone.THIRD);
    }

    @Override public int strokes() { return 0; }
    @Override public int radicalNo() { return 0; }
    @Override public String meaning() { return ""; }

    @Override public EtymologicalCategory etymology() {
        return new EtymologicalCategory.DerivativeCognate("");
    }
}
