// AUTO-GENERATED by kranji-codegen. Do not edit by hand.
package kranji.singular.body.zero;

import kranji.library.BasicSet;
import kranji.library.LibraryMember;
import kranji.zi.SingularZi;

public record Yu_Moment() implements LibraryMember<BasicSet>, SingularZi {
    public static final Yu_Moment INSTANCE = new Yu_Moment();

    @Override public String glyph() { return "\u81FE"; }
    @Override public String meaning() { return "hands pulling body"; }
    @Override public String pinyinText() { return "y\u00FA"; }
    @Override public int strokes() { return 8; }
    @Override public BasicSet library() { return BasicSet.INSTANCE; }
}
