// AUTO-GENERATED by CatalogIteratorMain - do not edit by hand.
package kranji.common.perclass.promoted.sh.ou4;

import kranji.classification.EtymologicalCategory;
import kranji.common.perclass.promoted.s.ou3.SouOld;
import kranji.component.basic.BasicComponents;
import kranji.component.basic.EnclosureFamily;
import kranji.pinyin.Body;
import kranji.pinyin.Final;
import kranji.pinyin.Head;
import kranji.pinyin.Initial;
import kranji.pinyin.PinyinSyllable;
import kranji.pinyin.Tail;
import kranji.pinyin.Tone;
import kranji.zi.ComposedZiT;
import kranji.zi.CompositionLayoutT;
import kranji.zi.SemiEnclosureUpperLeftT;

public record ShouThin() implements ComposedZiT, SemiEnclosureUpperLeftT<EnclosureFamily.BingZiPang, SouOld> {

    public static final ShouThin INSTANCE = new ShouThin();

    @Override public EnclosureFamily.BingZiPang wrapper() { return BasicComponents.BING_ZI_PANG; }
    @Override public SouOld content() { return SouOld.INSTANCE; }

    @Override public CompositionLayoutT layout() { return this; }

    @Override public String glyph() { return "\u7626"; }

    @Override public PinyinSyllable pinyin() {
        return new PinyinSyllable(Initial.SH, new Final(Head.OPEN, Body.O, Tail.VOWEL_U), Tone.FOURTH);
    }

    @Override public int strokes() { return 0; }
    @Override public int radicalNo() { return 0; }
    @Override public String meaning() { return ""; }

    @Override public EtymologicalCategory etymology() {
        return new EtymologicalCategory.PhonoSemantic(BasicComponents.BING_ZI_PANG, SouOld.INSTANCE);
    }
}
