// AUTO-GENERATED by PerclassGenerateMain - do not edit by hand.
package kranji.common.perclass.t.an1;

import kranji.classification.EtymologicalCategory;
import kranji.pinyin.Body;
import kranji.pinyin.Final;
import kranji.pinyin.Head;
import kranji.pinyin.Initial;
import kranji.pinyin.PinyinSyllable;
import kranji.pinyin.Tail;
import kranji.pinyin.Tone;
import kranji.singular.animals.Animals;
import kranji.singular.animals.Animals.Bei;
import kranji.singular.concepts.AbstractConcepts;
import kranji.singular.concepts.AbstractConcepts.Jin;
import kranji.zi.ComposedZiT;
import kranji.zi.CompositionLayoutT;
import kranji.zi.TopBottomT;

public record TanGreedy() implements ComposedZiT, TopBottomT<Jin, Bei> {

    public static final TanGreedy INSTANCE = new TanGreedy();

    @Override public Jin top() { return AbstractConcepts.JIN; }
    @Override public Bei bottom() { return Animals.BEI; }

    @Override public CompositionLayoutT layout() { return this; }

    @Override public String glyph() { return "\u8D2A"; }

    @Override public PinyinSyllable pinyin() {
        return new PinyinSyllable(Initial.T, new Final(Head.OPEN, Body.A, Tail.N), Tone.FIRST);
    }

    @Override public int strokes() { return 8; }
    @Override public int radicalNo() { return 154; }
    @Override public String meaning() { return ""; }

    @Override public EtymologicalCategory etymology() {
        return new EtymologicalCategory.PhonoSemantic(Animals.BEI, AbstractConcepts.JIN);
    }
}
