// AUTO-GENERATED by CatalogIteratorMain - do not edit by hand.
package kranji.common.perclass.promoted.j.iang3;

import kranji.classification.EtymologicalCategory;
import kranji.common.perclass.promoted.j.iang1.JiangJiangAuto;
import kranji.pinyin.Body;
import kranji.pinyin.Final;
import kranji.pinyin.Head;
import kranji.pinyin.Initial;
import kranji.pinyin.PinyinSyllable;
import kranji.pinyin.Tail;
import kranji.pinyin.Tone;
import kranji.singular.people.PeopleAndRoles;
import kranji.zi.ComposedZiT;
import kranji.zi.CompositionLayoutT;
import kranji.zi.TopBottomT;

public record JiangAward() implements ComposedZiT, TopBottomT<JiangJiangAuto, PeopleAndRoles.Da> {

    public static final JiangAward INSTANCE = new JiangAward();

    @Override public JiangJiangAuto top() { return JiangJiangAuto.INSTANCE; }
    @Override public PeopleAndRoles.Da bottom() { return PeopleAndRoles.DA; }

    @Override public CompositionLayoutT layout() { return this; }

    @Override public String glyph() { return "\u5956"; }

    @Override public PinyinSyllable pinyin() {
        return new PinyinSyllable(Initial.J, new Final(Head.I, Body.A, Tail.NG), Tone.THIRD);
    }

    @Override public int strokes() { return 0; }
    @Override public int radicalNo() { return 0; }
    @Override public String meaning() { return ""; }

    @Override public EtymologicalCategory etymology() {
        return new EtymologicalCategory.PhonoSemantic(PeopleAndRoles.DA, JiangJiangAuto.INSTANCE);
    }
}
