// AUTO-GENERATED by kranji-codegen. Do not edit by hand.
package kranji.singular.structures.c;

import kranji.library.BasicSet;
import kranji.library.LibraryMember;
import kranji.zi.SingularZi;

public record Cun_Inch() implements LibraryMember<BasicSet>, SingularZi {
    public static final Cun_Inch INSTANCE = new Cun_Inch();

    @Override public String glyph() { return "\u5BF8"; }
    @Override public String meaning() { return "inch"; }
    @Override public String pinyinText() { return "c\u00F9n"; }
    @Override public int strokes() { return 3; }
    @Override public BasicSet library() { return BasicSet.INSTANCE; }
}
