// AUTO-GENERATED by CatalogIteratorMain - do not edit by hand.
package kranji.common.perclass.promoted.j.ian1;

import kranji.classification.EtymologicalCategory;
import kranji.component.basic.BasicComponents;
import kranji.component.basic.FireFamily;
import kranji.pinyin.Body;
import kranji.pinyin.Final;
import kranji.pinyin.Head;
import kranji.pinyin.Initial;
import kranji.pinyin.PinyinSyllable;
import kranji.pinyin.Tail;
import kranji.pinyin.Tone;
import kranji.singular.space.SpaceAndDirection;
import kranji.zi.ComposedZiT;
import kranji.zi.CompositionLayoutT;
import kranji.zi.TopBottomT;

public record JianFry() implements ComposedZiT, TopBottomT<SpaceAndDirection.Qian_Front, FireFamily.SiDianDi> {

    public static final JianFry INSTANCE = new JianFry();

    @Override public SpaceAndDirection.Qian_Front top() { return SpaceAndDirection.QIAN_FRONT; }
    @Override public FireFamily.SiDianDi bottom() { return BasicComponents.SI_DIAN_DI; }

    @Override public CompositionLayoutT layout() { return this; }

    @Override public String glyph() { return "\u714E"; }

    @Override public PinyinSyllable pinyin() {
        return new PinyinSyllable(Initial.J, new Final(Head.I, Body.A, Tail.N), Tone.FIRST);
    }

    @Override public int strokes() { return 0; }
    @Override public int radicalNo() { return 0; }
    @Override public String meaning() { return ""; }

    @Override public EtymologicalCategory etymology() {
        return new EtymologicalCategory.PhonoSemantic(BasicComponents.SI_DIAN_DI, SpaceAndDirection.QIAN_FRONT);
    }
}
