// AUTO-GENERATED by PerclassGenerateMain - do not edit by hand.
package kranji.common.perclass.f.an1;

import kranji.classification.EtymologicalCategory;
import kranji.pinyin.Body;
import kranji.pinyin.Final;
import kranji.pinyin.Head;
import kranji.pinyin.Initial;
import kranji.pinyin.PinyinSyllable;
import kranji.pinyin.Tail;
import kranji.pinyin.Tone;
import kranji.singular.materials.Materials;
import kranji.singular.materials.Materials.Jin_Towel;
import kranji.singular.tools.ToolsAndVessels;
import kranji.singular.tools.ToolsAndVessels.Fan;
import kranji.zi.ComposedZiT;
import kranji.zi.CompositionLayoutT;
import kranji.zi.LeftRightT;

public record FanSail() implements ComposedZiT, LeftRightT<Jin_Towel, Fan> {

    public static final FanSail INSTANCE = new FanSail();

    @Override public Jin_Towel left() { return Materials.JIN_TOWEL; }
    @Override public Fan right() { return ToolsAndVessels.FAN; }

    @Override public CompositionLayoutT layout() { return this; }

    @Override public String glyph() { return "\u5E06"; }

    @Override public PinyinSyllable pinyin() {
        return new PinyinSyllable(Initial.F, new Final(Head.OPEN, Body.A, Tail.N), Tone.FIRST);
    }

    @Override public int strokes() { return 6; }
    @Override public int radicalNo() { return 50; }
    @Override public String meaning() { return ""; }

    @Override public EtymologicalCategory etymology() {
        return new EtymologicalCategory.PhonoSemantic(Materials.JIN_TOWEL, ToolsAndVessels.FAN);
    }
}
