// AUTO-GENERATED by kranji-codegen. Do not edit by hand.
package kranji.singular.radicals.n;

import kranji.library.BasicSet;
import kranji.library.LibraryMember;
import kranji.zi.SingularPart;

public record Niu_Left() implements LibraryMember<BasicSet>, SingularPart {
    public static final Niu_Left INSTANCE = new Niu_Left();

    @Override public String glyph() { return "\u725C"; }
    @Override public String meaning() { return "ox left radical"; }
    @Override public String pinyinText() { return "ni\u00FA"; }
    @Override public int strokes() { return 4; }
    @Override public BasicSet library() { return BasicSet.INSTANCE; }
}
