// AUTO-GENERATED by CatalogIteratorMain - do not edit by hand.
package kranji.common.perclass.promoted.d.ao3;

import kranji.classification.EtymologicalCategory;
import kranji.common.perclass.promoted.zero.iao3.YaoScoop;
import kranji.pinyin.Body;
import kranji.pinyin.Final;
import kranji.pinyin.Head;
import kranji.pinyin.Initial;
import kranji.pinyin.PinyinSyllable;
import kranji.pinyin.Tail;
import kranji.pinyin.Tone;
import kranji.singular.body.BodyParts;
import kranji.zi.ComposedZiT;
import kranji.zi.CompositionLayoutT;
import kranji.zi.LeftRightT;

public record DaoStamp() implements ComposedZiT, LeftRightT<BodyParts.Zu, YaoScoop> {

    public static final DaoStamp INSTANCE = new DaoStamp();

    @Override public BodyParts.Zu left() { return BodyParts.ZU; }
    @Override public YaoScoop right() { return YaoScoop.INSTANCE; }

    @Override public CompositionLayoutT layout() { return this; }

    @Override public String glyph() { return "\u8E48"; }

    @Override public PinyinSyllable pinyin() {
        return new PinyinSyllable(Initial.D, new Final(Head.OPEN, Body.A, Tail.VOWEL_U), Tone.THIRD);
    }

    @Override public int strokes() { return 0; }
    @Override public int radicalNo() { return 0; }
    @Override public String meaning() { return ""; }

    @Override public EtymologicalCategory etymology() {
        return new EtymologicalCategory.PhonoSemantic(BodyParts.ZU, YaoScoop.INSTANCE);
    }
}
