// AUTO-GENERATED by CatalogIteratorMain - do not edit by hand.
package kranji.common.perclass.promoted.zh.en1;

import kranji.classification.EtymologicalCategory;
import kranji.common.perclass.promoted.zh.en1.ZhenChaste;
import kranji.component.basic.BasicComponents;
import kranji.component.basic.PersonFamily;
import kranji.pinyin.Body;
import kranji.pinyin.Final;
import kranji.pinyin.Head;
import kranji.pinyin.Initial;
import kranji.pinyin.PinyinSyllable;
import kranji.pinyin.Tail;
import kranji.pinyin.Tone;
import kranji.zi.ComposedZiT;
import kranji.zi.CompositionLayoutT;
import kranji.zi.LeftRightT;

public record ZhenDetect() implements ComposedZiT, LeftRightT<PersonFamily.DanRenPang, ZhenChaste> {

    public static final ZhenDetect INSTANCE = new ZhenDetect();

    @Override public PersonFamily.DanRenPang left() { return BasicComponents.DAN_REN_PANG; }
    @Override public ZhenChaste right() { return ZhenChaste.INSTANCE; }

    @Override public CompositionLayoutT layout() { return this; }

    @Override public String glyph() { return "\u4FA6"; }

    @Override public PinyinSyllable pinyin() {
        return new PinyinSyllable(Initial.ZH, new Final(Head.OPEN, Body.E, Tail.N), Tone.FIRST);
    }

    @Override public int strokes() { return 0; }
    @Override public int radicalNo() { return 0; }
    @Override public String meaning() { return ""; }

    @Override public EtymologicalCategory etymology() {
        return new EtymologicalCategory.PhonoSemantic(BasicComponents.DAN_REN_PANG, ZhenChaste.INSTANCE);
    }
}
