// AUTO-GENERATED by PerclassGenerateMain - do not edit by hand.
package kranji.common.perclass.q.iao2;

import kranji.classification.EtymologicalCategory;
import kranji.component.basic.BasicComponents;
import kranji.component.basic.WoodFamily.Mu;
import kranji.pinyin.Body;
import kranji.pinyin.Final;
import kranji.pinyin.Head;
import kranji.pinyin.Initial;
import kranji.pinyin.PinyinSyllable;
import kranji.pinyin.Tail;
import kranji.pinyin.Tone;
import kranji.singular.unsure.UnsureSingulars;
import kranji.singular.unsure.UnsureSingulars.Qiao_Tall;
import kranji.zi.ComposedZiT;
import kranji.zi.CompositionLayoutT;
import kranji.zi.LeftRightT;

public record QiaoBridge() implements ComposedZiT, LeftRightT<Mu, Qiao_Tall> {

    public static final QiaoBridge INSTANCE = new QiaoBridge();

    @Override public Mu left() { return BasicComponents.MU; }
    @Override public Qiao_Tall right() { return UnsureSingulars.QIAO_TALL; }

    @Override public CompositionLayoutT layout() { return this; }

    @Override public String glyph() { return "\u6865"; }

    @Override public PinyinSyllable pinyin() {
        return new PinyinSyllable(Initial.Q, new Final(Head.I, Body.A, Tail.VOWEL_U), Tone.SECOND);
    }

    @Override public int strokes() { return 10; }
    @Override public int radicalNo() { return 75; }
    @Override public String meaning() { return ""; }

    @Override public EtymologicalCategory etymology() {
        return new EtymologicalCategory.PhonoSemantic(BasicComponents.MU, UnsureSingulars.QIAO_TALL);
    }
}
