// AUTO-GENERATED by PerclassGenerateMain - do not edit by hand.
package kranji.common.perclass.zero.uei4;

import kranji.classification.EtymologicalCategory;
import kranji.pinyin.Body;
import kranji.pinyin.Final;
import kranji.pinyin.Head;
import kranji.pinyin.Initial;
import kranji.pinyin.PinyinSyllable;
import kranji.pinyin.Tail;
import kranji.pinyin.Tone;
import kranji.singular.body.BodyParts;
import kranji.singular.body.BodyParts.Kou;
import kranji.singular.plants.PlantsAndAgriculture;
import kranji.singular.plants.PlantsAndAgriculture.Wei_Not;
import kranji.zi.ComposedZiT;
import kranji.zi.CompositionLayoutT;
import kranji.zi.LeftRightT;

public record WeiTaste() implements ComposedZiT, LeftRightT<Kou, Wei_Not> {

    public static final WeiTaste INSTANCE = new WeiTaste();

    @Override public Kou left() { return BodyParts.KOU; }
    @Override public Wei_Not right() { return PlantsAndAgriculture.WEI_NOT; }

    @Override public CompositionLayoutT layout() { return this; }

    @Override public String glyph() { return "\u5473"; }

    @Override public PinyinSyllable pinyin() {
        return new PinyinSyllable(Initial.ZERO, new Final(Head.U, Body.E, Tail.VOWEL_I), Tone.FOURTH);
    }

    @Override public int strokes() { return 8; }
    @Override public int radicalNo() { return 30; }
    @Override public String meaning() { return ""; }

    @Override public EtymologicalCategory etymology() {
        return new EtymologicalCategory.PhonoSemantic(BodyParts.KOU, PlantsAndAgriculture.WEI_NOT);
    }
}
