// AUTO-GENERATED by CatalogIteratorMain - do not edit by hand.
package kranji.common.perclass.promoted.t.eng2;

import kranji.classification.EtymologicalCategory;
import kranji.component.basic.BasicComponents;
import kranji.component.basic.EnclosureFamily;
import kranji.pinyin.Body;
import kranji.pinyin.Final;
import kranji.pinyin.Head;
import kranji.pinyin.Initial;
import kranji.pinyin.PinyinSyllable;
import kranji.pinyin.Tail;
import kranji.pinyin.Tone;
import kranji.singular.nature.NatureElements;
import kranji.zi.ComposedZiT;
import kranji.zi.CompositionLayoutT;
import kranji.zi.SemiEnclosureUpperLeftT;

public record TengPain() implements ComposedZiT, SemiEnclosureUpperLeftT<EnclosureFamily.BingZiPang, NatureElements.Dong_Winter> {

    public static final TengPain INSTANCE = new TengPain();

    @Override public EnclosureFamily.BingZiPang wrapper() { return BasicComponents.BING_ZI_PANG; }
    @Override public NatureElements.Dong_Winter content() { return NatureElements.DONG_WINTER; }

    @Override public CompositionLayoutT layout() { return this; }

    @Override public String glyph() { return "\u75BC"; }

    @Override public PinyinSyllable pinyin() {
        return new PinyinSyllable(Initial.T, new Final(Head.OPEN, Body.E, Tail.NG), Tone.SECOND);
    }

    @Override public int strokes() { return 0; }
    @Override public int radicalNo() { return 0; }
    @Override public String meaning() { return ""; }

    @Override public EtymologicalCategory etymology() {
        return new EtymologicalCategory.PhonoSemantic(BasicComponents.BING_ZI_PANG, NatureElements.DONG_WINTER);
    }
}
