// AUTO-GENERATED by PerclassGenerateMain - do not edit by hand.
package kranji.common.perclass.l.a1;

import kranji.classification.EtymologicalCategory;
import kranji.component.basic.BasicComponents;
import kranji.component.basic.HandFamily.TiShouPang;
import kranji.pinyin.Body;
import kranji.pinyin.Final;
import kranji.pinyin.Head;
import kranji.pinyin.Initial;
import kranji.pinyin.PinyinSyllable;
import kranji.pinyin.Tail;
import kranji.pinyin.Tone;
import kranji.singular.actions.ActionsAndStates;
import kranji.singular.actions.ActionsAndStates.Li_Stand;
import kranji.zi.ComposedZiT;
import kranji.zi.CompositionLayoutT;
import kranji.zi.LeftRightT;

public record LaPull() implements ComposedZiT, LeftRightT<TiShouPang, Li_Stand> {

    public static final LaPull INSTANCE = new LaPull();

    @Override public TiShouPang left() { return BasicComponents.TI_SHOU_PANG; }
    @Override public Li_Stand right() { return ActionsAndStates.LI_STAND; }

    @Override public CompositionLayoutT layout() { return this; }

    @Override public String glyph() { return "\u62C9"; }

    @Override public PinyinSyllable pinyin() {
        return new PinyinSyllable(Initial.L, new Final(Head.OPEN, Body.A, Tail.NONE), Tone.FIRST);
    }

    @Override public int strokes() { return 8; }
    @Override public int radicalNo() { return 64; }
    @Override public String meaning() { return ""; }

    @Override public EtymologicalCategory etymology() {
        return new EtymologicalCategory.PhonoSemantic(BasicComponents.TI_SHOU_PANG, ActionsAndStates.LI_STAND);
    }
}
