// AUTO-GENERATED by PerclassGenerateMain - do not edit by hand.
package kranji.common.perclass.d.iao4;

import kranji.classification.EtymologicalCategory;
import kranji.component.basic.BasicComponents;
import kranji.component.basic.MetalFamily.JinZiPang;
import kranji.pinyin.Body;
import kranji.pinyin.Final;
import kranji.pinyin.Head;
import kranji.pinyin.Initial;
import kranji.pinyin.PinyinSyllable;
import kranji.pinyin.Tail;
import kranji.pinyin.Tone;
import kranji.singular.tools.ToolsAndVessels;
import kranji.singular.tools.ToolsAndVessels.Shao;
import kranji.zi.ComposedZiT;
import kranji.zi.CompositionLayoutT;
import kranji.zi.LeftRightT;

public record DiaoFish() implements ComposedZiT, LeftRightT<JinZiPang, Shao> {

    public static final DiaoFish INSTANCE = new DiaoFish();

    @Override public JinZiPang left() { return BasicComponents.JIN_ZI_PANG; }
    @Override public Shao right() { return ToolsAndVessels.SHAO; }

    @Override public CompositionLayoutT layout() { return this; }

    @Override public String glyph() { return "\u9493"; }

    @Override public PinyinSyllable pinyin() {
        return new PinyinSyllable(Initial.D, new Final(Head.I, Body.A, Tail.VOWEL_U), Tone.FOURTH);
    }

    @Override public int strokes() { return 8; }
    @Override public int radicalNo() { return 167; }
    @Override public String meaning() { return ""; }

    @Override public EtymologicalCategory etymology() {
        return new EtymologicalCategory.PhonoSemantic(BasicComponents.JIN_ZI_PANG, ToolsAndVessels.SHAO);
    }
}
