// AUTO-GENERATED by PerclassGenerateMain - do not edit by hand.
package kranji.common.perclass.l.ao2;

import kranji.classification.EtymologicalCategory;
import kranji.component.basic.BasicComponents;
import kranji.component.basic.EnclosureFamily.BaoZiTou;
import kranji.component.basic.PlantFamily.CaoZiTou;
import kranji.pinyin.Body;
import kranji.pinyin.Final;
import kranji.pinyin.Head;
import kranji.pinyin.Initial;
import kranji.pinyin.PinyinSyllable;
import kranji.pinyin.Tail;
import kranji.pinyin.Tone;
import kranji.singular.tools.ToolsAndVessels;
import kranji.singular.tools.ToolsAndVessels.Li_Plow;
import kranji.zi.ComposedZiT;
import kranji.zi.CompositionLayoutT;
import kranji.zi.TopMiddleBottomT;

public record Lao() implements ComposedZiT, TopMiddleBottomT<CaoZiTou, BaoZiTou, Li_Plow> {

    public static final Lao INSTANCE = new Lao();

    @Override public CaoZiTou top() { return BasicComponents.CAO_ZI_TOU; }
    @Override public BaoZiTou middle() { return BasicComponents.BAO_ZI_TOU; }
    @Override public Li_Plow bottom() { return ToolsAndVessels.LI_PLOW; }

    @Override public CompositionLayoutT layout() { return this; }

    @Override public String glyph() { return "\u52B3"; }

    @Override public PinyinSyllable pinyin() {
        return new PinyinSyllable(Initial.L, new Final(Head.OPEN, Body.A, Tail.VOWEL_U), Tone.SECOND);
    }

    @Override public int strokes() { return 7; }
    @Override public int radicalNo() { return 19; }
    @Override public String meaning() { return ""; }

    @Override public EtymologicalCategory etymology() {
        return new EtymologicalCategory.CompoundIndicative("艹(plants) + 冖(cover) + 力(strength) → toil");
    }
}
