// AUTO-GENERATED by CatalogIteratorMain - do not edit by hand.
package kranji.common.perclass.promoted.j.ve2;

import kranji.classification.EtymologicalCategory;
import kranji.pinyin.Body;
import kranji.pinyin.Final;
import kranji.pinyin.Head;
import kranji.pinyin.Initial;
import kranji.pinyin.PinyinSyllable;
import kranji.pinyin.Tail;
import kranji.pinyin.Tone;
import kranji.singular.people.PeopleAndRoles;
import kranji.zi.ComposedZiT;
import kranji.zi.CompositionLayoutT;
import kranji.zi.LeftRightT;

public record JueJadePairAtom() implements ComposedZiT, LeftRightT<PeopleAndRoles.Wang, PeopleAndRoles.Wang> {

    public static final JueJadePairAtom INSTANCE = new JueJadePairAtom();

    @Override public PeopleAndRoles.Wang left() { return PeopleAndRoles.WANG; }
    @Override public PeopleAndRoles.Wang right() { return PeopleAndRoles.WANG; }

    @Override public CompositionLayoutT layout() { return this; }

    @Override public String glyph() { return "\u73A8"; }

    @Override public PinyinSyllable pinyin() {
        return new PinyinSyllable(Initial.J, new Final(Head.V, Body.E_CARON, Tail.NONE), Tone.SECOND);
    }

    @Override public int strokes() { return 0; }
    @Override public int radicalNo() { return 0; }
    @Override public String meaning() { return ""; }

    @Override public EtymologicalCategory etymology() {
        return new EtymologicalCategory.CompoundIndicative("");
    }
}
