// AUTO-GENERATED by kranji-codegen. Do not edit by hand.
package kranji.singular.radicals.q;

import kranji.library.BasicSet;
import kranji.library.LibraryMember;
import kranji.zi.SingularPart;

public record Qian_Owe() implements LibraryMember<BasicSet>, SingularPart {
    public static final Qian_Owe INSTANCE = new Qian_Owe();

    @Override public String glyph() { return "\u6B20"; }
    @Override public String meaning() { return "owe, lack, yawn"; }
    @Override public String pinyinText() { return "qi\u00E0n"; }
    @Override public int strokes() { return 4; }
    @Override public BasicSet library() { return BasicSet.INSTANCE; }
}
