// AUTO-GENERATED by PerclassGenerateMain - do not edit by hand.
package kranji.common.perclass.sh.i1;

import kranji.classification.EtymologicalCategory;
import kranji.common.perclass.s.i4.SiTemple;
import kranji.component.basic.BasicComponents;
import kranji.component.basic.SpeechFamily.YanZiPang;
import kranji.pinyin.Body;
import kranji.pinyin.Final;
import kranji.pinyin.Head;
import kranji.pinyin.Initial;
import kranji.pinyin.PinyinSyllable;
import kranji.pinyin.Tail;
import kranji.pinyin.Tone;
import kranji.zi.ComposedZiT;
import kranji.zi.CompositionLayoutT;
import kranji.zi.LeftRightT;

public record ShiPoetry() implements ComposedZiT, LeftRightT<YanZiPang, SiTemple> {

    public static final ShiPoetry INSTANCE = new ShiPoetry();

    @Override public YanZiPang left() { return BasicComponents.YAN_ZI_PANG; }
    @Override public SiTemple right() { return SiTemple.INSTANCE; }

    @Override public CompositionLayoutT layout() { return this; }

    @Override public String glyph() { return "\u8BD7"; }

    @Override public PinyinSyllable pinyin() {
        return new PinyinSyllable(Initial.SH, new Final(Head.OPEN, Body.NULL, Tail.NONE), Tone.FIRST);
    }

    @Override public int strokes() { return 8; }
    @Override public int radicalNo() { return 149; }
    @Override public String meaning() { return ""; }

    @Override public EtymologicalCategory etymology() {
        return new EtymologicalCategory.PhonoSemantic(BasicComponents.YAN_ZI_PANG, SiTemple.INSTANCE);
    }
}
