// AUTO-GENERATED by PerclassGenerateMain - do not edit by hand.
package kranji.common.perclass.zero.i2;

import kranji.classification.EtymologicalCategory;
import kranji.component.basic.BasicComponents;
import kranji.component.basic.PersonFamily.DanRenPang;
import kranji.pinyin.Body;
import kranji.pinyin.Final;
import kranji.pinyin.Head;
import kranji.pinyin.Initial;
import kranji.pinyin.PinyinSyllable;
import kranji.pinyin.Tail;
import kranji.pinyin.Tone;
import kranji.singular.concepts.AbstractConcepts;
import kranji.singular.concepts.AbstractConcepts.Yi_Meaning;
import kranji.zi.ComposedZiT;
import kranji.zi.CompositionLayoutT;
import kranji.zi.LeftRightT;

public record YiCeremony() implements ComposedZiT, LeftRightT<DanRenPang, Yi_Meaning> {

    public static final YiCeremony INSTANCE = new YiCeremony();

    @Override public DanRenPang left() { return BasicComponents.DAN_REN_PANG; }
    @Override public Yi_Meaning right() { return AbstractConcepts.YI_MEANING; }

    @Override public CompositionLayoutT layout() { return this; }

    @Override public String glyph() { return "\u4EEA"; }

    @Override public PinyinSyllable pinyin() {
        return new PinyinSyllable(Initial.ZERO, new Final(Head.OPEN, Body.I, Tail.NONE), Tone.SECOND);
    }

    @Override public int strokes() { return 5; }
    @Override public int radicalNo() { return 9; }
    @Override public String meaning() { return ""; }

    @Override public EtymologicalCategory etymology() {
        return new EtymologicalCategory.PhonoSemantic(BasicComponents.DAN_REN_PANG, AbstractConcepts.YI_MEANING);
    }
}
