// AUTO-GENERATED by CatalogIteratorMain - do not edit by hand.
package kranji.common.perclass.promoted.sh.u3;

import kranji.pinyin.Body;
import kranji.pinyin.Final;
import kranji.pinyin.Head;
import kranji.pinyin.Initial;
import kranji.pinyin.PinyinSyllable;
import kranji.pinyin.Tail;
import kranji.pinyin.Tone;
import kranji.zi.SingularZi;

public record ShuShu() implements SingularZi {

    public static final ShuShu INSTANCE = new ShuShu();

    @Override public String glyph() { return "\u8700"; }

    @Override public PinyinSyllable pinyin() {
        return new PinyinSyllable(Initial.SH, new Final(Head.U, Body.U, Tail.NONE), Tone.THIRD);
    }

    @Override public boolean unsure() { return true; }
}
