// AUTO-GENERATED by Depth2GenerateMain - do not edit by hand.
package kranji.common.depth2.p;

import kranji.classification.EtymologicalCategory.*;
import kranji.pinyin.Body;
import kranji.pinyin.Final;
import kranji.pinyin.Head;
import kranji.pinyin.Initial;
import kranji.pinyin.PinyinSyllable;
import kranji.pinyin.Tail;
import kranji.pinyin.Tone;
import kranji.singular.animals.Animals;
import kranji.zi.ComposedPart;
import kranji.zi.ComposedZi;
import kranji.zi.CompositionLayout.*;
import kranji.zi.SingularPart;
import kranji.zi.ZiChar;
import java.util.List;

public final class In2 {

    private In2() {}

    public static final ComposedZi PIN_POOR = new ComposedZi(
            new ZiChar.Unicode("\u8D2B"),
            new PinyinSyllable(Initial.P, new Final(Head.OPEN, Body.I, Tail.N), Tone.SECOND),
            8, 154, "",
            new TopBottom(kranji.common.depth1.f.En1.FEN.structure(), Animals.BEI),
            new PhonoSemantic(Animals.BEI, kranji.common.depth1.f.En1.FEN.structure()));

    public static final List<ComposedZi> ALL = List.of(
            PIN_POOR);
}
