// AUTO-GENERATED by PerclassGenerateMain - do not edit by hand.
package kranji.common.perclass.n.i3;

import kranji.classification.EtymologicalCategory;
import kranji.common.perclass.zero.er3.ErYouArchaic;
import kranji.component.basic.BasicComponents;
import kranji.component.basic.PersonFamily.DanRenPang;
import kranji.pinyin.Body;
import kranji.pinyin.Final;
import kranji.pinyin.Head;
import kranji.pinyin.Initial;
import kranji.pinyin.PinyinSyllable;
import kranji.pinyin.Tail;
import kranji.pinyin.Tone;
import kranji.zi.ComposedZiT;
import kranji.zi.CompositionLayoutT;
import kranji.zi.LeftRightT;

public record NiYou() implements ComposedZiT, LeftRightT<DanRenPang, ErYouArchaic> {

    public static final NiYou INSTANCE = new NiYou();

    @Override public DanRenPang left() { return BasicComponents.DAN_REN_PANG; }
    @Override public ErYouArchaic right() { return ErYouArchaic.INSTANCE; }

    @Override public CompositionLayoutT layout() { return this; }

    @Override public String glyph() { return "\u4F60"; }

    @Override public PinyinSyllable pinyin() {
        return new PinyinSyllable(Initial.N, new Final(Head.OPEN, Body.I, Tail.NONE), Tone.THIRD);
    }

    @Override public int strokes() { return 7; }
    @Override public int radicalNo() { return 9; }
    @Override public String meaning() { return ""; }

    @Override public EtymologicalCategory etymology() {
        return new EtymologicalCategory.PhonoSemantic(BasicComponents.DAN_REN_PANG, ErYouArchaic.INSTANCE);
    }
}
