// AUTO-GENERATED by PerclassGenerateMain - do not edit by hand.
package kranji.common.perclass.k.uai4;

import kranji.classification.EtymologicalCategory;
import kranji.common.perclass.k.uai4.KuaiFast;
import kranji.pinyin.Body;
import kranji.pinyin.Final;
import kranji.pinyin.Head;
import kranji.pinyin.Initial;
import kranji.pinyin.PinyinSyllable;
import kranji.pinyin.Tail;
import kranji.pinyin.Tone;
import kranji.singular.radicals.RadicalComponents;
import kranji.singular.radicals.RadicalComponents.Zhu_Bamboo;
import kranji.zi.ComposedZiT;
import kranji.zi.CompositionLayoutT;
import kranji.zi.TopBottomT;

public record KuaiChopstick() implements ComposedZiT, TopBottomT<Zhu_Bamboo, KuaiFast> {

    public static final KuaiChopstick INSTANCE = new KuaiChopstick();

    @Override public Zhu_Bamboo top() { return RadicalComponents.ZHU_BAMBOO; }
    @Override public KuaiFast bottom() { return KuaiFast.INSTANCE; }

    @Override public CompositionLayoutT layout() { return this; }

    @Override public String glyph() { return "\u7B77"; }

    @Override public PinyinSyllable pinyin() {
        return new PinyinSyllable(Initial.K, new Final(Head.U, Body.A, Tail.VOWEL_I), Tone.FOURTH);
    }

    @Override public int strokes() { return 13; }
    @Override public int radicalNo() { return 118; }
    @Override public String meaning() { return ""; }

    @Override public EtymologicalCategory etymology() {
        return new EtymologicalCategory.PhonoSemantic(RadicalComponents.ZHU_BAMBOO, KuaiFast.INSTANCE);
    }
}
