// AUTO-GENERATED by PerclassGenerateMain - do not edit by hand.
package kranji.common.perclass.r.an2;

import kranji.classification.EtymologicalCategory;
import kranji.component.basic.BasicComponents;
import kranji.component.basic.FireFamily.SiDianDi;
import kranji.pinyin.Body;
import kranji.pinyin.Final;
import kranji.pinyin.Head;
import kranji.pinyin.Initial;
import kranji.pinyin.PinyinSyllable;
import kranji.pinyin.Tail;
import kranji.pinyin.Tone;
import kranji.singular.animals.Animals;
import kranji.singular.animals.Animals.Quan;
import kranji.singular.nature.NatureElements;
import kranji.singular.nature.NatureElements.Yue;
import kranji.zi.ComposedZiT;
import kranji.zi.CompositionLayoutT;
import kranji.zi.LeftRightPartT;
import kranji.zi.TopBottomT;

public record RanSo() implements ComposedZiT, TopBottomT<LeftRightPartT<Yue, Quan>, SiDianDi> {

    public static final RanSo INSTANCE = new RanSo();

    @Override public LeftRightPartT<Yue, Quan> top() { return new LeftRightPartT<>(NatureElements.YUE, Animals.QUAN); }
    @Override public SiDianDi bottom() { return BasicComponents.SI_DIAN_DI; }

    @Override public CompositionLayoutT layout() { return this; }

    @Override public String glyph() { return "\u7136"; }

    @Override public PinyinSyllable pinyin() {
        return new PinyinSyllable(Initial.R, new Final(Head.OPEN, Body.A, Tail.N), Tone.SECOND);
    }

    @Override public int strokes() { return 12; }
    @Override public int radicalNo() { return 86; }
    @Override public String meaning() { return ""; }

    @Override public EtymologicalCategory etymology() {
        return new EtymologicalCategory.CompoundIndicative("月(肉, meat) + 犬(dog) + 灬(fire) → burn (original sense); loaned to mean 'thus, so'");
    }
}
