// AUTO-GENERATED by PerclassGenerateMain - do not edit by hand.
package kranji.common.perclass.q.i3;

import kranji.classification.EtymologicalCategory;
import kranji.pinyin.Body;
import kranji.pinyin.Final;
import kranji.pinyin.Head;
import kranji.pinyin.Initial;
import kranji.pinyin.PinyinSyllable;
import kranji.pinyin.Tail;
import kranji.pinyin.Tone;
import kranji.singular.actions.ActionsAndStates;
import kranji.singular.actions.ActionsAndStates.Zhi_Stop;
import kranji.singular.people.PeopleAndRoles;
import kranji.singular.people.PeopleAndRoles.Ren;
import kranji.zi.ComposedZiT;
import kranji.zi.CompositionLayoutT;
import kranji.zi.TopBottomT;

public record QiRise() implements ComposedZiT, TopBottomT<Ren, Zhi_Stop> {

    public static final QiRise INSTANCE = new QiRise();

    @Override public Ren top() { return PeopleAndRoles.REN; }
    @Override public Zhi_Stop bottom() { return ActionsAndStates.ZHI_STOP; }

    @Override public CompositionLayoutT layout() { return this; }

    @Override public String glyph() { return "\u4F01"; }

    @Override public PinyinSyllable pinyin() {
        return new PinyinSyllable(Initial.Q, new Final(Head.OPEN, Body.I, Tail.NONE), Tone.THIRD);
    }

    @Override public int strokes() { return 6; }
    @Override public int radicalNo() { return 9; }
    @Override public String meaning() { return ""; }

    @Override public EtymologicalCategory etymology() {
        return new EtymologicalCategory.CompoundIndicative("人(person) + 止(foot) → standing on tiptoes, aspire");
    }
}
