// AUTO-GENERATED by PerclassGenerateMain - do not edit by hand.
package kranji.common.perclass.p.an2;

import kranji.classification.EtymologicalCategory;
import kranji.pinyin.Body;
import kranji.pinyin.Final;
import kranji.pinyin.Head;
import kranji.pinyin.Initial;
import kranji.pinyin.PinyinSyllable;
import kranji.pinyin.Tail;
import kranji.pinyin.Tone;
import kranji.singular.tools.ToolsAndVessels;
import kranji.singular.tools.ToolsAndVessels.Min;
import kranji.singular.tools.ToolsAndVessels.Zhou;
import kranji.zi.ComposedZiT;
import kranji.zi.CompositionLayoutT;
import kranji.zi.TopBottomT;

public record PanPlate() implements ComposedZiT, TopBottomT<Zhou, Min> {

    public static final PanPlate INSTANCE = new PanPlate();

    @Override public Zhou top() { return ToolsAndVessels.ZHOU; }
    @Override public Min bottom() { return ToolsAndVessels.MIN; }

    @Override public CompositionLayoutT layout() { return this; }

    @Override public String glyph() { return "\u76D8"; }

    @Override public PinyinSyllable pinyin() {
        return new PinyinSyllable(Initial.P, new Final(Head.OPEN, Body.A, Tail.N), Tone.SECOND);
    }

    @Override public int strokes() { return 11; }
    @Override public int radicalNo() { return 108; }
    @Override public String meaning() { return ""; }

    @Override public EtymologicalCategory etymology() {
        return new EtymologicalCategory.PhonoSemantic(ToolsAndVessels.MIN, ToolsAndVessels.ZHOU);
    }
}
