// AUTO-GENERATED by kranji-codegen. Do not edit by hand.
package kranji.singular.nature.zero;

import kranji.library.BasicSet;
import kranji.library.LibraryMember;
import kranji.zi.SingularZi;

public record Ye_Night() implements LibraryMember<BasicSet>, SingularZi {
    public static final Ye_Night INSTANCE = new Ye_Night();

    @Override public String glyph() { return "\u591C"; }
    @Override public String meaning() { return "night"; }
    @Override public String pinyinText() { return "y\u00E8"; }
    @Override public int strokes() { return 8; }
    @Override public BasicSet library() { return BasicSet.INSTANCE; }
}
