// AUTO-GENERATED by kranji-codegen. Do not edit by hand.
package kranji.singular.nature.zero;

import kranji.library.BasicSet;
import kranji.library.LibraryMember;
import kranji.zi.SingularZi;

public record Yu() implements LibraryMember<BasicSet>, SingularZi {
    public static final Yu INSTANCE = new Yu();

    @Override public String glyph() { return "\u96E8"; }
    @Override public String meaning() { return "rain"; }
    @Override public String pinyinText() { return "y\u01D4"; }
    @Override public int strokes() { return 8; }
    @Override public BasicSet library() { return BasicSet.INSTANCE; }
}
