// AUTO-GENERATED by kranji-codegen. Do not edit by hand.
package kranji.singular.nature.zero;

import kranji.library.BasicSet;
import kranji.library.LibraryMember;
import kranji.zi.SingularZi;

public record Yun() implements LibraryMember<BasicSet>, SingularZi {
    public static final Yun INSTANCE = new Yun();

    @Override public String glyph() { return "\u4E91"; }
    @Override public String meaning() { return "cloud"; }
    @Override public String pinyinText() { return "y\u00FAn"; }
    @Override public int strokes() { return 4; }
    @Override public BasicSet library() { return BasicSet.INSTANCE; }
}
