// AUTO-GENERATED by CatalogIteratorMain - do not edit by hand.
package kranji.common.perclass.promoted.ch.ou2;

import kranji.classification.EtymologicalCategory;
import kranji.pinyin.Body;
import kranji.pinyin.Final;
import kranji.pinyin.Head;
import kranji.pinyin.Initial;
import kranji.pinyin.PinyinSyllable;
import kranji.pinyin.Tail;
import kranji.pinyin.Tone;
import kranji.singular.nature.NatureElements;
import kranji.singular.plants.PlantsAndAgriculture;
import kranji.zi.ComposedZiT;
import kranji.zi.CompositionLayoutT;
import kranji.zi.LeftRightT;

public record ChouDense() implements ComposedZiT, LeftRightT<PlantsAndAgriculture.He, NatureElements.Zhou> {

    public static final ChouDense INSTANCE = new ChouDense();

    @Override public PlantsAndAgriculture.He left() { return PlantsAndAgriculture.HE; }
    @Override public NatureElements.Zhou right() { return NatureElements.ZHOU; }

    @Override public CompositionLayoutT layout() { return this; }

    @Override public String glyph() { return "\u7A20"; }

    @Override public PinyinSyllable pinyin() {
        return new PinyinSyllable(Initial.CH, new Final(Head.OPEN, Body.O, Tail.VOWEL_U), Tone.SECOND);
    }

    @Override public int strokes() { return 0; }
    @Override public int radicalNo() { return 0; }
    @Override public String meaning() { return ""; }

    @Override public EtymologicalCategory etymology() {
        return new EtymologicalCategory.PhonoSemantic(PlantsAndAgriculture.HE, NatureElements.ZHOU);
    }
}
