// AUTO-GENERATED by CatalogIteratorMain - do not edit by hand.
package kranji.common.perclass.promoted.ch.ou2;

import kranji.classification.EtymologicalCategory;
import kranji.pinyin.Body;
import kranji.pinyin.Final;
import kranji.pinyin.Head;
import kranji.pinyin.Initial;
import kranji.pinyin.PinyinSyllable;
import kranji.pinyin.Tail;
import kranji.pinyin.Tone;
import kranji.singular.concepts.AbstractConcepts;
import kranji.singular.radicals.RadicalComponents;
import kranji.zi.ComposedZiT;
import kranji.zi.CompositionLayoutT;
import kranji.zi.TopBottomT;

public record ChouPlan() implements ComposedZiT, TopBottomT<RadicalComponents.Zhu_Bamboo, AbstractConcepts.Shou_Long> {

    public static final ChouPlan INSTANCE = new ChouPlan();

    @Override public RadicalComponents.Zhu_Bamboo top() { return RadicalComponents.ZHU_BAMBOO; }
    @Override public AbstractConcepts.Shou_Long bottom() { return AbstractConcepts.SHOU_LONG; }

    @Override public CompositionLayoutT layout() { return this; }

    @Override public String glyph() { return "\u7B79"; }

    @Override public PinyinSyllable pinyin() {
        return new PinyinSyllable(Initial.CH, new Final(Head.OPEN, Body.O, Tail.VOWEL_U), Tone.SECOND);
    }

    @Override public int strokes() { return 0; }
    @Override public int radicalNo() { return 0; }
    @Override public String meaning() { return ""; }

    @Override public EtymologicalCategory etymology() {
        return new EtymologicalCategory.PhonoSemantic(RadicalComponents.ZHU_BAMBOO, AbstractConcepts.SHOU_LONG);
    }
}
