// AUTO-GENERATED by CatalogIteratorMain - do not edit by hand.
package kranji.common.perclass.promoted.x.ven2;

import kranji.classification.EtymologicalCategory;
import kranji.common.perclass.promoted.ch.uan1.ChuanChuanAuto;
import kranji.component.basic.BasicComponents;
import kranji.component.basic.MovementFamily;
import kranji.pinyin.Body;
import kranji.pinyin.Final;
import kranji.pinyin.Head;
import kranji.pinyin.Initial;
import kranji.pinyin.PinyinSyllable;
import kranji.pinyin.Tail;
import kranji.pinyin.Tone;
import kranji.zi.ComposedZiT;
import kranji.zi.CompositionLayoutT;
import kranji.zi.SemiEnclosureBottomLeftT;

public record XunPatrol() implements ComposedZiT, SemiEnclosureBottomLeftT<MovementFamily.ZouZhiDi, ChuanChuanAuto> {

    public static final XunPatrol INSTANCE = new XunPatrol();

    @Override public MovementFamily.ZouZhiDi wrapper() { return BasicComponents.ZOU_ZHI_DI; }
    @Override public ChuanChuanAuto content() { return ChuanChuanAuto.INSTANCE; }

    @Override public CompositionLayoutT layout() { return this; }

    @Override public String glyph() { return "\u5DE1"; }

    @Override public PinyinSyllable pinyin() {
        return new PinyinSyllable(Initial.X, new Final(Head.V, Body.E, Tail.N), Tone.SECOND);
    }

    @Override public int strokes() { return 0; }
    @Override public int radicalNo() { return 0; }
    @Override public String meaning() { return ""; }

    @Override public EtymologicalCategory etymology() {
        return new EtymologicalCategory.PhonoSemantic(BasicComponents.ZOU_ZHI_DI, ChuanChuanAuto.INSTANCE);
    }
}
