// AUTO-GENERATED by CatalogIteratorMain - do not edit by hand.
package kranji.common.perclass.promoted.x.ven2;

import kranji.classification.EtymologicalCategory;
import kranji.pinyin.Body;
import kranji.pinyin.Final;
import kranji.pinyin.Head;
import kranji.pinyin.Initial;
import kranji.pinyin.PinyinSyllable;
import kranji.pinyin.Tail;
import kranji.pinyin.Tone;
import kranji.singular.radicals.RadicalComponents;
import kranji.singular.structures.Structures;
import kranji.zi.ComposedZiT;
import kranji.zi.CompositionLayoutT;
import kranji.zi.TopBottomT;

public record XunSeek() implements ComposedZiT, TopBottomT<RadicalComponents.Ji_Snout, Structures.Cun_Inch> {

    public static final XunSeek INSTANCE = new XunSeek();

    @Override public RadicalComponents.Ji_Snout top() { return RadicalComponents.JI_SNOUT; }
    @Override public Structures.Cun_Inch bottom() { return Structures.CUN_INCH; }

    @Override public CompositionLayoutT layout() { return this; }

    @Override public String glyph() { return "\u5BFB"; }

    @Override public PinyinSyllable pinyin() {
        return new PinyinSyllable(Initial.X, new Final(Head.V, Body.E, Tail.N), Tone.SECOND);
    }

    @Override public int strokes() { return 0; }
    @Override public int radicalNo() { return 0; }
    @Override public String meaning() { return ""; }

    @Override public EtymologicalCategory etymology() {
        return new EtymologicalCategory.DerivativeCognate("");
    }
}
