// AUTO-GENERATED by CatalogIteratorMain - do not edit by hand.
package kranji.common.perclass.promoted.zero.uei1;

import kranji.classification.EtymologicalCategory;
import kranji.common.perclass.promoted.x.v1.XuXuAuto;
import kranji.pinyin.Body;
import kranji.pinyin.Final;
import kranji.pinyin.Head;
import kranji.pinyin.Initial;
import kranji.pinyin.PinyinSyllable;
import kranji.pinyin.Tail;
import kranji.pinyin.Tone;
import kranji.singular.people.PeopleAndRoles;
import kranji.zi.ComposedZiT;
import kranji.zi.CompositionLayoutT;
import kranji.zi.SemiEnclosureUpperLeftT;

public record WeiPower() implements ComposedZiT, SemiEnclosureUpperLeftT<XuXuAuto, PeopleAndRoles.Nv> {

    public static final WeiPower INSTANCE = new WeiPower();

    @Override public XuXuAuto wrapper() { return XuXuAuto.INSTANCE; }
    @Override public PeopleAndRoles.Nv content() { return PeopleAndRoles.NV; }

    @Override public CompositionLayoutT layout() { return this; }

    @Override public String glyph() { return "\u5A01"; }

    @Override public PinyinSyllable pinyin() {
        return new PinyinSyllable(Initial.ZERO, new Final(Head.U, Body.E, Tail.VOWEL_I), Tone.FIRST);
    }

    @Override public int strokes() { return 0; }
    @Override public int radicalNo() { return 0; }
    @Override public String meaning() { return ""; }

    @Override public EtymologicalCategory etymology() {
        return new EtymologicalCategory.DerivativeCognate("");
    }
}
