// AUTO-GENERATED by CatalogIteratorMain - do not edit by hand.
package kranji.common.perclass.promoted.z.an4;

import kranji.classification.EtymologicalCategory;
import kranji.common.perclass.zh.an3.ZhanChop;
import kranji.pinyin.Body;
import kranji.pinyin.Final;
import kranji.pinyin.Head;
import kranji.pinyin.Initial;
import kranji.pinyin.PinyinSyllable;
import kranji.pinyin.Tail;
import kranji.pinyin.Tone;
import kranji.singular.nature.NatureElements;
import kranji.zi.ComposedZiT;
import kranji.zi.CompositionLayoutT;
import kranji.zi.TopBottomT;

public record ZanBrief() implements ComposedZiT, TopBottomT<ZhanChop, NatureElements.Ri> {

    public static final ZanBrief INSTANCE = new ZanBrief();

    @Override public ZhanChop top() { return ZhanChop.INSTANCE; }
    @Override public NatureElements.Ri bottom() { return NatureElements.RI; }

    @Override public CompositionLayoutT layout() { return this; }

    @Override public String glyph() { return "\u6682"; }

    @Override public PinyinSyllable pinyin() {
        return new PinyinSyllable(Initial.Z, new Final(Head.OPEN, Body.A, Tail.N), Tone.FOURTH);
    }

    @Override public int strokes() { return 0; }
    @Override public int radicalNo() { return 0; }
    @Override public String meaning() { return ""; }

    @Override public EtymologicalCategory etymology() {
        return new EtymologicalCategory.PhonoSemantic(NatureElements.RI, ZhanChop.INSTANCE);
    }
}
