// AUTO-GENERATED by CatalogIteratorMain - do not edit by hand.
package kranji.common.perclass.promoted.z.an4;

import kranji.classification.EtymologicalCategory;
import kranji.common.perclass.promoted.sh.en1.ShenShenAuto;
import kranji.pinyin.Body;
import kranji.pinyin.Final;
import kranji.pinyin.Head;
import kranji.pinyin.Initial;
import kranji.pinyin.PinyinSyllable;
import kranji.pinyin.Tail;
import kranji.pinyin.Tone;
import kranji.singular.animals.Animals;
import kranji.zi.ComposedZiT;
import kranji.zi.CompositionLayoutT;
import kranji.zi.TopBottomT;

public record ZanPraise() implements ComposedZiT, TopBottomT<ShenShenAuto, Animals.Bei> {

    public static final ZanPraise INSTANCE = new ZanPraise();

    @Override public ShenShenAuto top() { return ShenShenAuto.INSTANCE; }
    @Override public Animals.Bei bottom() { return Animals.BEI; }

    @Override public CompositionLayoutT layout() { return this; }

    @Override public String glyph() { return "\u8D5E"; }

    @Override public PinyinSyllable pinyin() {
        return new PinyinSyllable(Initial.Z, new Final(Head.OPEN, Body.A, Tail.N), Tone.FOURTH);
    }

    @Override public int strokes() { return 0; }
    @Override public int radicalNo() { return 0; }
    @Override public String meaning() { return ""; }

    @Override public EtymologicalCategory etymology() {
        return new EtymologicalCategory.PhonoSemantic(Animals.BEI, ShenShenAuto.INSTANCE);
    }
}
