package kranji.reading.app.read;

import hue.captains.singapura.js.homing.core.Importable;
import hue.captains.singapura.js.homing.core.ModuleImports;
import hue.captains.singapura.js.homing.workspace.LifecycleHint;
import hue.captains.singapura.js.homing.workspace.WorkspaceWidget;
import kranji.reading.app.css.ReadingCss;
import kranji.reading.app.ui.GlyphMetricsModule;
import kranji.reading.app.ui.ReaderControlsModule;
import kranji.reading.app.ui.TextBandsModule;
import kranji.reading.app.ui.TypefacePickerModule;

import java.util.List;

/**
 * The reader.
 *
 * <p>Each line of text is a two-row table: annotations above, characters below.
 * The table is what buys precise control — every column is exactly one
 * character wide, so the page keeps the even rhythm of 方块字 and, with the
 * grid turned on, looks like the squared practice book a child already writes
 * in.</p>
 *
 * <h2>Why a table and not ruby</h2>
 *
 * <p>Ruby spreads its base characters apart to fit the annotation, so spacing
 * would depend on <em>which characters this reader knows</em> — the page would
 * re-space as a child learns. A fixed table cannot do that.</p>
 *
 * <h2>Showing and hiding never moves anything</h2>
 *
 * <p>An annotation is hidden with {@code visibility}, never {@code display}:
 * the row keeps its height, so switching modes cannot reflow the page. Text
 * that jumps when a setting changes is disorienting for a child.</p>
 *
 * <p>Punctuation rides inside the preceding character's cell rather than
 * taking a column of its own. That is 禁则 handled structurally — a row cannot
 * break inside a cell, so 。 can never begin a line.</p>
 *
 * <p>No CJK appears in this file. Characters arrive from the corpus.</p>
 */
public final class ArticleReaderWidget
        extends WorkspaceWidget<WorkspaceWidget._None, ArticleReaderWidget> {

    public static final ArticleReaderWidget INSTANCE = new ArticleReaderWidget();

    private ArticleReaderWidget() {}

    private record construct() implements WorkspaceWidget._Construct<_None, ArticleReaderWidget> {}

    @Override protected _Construct<_None, ArticleReaderWidget> construct() { return new construct(); }
    @Override public Class<_None> paramsType() { return _None.class; }
    @Override public String title() { return "Reader"; }
    @Override public LifecycleHint lifecycleHint() { return LifecycleHint.MULTI; }

    @Override
    protected List<ModuleImports<? extends Importable>> bodyImports() {
        return List.of(
                new ModuleImports<>(List.of(
                        new ReadingCss.kr_widget_root(),
                        new ReadingCss.kr_status(),
                        new ReadingCss.kr_control(),
                        new ReadingCss.kr_select(),
                        new ReadingCss.kr_btn(),
                        new ReadingCss.kr_read_title(),
                        new ReadingCss.kr_read_verse(),
                        new ReadingCss.kr_read_line(),
                        new ReadingCss.kr_read_ann(),
                        new ReadingCss.kr_read_hidden(),
                        new ReadingCss.kr_read_zi(),
                        new ReadingCss.kr_read_grid(),
                        new ReadingCss.kr_read_size_s(),
                        new ReadingCss.kr_read_size_m(),
                        new ReadingCss.kr_read_size_l(),
                        new ReadingCss.kr_read_ann_s(),
                        new ReadingCss.kr_read_ann_m(),
                        new ReadingCss.kr_read_ann_l(),
                        new ReadingCss.kr_read_punct(),
                        new ReadingCss.kr_read_punct_x0(),
                        new ReadingCss.kr_read_punct_x1(),
                        new ReadingCss.kr_read_punct_x2(),
                        new ReadingCss.kr_read_punct_x3(),
                        new ReadingCss.kr_read_punct_lead(),
                        new ReadingCss.kr_font_system(),
                        new ReadingCss.kr_font_hei(),
                        new ReadingCss.kr_font_song(),
                        new ReadingCss.kr_font_kai(),
                        new ReadingCss.kr_font_fangsong()),
                        ReadingCss.INSTANCE),
                new ModuleImports<>(
                        List.of(new TypefacePickerModule.createTypefacePicker()),
                        TypefacePickerModule.INSTANCE),
                new ModuleImports<>(
                        List.of(new GlyphMetricsModule.createGlyphMetrics()),
                        GlyphMetricsModule.INSTANCE),
                new ModuleImports<>(
                        List.of(new TextBandsModule.createBanding()),
                        TextBandsModule.INSTANCE),
                new ModuleImports<>(
                        List.of(new ReaderControlsModule.createReaderControls()),
                        ReaderControlsModule.INSTANCE));
    }

    @Override
    protected List<String> constructBodyJs() {
        return List.of(
                "    var root = branch.createElement('root', 'div');",
                "    css.setClass(root, kr_widget_root);",
                "",
                "    var owner = Object.freeze({ toString: function () { return 'reader'; } });",
                "",
                "    // The article currently rendered. Kept because a band change needs to",
                "    // lay it out again, and nothing else remembers it.",
                "    var loaded = null;",
                "    var __mod = null;",
                "",
                "    var typeface = createTypefacePicker({",
                "        branch: branch, css: css, prefix: 'read', selectClass: kr_select,",
                "        classes: { system: kr_font_system, kai: kr_font_kai, hei: kr_font_hei,",
                "                   song: kr_font_song, fangsong: kr_font_fangsong },",
                "        onChange: function () { applyCells(); }",
                "    });",
                "",
                "    var controls = createReaderControls({",
                "        branch: branch, css: css,",
                "        selectClass: kr_select, btnClass: kr_btn,",
                "        sizes: [",
                "            { id: 's', label: 'Small',  w: 47, zi: kr_read_size_s, ann: kr_read_ann_s },",
                "            { id: 'm', label: 'Medium', w: 63, zi: kr_read_size_m, ann: kr_read_ann_m },",
                "            { id: 'l', label: 'Large',  w: 81, zi: kr_read_size_l, ann: kr_read_ann_l }",
                "        ],",
                "        extra: [typeface.element],",
                "        onChange: function () { applyCells(); },",
                "        onArticle: function (id) { load(id); }",
                "    });",
                "    css.setClass(controls.element, kr_control);",
                "    root.appendChild(controls.element);",
                "",
                "    var status = branch.createElement('status', 'div');",
                "    css.setClass(status, kr_status);",
                "    root.appendChild(status);",
                "",
                "    var body = branch.createElement('body', 'div');",
                "    root.appendChild(body);",
                "",
                "    // Kept so a mode or grid change restyles in place rather than",
                "    // rebuilding - a rebuild would dissolve the branch and lose nothing",
                "    // but cost everything.",
                "    var annCells = [];",
                "    var ziCells = [];",
                "",
                "    // How far a mark is pushed depends on how much of its box the",
                "    // character in front of it fills. Measured, then quantised into four",
                "    // classes - a computed offset would have to be an inline style,",
                "    // which conformance rejects, rightly.",
                "    var metrics = createGlyphMetrics({ branch: branch, name: 'measure' });",
                "    var banding = createBanding({});",
                "    var band = 0;",
                "",
                "    // Chunking has to happen BEFORE anything is laid out, so the width",
                "    // comes from the size entry rather than from a measurement. Deriving",
                "    // it from a rendered cell was tried and is subtly wrong: the value",
                "    // available at chunk time is the PREVIOUS size's, so changing size",
                "    // laid the text out to the width it just left.",
                "    function cellsPerRow() {",
                "        var available = body.clientWidth || root.clientWidth || 0;",
                "        return banding.cellsPerRow(available, controls.size().w);",
                "    }",
                "",
                "    function offsetClass(ratio) {",
                "        if (ratio >= 0.18) return kr_read_punct_x0;",
                "        if (ratio >= 0.10) return kr_read_punct_x1;",
                "        if (ratio >= 0.05) return kr_read_punct_x2;",
                "        return kr_read_punct_x3;",
                "    }",
                "",
                "    /* The font the cells are actually rendered in, for measuring against. */",
                "    function fontSpecOf(td) {",
                "        var s = window.getComputedStyle(td);",
                "        return s.fontSize + ' ' + s.fontFamily;",
                "    }",
                "",
                "    // Every cell's classes are assembled rather than enumerated: a base,",
                "    // a size, a typeface, and whatever else that cell happens to need.",
                "    // setClass replaces, so the whole list is rebuilt each time - which is",
                "    // also why nothing gets lost when one control changes.",
                "    function styleCell(td, fontSpec) {",
                "        var classes = [td, kr_read_zi, controls.size().zi, typeface.currentClass()];",
                "        if (controls.grid()) classes.push(kr_read_grid);",
                "        if (td.getAttribute('data-lead'))  classes.push(kr_read_punct_lead);",
                "        if (td.getAttribute('data-punct')) {",
                "            classes.push(kr_read_punct);",
                "            if (fontSpec) {",
                "                classes.push(offsetClass(metrics.gapRatio(td.textContent, fontSpec)));",
                "            }",
                "        }",
                "        css.setClass.apply(css, classes);",
                "    }",
                "",
                "    function styleAnn(td) {",
                "        var classes = [td, kr_read_ann, controls.size().ann];",
                "        if (controls.mode() === 'none') classes.push(kr_read_hidden);",
                "        css.setClass.apply(css, classes);",
                "    }",
                "",
                "    function applyMode() {",
                "        for (var i = 0; i < annCells.length; i++) styleAnn(annCells[i]);",
                "    }",
                "",
                "    // Two passes, because measuring needs the font the cells ended up",
                "    // with. The first settles size and typeface; the second reads that",
                "    // back and places each mark against its own character.",
                "    function applyCells() {",
                "        for (var i = 0; i < ziCells.length; i++) styleCell(ziCells[i], null);",
                "        if (ziCells.length === 0) return;",
                "",
                "        // A size change can move the article into a different band. Record",
                "        // the new band BEFORE relaying out: the rebuild calls back into",
                "        // here, and if band were still stale that call would try to relay",
                "        // out again, be refused by the recursion guard, and return without",
                "        // ever styling anything.",
                "        var want = cellsPerRow();",
                "        if (__mod && want !== band) { band = want; relayout(); return; }",
                "        band = want;",
                "",
                "        var spec = fontSpecOf(ziCells[0]);",
                "        for (var k = 0; k < ziCells.length; k++) {",
                "            if (ziCells[k].getAttribute('data-punct')) styleCell(ziCells[k], spec);",
                "        }",
                "        for (var j = 0; j < annCells.length; j++) styleAnn(annCells[j]);",
                "    }",
                "",
                "    function applyGrid() { applyCells(); }",
                "",
                "    var __ziParty = (workspaceCtx && workspaceCtx.ziParty)",
                "                  ? workspaceCtx.ziParty : null;",
                "    var __ziActorId = null;",
                "    if (__ziParty) {",
                "        __ziActorId = 'zi/reader-' + Math.random().toString(36).slice(2, 8);",
                "        __ziParty.joinActor({",
                "            id: __ziActorId, parentSecretary: 'ziSelection', reactors: {}",
                "        });",
                "    }",
                "",
                "    function clearBody() {",
                "        annCells = [];",
                "        ziCells = [];",
                "        if (branch.getBranch('doc')) branch.dissolveBranch('doc');",
                "    }",
                "",
                "    /* One line of text: a table of two rows over the same columns. */",
                "    function lineTable(db, key, cells) {",
                "        var table = db.createElement('t' + key, 'table');",
                "        css.setClass(table, kr_read_line);",
                "        var annRow = db.createElement('ar' + key, 'tr');",
                "        var ziRow  = db.createElement('zr' + key, 'tr');",
                "        table.appendChild(annRow);",
                "        table.appendChild(ziRow);",
                "",
                "        for (var i = 0; i < cells.length; i++) {",
                "            var cell = cells[i];",
                "            var ann = db.createElement('a' + key + '_' + i, 'td');",
                "            styleAnn(ann);",
                "            ann.textContent = cell.r || '';",
                "            annCells.push(ann);",
                "            annRow.appendChild(ann);",
                "",
                "            var zi = db.createElement('z' + key + '_' + i, 'td');",
                "            ziCells.push(zi);",
                "",
                "            // The character is the cell's only content. Punctuation is drawn",
                "            // by the cell's own class - ::before and ::after reading it back",
                "            // out of these attributes - so no element carries it and nothing",
                "            // can widen the square.",
                "            zi.textContent = cell.z || cell.t || '';",
                "            if (cell.lp) zi.setAttribute('data-lead', cell.lp);",
                "            if (cell.p)  zi.setAttribute('data-punct', cell.p);",
                "            if (cell.c) {",
                "                zi.setAttribute('data-cp', cell.c);",
                "                zi.setAttribute('aria-label',",
                "                        (cell.lp || '') + cell.z + (cell.p || '') + ' ' + cell.r);",
                "            }",
                "            styleCell(zi, null);",
                "            ziRow.appendChild(zi);",
                "        }",
                "        return table;",
                "    }",
                "",
                "    function render(mod) {",
                "        __mod = mod;",
                "        clearBody();",
                "        if (!mod.id) {",
                "            status.textContent = mod.problem ? 'Nothing here: ' + mod.problem",
                "                                            : 'No such article.';",
                "            return;",
                "        }",
                "        var db = branch.createBranch('doc');",
                "        db.activate(owner);",
                "",
                "        var title = db.createElement('title', 'div');",
                "        css.setClass(title, kr_read_title);",
                "        title.textContent = mod.title;",
                "        body.appendChild(title);",
                "",
                "        status.textContent = mod.length + ' characters.';",
                "        controls.fillCatalogue(mod.catalogue, mod.id);",
                "",
                "        for (var b = 0; b < mod.blocks.length; b++) {",
                "            var block = mod.blocks[b];",
                "            if (block.kind === 'verse') {",
                "                var verse = db.createElement('v' + b, 'div');",
                "                css.setClass(verse, kr_read_verse);",
                "                for (var l = 0; l < block.lines.length; l++) {",
                "                    verse.appendChild(lineTable(db, b + '_' + l, block.lines[l]));",
                "                }",
                "                body.appendChild(verse);",
                "            } else if (block.kind === 'p') {",
                "                // Prose wraps; a verse does not. A poem's lines are the",
                "                // author's, and re-breaking them would destroy the form.",
                "                var rows = banding.chunk(block.cells, cellsPerRow());",
                "                var para = db.createElement('para' + b, 'div');",
                "                for (var r = 0; r < rows.length; r++) {",
                "                    para.appendChild(lineTable(db, 'p' + b + '_' + r, rows[r]));",
                "                }",
                "                body.appendChild(para);",
                "            }",
                "        }",
                "",
                "        // Now that the cells are in the document they have a resolved font,",
                "        // which is what the marks have to be measured against. Building them",
                "        // could not do this - nothing was laid out yet.",
                "        applyCells();",
                "    }",
                "",
                "    // One delegated listener rather than one per cell - an article is",
                "    // hundreds of cells and they are rebuilt on every load.",
                "    body.addEventListener('click', function (ev) {",
                "        var el = ev.target;",
                "        while (el && el !== body && !el.getAttribute('data-cp')) el = el.parentElement;",
                "        if (!el || el === body) return;",
                "        if (__ziParty && __ziActorId) {",
                "            __ziParty.tellFrom(__ziActorId, { kind: 'ZiSelected', zi: {",
                "                codePoint: el.getAttribute('data-cp'),",
                "                glyph: el.textContent } });",
                "        }",
                "    });",
                "",
                "    // A band change is the only thing that needs the article rebuilt -",
                "    // everything else is a restyle. Guarded so it cannot recurse through",
                "    // applyCells, which is what calls it.",
                "    var __relaying = false;",
                "    function relayout() {",
                "        if (__relaying || !__mod) return;",
                "        __relaying = true;",
                "        try { render(__mod); } finally { __relaying = false; }",
                "    }",
                "",
                "    if (typeof ResizeObserver !== 'undefined') {",
                "        new ResizeObserver(function () {",
                "            if (!__mod || ziCells.length === 0) return;",
                "            if (cellsPerRow() !== band) relayout();",
                "        }).observe(root);",
                "    }",
                "",
                "    function load(id) {",
                "        loaded = id;",
                "        status.textContent = 'Loading ' + id + '\\u2026';",
                "        import('/article?id=' + encodeURIComponent(id))",
                "            .then(function (mod) { render(mod); })",
                "            .catch(function (err) {",
                "                clearBody();",
                "                status.textContent = 'Could not load ' + id + ': '",
                "                    + (err && err.message ? err.message : String(err));",
                "            });",
                "    }",
                "",
                "    load('jing-ye-si');",
                "",
                "    return {",
                "        root: root,",
                "        setActive: function (active) {},",
                "        partyDeregister: function () {",
                "            if (__ziActorId && __ziParty) {",
                "                try { __ziParty.leave(__ziActorId); } catch (e) {}",
                "            }",
                "        }",
                "    };");
    }
}
