package kranji.reading.app.read;

import hue.captains.singapura.js.homing.core.Importable;
import hue.captains.singapura.js.homing.core.ModuleImports;
import hue.captains.singapura.js.homing.workspace.LifecycleHint;
import hue.captains.singapura.js.homing.workspace.WorkspaceWidget;
import kranji.reading.app.css.ReadingCss;
import kranji.reading.app.ui.PinyinSwfModule;
import kranji.reading.app.known.KnownWatchModule;
import kranji.reading.app.ui.GlyphMetricsModule;
import kranji.reading.app.ui.ReaderControlsModule;
import kranji.reading.app.ui.TextBandsModule;
import kranji.reading.app.ui.TypefacePickerModule;
import kranji.reading.library.ArticleAddress;
import kranji.reading.library.ArticleCollection;
import kranji.reading.library.ArticleRef;
import kranji.reading.library.Libraries;

import java.util.List;

/**
 * The reader.
 *
 * <p>Each line of text is a two-row table: annotations above, characters below.
 * The table is what buys precise control — every column is exactly one
 * character wide, so the page keeps the even rhythm of 方块字 and, with the
 * grid turned on, looks like the squared practice book a child already writes
 * in.</p>
 *
 * <h2>Why a table and not ruby</h2>
 *
 * <p>Ruby spreads its base characters apart to fit the annotation, so spacing
 * would depend on <em>which characters this reader knows</em> — the page would
 * re-space as a child learns. A fixed table cannot do that.</p>
 *
 * <h2>Showing and hiding never moves anything</h2>
 *
 * <p>An annotation is hidden with {@code visibility}, never {@code display}:
 * the row keeps its height, so switching modes cannot reflow the page. Text
 * that jumps when a setting changes is disorienting for a child.</p>
 *
 * <p>Punctuation rides inside the preceding character's cell rather than
 * taking a column of its own. That is 禁则 handled structurally — a row cannot
 * break inside a cell, so 。 can never begin a line.</p>
 *
 * <p>No CJK appears in this file. Characters arrive from the corpus.</p>
 */
public final class ArticleReaderWidget
        extends WorkspaceWidget<WorkspaceWidget._None, ArticleReaderWidget> {

    public static final ArticleReaderWidget INSTANCE = new ArticleReaderWidget();

    private ArticleReaderWidget() {}

    private record construct() implements WorkspaceWidget._Construct<_None, ArticleReaderWidget> {}

    @Override protected _Construct<_None, ArticleReaderWidget> construct() { return new construct(); }
    @Override public Class<_None> paramsType() { return _None.class; }
    @Override public String title() { return "Reader"; }
    @Override public LifecycleHint lifecycleHint() { return LifecycleHint.MULTI; }

    @Override
    protected List<ModuleImports<? extends Importable>> bodyImports() {
        return List.of(
                new ModuleImports<>(List.of(
                        new ReadingCss.kr_widget_root(),
                        new ReadingCss.kr_status(),
                        new ReadingCss.kr_rd_head(),
                        new ReadingCss.kr_rd_settings(),
                        new ReadingCss.kr_kn_hidden(),
                        new ReadingCss.kr_select(),
                        new ReadingCss.kr_btn(),
                        new ReadingCss.kr_read_title(),
                        new ReadingCss.kr_read_title_zi(),
                        new ReadingCss.kr_read_title_rt(),
                        new ReadingCss.kr_read_hidden(),
                        new ReadingCss.kr_read_verse(),
                        new ReadingCss.kr_gr_host(),
                        new ReadingCss.kr_gr_ruled(),
                        new ReadingCss.kr_gr_quiet(),
                        new ReadingCss.kr_read_size_s(),
                        new ReadingCss.kr_read_size_m(),
                        new ReadingCss.kr_read_size_l(),
                        new ReadingCss.kr_read_ann_s(),
                        new ReadingCss.kr_read_ann_m(),
                        new ReadingCss.kr_read_ann_l(),
                        new ReadingCss.kr_font_system(),
                        new ReadingCss.kr_font_hei(),
                        new ReadingCss.kr_font_song(),
                        new ReadingCss.kr_font_kai(),
                        new ReadingCss.kr_font_fangsong()),
                        ReadingCss.INSTANCE),
                new ModuleImports<>(
                        List.of(new TypefacePickerModule.createTypefacePicker()),
                        TypefacePickerModule.INSTANCE),
                new ModuleImports<>(
                        List.of(new GlyphMetricsModule.createGlyphMetrics()),
                        GlyphMetricsModule.INSTANCE),
                new ModuleImports<>(
                        List.of(new TextBandsModule.createBanding()),
                        TextBandsModule.INSTANCE),
                new ModuleImports<>(
                        List.of(new ReaderControlsModule.createReaderControls()),
                        ReaderControlsModule.INSTANCE),
                new ModuleImports<>(
                        List.of(new KnownWatchModule.createKnownWatch()),
                        KnownWatchModule.INSTANCE),
                new ModuleImports<>(
                        List.of(new ArticleScannerModule.createArticleScanner()),
                        ArticleScannerModule.INSTANCE),
                new ModuleImports<>(
                        List.of(new ArticleTextModule.createArticleText()),
                        ArticleTextModule.INSTANCE),
                new ModuleImports<>(
                        List.of(new ArticleReadingsModule.createArticleReadings()),
                        ArticleReadingsModule.INSTANCE),
                new ModuleImports<>(
                        List.of(new ReaderCellStyleModule.createReaderCellStyle()),
                        ReaderCellStyleModule.INSTANCE),
                new ModuleImports<>(
                        List.of(new ReaderTitleModule.createReaderTitle()),
                        ReaderTitleModule.INSTANCE),
                new ModuleImports<>(
                        List.of(new PinyinSwfModule.createPinyinSwf()),
                        PinyinSwfModule.INSTANCE),
                new ModuleImports<>(List.of(
                        new ArticleBoardModule.createArticleCell(),
                        new ArticleBoardModule.createLineRelation(),
                        new ArticleBoardModule.repaintGrid(),
                        new ArticleBoardModule.articleLines(),
                        new ArticleBoardModule.buildArticleBoard()),
                        ArticleBoardModule.INSTANCE));
    }

    @Override
    protected List<String> constructBodyJs() {
        return List.of(
                "    var root = branch.createElement('root', 'div');",
                "    css.setClass(root, kr_widget_root);",
                "",
                "    var owner = Object.freeze({ toString: function () { return 'reader'; } });",
                "",
                "    // The article currently rendered. Kept because a band change needs to",
                "    // lay it out again, and nothing else remembers it.",
                "    var loaded = null;",
                "    var __mod = null;",
                "",
                "    var scanner = createArticleScanner({});",
                "",
                "    // What this reader already knows - and, now, where they say so.",
                "    //",
                "    // This used to watch without claiming, on the reasoning that marking",
                "    // is a deliberate act made in front of a character's other readings",
                "    // rather than a side effect of reading past one. The first half of",
                "    // that still holds and is why the Character pane exists. The second",
                "    // was wrong about where the act happens: meeting a character in a",
                "    // sentence is the moment a child knows whether they can read it, and",
                "    // sending them to another pane to say so loses the moment.",
                "    //",
                "    // It is not a side effect here either. Nothing marks by being read",
                "    // past, or clicked, or arrowed over - only Enter or a double click,",
                "    // both of which are deliberate and neither of which a cursor can",
                "    // trip over on its way somewhere else.",
                "    //",
                "    // A change is a RESTYLE, not a reload - applyCells repaints the",
                "    // squares in place, so pinyin leaving every 行走 in the article cannot",
                "    // move the child's place on the page.",
                "    // claims: true is now two things at once - this pane may change the",
                "    // set, and this pane keeps it. The reader used to claim and never",
                "    // save, so marking was durable only when some other pane happened to",
                "    // be open: a child reading with the library and the reader up lost",
                "    // the lot on closing the tab, with ticks on the page throughout.",
                "    var known = createKnownWatch({",
                "        party: (workspaceCtx && workspaceCtx.knownParty)",
                "                    ? workspaceCtx.knownParty : null,",
                "        id: 'reader',",
                "        claims: true,",
                "        onChanged: function () { if (board) applyCells(); },",
                "        // Announced without being asked for. A claim that did not reach",
                "        // the device looks exactly like one that did, and what was lost",
                "        // is discovered a week later with no way to tell which marks",
                "        // survived.",
                "        onProblem: function () {",
                "            status.textContent = 'This device would not save the record. "
                        + "Readings marked now may not survive closing the page.';",
                "        }",
                "    });",
                "",
                "    // The article sends text; the readings come from the corpus. The",
                "    // browser caches each partition module by URL, so a second article",
                "    // pays only for what the first did not already pull.",
                "    var readings = createArticleReadings({",
                "        load: function (p) { return import('/syllable-map?p=' + p); }",
                "    });",
                "",
                "    // Three questions about the article rather than about this pane:",
                "    // its lines, the squares a line becomes, and the paragraph indent.",
                "    var text = createArticleText({ scanner: scanner, readings: readings });",
                "",
                "    // The title is Chinese too, and was the one line of it in the pane",
                "    // with nothing over it. It asks the same known set the squares ask,",
                "    // so the two can never disagree about what this reader knows.",
                "    var titleText = createReaderTitle({",
                "        css: css, swf: createPinyinSwf(),",
                "        cellsOf: function (s) { return text.cellsOf(s); },",
                "        annotates: function (c) {",
                "            return known.annotates(controls.mode(), c && c.z, c && c.r);",
                "        },",
                "        ziClass: kr_read_title_zi, rtClass: kr_read_title_rt,",
                "        hiddenClass: kr_read_hidden",
                "    });",
                "",
                "    var typeface = createTypefacePicker({",
                "        branch: branch, css: css, prefix: 'read', selectClass: kr_select,",
                "        classes: { system: kr_font_system, kai: kr_font_kai, hei: kr_font_hei,",
                "                   song: kr_font_song, fangsong: kr_font_fangsong },",
                "        onChange: function () { applyCells(); }",
                "    });",
                "",
                "    var controls = createReaderControls({",
                "        branch: branch, css: css,",
                "        selectClass: kr_select, btnClass: kr_btn,",
                "        headClass: kr_rd_head, panelClass: kr_rd_settings,",
                "        hiddenClass: kr_kn_hidden,",
                "        // Closing hands the keyboard back to the page, so Enter goes on",
                "        // meaning I know this one without a click to re-aim it.",
                "        onToggle: function (open) { if (!open) focusBoard(); },",
                "        sizes: [",
                "            { id: 's', label: 'Small',  w: 47, zi: kr_read_size_s, ann: kr_read_ann_s },",
                "            { id: 'm', label: 'Medium', w: 63, zi: kr_read_size_m, ann: kr_read_ann_m },",
                "            { id: 'l', label: 'Large',  w: 81, zi: kr_read_size_l, ann: kr_read_ann_l }",
                "        ],",
                "        extra: [typeface.element],",
                "        onChange: function () { applyCells(); }",
                "    });",
                "    // The header strip owns the Settings button and the folded panel;",
                "    // the status line is ours, and sits in the strip beside the button.",
                "    root.appendChild(controls.element);",
                "",
                "    var status = branch.createElement('status', 'div');",
                "    css.setClass(status, kr_status);",
                "    controls.element.appendChild(status);",
                "",
                "    var body = branch.createElement('body', 'div');",
                "    root.appendChild(body);",
                "",
                "    // Kept so a mode or grid change restyles in place rather than",
                "    // rebuilding - a rebuild would dissolve the branch and lose nothing",
                "    // but cost everything.",
                "",
                "    // How far a mark is pushed depends on how much of its box the",
                "    // character in front of it fills. Measured, then quantised into four",
                "    // classes - a computed offset would have to be an inline style,",
                "    // which conformance rejects, rightly.",
                "    var metrics = createGlyphMetrics({ branch: branch, name: 'measure' });",
                "    var banding = createBanding({});",
                "    var band = 0;",
                "",
                "    // Chunking has to happen BEFORE anything is laid out, so the width",
                "    // comes from the size entry rather than from a measurement. Deriving",
                "    // it from a rendered cell was tried and is subtly wrong: the value",
                "    // available at chunk time is the PREVIOUS size's, so changing size",
                "    // laid the text out to the width it just left.",
                "    function cellsPerRow() {",
                "        var available = body.clientWidth || root.clientWidth || 0;",
                "        return banding.cellsPerRow(available, controls.size().w);",
                "    }",
                "",
                "    // Only the mark offsets are left here; a square dresses itself.",
                "    var style = createReaderCellStyle({ metrics: metrics });",
                "    function fontSpecOf(el) { return style.fontSpecOf(el); }",
                "",
                "    function applyMode() { applyCells(); }",
                "",
                "    // Two passes, because measuring needs the font the cells ended up",
                "    // with. The first settles size and typeface; the second reads that",
                "    // back and places each mark against its own character.",
                "    function applyCells() {",
                "        // The title carries readings too, and the same mode change or",
                "        // mark that restyles a square restyles it. Before the board",
                "        // guard below: the title exists whether or not the board does.",
                "        titleText.restyle();",
                "",
                "        if (!board) return;",
                "",
                "        // Dress the host FIRST, before anything can return early.",
                "        //",
                "        // buildArticleBoard makes it bare, and kr_gr_host is what stops the",
                "        // grid substrate stretching the board: the table under it asks for",
                "        // width 100%, so without fit-content a wide pane spreads five",
                "        // squares across the whole width and leaves them floating in the",
                "        // middle of columns three times their size.",
                "        //",
                "        // It used to be dressed after the band guard below, and a pane",
                "        // resize slipped through the gap: relayout() built a fresh bare",
                "        // host, this ran, measured THAT host - full width, because it was",
                "        // not styled yet - got a different band, asked to relay out again,",
                "        // was refused by the recursion guard, and returned. The host stayed",
                "        // bare, and nothing afterwards ever dressed it.",
                "        //",
                "        // A control change alters how a square is dressed, not what it",
                "        // holds, so the value goes back unchanged and the cell re-reads",
                "        // the settings. One coalesced batch for the whole article.",
                "        // The board outline is part of the ruling: with the grid off,",
                "        // a rectangle still around the paragraph is the one line",
                "        // nobody asked for.",
                "        if (controls.grid()) css.setClass(board.host, kr_gr_host, kr_gr_quiet, kr_gr_ruled);",
                "        else                 css.setClass(board.host, kr_gr_host, kr_gr_quiet);",
                "",
                "        // A size change can move the article into a different band. Record",
                "        // the new band BEFORE relaying out: the rebuild calls back into",
                "        // here, and if band were still stale that call would try to relay",
                "        // out again and be refused by the recursion guard.",
                "        var want = cellsPerRow();",
                "        if (__mod && want !== band) { band = want; relayout(); return; }",
                "        band = want;",
                "",
                "        __probe = null;",
                "        __spec = null;",
                "        repaintAll();",
                "",
                "        // Two passes, because measuring needs the font the squares ended",
                "        // up with. The first settles size and typeface; the second reads",
                "        // that back and places each mark against its own character.",
                "        if (!__probe) return;",
                "        __spec = fontSpecOf(__probe);",
                "        repaintAll();",
                "    }",
                "",
                "    function repaintAll() {",
                "        repaintGrid(board.grid, board.relation);",
                "        board.grid.flushNow();",
                "    }",
                "",
                "    function applyGrid() { applyCells(); }",
                "",
                "    var __ziParty = (workspaceCtx && workspaceCtx.ziParty)",
                "                  ? workspaceCtx.ziParty : null;",
                "    var __ziActorId = null;",
                "    if (__ziParty) {",
                "        __ziActorId = 'zi/reader-' + Math.random().toString(36).slice(2, 8);",
                "        __ziParty.joinActor({",
                "            id: __ziActorId, parentSecretary: 'ziSelection', reactors: {}",
                "        });",
                "    }",
                "",
                "    function clearBody() {",
                "        board = null;",
                "        if (branch.getBranch('doc')) branch.dissolveBranch('doc');",
                "    }",
                "",
                "    // One grid per block. A block is the natural rectangle: a verse's",
                "    // rows are the lines the author wrote, a paragraph's are the wrap.",
                "    // Blocks do not share a shape, so they do not share a grid.",
                "    var board = null;",
                "    var __active = false;",
                "",
                "    // Hand the keyboard to the squares as soon as the pane is the active",
                "    // one, so arrow keys read the article instead of doing nothing until",
                "    // something is clicked.",
                "    //",
                "    // Never steal it, though. The pane also becomes active when a control",
                "    // in its own bar is clicked, and yanking focus off a select the",
                "    // moment it opens would make the dropdowns unusable - so this only",
                "    // acts when the focus is somewhere outside this widget.",
                "    function focusBoard() {",
                "        if (!board || !board.grid) return;",
                "        var here = document.activeElement;",
                "        if (here && here !== document.body && root.contains(here)) return;",
                "        try { board.grid.focus(); } catch (e) {}",
                "    }",
                "    var __probe = null;   // one painted square, to measure the font from",
                "    var __spec  = null;   // that font, once it is known",
                "",
                "    function render(mod) {",
                "        __mod = mod;",
                "        clearBody();",
                "        if (!mod.id) {",
                "            status.textContent = mod.problem ? 'Nothing here: ' + mod.problem",
                "                                            : 'No such article.';",
                "            return;",
                "        }",
                "        var db = branch.createBranch('doc');",
                "        db.activate(owner);",
                "",
                "        var title = db.createElement('title', 'div');",
                "        css.setClass(title, kr_read_title);",
                "        titleText.show(db, title, mod.title);",
                "        body.appendChild(title);",
                "",
                "        // How long this is, and nothing about whether the reader",
                "        // ought to be here. What used to sit on this line worked out",
                "        // what percentage of the article a child could already read",
                "        // and then named the answer - Too hard - which is a verdict",
                "        // the pinyin directly above it exists to refute. A length is",
                "        // a fact about the text rather than about the reader.",
                "        status.textContent = mod.length + ' characters.';",
                "",
                "",
                "        var cellFactory = createArticleCell({",
                "            branch:   db,",
                "            grid:     function () { return controls.grid(); },",
                "            size:     function () { return controls.size(); },",
                "            annotates: function (v) {",
                "                return known.annotates(controls.mode(), v && v.z, v && v.r);",
                "            },",
                "            // Whether ticks are drawn at all, and whether this",
                "            // reading has earned one. The badge asks the same set the",
                "            // annotation does, so the two can never disagree about",
                "            // whether a reading is claimed.",
                "            marks: function () { return controls.marks(); },",
                "            mastered: function (v) {",
                "                return known.isKnown(v && v.z, v && v.r);",
                "            },",
                "            typefaceClass: function () { return typeface.currentClass(); },",
                "            fontSpec: function () { return __spec; },",
                "            offsetOf: function (ch, spec) {",
                "                return style.offsetClass(metrics.gapRatio(ch, spec));",
                "            },",
                "            onPainted: function (el, v) { if (!__probe) __probe = el; }",
                "        });",
                "",
                "        board = buildArticleBoard({",
                "            db: db, owner: owner, body: body, blocks: mod.blocks,",
                "            cellFactory: cellFactory, cellsOf: text.cellsOf,",
                "            indented: text.indented, chunk: banding.chunk, columns: cellsPerRow,",
                "            onSelect: function (cell) {",
                "                if (!cell || !cell.z || !__ziParty || !__ziActorId) return;",
                "                __ziParty.tellFrom(__ziActorId, { kind: 'ZiSelected', zi: {",
                "                    codePoint: readings.cpLabel(cell.z), glyph: cell.z,",
                "                    reading: cell.r } });",
                "            },",
                "            // Enter or a double click on a square. Not a single click -",
                "            // see the note in buildArticleBoard.",
                "            onClaim: function (cell) { known.toggle(cell.z, cell.r); }",
                "        });",
                "",
                "        // Now that the squares are in the document they have a resolved",
                "        // font, which is what the marks have to be measured against.",
                "        // Building them could not do this - nothing was laid out yet.",
                "        applyCells();",
                "",
                "        // A new article arriving in an already-active pane should be",
                "        // readable from the keyboard without being clicked first.",
                "        if (__active) focusBoard();",
                "    }",
                "",
                "    // A band change is the only thing that needs the article rebuilt -",
                "    // everything else is a restyle. Guarded so it cannot recurse through",
                "    // applyCells, which is what calls it.",
                "    var __relaying = false;",
                "    function relayout() {",
                "        if (__relaying || !__mod) return;",
                "        __relaying = true;",
                "        try { render(__mod); } finally { __relaying = false; }",
                "    }",
                "",
                "    if (typeof ResizeObserver !== 'undefined') {",
                "        new ResizeObserver(function () {",
                "            if (!__mod || !board) return;",
                "            if (cellsPerRow() !== band) relayout();",
                "        }).observe(root);",
                "    }",
                "",
                "    function load(id) {",
                "        loaded = id;",
                "        status.textContent = 'Loading ' + id + '\\u2026';",
                "        import('/article?id=' + encodeURIComponent(id))",
                "            .then(function (mod) {",
                "                // The readings have to be in hand before the first cell is",
                "                // drawn - an annotation appearing late would reflow the page",
                "                // under a child's eyes, which is the one thing the fixed",
                "                // table exists to prevent.",
                "                if (!mod.id) { render(mod); return; }",
                "                // The title is not part of the article for counting -",
                "                // text.textsOf is what the census reads - but it is on the",
                "                // the screen, so its partitions have to be here too.",
                "                return readings.ensure(text.textsOf(mod).concat([mod.title]))",
                "                    .then(function () { render(mod); });",
                "            })",
                "            .catch(function (err) {",
                "                clearBody();",
                "                status.textContent = 'Could not load ' + id + ': '",
                "                    + (err && err.message ? err.message : String(err));",
                "            });",
                "    }",
                "",
                "    // The library says which article; this pane never asks it",
                "    // which, and never names it back.",
                "    var __artParty = (workspaceCtx && workspaceCtx.articleParty)",
                "                   ? workspaceCtx.articleParty : null;",
                "    var __artActorId = null;",
                "    if (__artParty) {",
                "        __artActorId = 'read/reader-' + Math.random().toString(36).slice(2, 8);",
                "        __artParty.joinActor({",
                "            id: __artActorId,",
                "            parentSecretary: 'articleSelection',",
                "            reactors: {",
                "                ShowArticle: function (msg) {",
                "                    if (msg && msg.article && msg.article !== loaded) {",
                "                        load(msg.article);",
                "                    }",
                "                }",
                "            }",
                "        });",
                "    }",
                "",
                "    load('" + opensAt() + "');",
                "",
                "    return {",
                "        root: root,",
                "        setActive: function (active) {",
                "            __active = active;",
                "            if (active) focusBoard();",
                "        },",
                "        partyDeregister: function () {",
                "            if (__ziActorId && __ziParty) {",
                "                try { __ziParty.leave(__ziActorId); } catch (e) {}",
                "            }",
                "            if (__artActorId && __artParty) {",
                "                try { __artParty.leave(__artActorId); } catch (e) {}",
                "            }",
                "            known.leave();",
                "        }",
                "    };");
    }

    /**
     * What the reader opens on: the first article in the mounted library.
     *
     * <p>Asked of the library rather than written out. A literal address here
     * is a second place the catalogue has to be kept true, and the one nothing
     * checks: it held one demo poem until a published root displaced it,
     * at which point the reader would have opened on "no article" and the
     * build would have stayed green.</p>
     *
     * <p>First rather than chosen, because choosing means naming one, which is
     * the literal again. Which article that is stays a decision of whoever
     * arranged the root — it is the first thing a reader sees, so it is an
     * editorial call and belongs with the other one.</p>
     */
    static ArticleAddress opensAt() {
        for (ArticleCollection c : Libraries.mounted().tree().collections()) {
            for (ArticleRef ref : c.articles()) return c.address(ref.id());
        }
        throw new IllegalStateException("library '" + Libraries.mounted().name()
                + "' mounted with no articles in it, so the reader has nothing to open");
    }
}
