package kranji.reading.app.read;

import hue.captains.singapura.js.homing.core.Importable;
import hue.captains.singapura.js.homing.core.ModuleImports;
import hue.captains.singapura.js.homing.workspace.LifecycleHint;
import hue.captains.singapura.js.homing.workspace.WorkspaceWidget;
import kranji.reading.app.css.ReadingCss;
import kranji.reading.app.ui.GlyphMetricsModule;
import kranji.reading.app.ui.ReaderControlsModule;
import kranji.reading.app.ui.TextBandsModule;
import kranji.reading.app.ui.TypefacePickerModule;

import java.util.List;

/**
 * The reader.
 *
 * <p>Each line of text is a two-row table: annotations above, characters below.
 * The table is what buys precise control — every column is exactly one
 * character wide, so the page keeps the even rhythm of 方块字 and, with the
 * grid turned on, looks like the squared practice book a child already writes
 * in.</p>
 *
 * <h2>Why a table and not ruby</h2>
 *
 * <p>Ruby spreads its base characters apart to fit the annotation, so spacing
 * would depend on <em>which characters this reader knows</em> — the page would
 * re-space as a child learns. A fixed table cannot do that.</p>
 *
 * <h2>Showing and hiding never moves anything</h2>
 *
 * <p>An annotation is hidden with {@code visibility}, never {@code display}:
 * the row keeps its height, so switching modes cannot reflow the page. Text
 * that jumps when a setting changes is disorienting for a child.</p>
 *
 * <p>Punctuation rides inside the preceding character's cell rather than
 * taking a column of its own. That is 禁则 handled structurally — a row cannot
 * break inside a cell, so 。 can never begin a line.</p>
 *
 * <p>No CJK appears in this file. Characters arrive from the corpus.</p>
 */
public final class ArticleReaderWidget
        extends WorkspaceWidget<WorkspaceWidget._None, ArticleReaderWidget> {

    public static final ArticleReaderWidget INSTANCE = new ArticleReaderWidget();

    private ArticleReaderWidget() {}

    private record construct() implements WorkspaceWidget._Construct<_None, ArticleReaderWidget> {}

    @Override protected _Construct<_None, ArticleReaderWidget> construct() { return new construct(); }
    @Override public Class<_None> paramsType() { return _None.class; }
    @Override public String title() { return "Reader"; }
    @Override public LifecycleHint lifecycleHint() { return LifecycleHint.MULTI; }

    @Override
    protected List<ModuleImports<? extends Importable>> bodyImports() {
        return List.of(
                new ModuleImports<>(List.of(
                        new ReadingCss.kr_widget_root(),
                        new ReadingCss.kr_status(),
                        new ReadingCss.kr_control(),
                        new ReadingCss.kr_select(),
                        new ReadingCss.kr_btn(),
                        new ReadingCss.kr_read_title(),
                        new ReadingCss.kr_read_verse(),
                        new ReadingCss.kr_gr_host(),
                        new ReadingCss.kr_gr_ruled(),
                        new ReadingCss.kr_read_size_s(),
                        new ReadingCss.kr_read_size_m(),
                        new ReadingCss.kr_read_size_l(),
                        new ReadingCss.kr_read_ann_s(),
                        new ReadingCss.kr_read_ann_m(),
                        new ReadingCss.kr_read_ann_l(),
                        new ReadingCss.kr_font_system(),
                        new ReadingCss.kr_font_hei(),
                        new ReadingCss.kr_font_song(),
                        new ReadingCss.kr_font_kai(),
                        new ReadingCss.kr_font_fangsong()),
                        ReadingCss.INSTANCE),
                new ModuleImports<>(
                        List.of(new TypefacePickerModule.createTypefacePicker()),
                        TypefacePickerModule.INSTANCE),
                new ModuleImports<>(
                        List.of(new GlyphMetricsModule.createGlyphMetrics()),
                        GlyphMetricsModule.INSTANCE),
                new ModuleImports<>(
                        List.of(new TextBandsModule.createBanding()),
                        TextBandsModule.INSTANCE),
                new ModuleImports<>(
                        List.of(new ReaderControlsModule.createReaderControls()),
                        ReaderControlsModule.INSTANCE),
                new ModuleImports<>(
                        List.of(new ArticleScannerModule.createArticleScanner()),
                        ArticleScannerModule.INSTANCE),
                new ModuleImports<>(
                        List.of(new ArticleReadingsModule.createArticleReadings()),
                        ArticleReadingsModule.INSTANCE),
                new ModuleImports<>(
                        List.of(new ReaderCellStyleModule.createReaderCellStyle()),
                        ReaderCellStyleModule.INSTANCE),
                new ModuleImports<>(List.of(
                        new GridReaderCellModule.createGridReaderCell(),
                        new GridReaderCellModule.createParagraphRelation(),
                        new GridReaderCellModule.createVerseRelation(),
                        new GridReaderCellModule.repaintGrid(),
                        new GridReaderCellModule.buildArticleBoards()),
                        GridReaderCellModule.INSTANCE));
    }

    @Override
    protected List<String> constructBodyJs() {
        return List.of(
                "    var root = branch.createElement('root', 'div');",
                "    css.setClass(root, kr_widget_root);",
                "",
                "    var owner = Object.freeze({ toString: function () { return 'reader'; } });",
                "",
                "    // The article currently rendered. Kept because a band change needs to",
                "    // lay it out again, and nothing else remembers it.",
                "    var loaded = null;",
                "    var __mod = null;",
                "",
                "    var scanner = createArticleScanner({});",
                "",
                "    // The article sends text; the readings come from the corpus. The",
                "    // browser caches each partition module by URL, so a second article",
                "    // pays only for what the first did not already pull.",
                "    var readings = createArticleReadings({",
                "        load: function (p) { return import('/syllable-map?p=' + p); }",
                "    });",
                "",
                "    // One authored line -> the squares it is written in. The scan rule is",
                "    // ArticleScannerModule; the readings are filled in after, and an",
                "    // authored one always wins because the corpus cannot know it.",
                "    function cellsOf(line) {",
                "        return readings.fill(scanner.scan(line));",
                "    }",
                "",
                "    // 首行缩进两格. On squared paper those two squares are left empty",
                "    // rather than the text being nudged, so the indent is two blank",
                "    // cells - it keeps the column grid, and with the grid on it looks",
                "    // like what a child writes.",
                "    function indented(cells) {",
                "        return [{ t: '' }, { t: '' }].concat(cells);",
                "    }",
                "",
                "    function textsOf(mod) {",
                "        var out = [];",
                "        for (var b = 0; b < mod.blocks.length; b++) {",
                "            var block = mod.blocks[b];",
                "            if (block.kind === 'verse') out = out.concat(block.lines);",
                "            else if (block.kind === 'p') out.push(block.text);",
                "        }",
                "        return out;",
                "    }",
                "",
                "    var typeface = createTypefacePicker({",
                "        branch: branch, css: css, prefix: 'read', selectClass: kr_select,",
                "        classes: { system: kr_font_system, kai: kr_font_kai, hei: kr_font_hei,",
                "                   song: kr_font_song, fangsong: kr_font_fangsong },",
                "        onChange: function () { applyCells(); }",
                "    });",
                "",
                "    var controls = createReaderControls({",
                "        branch: branch, css: css,",
                "        selectClass: kr_select, btnClass: kr_btn,",
                "        sizes: [",
                "            { id: 's', label: 'Small',  w: 47, zi: kr_read_size_s, ann: kr_read_ann_s },",
                "            { id: 'm', label: 'Medium', w: 63, zi: kr_read_size_m, ann: kr_read_ann_m },",
                "            { id: 'l', label: 'Large',  w: 81, zi: kr_read_size_l, ann: kr_read_ann_l }",
                "        ],",
                "        extra: [typeface.element],",
                "        onChange: function () { applyCells(); }",
                "    });",
                "    css.setClass(controls.element, kr_control);",
                "    root.appendChild(controls.element);",
                "",
                "    var status = branch.createElement('status', 'div');",
                "    css.setClass(status, kr_status);",
                "    root.appendChild(status);",
                "",
                "    var body = branch.createElement('body', 'div');",
                "    root.appendChild(body);",
                "",
                "    // Kept so a mode or grid change restyles in place rather than",
                "    // rebuilding - a rebuild would dissolve the branch and lose nothing",
                "    // but cost everything.",
                "",
                "    // How far a mark is pushed depends on how much of its box the",
                "    // character in front of it fills. Measured, then quantised into four",
                "    // classes - a computed offset would have to be an inline style,",
                "    // which conformance rejects, rightly.",
                "    var metrics = createGlyphMetrics({ branch: branch, name: 'measure' });",
                "    var banding = createBanding({});",
                "    var band = 0;",
                "",
                "    // Chunking has to happen BEFORE anything is laid out, so the width",
                "    // comes from the size entry rather than from a measurement. Deriving",
                "    // it from a rendered cell was tried and is subtly wrong: the value",
                "    // available at chunk time is the PREVIOUS size's, so changing size",
                "    // laid the text out to the width it just left.",
                "    function cellsPerRow() {",
                "        var available = body.clientWidth || root.clientWidth || 0;",
                "        return banding.cellsPerRow(available, controls.size().w);",
                "    }",
                "",
                "    var style = createReaderCellStyle({",
                "        metrics: metrics,",
                "        size: function () { return controls.size(); },",
                "        grid: function () { return controls.grid(); },",
                "        mode: function () { return controls.mode(); },",
                "        typefaceClass: function () { return typeface.currentClass(); }",
                "    });",
                "    function styleCell(td, fontSpec) { style.cell(td, fontSpec); }",
                "    function styleAnn(td) { style.ann(td); }",
                "    function fontSpecOf(td) { return style.fontSpecOf(td); }",
                "",
                "    function applyMode() { applyCells(); }",
                "",
                "    // Two passes, because measuring needs the font the cells ended up",
                "    // with. The first settles size and typeface; the second reads that",
                "    // back and places each mark against its own character.",
                "    function applyCells() {",
                "        if (grids.length === 0) return;",
                "",
                "        // A size change can move the article into a different band. Record",
                "        // the new band BEFORE relaying out: the rebuild calls back into",
                "        // here, and if band were still stale that call would try to relay",
                "        // out again, be refused by the recursion guard, and return without",
                "        // ever styling anything.",
                "        var want = cellsPerRow();",
                "        if (__mod && want !== band) { band = want; relayout(); return; }",
                "        band = want;",
                "",
                "        // A control change alters how a square is dressed, not what it",
                "        // holds, so the value goes back unchanged and the cell re-reads",
                "        // the settings. One coalesced batch for the whole article.",
                "        // The board outline is part of the ruling: with the grid off,",
                "        // a rectangle still around the paragraph is the one line",
                "        // nobody asked for.",
                "        for (var h = 0; h < grids.length; h++) {",
                "            if (controls.grid()) css.setClass(grids[h].host, kr_gr_host, kr_gr_ruled);",
                "            else                 css.setClass(grids[h].host, kr_gr_host);",
                "        }",
                "",
                "        __probe = null;",
                "        __spec = null;",
                "        repaintAll();",
                "",
                "        // Two passes, because measuring needs the font the squares ended",
                "        // up with. The first settles size and typeface; the second reads",
                "        // that back and places each mark against its own character.",
                "        if (!__probe) return;",
                "        __spec = fontSpecOf(__probe);",
                "        repaintAll();",
                "    }",
                "",
                "    function repaintAll() {",
                "        for (var g = 0; g < grids.length; g++) {",
                "            repaintGrid(grids[g].grid, grids[g].relation);",
                "            grids[g].grid.flushNow();",
                "        }",
                "    }",
                "",
                "    function applyGrid() { applyCells(); }",
                "",
                "    var __ziParty = (workspaceCtx && workspaceCtx.ziParty)",
                "                  ? workspaceCtx.ziParty : null;",
                "    var __ziActorId = null;",
                "    if (__ziParty) {",
                "        __ziActorId = 'zi/reader-' + Math.random().toString(36).slice(2, 8);",
                "        __ziParty.joinActor({",
                "            id: __ziActorId, parentSecretary: 'ziSelection', reactors: {}",
                "        });",
                "    }",
                "",
                "    function clearBody() {",
                "        grids = [];",
                "        if (branch.getBranch('doc')) branch.dissolveBranch('doc');",
                "    }",
                "",
                "    // One grid per block. A block is the natural rectangle: a verse's",
                "    // rows are the lines the author wrote, a paragraph's are the wrap.",
                "    // Blocks do not share a shape, so they do not share a grid.",
                "    var grids = [];",
                "    var __probe = null;   // one painted square, to measure the font from",
                "    var __spec  = null;   // that font, once it is known",
                "",
                "    function render(mod) {",
                "        __mod = mod;",
                "        clearBody();",
                "        if (!mod.id) {",
                "            status.textContent = mod.problem ? 'Nothing here: ' + mod.problem",
                "                                            : 'No such article.';",
                "            return;",
                "        }",
                "        var db = branch.createBranch('doc');",
                "        db.activate(owner);",
                "",
                "        var title = db.createElement('title', 'div');",
                "        css.setClass(title, kr_read_title);",
                "        title.textContent = mod.title;",
                "        body.appendChild(title);",
                "",
                "        status.textContent = mod.length + ' characters.';",
                "",
                "",
                "        var cellFactory = createGridReaderCell({",
                "            branch:   db,",
                "            grid:     function () { return controls.grid(); },",
                "            size:     function () { return controls.size(); },",
                "            mode:     function () { return controls.mode(); },",
                "            typefaceClass: function () { return typeface.currentClass(); },",
                "            fontSpec: function () { return __spec; },",
                "            offsetOf: function (ch, spec) {",
                "                return style.offsetClass(metrics.gapRatio(ch, spec));",
                "            },",
                "            onPainted: function (el, v) { if (!__probe) __probe = el; }",
                "        });",
                "",
                "        grids = buildArticleBoards({",
                "            db: db, owner: owner, body: body, blocks: mod.blocks,",
                "            cellFactory: cellFactory, cellsOf: cellsOf,",
                "            indented: indented, columns: cellsPerRow,",
                "            onSelect: function (cell) {",
                "                if (!cell || !cell.z || !__ziParty || !__ziActorId) return;",
                "                __ziParty.tellFrom(__ziActorId, { kind: 'ZiSelected', zi: {",
                "                    codePoint: readings.cpLabel(cell.z), glyph: cell.z } });",
                "            }",
                "        });",
                "",
                "        // Now that the squares are in the document they have a resolved",
                "        // font, which is what the marks have to be measured against.",
                "        // Building them could not do this - nothing was laid out yet.",
                "        applyCells();",
                "    }",
                "",
                "    // One delegated listener rather than one per cell - an article is",
                "    // hundreds of cells and they are rebuilt on every load.",
                "    body.addEventListener('click', function (ev) {",
                "        var el = ev.target;",
                "        while (el && el !== body && !el.getAttribute('data-cp')) el = el.parentElement;",
                "        if (!el || el === body) return;",
                "        if (__ziParty && __ziActorId) {",
                "            __ziParty.tellFrom(__ziActorId, { kind: 'ZiSelected', zi: {",
                "                codePoint: el.getAttribute('data-cp'),",
                "                glyph: el.textContent } });",
                "        }",
                "    });",
                "",
                "    // A band change is the only thing that needs the article rebuilt -",
                "    // everything else is a restyle. Guarded so it cannot recurse through",
                "    // applyCells, which is what calls it.",
                "    var __relaying = false;",
                "    function relayout() {",
                "        if (__relaying || !__mod) return;",
                "        __relaying = true;",
                "        try { render(__mod); } finally { __relaying = false; }",
                "    }",
                "",
                "    if (typeof ResizeObserver !== 'undefined') {",
                "        new ResizeObserver(function () {",
                "            if (!__mod || grids.length === 0) return;",
                "            if (cellsPerRow() !== band) relayout();",
                "        }).observe(root);",
                "    }",
                "",
                "    function load(id) {",
                "        loaded = id;",
                "        status.textContent = 'Loading ' + id + '\\u2026';",
                "        import('/article?id=' + encodeURIComponent(id))",
                "            .then(function (mod) {",
                "                // The readings have to be in hand before the first cell is",
                "                // drawn - an annotation appearing late would reflow the page",
                "                // under a child's eyes, which is the one thing the fixed",
                "                // table exists to prevent.",
                "                if (!mod.id) { render(mod); return; }",
                "                return readings.ensure(textsOf(mod))",
                "                    .then(function () { render(mod); });",
                "            })",
                "            .catch(function (err) {",
                "                clearBody();",
                "                status.textContent = 'Could not load ' + id + ': '",
                "                    + (err && err.message ? err.message : String(err));",
                "            });",
                "    }",
                "",
                "    // The library says which article; this pane never asks it",
                "    // which, and never names it back.",
                "    var __artParty = (workspaceCtx && workspaceCtx.articleParty)",
                "                   ? workspaceCtx.articleParty : null;",
                "    var __artActorId = null;",
                "    if (__artParty) {",
                "        __artActorId = 'read/reader-' + Math.random().toString(36).slice(2, 8);",
                "        __artParty.joinActor({",
                "            id: __artActorId,",
                "            parentSecretary: 'articleSelection',",
                "            reactors: {",
                "                ShowArticle: function (msg) {",
                "                    if (msg && msg.article && msg.article !== loaded) {",
                "                        load(msg.article);",
                "                    }",
                "                }",
                "            }",
                "        });",
                "    }",
                "",
                "    load('kranji.reader.demo.tangshi:jing-ye-si');",
                "",
                "    return {",
                "        root: root,",
                "        setActive: function (active) {},",
                "        partyDeregister: function () {",
                "            if (__ziActorId && __ziParty) {",
                "                try { __ziParty.leave(__ziActorId); } catch (e) {}",
                "            }",
                "            if (__artActorId && __artParty) {",
                "                try { __artParty.leave(__artActorId); } catch (e) {}",
                "            }",
                "        }",
                "    };");
    }
}
