// AUTO-GENERATED by kranji-codegen. Do not edit by hand.
package kranji.singular.structures.t;

import kranji.library.BasicSet;
import kranji.library.LibraryMember;
import kranji.zi.SingularZi;

public record Tai() implements LibraryMember<BasicSet>, SingularZi {
    public static final Tai INSTANCE = new Tai();

    @Override public String glyph() { return "\u53F0"; }
    @Override public String meaning() { return "platform"; }
    @Override public String pinyinText() { return "t\u00E1i"; }
    @Override public int strokes() { return 5; }
    @Override public BasicSet library() { return BasicSet.INSTANCE; }
}
