// AUTO-GENERATED by CatalogIteratorMain - do not edit by hand.
package kranji.common.perclass.promoted.zero.ing1;

import kranji.classification.EtymologicalCategory;
import kranji.common.perclass.promoted.zero.ing1.YingEagle_Inner2;
import kranji.pinyin.Body;
import kranji.pinyin.Final;
import kranji.pinyin.Head;
import kranji.pinyin.Initial;
import kranji.pinyin.PinyinSyllable;
import kranji.pinyin.Tail;
import kranji.pinyin.Tone;
import kranji.singular.animals.Animals;
import kranji.zi.ComposedZiT;
import kranji.zi.CompositionLayoutT;
import kranji.zi.TopBottomT;

public record YingEagle_Inner1() implements ComposedZiT, TopBottomT<YingEagle_Inner2, Animals.Niao> {

    public static final YingEagle_Inner1 INSTANCE = new YingEagle_Inner1();

    @Override public YingEagle_Inner2 top() { return YingEagle_Inner2.INSTANCE; }
    @Override public Animals.Niao bottom() { return Animals.NIAO; }

    @Override public CompositionLayoutT layout() { return this; }

    @Override public String glyph() { return ""; }

    @Override public PinyinSyllable pinyin() {
        return new PinyinSyllable(Initial.ZERO, new Final(Head.OPEN, Body.I, Tail.NG), Tone.FIRST);
    }

    @Override public int strokes() { return 0; }
    @Override public int radicalNo() { return 0; }
    @Override public String meaning() { return ""; }

    @Override public EtymologicalCategory etymology() {
        return new EtymologicalCategory.CompoundIndicative("");
    }
}
