// AUTO-GENERATED by CatalogIteratorMain - do not edit by hand.
package kranji.common.perclass.promoted.q.ie4;

import kranji.classification.EtymologicalCategory;
import kranji.common.perclass.q.ie1.QieCut;
import kranji.pinyin.Body;
import kranji.pinyin.Final;
import kranji.pinyin.Head;
import kranji.pinyin.Initial;
import kranji.pinyin.PinyinSyllable;
import kranji.pinyin.Tail;
import kranji.pinyin.Tone;
import kranji.singular.structures.Structures;
import kranji.zi.ComposedZiT;
import kranji.zi.CompositionLayoutT;
import kranji.zi.SemiEnclosureUpperLeftT;

public record QieSteal() implements ComposedZiT, SemiEnclosureUpperLeftT<Structures.Xue, QieCut> {

    public static final QieSteal INSTANCE = new QieSteal();

    @Override public Structures.Xue wrapper() { return Structures.XUE; }
    @Override public QieCut content() { return QieCut.INSTANCE; }

    @Override public CompositionLayoutT layout() { return this; }

    @Override public String glyph() { return "\u7A83"; }

    @Override public PinyinSyllable pinyin() {
        return new PinyinSyllable(Initial.Q, new Final(Head.I, Body.E_CARON, Tail.NONE), Tone.FOURTH);
    }

    @Override public int strokes() { return 0; }
    @Override public int radicalNo() { return 0; }
    @Override public String meaning() { return ""; }

    @Override public EtymologicalCategory etymology() {
        return new EtymologicalCategory.PhonoSemantic(Structures.XUE, QieCut.INSTANCE);
    }
}
