// AUTO-GENERATED by kranji-codegen. Do not edit by hand.
package kranji.singular.tools.zero;

import kranji.library.BasicSet;
import kranji.library.LibraryMember;
import kranji.zi.SingularZi;

public record Ya_Fork() implements LibraryMember<BasicSet>, SingularZi {
    public static final Ya_Fork INSTANCE = new Ya_Fork();

    @Override public String glyph() { return "\u4E2B"; }
    @Override public String meaning() { return "fork/girl"; }
    @Override public String pinyinText() { return "y\u0101"; }
    @Override public int strokes() { return 3; }
    @Override public BasicSet library() { return BasicSet.INSTANCE; }
}
