// AUTO-GENERATED by PerclassGenerateMain - do not edit by hand.
package kranji.common.perclass.l.v2;

import kranji.classification.EtymologicalCategory;
import kranji.pinyin.Body;
import kranji.pinyin.Final;
import kranji.pinyin.Head;
import kranji.pinyin.Initial;
import kranji.pinyin.PinyinSyllable;
import kranji.pinyin.Tail;
import kranji.pinyin.Tone;
import kranji.singular.animals.Animals;
import kranji.singular.animals.Animals.Ma;
import kranji.singular.structures.Structures;
import kranji.singular.structures.Structures.Hu;
import kranji.zi.ComposedZiT;
import kranji.zi.CompositionLayoutT;
import kranji.zi.LeftRightT;

public record LvDonkey() implements ComposedZiT, LeftRightT<Ma, Hu> {

    public static final LvDonkey INSTANCE = new LvDonkey();

    @Override public Ma left() { return Animals.MA; }
    @Override public Hu right() { return Structures.HU; }

    @Override public CompositionLayoutT layout() { return this; }

    @Override public String glyph() { return "\u9A74"; }

    @Override public PinyinSyllable pinyin() {
        return new PinyinSyllable(Initial.L, new Final(Head.V, Body.V, Tail.NONE), Tone.SECOND);
    }

    @Override public int strokes() { return 7; }
    @Override public int radicalNo() { return 187; }
    @Override public String meaning() { return ""; }

    @Override public EtymologicalCategory etymology() {
        return new EtymologicalCategory.PhonoSemantic(Animals.MA, Structures.HU);
    }
}
