// AUTO-GENERATED by CatalogIteratorMain - do not edit by hand.
package kranji.common.perclass.promoted.zh.a3;

import kranji.classification.EtymologicalCategory;
import kranji.pinyin.Body;
import kranji.pinyin.Final;
import kranji.pinyin.Head;
import kranji.pinyin.Initial;
import kranji.pinyin.PinyinSyllable;
import kranji.pinyin.Tail;
import kranji.pinyin.Tone;
import kranji.singular.body.BodyParts;
import kranji.singular.concepts.AbstractConcepts;
import kranji.zi.ComposedZiT;
import kranji.zi.CompositionLayoutT;
import kranji.zi.LeftRightT;

public record ZhaBlink() implements ComposedZiT, LeftRightT<BodyParts.Mu, AbstractConcepts.Fa> {

    public static final ZhaBlink INSTANCE = new ZhaBlink();

    @Override public BodyParts.Mu left() { return BodyParts.MU; }
    @Override public AbstractConcepts.Fa right() { return AbstractConcepts.FA; }

    @Override public CompositionLayoutT layout() { return this; }

    @Override public String glyph() { return "\u7728"; }

    @Override public PinyinSyllable pinyin() {
        return new PinyinSyllable(Initial.ZH, new Final(Head.OPEN, Body.A, Tail.NONE), Tone.THIRD);
    }

    @Override public int strokes() { return 0; }
    @Override public int radicalNo() { return 0; }
    @Override public String meaning() { return ""; }

    @Override public EtymologicalCategory etymology() {
        return new EtymologicalCategory.PhonoSemantic(BodyParts.MU, AbstractConcepts.FA);
    }
}
