// AUTO-GENERATED by CatalogIteratorMain - do not edit by hand.
package kranji.common.perclass.promoted.b.ing4;

import kranji.pinyin.Body;
import kranji.pinyin.Final;
import kranji.pinyin.Head;
import kranji.pinyin.Initial;
import kranji.pinyin.PinyinSyllable;
import kranji.pinyin.Tail;
import kranji.pinyin.Tone;
import kranji.zi.SingularZi;

public record BingCombineAtom() implements SingularZi {

    public static final BingCombineAtom INSTANCE = new BingCombineAtom();

    @Override public String glyph() { return "\u5E76"; }

    @Override public PinyinSyllable pinyin() {
        return new PinyinSyllable(Initial.B, new Final(Head.OPEN, Body.I, Tail.NG), Tone.FOURTH);
    }

    @Override public boolean unsure() { return true; }
}
