// AUTO-GENERATED by CatalogIteratorMain - do not edit by hand.
package kranji.common.perclass.promoted.m.an2;

import kranji.classification.EtymologicalCategory;
import kranji.common.perclass.promoted.m.an4.ManGraceful;
import kranji.component.basic.BasicComponents;
import kranji.component.basic.FoodFamily;
import kranji.pinyin.Body;
import kranji.pinyin.Final;
import kranji.pinyin.Head;
import kranji.pinyin.Initial;
import kranji.pinyin.PinyinSyllable;
import kranji.pinyin.Tail;
import kranji.pinyin.Tone;
import kranji.zi.ComposedZiT;
import kranji.zi.CompositionLayoutT;
import kranji.zi.LeftRightT;

public record ManBun() implements ComposedZiT, LeftRightT<FoodFamily.ShiZiPang, ManGraceful> {

    public static final ManBun INSTANCE = new ManBun();

    @Override public FoodFamily.ShiZiPang left() { return BasicComponents.SHI_ZI_PANG; }
    @Override public ManGraceful right() { return ManGraceful.INSTANCE; }

    @Override public CompositionLayoutT layout() { return this; }

    @Override public String glyph() { return "\u9992"; }

    @Override public PinyinSyllable pinyin() {
        return new PinyinSyllable(Initial.M, new Final(Head.OPEN, Body.A, Tail.N), Tone.SECOND);
    }

    @Override public int strokes() { return 0; }
    @Override public int radicalNo() { return 0; }
    @Override public String meaning() { return ""; }

    @Override public EtymologicalCategory etymology() {
        return new EtymologicalCategory.PhonoSemantic(BasicComponents.SHI_ZI_PANG, ManGraceful.INSTANCE);
    }
}
