// AUTO-GENERATED by CatalogIteratorMain - do not edit by hand.
package kranji.common.perclass.promoted.m.an2;

import kranji.classification.EtymologicalCategory;
import kranji.common.perclass.promoted.m.an2.ManCover;
import kranji.pinyin.Body;
import kranji.pinyin.Final;
import kranji.pinyin.Head;
import kranji.pinyin.Initial;
import kranji.pinyin.PinyinSyllable;
import kranji.pinyin.Tail;
import kranji.pinyin.Tone;
import kranji.singular.body.BodyParts;
import kranji.zi.ComposedZiT;
import kranji.zi.CompositionLayoutT;
import kranji.zi.LeftRightT;

public record ManConceal() implements ComposedZiT, LeftRightT<BodyParts.Mu, ManCover> {

    public static final ManConceal INSTANCE = new ManConceal();

    @Override public BodyParts.Mu left() { return BodyParts.MU; }
    @Override public ManCover right() { return ManCover.INSTANCE; }

    @Override public CompositionLayoutT layout() { return this; }

    @Override public String glyph() { return "\u7792"; }

    @Override public PinyinSyllable pinyin() {
        return new PinyinSyllable(Initial.M, new Final(Head.OPEN, Body.A, Tail.N), Tone.SECOND);
    }

    @Override public int strokes() { return 0; }
    @Override public int radicalNo() { return 0; }
    @Override public String meaning() { return ""; }

    @Override public EtymologicalCategory etymology() {
        return new EtymologicalCategory.PhonoSemantic(BodyParts.MU, ManCover.INSTANCE);
    }
}
