// AUTO-GENERATED by Depth1GenerateMain - do not edit by hand.
package kranji.common.depth1.ch;

import kranji.classification.EtymologicalCategory.*;
import kranji.component.basic.BasicComponents;
import kranji.pinyin.Body;
import kranji.pinyin.Final;
import kranji.pinyin.Head;
import kranji.pinyin.Initial;
import kranji.pinyin.PinyinSyllable;
import kranji.pinyin.Tail;
import kranji.pinyin.Tone;
import kranji.singular.numbers.NumbersAndMeasure;
import kranji.zi.ComposedPart;
import kranji.zi.ComposedZi;
import kranji.zi.CompositionLayout.*;
import kranji.zi.SingularPart;
import kranji.zi.ZiChar;
import java.util.List;

public final class Ou2 {

    private Ou2() {}

    public static final ComposedZi CHOU_HATRED = new ComposedZi(
            new ZiChar.Unicode("\u4EC7"),
            new PinyinSyllable(Initial.CH, new Final(Head.OPEN, Body.O, Tail.VOWEL_U), Tone.SECOND),
            4, 9, "",
            new LeftRight(BasicComponents.DAN_REN_PANG, NumbersAndMeasure.JIU),
            new PhonoSemantic(BasicComponents.DAN_REN_PANG, NumbersAndMeasure.JIU));

    public static final List<ComposedZi> ALL = List.of(
            CHOU_HATRED);
}
