// AUTO-GENERATED by CatalogIteratorMain - do not edit by hand.
package kranji.common.perclass.promoted.s.uan4;

import kranji.classification.EtymologicalCategory;
import kranji.pinyin.Body;
import kranji.pinyin.Final;
import kranji.pinyin.Head;
import kranji.pinyin.Initial;
import kranji.pinyin.PinyinSyllable;
import kranji.pinyin.Tail;
import kranji.pinyin.Tone;
import kranji.singular.radicals.RadicalComponents;
import kranji.singular.tools.ToolsAndVessels;
import kranji.zi.ComposedZiT;
import kranji.zi.CompositionLayoutT;
import kranji.zi.TopBottomT;

public record SuanCalculate() implements ComposedZiT, TopBottomT<RadicalComponents.Zhu_Bamboo, ToolsAndVessels.Ju_Tool> {

    public static final SuanCalculate INSTANCE = new SuanCalculate();

    @Override public RadicalComponents.Zhu_Bamboo top() { return RadicalComponents.ZHU_BAMBOO; }
    @Override public ToolsAndVessels.Ju_Tool bottom() { return ToolsAndVessels.JU_TOOL; }

    @Override public CompositionLayoutT layout() { return this; }

    @Override public String glyph() { return "\u7B97"; }

    @Override public PinyinSyllable pinyin() {
        return new PinyinSyllable(Initial.S, new Final(Head.U, Body.A, Tail.N), Tone.FOURTH);
    }

    @Override public int strokes() { return 0; }
    @Override public int radicalNo() { return 0; }
    @Override public String meaning() { return ""; }

    @Override public EtymologicalCategory etymology() {
        return new EtymologicalCategory.CompoundIndicative("");
    }
}
