// AUTO-GENERATED by PerclassGenerateMain - do not edit by hand.
package kranji.common.perclass.k.ong1;

import kranji.classification.EtymologicalCategory;
import kranji.pinyin.Body;
import kranji.pinyin.Final;
import kranji.pinyin.Head;
import kranji.pinyin.Initial;
import kranji.pinyin.PinyinSyllable;
import kranji.pinyin.Tail;
import kranji.pinyin.Tone;
import kranji.singular.actions.ActionsAndStates;
import kranji.singular.actions.ActionsAndStates.Gong_Work;
import kranji.singular.structures.Structures;
import kranji.singular.structures.Structures.Xue;
import kranji.zi.ComposedZiT;
import kranji.zi.CompositionLayoutT;
import kranji.zi.TopBottomT;

public record Kong() implements ComposedZiT, TopBottomT<Xue, Gong_Work> {

    public static final Kong INSTANCE = new Kong();

    @Override public Xue top() { return Structures.XUE; }
    @Override public Gong_Work bottom() { return ActionsAndStates.GONG_WORK; }

    @Override public CompositionLayoutT layout() { return this; }

    @Override public String glyph() { return "\u7A7A"; }

    @Override public PinyinSyllable pinyin() {
        return new PinyinSyllable(Initial.K, new Final(Head.OPEN, Body.O, Tail.NG), Tone.FIRST);
    }

    @Override public int strokes() { return 8; }
    @Override public int radicalNo() { return 116; }
    @Override public String meaning() { return ""; }

    @Override public EtymologicalCategory etymology() {
        return new EtymologicalCategory.PhonoSemantic(Structures.XUE, ActionsAndStates.GONG_WORK);
    }
}
