// AUTO-GENERATED by Depth1GenerateMain - do not edit by hand.
package kranji.common.depth1.zero;

import kranji.classification.EtymologicalCategory.*;
import kranji.component.basic.BasicComponents;
import kranji.pinyin.Body;
import kranji.pinyin.Final;
import kranji.pinyin.Head;
import kranji.pinyin.Initial;
import kranji.pinyin.PinyinSyllable;
import kranji.pinyin.Tail;
import kranji.pinyin.Tone;
import kranji.singular.concepts.AbstractConcepts;
import kranji.zi.ComposedPart;
import kranji.zi.ComposedZi;
import kranji.zi.CompositionLayout.*;
import kranji.zi.SingularPart;
import kranji.zi.ZiChar;
import java.util.List;

public final class I2 {

    private I2() {}

    public static final ComposedZi YI_CEREMONY = new ComposedZi(
            new ZiChar.Unicode("\u4EEA"),
            new PinyinSyllable(Initial.ZERO, new Final(Head.OPEN, Body.I, Tail.NONE), Tone.SECOND),
            5, 9, "",
            new LeftRight(BasicComponents.DAN_REN_PANG, AbstractConcepts.YI_MEANING),
            new PhonoSemantic(BasicComponents.DAN_REN_PANG, AbstractConcepts.YI_MEANING));

    public static final ComposedZi YI_FITTING = new ComposedZi(
            new ZiChar.Unicode("\u5B9C"),
            new PinyinSyllable(Initial.ZERO, new Final(Head.OPEN, Body.I, Tail.NONE), Tone.SECOND),
            8, 40, "",
            new TopBottom(BasicComponents.BAO_GAI_TOU, AbstractConcepts.QIE),
            new CompoundIndicative("宀(roof) + 且(moreover) → fitting"));

    public static final List<ComposedZi> ALL = List.of(
            YI_CEREMONY,
            YI_FITTING);
}
