// AUTO-GENERATED by Depth1GenerateMain - do not edit by hand.
package kranji.common.depth1.zero;

import kranji.classification.EtymologicalCategory.*;
import kranji.component.basic.BasicComponents;
import kranji.pinyin.Body;
import kranji.pinyin.Final;
import kranji.pinyin.Head;
import kranji.pinyin.Initial;
import kranji.pinyin.PinyinSyllable;
import kranji.pinyin.Tail;
import kranji.pinyin.Tone;
import kranji.singular.space.SpaceAndDirection;
import kranji.zi.ComposedPart;
import kranji.zi.ComposedZi;
import kranji.zi.CompositionLayout.*;
import kranji.zi.SingularPart;
import kranji.zi.ZiChar;
import java.util.List;

public final class Ia1 {

    private Ia1() {}

    public static final ComposedZi YA_PRESS = new ComposedZi(
            new ZiChar.Unicode("\u62BC"),
            new PinyinSyllable(Initial.ZERO, new Final(Head.I, Body.A, Tail.NONE), Tone.FIRST),
            8, 64, "",
            new LeftRight(BasicComponents.TI_SHOU_PANG, SpaceAndDirection.JIA_FIRST),
            new PhonoSemantic(BasicComponents.TI_SHOU_PANG, SpaceAndDirection.JIA_FIRST));

    public static final List<ComposedZi> ALL = List.of(
            YA_PRESS);
}
