// AUTO-GENERATED by Depth1GenerateMain - do not edit by hand.
package kranji.common.depth1.zero;

import kranji.classification.EtymologicalCategory.*;
import kranji.component.basic.BasicComponents;
import kranji.pinyin.Body;
import kranji.pinyin.Final;
import kranji.pinyin.Head;
import kranji.pinyin.Initial;
import kranji.pinyin.PinyinSyllable;
import kranji.pinyin.Tail;
import kranji.pinyin.Tone;
import kranji.singular.radicals.RadicalComponents;
import kranji.singular.tools.ToolsAndVessels;
import kranji.zi.ComposedPart;
import kranji.zi.ComposedZi;
import kranji.zi.CompositionLayout.*;
import kranji.zi.SingularPart;
import kranji.zi.ZiChar;
import java.util.List;

public final class In3 {

    private In3() {}

    public static final ComposedZi YIN_DRINK = new ComposedZi(
            new ZiChar.Unicode("\u996E"),
            new PinyinSyllable(Initial.ZERO, new Final(Head.OPEN, Body.I, Tail.N), Tone.THIRD),
            7, 184, "",
            new LeftRight(BasicComponents.SHI_ZI_PANG, RadicalComponents.QIAN_OWE),
            new PhonoSemantic(BasicComponents.SHI_ZI_PANG, RadicalComponents.QIAN_OWE));

    public static final ComposedZi YIN_PULL = new ComposedZi(
            new ZiChar.Unicode("\u5F15"),
            new PinyinSyllable(Initial.ZERO, new Final(Head.OPEN, Body.I, Tail.N), Tone.THIRD),
            4, 57, "",
            new LeftRight(ToolsAndVessels.GONG, RadicalComponents.GUN),
            new CompoundIndicative("弓(bow) + 丨(string) → draw, pull"));

    public static final List<ComposedZi> ALL = List.of(
            YIN_DRINK,
            YIN_PULL);
}
