// AUTO-GENERATED by CatalogIteratorMain - do not edit by hand.
package kranji.common.perclass.promoted.p.ou1;

import kranji.classification.EtymologicalCategory;
import kranji.common.perclass.promoted.p.ou3.PouPou;
import kranji.component.basic.BasicComponents;
import kranji.component.basic.KnifeFamily;
import kranji.pinyin.Body;
import kranji.pinyin.Final;
import kranji.pinyin.Head;
import kranji.pinyin.Initial;
import kranji.pinyin.PinyinSyllable;
import kranji.pinyin.Tail;
import kranji.pinyin.Tone;
import kranji.zi.ComposedZiT;
import kranji.zi.CompositionLayoutT;
import kranji.zi.LeftRightT;

public record PouCut() implements ComposedZiT, LeftRightT<PouPou, KnifeFamily.LiDaoPang> {

    public static final PouCut INSTANCE = new PouCut();

    @Override public PouPou left() { return PouPou.INSTANCE; }
    @Override public KnifeFamily.LiDaoPang right() { return BasicComponents.LI_DAO_PANG; }

    @Override public CompositionLayoutT layout() { return this; }

    @Override public String glyph() { return "\u5256"; }

    @Override public PinyinSyllable pinyin() {
        return new PinyinSyllable(Initial.P, new Final(Head.OPEN, Body.O, Tail.VOWEL_U), Tone.FIRST);
    }

    @Override public int strokes() { return 0; }
    @Override public int radicalNo() { return 0; }
    @Override public String meaning() { return ""; }

    @Override public EtymologicalCategory etymology() {
        return new EtymologicalCategory.PhonoSemantic(BasicComponents.LI_DAO_PANG, PouPou.INSTANCE);
    }
}
