// AUTO-GENERATED by PerclassGenerateMain - do not edit by hand.
package kranji.common.perclass.k.en3;

import kranji.classification.EtymologicalCategory;
import kranji.pinyin.Body;
import kranji.pinyin.Final;
import kranji.pinyin.Head;
import kranji.pinyin.Initial;
import kranji.pinyin.PinyinSyllable;
import kranji.pinyin.Tail;
import kranji.pinyin.Tone;
import kranji.singular.body.BodyParts;
import kranji.singular.body.BodyParts.Gen_Tough;
import kranji.singular.nature.NatureElements;
import kranji.singular.nature.NatureElements.Tu;
import kranji.zi.ComposedZiT;
import kranji.zi.CompositionLayoutT;
import kranji.zi.TopBottomT;

public record KenReclaim() implements ComposedZiT, TopBottomT<Gen_Tough, Tu> {

    public static final KenReclaim INSTANCE = new KenReclaim();

    @Override public Gen_Tough top() { return BodyParts.GEN_TOUGH; }
    @Override public Tu bottom() { return NatureElements.TU; }

    @Override public CompositionLayoutT layout() { return this; }

    @Override public String glyph() { return "\u57A6"; }

    @Override public PinyinSyllable pinyin() {
        return new PinyinSyllable(Initial.K, new Final(Head.OPEN, Body.E, Tail.N), Tone.THIRD);
    }

    @Override public int strokes() { return 9; }
    @Override public int radicalNo() { return 32; }
    @Override public String meaning() { return ""; }

    @Override public EtymologicalCategory etymology() {
        return new EtymologicalCategory.CompoundIndicative("simplified from 墾; 艮(firm) + 土(earth) → reclaim, cultivate land");
    }
}
