// AUTO-GENERATED by kranji-codegen. Do not edit by hand.
package kranji.singular.radicals.p;

import kranji.library.BasicSet;
import kranji.library.LibraryMember;
import kranji.zi.SingularPart;

public record Pai_Spread() implements LibraryMember<BasicSet>, SingularPart {
    public static final Pai_Spread INSTANCE = new Pai_Spread();

    @Override public String glyph() { return "\uD840\uDCA2"; }
    @Override public String meaning() { return "spreading lines"; }
    @Override public String pinyinText() { return "p\u00E0i"; }
    @Override public int strokes() { return 4; }
    @Override public BasicSet library() { return BasicSet.INSTANCE; }
}
