// AUTO-GENERATED by CatalogIteratorMain - do not edit by hand.
package kranji.common.perclass.promoted.l.v4;

import kranji.classification.EtymologicalCategory;
import kranji.component.basic.BasicComponents;
import kranji.component.basic.SilkFamily;
import kranji.pinyin.Body;
import kranji.pinyin.Final;
import kranji.pinyin.Head;
import kranji.pinyin.Initial;
import kranji.pinyin.PinyinSyllable;
import kranji.pinyin.Tail;
import kranji.pinyin.Tone;
import kranji.singular.actions.ActionsAndStates;
import kranji.zi.ComposedZiT;
import kranji.zi.CompositionLayoutT;
import kranji.zi.LeftRightT;

public record LvGreen() implements ComposedZiT, LeftRightT<SilkFamily.JiaoSiPang, ActionsAndStates.Lu_Record> {

    public static final LvGreen INSTANCE = new LvGreen();

    @Override public SilkFamily.JiaoSiPang left() { return BasicComponents.JIAO_SI_PANG; }
    @Override public ActionsAndStates.Lu_Record right() { return ActionsAndStates.LU_RECORD; }

    @Override public CompositionLayoutT layout() { return this; }

    @Override public String glyph() { return "\u7EFF"; }

    @Override public PinyinSyllable pinyin() {
        return new PinyinSyllable(Initial.L, new Final(Head.V, Body.U, Tail.NONE), Tone.FOURTH);
    }

    @Override public int strokes() { return 0; }
    @Override public int radicalNo() { return 0; }
    @Override public String meaning() { return ""; }

    @Override public EtymologicalCategory etymology() {
        return new EtymologicalCategory.PhonoSemantic(BasicComponents.JIAO_SI_PANG, ActionsAndStates.LU_RECORD);
    }
}
