// AUTO-GENERATED by kranji-codegen. Do not edit by hand.
package kranji.singular.body.m;

import kranji.library.BasicSet;
import kranji.library.LibraryMember;
import kranji.zi.SingularZi;

public record Mao() implements LibraryMember<BasicSet>, SingularZi {
    public static final Mao INSTANCE = new Mao();

    @Override public String glyph() { return "\u6BDB"; }
    @Override public String meaning() { return "hair, fur"; }
    @Override public String pinyinText() { return "m\u00E1o"; }
    @Override public int strokes() { return 4; }
    @Override public BasicSet library() { return BasicSet.INSTANCE; }
}
