// AUTO-GENERATED by CatalogIteratorMain - do not edit by hand.
package kranji.common.perclass.promoted.g.e2;

import kranji.pinyin.Body;
import kranji.pinyin.Final;
import kranji.pinyin.Head;
import kranji.pinyin.Initial;
import kranji.pinyin.PinyinSyllable;
import kranji.pinyin.Tail;
import kranji.pinyin.Tone;
import kranji.zi.SingularZi;

public record GeGeAuto() implements SingularZi {

    public static final GeGeAuto INSTANCE = new GeGeAuto();

    @Override public String glyph() { return "\u9B32"; }

    @Override public PinyinSyllable pinyin() {
        return new PinyinSyllable(Initial.G, new Final(Head.OPEN, Body.E, Tail.NONE), Tone.SECOND);
    }

    @Override public boolean unsure() { return true; }
}
