// AUTO-GENERATED by CatalogIteratorMain - do not edit by hand.
package kranji.common.perclass.promoted.t.ao1;

import kranji.classification.EtymologicalCategory;
import kranji.common.perclass.promoted.t.ao2.TaoTao;
import kranji.component.basic.BasicComponents;
import kranji.component.basic.HandFamily;
import kranji.pinyin.Body;
import kranji.pinyin.Final;
import kranji.pinyin.Head;
import kranji.pinyin.Initial;
import kranji.pinyin.PinyinSyllable;
import kranji.pinyin.Tail;
import kranji.pinyin.Tone;
import kranji.zi.ComposedZiT;
import kranji.zi.CompositionLayoutT;
import kranji.zi.LeftRightT;

public record TaoScoop() implements ComposedZiT, LeftRightT<HandFamily.TiShouPang, TaoTao> {

    public static final TaoScoop INSTANCE = new TaoScoop();

    @Override public HandFamily.TiShouPang left() { return BasicComponents.TI_SHOU_PANG; }
    @Override public TaoTao right() { return TaoTao.INSTANCE; }

    @Override public CompositionLayoutT layout() { return this; }

    @Override public String glyph() { return "\u638F"; }

    @Override public PinyinSyllable pinyin() {
        return new PinyinSyllable(Initial.T, new Final(Head.OPEN, Body.A, Tail.VOWEL_U), Tone.FIRST);
    }

    @Override public int strokes() { return 0; }
    @Override public int radicalNo() { return 0; }
    @Override public String meaning() { return ""; }

    @Override public EtymologicalCategory etymology() {
        return new EtymologicalCategory.PhonoSemantic(BasicComponents.TI_SHOU_PANG, TaoTao.INSTANCE);
    }
}
