// AUTO-GENERATED by CatalogIteratorMain - do not edit by hand.
package kranji.common.perclass.promoted.h.ua1;

import kranji.classification.EtymologicalCategory;
import kranji.common.perclass.promoted.h.ua2.HuaChina;
import kranji.pinyin.Body;
import kranji.pinyin.Final;
import kranji.pinyin.Head;
import kranji.pinyin.Initial;
import kranji.pinyin.PinyinSyllable;
import kranji.pinyin.Tail;
import kranji.pinyin.Tone;
import kranji.singular.body.BodyParts;
import kranji.zi.ComposedZiT;
import kranji.zi.CompositionLayoutT;
import kranji.zi.LeftRightT;

public record HuaClamor() implements ComposedZiT, LeftRightT<BodyParts.Kou, HuaChina> {

    public static final HuaClamor INSTANCE = new HuaClamor();

    @Override public BodyParts.Kou left() { return BodyParts.KOU; }
    @Override public HuaChina right() { return HuaChina.INSTANCE; }

    @Override public CompositionLayoutT layout() { return this; }

    @Override public String glyph() { return "\u54D7"; }

    @Override public PinyinSyllable pinyin() {
        return new PinyinSyllable(Initial.H, new Final(Head.U, Body.A, Tail.NONE), Tone.FIRST);
    }

    @Override public int strokes() { return 0; }
    @Override public int radicalNo() { return 0; }
    @Override public String meaning() { return ""; }

    @Override public EtymologicalCategory etymology() {
        return new EtymologicalCategory.PhonoSemantic(BodyParts.KOU, HuaChina.INSTANCE);
    }
}
