// AUTO-GENERATED by CatalogIteratorMain - do not edit by hand.
package kranji.common.perclass.promoted.zh.an3;

import kranji.classification.EtymologicalCategory;
import kranji.common.perclass.zh.an3.ZhanChop;
import kranji.pinyin.Body;
import kranji.pinyin.Final;
import kranji.pinyin.Head;
import kranji.pinyin.Initial;
import kranji.pinyin.PinyinSyllable;
import kranji.pinyin.Tail;
import kranji.pinyin.Tone;
import kranji.singular.nature.NatureElements;
import kranji.zi.ComposedZiT;
import kranji.zi.CompositionLayoutT;
import kranji.zi.TopBottomT;

public record ZhanTowering() implements ComposedZiT, TopBottomT<NatureElements.Shan, ZhanChop> {

    public static final ZhanTowering INSTANCE = new ZhanTowering();

    @Override public NatureElements.Shan top() { return NatureElements.SHAN; }
    @Override public ZhanChop bottom() { return ZhanChop.INSTANCE; }

    @Override public CompositionLayoutT layout() { return this; }

    @Override public String glyph() { return "\u5D2D"; }

    @Override public PinyinSyllable pinyin() {
        return new PinyinSyllable(Initial.ZH, new Final(Head.OPEN, Body.A, Tail.N), Tone.THIRD);
    }

    @Override public int strokes() { return 0; }
    @Override public int radicalNo() { return 0; }
    @Override public String meaning() { return ""; }

    @Override public EtymologicalCategory etymology() {
        return new EtymologicalCategory.PhonoSemantic(NatureElements.SHAN, ZhanChop.INSTANCE);
    }
}
