// AUTO-GENERATED by CatalogIteratorMain - do not edit by hand.
package kranji.common.perclass.promoted.sh.i2;

import kranji.classification.EtymologicalCategory;
import kranji.pinyin.Body;
import kranji.pinyin.Final;
import kranji.pinyin.Head;
import kranji.pinyin.Initial;
import kranji.pinyin.PinyinSyllable;
import kranji.pinyin.Tail;
import kranji.pinyin.Tone;
import kranji.singular.actions.ActionsAndStates;
import kranji.singular.animals.Animals;
import kranji.zi.ComposedZiT;
import kranji.zi.CompositionLayoutT;
import kranji.zi.TopBottomT;

public record ShiErode() implements ComposedZiT, TopBottomT<ActionsAndStates.Shi_Eat, Animals.Chong> {

    public static final ShiErode INSTANCE = new ShiErode();

    @Override public ActionsAndStates.Shi_Eat top() { return ActionsAndStates.SHI_EAT; }
    @Override public Animals.Chong bottom() { return Animals.CHONG; }

    @Override public CompositionLayoutT layout() { return this; }

    @Override public String glyph() { return "\u8680"; }

    @Override public PinyinSyllable pinyin() {
        return new PinyinSyllable(Initial.SH, new Final(Head.OPEN, Body.I, Tail.NONE), Tone.SECOND);
    }

    @Override public int strokes() { return 0; }
    @Override public int radicalNo() { return 0; }
    @Override public String meaning() { return ""; }

    @Override public EtymologicalCategory etymology() {
        return new EtymologicalCategory.PhonoSemantic(Animals.CHONG, ActionsAndStates.SHI_EAT);
    }
}
