// AUTO-GENERATED by CatalogIteratorMain - do not edit by hand.
package kranji.common.perclass.promoted.l.v3;

import kranji.classification.EtymologicalCategory;
import kranji.common.perclass.c.ong2.CongFrom;
import kranji.pinyin.Body;
import kranji.pinyin.Final;
import kranji.pinyin.Head;
import kranji.pinyin.Initial;
import kranji.pinyin.PinyinSyllable;
import kranji.pinyin.Tail;
import kranji.pinyin.Tone;
import kranji.singular.radicals.RadicalComponents;
import kranji.zi.ComposedZiT;
import kranji.zi.CompositionLayoutT;
import kranji.zi.LeftRightT;

public record LvTravel_Inner1() implements ComposedZiT, LeftRightT<RadicalComponents.Hua_Stroke, CongFrom> {

    public static final LvTravel_Inner1 INSTANCE = new LvTravel_Inner1();

    @Override public RadicalComponents.Hua_Stroke left() { return RadicalComponents.HUA_STROKE; }
    @Override public CongFrom right() { return CongFrom.INSTANCE; }

    @Override public CompositionLayoutT layout() { return this; }

    @Override public String glyph() { return ""; }

    @Override public PinyinSyllable pinyin() {
        return new PinyinSyllable(Initial.L, new Final(Head.V, Body.U, Tail.NONE), Tone.THIRD);
    }

    @Override public int strokes() { return 0; }
    @Override public int radicalNo() { return 0; }
    @Override public String meaning() { return ""; }

    @Override public EtymologicalCategory etymology() {
        return new EtymologicalCategory.CompoundIndicative("");
    }
}
