// AUTO-GENERATED by CatalogIteratorMain - do not edit by hand.
package kranji.common.perclass.promoted.zh.eng1;

import kranji.classification.EtymologicalCategory;
import kranji.component.basic.BasicComponents;
import kranji.component.basic.HandFamily;
import kranji.pinyin.Body;
import kranji.pinyin.Final;
import kranji.pinyin.Head;
import kranji.pinyin.Initial;
import kranji.pinyin.PinyinSyllable;
import kranji.pinyin.Tail;
import kranji.pinyin.Tone;
import kranji.singular.actions.ActionsAndStates;
import kranji.zi.ComposedZiT;
import kranji.zi.CompositionLayoutT;
import kranji.zi.LeftRightT;

public record ZhengEarn() implements ComposedZiT, LeftRightT<HandFamily.TiShouPang, ActionsAndStates.Zheng_Contest> {

    public static final ZhengEarn INSTANCE = new ZhengEarn();

    @Override public HandFamily.TiShouPang left() { return BasicComponents.TI_SHOU_PANG; }
    @Override public ActionsAndStates.Zheng_Contest right() { return ActionsAndStates.ZHENG_CONTEST; }

    @Override public CompositionLayoutT layout() { return this; }

    @Override public String glyph() { return "\u6323"; }

    @Override public PinyinSyllable pinyin() {
        return new PinyinSyllable(Initial.ZH, new Final(Head.OPEN, Body.E, Tail.NG), Tone.FIRST);
    }

    @Override public int strokes() { return 0; }
    @Override public int radicalNo() { return 0; }
    @Override public String meaning() { return ""; }

    @Override public EtymologicalCategory etymology() {
        return new EtymologicalCategory.PhonoSemantic(BasicComponents.TI_SHOU_PANG, ActionsAndStates.ZHENG_CONTEST);
    }
}
