// AUTO-GENERATED by CatalogIteratorMain - do not edit by hand.
package kranji.common.perclass.promoted.b.eng1;

import kranji.pinyin.Body;
import kranji.pinyin.Final;
import kranji.pinyin.Head;
import kranji.pinyin.Initial;
import kranji.pinyin.PinyinSyllable;
import kranji.pinyin.Tail;
import kranji.pinyin.Tone;
import kranji.zi.SingularZi;

public record BengBengAuto() implements SingularZi {

    public static final BengBengAuto INSTANCE = new BengBengAuto();

    @Override public String glyph() { return "\u5D29"; }

    @Override public PinyinSyllable pinyin() {
        return new PinyinSyllable(Initial.B, new Final(Head.OPEN, Body.E, Tail.NG), Tone.FIRST);
    }

    @Override public boolean unsure() { return true; }
}
