// AUTO-GENERATED by PerclassGenerateMain - do not edit by hand.
package kranji.common.perclass.zero.u2;

import kranji.classification.EtymologicalCategory;
import kranji.pinyin.Body;
import kranji.pinyin.Final;
import kranji.pinyin.Head;
import kranji.pinyin.Initial;
import kranji.pinyin.PinyinSyllable;
import kranji.pinyin.Tail;
import kranji.pinyin.Tone;
import kranji.singular.body.BodyParts;
import kranji.singular.body.BodyParts.Kou;
import kranji.singular.nature.NatureElements;
import kranji.singular.nature.NatureElements.Tian_Sky;
import kranji.zi.ComposedZiT;
import kranji.zi.CompositionLayoutT;
import kranji.zi.TopBottomT;

public record WuSurname() implements ComposedZiT, TopBottomT<Kou, Tian_Sky> {

    public static final WuSurname INSTANCE = new WuSurname();

    @Override public Kou top() { return BodyParts.KOU; }
    @Override public Tian_Sky bottom() { return NatureElements.TIAN_SKY; }

    @Override public CompositionLayoutT layout() { return this; }

    @Override public String glyph() { return "\u5434"; }

    @Override public PinyinSyllable pinyin() {
        return new PinyinSyllable(Initial.ZERO, new Final(Head.U, Body.U, Tail.NONE), Tone.SECOND);
    }

    @Override public int strokes() { return 7; }
    @Override public int radicalNo() { return 30; }
    @Override public String meaning() { return ""; }

    @Override public EtymologicalCategory etymology() {
        return new EtymologicalCategory.CompoundIndicative("口(mouth) + 天(heaven) → cry out loud");
    }
}
