// AUTO-GENERATED by PerclassGenerateMain - do not edit by hand.
package kranji.common.perclass.b.u3;

import kranji.classification.EtymologicalCategory;
import kranji.component.basic.BasicComponents;
import kranji.component.basic.ClothingFamily.YiZiPang;
import kranji.pinyin.Body;
import kranji.pinyin.Final;
import kranji.pinyin.Head;
import kranji.pinyin.Initial;
import kranji.pinyin.PinyinSyllable;
import kranji.pinyin.Tail;
import kranji.pinyin.Tone;
import kranji.singular.tools.ToolsAndVessels;
import kranji.singular.tools.ToolsAndVessels.Bu_Divination;
import kranji.zi.ComposedZiT;
import kranji.zi.CompositionLayoutT;
import kranji.zi.LeftRightT;

public record BuMend() implements ComposedZiT, LeftRightT<YiZiPang, Bu_Divination> {

    public static final BuMend INSTANCE = new BuMend();

    @Override public YiZiPang left() { return BasicComponents.YI_ZI_PANG; }
    @Override public Bu_Divination right() { return ToolsAndVessels.BU_DIVINATION; }

    @Override public CompositionLayoutT layout() { return this; }

    @Override public String glyph() { return "\u8865"; }

    @Override public PinyinSyllable pinyin() {
        return new PinyinSyllable(Initial.B, new Final(Head.U, Body.U, Tail.NONE), Tone.THIRD);
    }

    @Override public int strokes() { return 7; }
    @Override public int radicalNo() { return 145; }
    @Override public String meaning() { return ""; }

    @Override public EtymologicalCategory etymology() {
        return new EtymologicalCategory.PhonoSemantic(BasicComponents.YI_ZI_PANG, ToolsAndVessels.BU_DIVINATION);
    }
}
