// AUTO-GENERATED by CatalogIteratorMain - do not edit by hand.
package kranji.common.perclass.promoted.d.e2;

import kranji.classification.EtymologicalCategory;
import kranji.common.perclass.promoted.d.e2.DeObtainAtom;
import kranji.pinyin.Body;
import kranji.pinyin.Final;
import kranji.pinyin.Head;
import kranji.pinyin.Initial;
import kranji.pinyin.PinyinSyllable;
import kranji.pinyin.Tail;
import kranji.pinyin.Tone;
import kranji.singular.tools.ToolsAndVessels;
import kranji.zi.ComposedZiT;
import kranji.zi.CompositionLayoutT;
import kranji.zi.LeftRightT;

public record DeObtain() implements ComposedZiT, LeftRightT<ToolsAndVessels.Chi_Step, DeObtainAtom> {

    public static final DeObtain INSTANCE = new DeObtain();

    @Override public ToolsAndVessels.Chi_Step left() { return ToolsAndVessels.CHI_STEP; }
    @Override public DeObtainAtom right() { return DeObtainAtom.INSTANCE; }

    @Override public CompositionLayoutT layout() { return this; }

    @Override public String glyph() { return "\u5F97"; }

    @Override public PinyinSyllable pinyin() {
        return new PinyinSyllable(Initial.D, new Final(Head.OPEN, Body.E, Tail.NONE), Tone.SECOND);
    }

    @Override public int strokes() { return 0; }
    @Override public int radicalNo() { return 0; }
    @Override public String meaning() { return ""; }

    @Override public EtymologicalCategory etymology() {
        return new EtymologicalCategory.PhonoSemantic(ToolsAndVessels.CHI_STEP, DeObtainAtom.INSTANCE);
    }
}
