// AUTO-GENERATED by CatalogIteratorMain - do not edit by hand.
package kranji.common.perclass.promoted.l.ie4;

import kranji.classification.EtymologicalCategory;
import kranji.common.perclass.promoted.l.ie4.LieArrange;
import kranji.pinyin.Body;
import kranji.pinyin.Final;
import kranji.pinyin.Head;
import kranji.pinyin.Initial;
import kranji.pinyin.PinyinSyllable;
import kranji.pinyin.Tail;
import kranji.pinyin.Tone;
import kranji.singular.materials.Materials;
import kranji.zi.ComposedZiT;
import kranji.zi.CompositionLayoutT;
import kranji.zi.TopBottomT;

public record LieSplit() implements ComposedZiT, TopBottomT<LieArrange, Materials.Yi_Clothes> {

    public static final LieSplit INSTANCE = new LieSplit();

    @Override public LieArrange top() { return LieArrange.INSTANCE; }
    @Override public Materials.Yi_Clothes bottom() { return Materials.YI_CLOTHES; }

    @Override public CompositionLayoutT layout() { return this; }

    @Override public String glyph() { return "\u88C2"; }

    @Override public PinyinSyllable pinyin() {
        return new PinyinSyllable(Initial.L, new Final(Head.I, Body.E_CARON, Tail.NONE), Tone.FOURTH);
    }

    @Override public int strokes() { return 0; }
    @Override public int radicalNo() { return 0; }
    @Override public String meaning() { return ""; }

    @Override public EtymologicalCategory etymology() {
        return new EtymologicalCategory.PhonoSemantic(Materials.YI_CLOTHES, LieArrange.INSTANCE);
    }
}
