// AUTO-GENERATED by CatalogIteratorMain - do not edit by hand.
package kranji.common.perclass.promoted.ch.uan3;

import kranji.classification.EtymologicalCategory;
import kranji.pinyin.Body;
import kranji.pinyin.Final;
import kranji.pinyin.Head;
import kranji.pinyin.Initial;
import kranji.pinyin.PinyinSyllable;
import kranji.pinyin.Tail;
import kranji.pinyin.Tone;
import kranji.singular.body.BodyParts;
import kranji.singular.radicals.RadicalComponents;
import kranji.zi.ComposedZiT;
import kranji.zi.CompositionLayoutT;
import kranji.zi.LeftRightT;

public record ChuanPant() implements ComposedZiT, LeftRightT<BodyParts.Kou, RadicalComponents.Duan_Upright> {

    public static final ChuanPant INSTANCE = new ChuanPant();

    @Override public BodyParts.Kou left() { return BodyParts.KOU; }
    @Override public RadicalComponents.Duan_Upright right() { return RadicalComponents.DUAN_UPRIGHT; }

    @Override public CompositionLayoutT layout() { return this; }

    @Override public String glyph() { return "\u5598"; }

    @Override public PinyinSyllable pinyin() {
        return new PinyinSyllable(Initial.CH, new Final(Head.U, Body.A, Tail.N), Tone.THIRD);
    }

    @Override public int strokes() { return 0; }
    @Override public int radicalNo() { return 0; }
    @Override public String meaning() { return ""; }

    @Override public EtymologicalCategory etymology() {
        return new EtymologicalCategory.PhonoSemantic(BodyParts.KOU, RadicalComponents.DUAN_UPRIGHT);
    }
}
