// AUTO-GENERATED by kranji-codegen. Do not edit by hand.
package kranji.singular.tools.ch;

import kranji.library.BasicSet;
import kranji.library.LibraryMember;
import kranji.zi.SingularZi;

public record Che() implements LibraryMember<BasicSet>, SingularZi {
    public static final Che INSTANCE = new Che();

    @Override public String glyph() { return "\u8F66"; }
    @Override public String meaning() { return "vehicle"; }
    @Override public String pinyinText() { return "ch\u0113"; }
    @Override public int strokes() { return 4; }
    @Override public BasicSet library() { return BasicSet.INSTANCE; }
}
