// AUTO-GENERATED by PerclassGenerateMain - do not edit by hand.
package kranji.common.perclass.h.ao3;

import kranji.classification.EtymologicalCategory;
import kranji.pinyin.Body;
import kranji.pinyin.Final;
import kranji.pinyin.Head;
import kranji.pinyin.Initial;
import kranji.pinyin.PinyinSyllable;
import kranji.pinyin.Tail;
import kranji.pinyin.Tone;
import kranji.singular.people.PeopleAndRoles;
import kranji.singular.people.PeopleAndRoles.Nv;
import kranji.singular.people.PeopleAndRoles.Zi;
import kranji.zi.ComposedZiT;
import kranji.zi.CompositionLayoutT;
import kranji.zi.LeftRightT;

public record Hao() implements ComposedZiT, LeftRightT<Nv, Zi> {

    public static final Hao INSTANCE = new Hao();

    @Override public Nv left() { return PeopleAndRoles.NV; }
    @Override public Zi right() { return PeopleAndRoles.ZI; }

    @Override public CompositionLayoutT layout() { return this; }

    @Override public String glyph() { return "\u597D"; }

    @Override public PinyinSyllable pinyin() {
        return new PinyinSyllable(Initial.H, new Final(Head.OPEN, Body.A, Tail.VOWEL_U), Tone.THIRD);
    }

    @Override public int strokes() { return 6; }
    @Override public int radicalNo() { return 38; }
    @Override public String meaning() { return ""; }

    @Override public EtymologicalCategory etymology() {
        return new EtymologicalCategory.CompoundIndicative("女(woman) + 子(child) → good");
    }
}
