// AUTO-GENERATED by CatalogIteratorMain - do not edit by hand.
package kranji.common.perclass.promoted.ch.eng2;

import kranji.pinyin.Body;
import kranji.pinyin.Final;
import kranji.pinyin.Head;
import kranji.pinyin.Initial;
import kranji.pinyin.PinyinSyllable;
import kranji.pinyin.Tail;
import kranji.pinyin.Tone;
import kranji.zi.SingularZi;

public record ChengChengAuto() implements SingularZi {

    public static final ChengChengAuto INSTANCE = new ChengChengAuto();

    @Override public String glyph() { return "\u4E58"; }

    @Override public PinyinSyllable pinyin() {
        return new PinyinSyllable(Initial.CH, new Final(Head.OPEN, Body.E, Tail.NG), Tone.SECOND);
    }

    @Override public boolean unsure() { return true; }
}
