// AUTO-GENERATED by Depth1GenerateMain - do not edit by hand.
package kranji.common.depth1.g;

import kranji.classification.EtymologicalCategory.*;
import kranji.component.basic.BasicComponents;
import kranji.pinyin.Body;
import kranji.pinyin.Final;
import kranji.pinyin.Head;
import kranji.pinyin.Initial;
import kranji.pinyin.PinyinSyllable;
import kranji.pinyin.Tail;
import kranji.pinyin.Tone;
import kranji.singular.concepts.AbstractConcepts;
import kranji.zi.ComposedPart;
import kranji.zi.ComposedZi;
import kranji.zi.CompositionLayout.*;
import kranji.zi.SingularPart;
import kranji.zi.ZiChar;
import java.util.List;

public final class U4 {

    private U4() {}

    public static final ComposedZi GU_SOLID = new ComposedZi(
            new ZiChar.Unicode("\u56FA"),
            new PinyinSyllable(Initial.G, new Final(Head.U, Body.U, Tail.NONE), Tone.FOURTH),
            8, 31, "",
            new FullEnclosure(BasicComponents.GUO_ZI_KUANG, AbstractConcepts.GU),
            new PhonoSemantic(BasicComponents.GUO_ZI_KUANG, AbstractConcepts.GU));

    public static final List<ComposedZi> ALL = List.of(
            GU_SOLID);
}
