// AUTO-GENERATED by Depth1GenerateMain - do not edit by hand.
package kranji.common.depth1.g;

import kranji.classification.EtymologicalCategory.*;
import kranji.component.basic.BasicComponents;
import kranji.pinyin.Body;
import kranji.pinyin.Final;
import kranji.pinyin.Head;
import kranji.pinyin.Initial;
import kranji.pinyin.PinyinSyllable;
import kranji.pinyin.Tail;
import kranji.pinyin.Tone;
import kranji.singular.materials.Materials;
import kranji.zi.ComposedPart;
import kranji.zi.ComposedZi;
import kranji.zi.CompositionLayout.*;
import kranji.zi.SingularPart;
import kranji.zi.ZiChar;
import java.util.List;

public final class Uo2 {

    private Uo2() {}

    public static final ComposedZi GUO = new ComposedZi(
            new ZiChar.Unicode("\u56FD"),
            new PinyinSyllable(Initial.G, new Final(Head.U, Body.O, Tail.NONE), Tone.SECOND),
            8, 31, "",
            new FullEnclosure(BasicComponents.GUO_ZI_KUANG, Materials.YU_JADE),
            new PhonoSemantic(BasicComponents.GUO_ZI_KUANG, Materials.YU_JADE));

    public static final List<ComposedZi> ALL = List.of(
            GUO);
}
