// AUTO-GENERATED by CatalogIteratorMain - do not edit by hand.
package kranji.common.perclass.promoted.c.a1;

import kranji.classification.EtymologicalCategory;
import kranji.common.perclass.ch.a2.ChaInspect;
import kranji.component.basic.BasicComponents;
import kranji.component.basic.HandFamily;
import kranji.pinyin.Body;
import kranji.pinyin.Final;
import kranji.pinyin.Head;
import kranji.pinyin.Initial;
import kranji.pinyin.PinyinSyllable;
import kranji.pinyin.Tail;
import kranji.pinyin.Tone;
import kranji.zi.ComposedZiT;
import kranji.zi.CompositionLayoutT;
import kranji.zi.LeftRightT;

public record CaWipe() implements ComposedZiT, LeftRightT<HandFamily.TiShouPang, ChaInspect> {

    public static final CaWipe INSTANCE = new CaWipe();

    @Override public HandFamily.TiShouPang left() { return BasicComponents.TI_SHOU_PANG; }
    @Override public ChaInspect right() { return ChaInspect.INSTANCE; }

    @Override public CompositionLayoutT layout() { return this; }

    @Override public String glyph() { return "\u64E6"; }

    @Override public PinyinSyllable pinyin() {
        return new PinyinSyllable(Initial.C, new Final(Head.OPEN, Body.A, Tail.NONE), Tone.FIRST);
    }

    @Override public int strokes() { return 0; }
    @Override public int radicalNo() { return 0; }
    @Override public String meaning() { return ""; }

    @Override public EtymologicalCategory etymology() {
        return new EtymologicalCategory.PhonoSemantic(BasicComponents.TI_SHOU_PANG, ChaInspect.INSTANCE);
    }
}
