// AUTO-GENERATED by Depth2GenerateMain - do not edit by hand.
package kranji.common.depth2.n;

import kranji.classification.EtymologicalCategory.*;
import kranji.component.basic.BasicComponents;
import kranji.pinyin.Body;
import kranji.pinyin.Final;
import kranji.pinyin.Head;
import kranji.pinyin.Initial;
import kranji.pinyin.PinyinSyllable;
import kranji.pinyin.Tail;
import kranji.pinyin.Tone;
import kranji.zi.ComposedPart;
import kranji.zi.ComposedZi;
import kranji.zi.CompositionLayout.*;
import kranji.zi.SingularPart;
import kranji.zi.ZiChar;
import java.util.List;

public final class I2 {

    private I2() {}

    public static final ComposedZi NI_MUD = new ComposedZi(
            new ZiChar.Unicode("\u6CE5"),
            new PinyinSyllable(Initial.N, new Final(Head.OPEN, Body.I, Tail.NONE), Tone.SECOND),
            8, 85, "",
            new LeftRight(BasicComponents.SAN_DIAN_SHUI, kranji.common.depth1.n.I2.NI_NUN.structure()),
            new PhonoSemantic(BasicComponents.SAN_DIAN_SHUI, kranji.common.depth1.n.I2.NI_NUN.structure()));

    public static final List<ComposedZi> ALL = List.of(
            NI_MUD);
}
