// AUTO-GENERATED by CatalogIteratorMain - do not edit by hand.
package kranji.common.perclass.promoted.t.ou4;

import kranji.classification.EtymologicalCategory;
import kranji.common.perclass.x.iou4.XiuElegant;
import kranji.component.basic.BasicComponents;
import kranji.component.basic.MovementFamily;
import kranji.pinyin.Body;
import kranji.pinyin.Final;
import kranji.pinyin.Head;
import kranji.pinyin.Initial;
import kranji.pinyin.PinyinSyllable;
import kranji.pinyin.Tail;
import kranji.pinyin.Tone;
import kranji.zi.ComposedZiT;
import kranji.zi.CompositionLayoutT;
import kranji.zi.SemiEnclosureBottomLeftT;

public record TouPierce() implements ComposedZiT, SemiEnclosureBottomLeftT<MovementFamily.ZouZhiDi, XiuElegant> {

    public static final TouPierce INSTANCE = new TouPierce();

    @Override public MovementFamily.ZouZhiDi wrapper() { return BasicComponents.ZOU_ZHI_DI; }
    @Override public XiuElegant content() { return XiuElegant.INSTANCE; }

    @Override public CompositionLayoutT layout() { return this; }

    @Override public String glyph() { return "\u900F"; }

    @Override public PinyinSyllable pinyin() {
        return new PinyinSyllable(Initial.T, new Final(Head.OPEN, Body.O, Tail.VOWEL_U), Tone.FOURTH);
    }

    @Override public int strokes() { return 0; }
    @Override public int radicalNo() { return 0; }
    @Override public String meaning() { return ""; }

    @Override public EtymologicalCategory etymology() {
        return new EtymologicalCategory.PhonoSemantic(BasicComponents.ZOU_ZHI_DI, XiuElegant.INSTANCE);
    }
}
