// AUTO-GENERATED by CatalogIteratorMain - do not edit by hand.
package kranji.common.perclass.promoted.h.ai1;

import kranji.classification.EtymologicalCategory;
import kranji.pinyin.Body;
import kranji.pinyin.Final;
import kranji.pinyin.Head;
import kranji.pinyin.Initial;
import kranji.pinyin.PinyinSyllable;
import kranji.pinyin.Tail;
import kranji.pinyin.Tone;
import kranji.singular.body.BodyParts;
import kranji.singular.concepts.AbstractConcepts;
import kranji.zi.ComposedZiT;
import kranji.zi.CompositionLayoutT;
import kranji.zi.LeftRightT;

public record HaiCough() implements ComposedZiT, LeftRightT<BodyParts.Kou, AbstractConcepts.Hai> {

    public static final HaiCough INSTANCE = new HaiCough();

    @Override public BodyParts.Kou left() { return BodyParts.KOU; }
    @Override public AbstractConcepts.Hai right() { return AbstractConcepts.HAI; }

    @Override public CompositionLayoutT layout() { return this; }

    @Override public String glyph() { return "\u54B3"; }

    @Override public PinyinSyllable pinyin() {
        return new PinyinSyllable(Initial.H, new Final(Head.OPEN, Body.A, Tail.VOWEL_I), Tone.FIRST);
    }

    @Override public int strokes() { return 0; }
    @Override public int radicalNo() { return 0; }
    @Override public String meaning() { return ""; }

    @Override public EtymologicalCategory etymology() {
        return new EtymologicalCategory.PhonoSemantic(BodyParts.KOU, AbstractConcepts.HAI);
    }
}
