// AUTO-GENERATED by kranji-codegen. Do not edit by hand.
package kranji.singular.space.n;

import kranji.library.BasicSet;
import kranji.library.LibraryMember;
import kranji.zi.SingularZi;

public record Nei() implements LibraryMember<BasicSet>, SingularZi {
    public static final Nei INSTANCE = new Nei();

    @Override public String glyph() { return "\u5185"; }
    @Override public String meaning() { return "inside"; }
    @Override public String pinyinText() { return "n\u00E8i"; }
    @Override public int strokes() { return 4; }
    @Override public BasicSet library() { return BasicSet.INSTANCE; }
}
