// AUTO-GENERATED by kranji-codegen. Do not edit by hand.
package kranji.singular.people.zero;

import kranji.library.BasicSet;
import kranji.library.LibraryMember;
import kranji.zi.SingularZi;

public record Yi_Barbarian() implements LibraryMember<BasicSet>, SingularZi {
    public static final Yi_Barbarian INSTANCE = new Yi_Barbarian();

    @Override public String glyph() { return "\u5937"; }
    @Override public String meaning() { return "foreigner/barbarian"; }
    @Override public String pinyinText() { return "y\u00ED"; }
    @Override public int strokes() { return 6; }
    @Override public BasicSet library() { return BasicSet.INSTANCE; }
}
