// AUTO-GENERATED by CatalogIteratorMain - do not edit by hand.
package kranji.common.perclass.promoted.d.uan1;

import kranji.classification.EtymologicalCategory;
import kranji.pinyin.Body;
import kranji.pinyin.Final;
import kranji.pinyin.Head;
import kranji.pinyin.Initial;
import kranji.pinyin.PinyinSyllable;
import kranji.pinyin.Tail;
import kranji.pinyin.Tone;
import kranji.singular.actions.ActionsAndStates;
import kranji.singular.radicals.RadicalComponents;
import kranji.zi.ComposedZiT;
import kranji.zi.CompositionLayoutT;
import kranji.zi.LeftRightT;

public record DuanEnd() implements ComposedZiT, LeftRightT<ActionsAndStates.Li_Stand, RadicalComponents.Duan_Upright> {

    public static final DuanEnd INSTANCE = new DuanEnd();

    @Override public ActionsAndStates.Li_Stand left() { return ActionsAndStates.LI_STAND; }
    @Override public RadicalComponents.Duan_Upright right() { return RadicalComponents.DUAN_UPRIGHT; }

    @Override public CompositionLayoutT layout() { return this; }

    @Override public String glyph() { return "\u7AEF"; }

    @Override public PinyinSyllable pinyin() {
        return new PinyinSyllable(Initial.D, new Final(Head.U, Body.A, Tail.N), Tone.FIRST);
    }

    @Override public int strokes() { return 0; }
    @Override public int radicalNo() { return 0; }
    @Override public String meaning() { return ""; }

    @Override public EtymologicalCategory etymology() {
        return new EtymologicalCategory.PhonoSemantic(ActionsAndStates.LI_STAND, RadicalComponents.DUAN_UPRIGHT);
    }
}
