// AUTO-GENERATED by CatalogIteratorMain - do not edit by hand.
package kranji.common.perclass.promoted.p.u3;

import kranji.classification.EtymologicalCategory;
import kranji.common.perclass.promoted.p.u3.PuVastAtom_Inner1;
import kranji.component.basic.BasicComponents;
import kranji.component.basic.WaterFamily;
import kranji.pinyin.Body;
import kranji.pinyin.Final;
import kranji.pinyin.Head;
import kranji.pinyin.Initial;
import kranji.pinyin.PinyinSyllable;
import kranji.pinyin.Tail;
import kranji.pinyin.Tone;
import kranji.zi.ComposedZiT;
import kranji.zi.CompositionLayoutT;
import kranji.zi.LeftRightT;

public record PuVastAtom() implements ComposedZiT, LeftRightT<WaterFamily.SanDianShui, PuVastAtom_Inner1> {

    public static final PuVastAtom INSTANCE = new PuVastAtom();

    @Override public WaterFamily.SanDianShui left() { return BasicComponents.SAN_DIAN_SHUI; }
    @Override public PuVastAtom_Inner1 right() { return PuVastAtom_Inner1.INSTANCE; }

    @Override public CompositionLayoutT layout() { return this; }

    @Override public String glyph() { return "\u6EA5"; }

    @Override public PinyinSyllable pinyin() {
        return new PinyinSyllable(Initial.P, new Final(Head.U, Body.U, Tail.NONE), Tone.THIRD);
    }

    @Override public int strokes() { return 0; }
    @Override public int radicalNo() { return 0; }
    @Override public String meaning() { return ""; }

    @Override public EtymologicalCategory etymology() {
        return new EtymologicalCategory.CompoundIndicative("");
    }
}
