// AUTO-GENERATED by kranji-codegen. Do not edit by hand.
package kranji.singular.concepts.x;

import kranji.library.BasicSet;
import kranji.library.LibraryMember;
import kranji.zi.SingularZi;

public record Xi_System() implements LibraryMember<BasicSet>, SingularZi {
    public static final Xi_System INSTANCE = new Xi_System();

    @Override public String glyph() { return "\u7CFB"; }
    @Override public String meaning() { return "system, tie"; }
    @Override public String pinyinText() { return "x\u00EC"; }
    @Override public int strokes() { return 7; }
    @Override public BasicSet library() { return BasicSet.INSTANCE; }
}
