// AUTO-GENERATED by Depth1GenerateMain - do not edit by hand.
package kranji.common.depth1.n;

import kranji.classification.EtymologicalCategory.*;
import kranji.pinyin.Body;
import kranji.pinyin.Final;
import kranji.pinyin.Head;
import kranji.pinyin.Initial;
import kranji.pinyin.PinyinSyllable;
import kranji.pinyin.Tail;
import kranji.pinyin.Tone;
import kranji.singular.structures.Structures;
import kranji.singular.tools.ToolsAndVessels;
import kranji.zi.ComposedPart;
import kranji.zi.ComposedZi;
import kranji.zi.CompositionLayout.*;
import kranji.zi.SingularPart;
import kranji.zi.ZiChar;
import java.util.List;

public final class Ao4 {

    private Ao4() {}

    public static final ComposedZi NAO_NOISY = new ComposedZi(
            new ZiChar.Unicode("\u95F9"),
            new PinyinSyllable(Initial.N, new Final(Head.OPEN, Body.A, Tail.VOWEL_U), Tone.FOURTH),
            8, 169, "",
            new FullEnclosure(ToolsAndVessels.MEN, Structures.SHI_MARKET),
            new PhonoSemantic(ToolsAndVessels.MEN, Structures.SHI_MARKET));

    public static final List<ComposedZi> ALL = List.of(
            NAO_NOISY);
}
