// AUTO-GENERATED by Depth1GenerateMain - do not edit by hand.
package kranji.common.depth1.n;

import kranji.classification.EtymologicalCategory.*;
import kranji.pinyin.Body;
import kranji.pinyin.Final;
import kranji.pinyin.Head;
import kranji.pinyin.Initial;
import kranji.pinyin.PinyinSyllable;
import kranji.pinyin.Tail;
import kranji.pinyin.Tone;
import kranji.singular.structures.Structures;
import kranji.singular.tools.ToolsAndVessels;
import kranji.zi.ComposedPart;
import kranji.zi.ComposedZi;
import kranji.zi.CompositionLayout.*;
import kranji.zi.SingularPart;
import kranji.zi.ZiChar;
import java.util.List;

public final class I2 {

    private I2() {}

    public static final ComposedZi NI_NUN = new ComposedZi(
            new ZiChar.Unicode("\u5C3C"),
            new PinyinSyllable(Initial.N, new Final(Head.OPEN, Body.I, Tail.NONE), Tone.SECOND),
            5, 44, "",
            new SemiEnclosureUpperLeft(Structures.SHI_CORPSE, ToolsAndVessels.BI_SPOON),
            new PhonoSemantic(Structures.SHI_CORPSE, ToolsAndVessels.BI_SPOON));

    public static final List<ComposedZi> ALL = List.of(
            NI_NUN);
}
