// AUTO-GENERATED by CatalogIteratorMain - do not edit by hand.
package kranji.common.perclass.promoted.zh.e5;

import kranji.classification.EtymologicalCategory;
import kranji.common.perclass.promoted.zero.iang2.YangSheepVariantAtom;
import kranji.pinyin.Body;
import kranji.pinyin.Final;
import kranji.pinyin.Head;
import kranji.pinyin.Initial;
import kranji.pinyin.PinyinSyllable;
import kranji.pinyin.Tail;
import kranji.pinyin.Tone;
import kranji.singular.body.BodyParts;
import kranji.zi.ComposedZiT;
import kranji.zi.CompositionLayoutT;
import kranji.zi.TopBottomT;

public record ZheParticle() implements ComposedZiT, TopBottomT<YangSheepVariantAtom, BodyParts.Mu> {

    public static final ZheParticle INSTANCE = new ZheParticle();

    @Override public YangSheepVariantAtom top() { return YangSheepVariantAtom.INSTANCE; }
    @Override public BodyParts.Mu bottom() { return BodyParts.MU; }

    @Override public CompositionLayoutT layout() { return this; }

    @Override public String glyph() { return "\u7740"; }

    @Override public PinyinSyllable pinyin() {
        return new PinyinSyllable(Initial.ZH, new Final(Head.OPEN, Body.E, Tail.NONE), Tone.NEUTRAL);
    }

    @Override public int strokes() { return 0; }
    @Override public int radicalNo() { return 0; }
    @Override public String meaning() { return ""; }

    @Override public EtymologicalCategory etymology() {
        return new EtymologicalCategory.DerivativeCognate("");
    }
}
