// AUTO-GENERATED by CatalogIteratorMain - do not edit by hand.
package kranji.common.perclass.promoted.t.ao2;

import kranji.classification.EtymologicalCategory;
import kranji.common.perclass.promoted.t.ao2.TaoTao;
import kranji.component.basic.BasicComponents;
import kranji.component.basic.PlantFamily;
import kranji.pinyin.Body;
import kranji.pinyin.Final;
import kranji.pinyin.Head;
import kranji.pinyin.Initial;
import kranji.pinyin.PinyinSyllable;
import kranji.pinyin.Tail;
import kranji.pinyin.Tone;
import kranji.zi.ComposedZiT;
import kranji.zi.CompositionLayoutT;
import kranji.zi.TopBottomT;

public record TaoGrape() implements ComposedZiT, TopBottomT<PlantFamily.CaoZiTou, TaoTao> {

    public static final TaoGrape INSTANCE = new TaoGrape();

    @Override public PlantFamily.CaoZiTou top() { return BasicComponents.CAO_ZI_TOU; }
    @Override public TaoTao bottom() { return TaoTao.INSTANCE; }

    @Override public CompositionLayoutT layout() { return this; }

    @Override public String glyph() { return "\u8404"; }

    @Override public PinyinSyllable pinyin() {
        return new PinyinSyllable(Initial.T, new Final(Head.OPEN, Body.A, Tail.VOWEL_U), Tone.SECOND);
    }

    @Override public int strokes() { return 0; }
    @Override public int radicalNo() { return 0; }
    @Override public String meaning() { return ""; }

    @Override public EtymologicalCategory etymology() {
        return new EtymologicalCategory.PhonoSemantic(BasicComponents.CAO_ZI_TOU, TaoTao.INSTANCE);
    }
}
